### ISSUE TITLE
Bug subtitle

### ISSUE THREAD

**Issue by Github-com-foss** [moneytoo/Player#10]
Subtitle not loaded from the folder(SRT)

**Comment by moneytoo** [comment]
Subtitles are not currently loaded automatically. 

> To load an external (non-embedded) subtitles, long press the file open action in the bottom bar.

**Comment by Github-com-foss** [comment]
I tried manually from folder does not work.

**Comment by moneytoo** [comment]
Once subtitles are loaded, you will be able to enable them from the [CC] (Closed Captions) button.
