### ISSUE TITLE
File sorting problem

### ISSUE THREAD

**Issue by YanceyChiew** [moneytoo/Player#100]
At present, when the application uses ACTION_OPEN_DOCUMENT to open the video file, the video in the file manager will be sorted by modification date, maybe it is more reasonable to sort by file name.

**Comment by moneytoo** [comment]
The system file chooser uses different sorting views depending on the content you're browsing. When you're browsing all device videos, it's sorted by time. When you browse directories from device root (internal storage), it is sorted by name.
