### ISSUE TITLE
[Feature request] add panning in addition to zooming

### ISSUE THREAD

**Issue by LoveChocoCat** [moneytoo/Player#101]
I would like to be able to pan and zoom my video to see more detail not just in the middle of my video. This might screw up the other gesture. Can you add this feature? If you don't like the idea just scrap this feature request

**Comment by moneytoo** [comment]
I believe it's theoretically possible (panning using two fingers during zoom, or one finger with double tap drag). Google Photos can do that. However I don't really see it as that important, especially for watching content like movies and TV shows.

**Comment by asl97** [comment]
Hi, sorry for hijacking this issue,  this player is one of the top result when searching `video zoom pan android "foss"` on google for me.

If you still don't plan on adding such a feature, can you suggest a foss player with the feature?

Kodi only has vertical panning, not horizontal, as far as I can tell, not to mention the zoom and pan interface is very clunky.

The only other player mentioned online by people is MX Player but with there being reports of "Adult ads" in their recent reviews, I rather not point users to it.

**Comment by asl97** [comment]
> Please see feature wise comparative alternative open source player's list in Readme [here](https://github.com/moneytoo/Player?tab=readme-ov-file#other-open-source-android-video-players)
> 
> [Next Player](https://github.com/anilbeesetti/nextplayer) may fulfill your needs as it has zoom feature available in it.

Next Player doesn't have a panning feature.

while we are at it, let me list the players I tried:

Next: up to 4x zoom but No panning
VLC: there mention of zoom but it really just change between "fit screen" and "best fit", no panning, they have an existing issue opened years ago, feature stated for version 4, whenever that comes.
MPV: No zoom control, but there is something called "Panscan", you can't pan while "zoomed" in using portrait mode "Panscan" zoom
MPVKT: No zoom control, portrait mode crop zoom, but no panning
Kodi: clunky 2x Zoom, only vertical panning (clunky too)
Nova: No zoom control, portrait mode crop zoom, but no panning
leafpic: No video control other than play/pause
photochiotte: has zoom and pan but there no usual video control UI, their user interface is very "unique" to say the least, very laggy/slow too, not something I could recommend to basic users.

also:

Fermata: not on fdroid
