### ISSUE TITLE
This Player is not correctly fit on Fragment

### ISSUE THREAD

**Issue by naveen-nuveda** [moneytoo/Player#102]
I tried to add this player in fragment, But my toolbar is no visible, it covers entire window, Toolbar is partially visible, 
Is there any solution for this

![IMG_20210506_162841](https://user-images.githubusercontent.com/51476997/117291735-fee4e400-ae8c-11eb-9b8c-797b16a454f0.jpeg)

**fragment_player.xml**
```
<androidx.coordinatorlayout.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    tools:context=".util.player.PlayerFragment">

    <com.nuveda.taoacademy.util.player.dtpv.DoubleTapPlayerView
        android:id="@+id/video_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:show_subtitle_button="false"
        app:dtpv_controller="@id/youtube_overlay" />

</androidx.coordinatorlayout.widget.CoordinatorLayout>
```

**Comment by moneytoo** [comment]
Just Player isn't really designed for use outside a standalone app (as it requests fullscreen, works with insets etc.) so this use isn't supported. I suggest using ExoPlayer directly.
