### ISSUE TITLE
How to detect pause and stop

### ISSUE THREAD

**Issue by sanoj26692** [moneytoo/Player#103]
I want to detect pause or stopped, so i followed below method but nothing works, And also if video is forwarded or rewind it detects there is a pause, So i only want to detect on pause and on end.

    @Override
        public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
            if (!playWhenReady){
                Log.d("TAG", "video paused");
            }
        }

**Comment by moneytoo** [comment]
This us not really a Just Player issue so reffer to https://exoplayer.dev/ for help.
