### ISSUE TITLE
Stream URL within the player

### ISSUE THREAD

**Issue by DarremMolko** [moneytoo/Player#106]
Would you consider adding a text box or something within the player to input video stream URLs? Currently we need to select the player from within other apps, leaving these other apps in the background and consuming battery. I have noticed this when streaming my cloud videos through MiXPlorer, it consumes more battery than the player itself. 
Thank you in advance.

**Comment by moneytoo** [comment]
File managers usually consume battery because they fetch the content (from Samba, WebDAV, SFTP, FTP etc.) and stream it using local HTTP server.
