### ISSUE TITLE
Add a toggle for automatic resume upon app restart

### ISSUE THREAD

**Issue by Githubsbiggestdumbass** [moneytoo/Player#115]
Hi,
I hope I'm doing this right (if not I refer you to my nickname :-) and I'm sorry).
I really love the simplicity and speed of Just (video) player...but each time I close a video and open it up later I have to skip back to the timestamp I quit watching at.
VLC (Desktop) had this feature for years and I think it would be a great option for Just as well.

**Comment by moneytoo** [comment]
If I understand correctly, it should already be there - Just Player saves video playback position on app stop and resumes this position on next startup. However it may also depend on a video as ExoPlayer cannot seek in some `fMP4` videos for example. Couldn't that be your case?

**Comment by Githubsbiggestdumbass** [comment]
Whoa that was fast. Yes i think you got what i meant. In my case I often Download Youtube videos via Newpipe on my Wifi and then take them with me in my runs/trips. So far resuming has not worked for me. Maybe thats the Issues?

**Comment by moneytoo** [comment]
How do you open these videos? Try opening them from within Just Player. Maybe try different video (for example test file from https://jell.yfish.us), just to be sure.

**Comment by Githubsbiggestdumbass** [comment]
Ok i guess it works if I open the video from within Juist player...weird. I have a OP 9 Pro...I would be great if it would work just from Android/outside the app.

**Comment by moneytoo** [comment]
From what app do you open the videos? I mostly use Solid Explorer but it should work with most apps. There are some limits when opening files that way (like no access to the file after a device reboot, but playback position could still be remembered).

**Comment by Githubsbiggestdumbass** [comment]
I use https://github.com/TeamAmaze/AmazeFileManager downloaded from the play store.

**Comment by moneytoo** [comment]
It works for me when using Amaze. (I'm on OP 7 but at Android 10) I will try it on newer OS version with this file manager.
Anyway, what us the location of the opened video on the file system?

**Comment by Githubsbiggestdumbass** [comment]
It's in the stock download folder of oxygen os. Is that a helpful answer?

**Comment by Githubsbiggestdumbass** [comment]
Welp i guess not ;-)
