### ISSUE TITLE
Feature request: Create a toggle to make PiP the default way of playback when switching apps

### ISSUE THREAD

**Issue by Githubsbiggestdumbass** [moneytoo/Player#116]
Hi again,

I have yet another feature request: I use youtube vanced (https://vancedapp.com/). The default setting for this app is to switch to PiP if the user switches apps/swipes up from the bottom to go "home". Just Video Player already his built in PiP but if the user switches apps/swipes to go home it currently pauses playback if the user doesn't click on PiP mode beforehand. An option to toggle this behavior would be much appreciated.

**Comment by moneytoo** [comment]
it's already there as a hidden feature (Auto PiP). Long press the PiP icon to activate this feature. Then, when you exit Just Player through the home button and video is playing, PiP will be activated automatically.
I will document that in a Readme.

**Comment by Githubsbiggestdumbass** [comment]
Ok thanks i figured it out. I would still be awesome to have some kind of indication whether or not PiP is enabled...maybe a with background or something around the button?

Another related issue: Is it a bug that playback stops once I lock the screen (even in PiP mode)? Vanced continues playback with the screen turned off.

**Comment by moneytoo** [comment]
> Is it a bug that playback stops once I lock the screen (even in PiP mode)? Vanced continues playback with the screen turned off.

Currently it's required to have the screen on, even for PiP, as full [background playback](https://github.com/moneytoo/Player/issues/44) isn't supported.

**Comment by Githubsbiggestdumbass** [comment]
So are you going to include this feature in future releases?

**Comment by moneytoo** [comment]
> So are you going to include this feature in future releases?

I can't really say. I mostly include what I personally need or ExoPlayer already provides / is easy while challenging to implement (without a need to configure that). Most importantly I want to keep this Player simple and without almost any options.

**Comment by Githubsbiggestdumbass** [comment]
Doesn't youtube vanced also use ExoPlayer? Then the feature should be available, shouldn't it?

**Comment by moneytoo** [comment]
This toggle is already available in advanced settings since [v0.61](https://github.com/moneytoo/Player/releases/tag/v0.61).
