### ISSUE TITLE
[Feature request] Detailed information about the audio track. (-online version)

### ISSUE THREAD

**Issue by vladlenas** [moneytoo/Player#118]
Hello, again I.)
It would be nice to see more detailed information about the audio track. Now only the language and the number of channels are visible. If possible, provide more detailed audio information like Dolby Digital 5.1, Dolby Digital Plus, DTS, DTS HD, etc.
Also, a big request to change the location of the Audio button. In the current version, it is very inconvenient to switch audio tracks. You can, for example, move it to the Subtitle button.

**Comment by Pentaphon** [comment]
I think the dev prefers we just use mediainfo for this. This is not really the job of a small, fast player.

**Comment by moneytoo** [comment]
I agree that audio/subtitle selection can sometimes lack important info. To distinguish SDH CC, commentary audio track etc. Currently thats the ExoPlayer default. But I agree thats something to further improve.

**Comment by vladlenas** [comment]
> I think the dev prefers we just use mediainfo for this. This is not really the job of a small, fast player.

I wrote that this is for the **-online** version, which is now great for TV boxes on Android TV. And I completely agree with you that this functionality is not necessary for mobile phones.

**Comment by moneytoo** [comment]
![Screenshot_20210618-170309](https://user-images.githubusercontent.com/1071643/122581478-60d16580-d057-11eb-9e1a-8999c9e2bb0d.jpg)

![Screenshot_20210618-170327](https://user-images.githubusercontent.com/1071643/122581512-6929a080-d057-11eb-9af2-d93a5da08a05.jpg)

https://github.com/google/ExoPlayer/blob/0ba317b1337eaa789f05dd6c5241246478a3d1e5/library/ui/src/main/java/com/google/android/exoplayer2/ui/DefaultTrackNameProvider.java

**Comment by moneytoo** [comment]
![Screenshot_20210618-221549](https://user-images.githubusercontent.com/1071643/122612117-e1f22200-d082-11eb-95a1-1105629ca8dc.jpg)

![Screenshot_20210618-221539](https://user-images.githubusercontent.com/1071643/122612138-ea4a5d00-d082-11eb-8799-4bafbae3ffcb.jpg)

😉

**Comment by vladlenas** [comment]
Looks great, you are the best.)
