### ISSUE TITLE
Make gesture onscreen indicators more readable/bigger or even animated like Newpipe?

### ISSUE THREAD

**Issue by Pentaphon** [moneytoo/Player#121]
When you change brightness or volume with the gestures, the onscreen vol/brightness value counter seems a bit too small for the screen. 

Perhaps they can be made bigger or more readable somehow? I have a 6.7 inch phone and it seems too small. I can still see it but I can't imagine that somebody with bad eyesight can read the indicator easily in the middle of the screen with a lot of stuff happening on video. 

Newpipe's animated indicator is a lot more viewable because of the bigger size and circle animation, Perhaps it can be more like that?

**Comment by moneytoo** [comment]
I agree with this. I attempted to put these indicators in the center and make them bigger. But then, I had to make an animation for showing/hiding the play button. Then the thing is that I strongly prefer having the play button big and in centre. Showing and hiding the most important button didnt look right when I tried.

**Comment by Pentaphon** [comment]
> I attempted to put these indicators in the center and make them bigger. But then, I had to make an animation for showing/hiding the play button. Then the thing is that I strongly prefer having the play button big and in centre.

Could you put the bigger/more readable onscreen gesture indicators on the sides then? Rather than the center? My only issue is that the gesture counters are too small. I don't mind if they are in a different place.
