### ISSUE TITLE
[Feature Request] Subtitle's Color

### ISSUE THREAD

**Issue by joaopedromfigueiredo** [moneytoo/Player#122]
If be possible, could you add a feature that user can choose the subtitle color? Someone prefer yellow subtitles, others prefer a white subtitle, others cyan... That's a feature it will turn this app much more completely and I think many user would enjoy.

**Comment by moneytoo** [comment]
There's already a way: https://github.com/moneytoo/Player#how-do-i-change-subtitle-font-size-or-color
