### ISSUE TITLE
Player maybe can not play DTS song correctly.

### ISSUE THREAD

**Issue by shenbuqingyun** [moneytoo/Player#125]
Hello there,

Player does play AC3 correctly, but not a dts.

a wav song, with ffprobe info:
 "codec_name": "dts"
 "format_name": "wav"

it`s voice is "sasasa". 

EXO FfmpegLibrary will reture abdio/raw, not audio/dts.
so it`s voice is incorrect.

You can download wav song with it`s codec fomat is DTS, not pcm_s16le, give it a try.

And by the way, I have setExtensionRendererMode(EXTENSION_RENDERER_MODE_PREFER).

**Comment by shenbuqingyun** [comment]
a song with ffprobe -show_format&-show_streams info:
 "codec_name": "dts"
 "codec_long_name": "DCA (DTS Coherent Acoustics)"
 "profile": "DTS-ES"
 "channels": 7
 "filename": "new.wav"
 "format_name": "wav"
"format_long_name": "WAV / WAVE (Waveform Audio)"

**Comment by moneytoo** [comment]
Do you have a sample to share?

**Comment by shenbuqingyun** [comment]
https://www.dtshot.com/category/DTS/

**Comment by shenbuqingyun** [comment]
I can email you？ send a song to you, maybe faster

**Comment by shenbuqingyun** [comment]
when handle a dts wav song, FfmpegLibrary.java - getCodecName() will not return codec name audio/dca, but audio/raw, so getCodecName() will return null, it means will use MediaCodecAudioRenderer, not FfmpegAudioRenderer to handle this song.

it`s voice indeed is "sasasa".

if change FfmpegLibrary.java - getCodecName() to return audio/raw, ExoPlayer will play this song with error "AudioTrack: Discontinuity detected".

**Comment by shenbuqingyun** [comment]
For a wav song， it`s default decoder name is pcm_s16le，but there are some other decoders like dts, WavExtractor can not read them correctly.

for a ac3, Exo have a Ac3Extractor to handle it, after add ffmpeg extension, ac3 will play correctly.

but not dts, There is not a Extractor for it.

currently, I can use ffmpg library to transfer a local dts song to ac3, and use ExoPlayer to play it. But this way is useless for a net song.

What should I do to solve this problm?

**Comment by moneytoo** [comment]
I see you already dealing with it at the appropriate place: https://github.com/google/ExoPlayer/issues/9096 Which is where this belongs (as this is an issue related to ExoPlayer extractors).

**Comment by shenbuqingyun** [comment]
> I see you already dealing with it at the appropriate place: [google/ExoPlayer#9096](https://github.com/google/ExoPlayer/issues/9096) Which is where this belongs (as this is an issue related to ExoPlayer extractors).

Yes Thank you.
 
I haved compile ffmpeg extension for Exo in my project, it can play ac3, but not dts.

So I doubt it`s the problem of my ffmpeg so, and I change Player`s jni so.

Want to configure out which is the real problem.

What is the problem？Why can not play dts after add ffmpeg extension? Is it really the WavExtractor problem?

**Comment by moneytoo** [comment]
It's about the container. `WavExtractor` in ExoPlayer needs to be updated to allow playback of "DTS WAV".

**Comment by shenbuqingyun** [comment]
> It's about the container. `WavExtractor` in ExoPlayer needs to be updated to allow playback of "DTS WAV".

Ok, thank you very much. I'll keep an eye on this
