### ISSUE TITLE
more details in sound tracks mp4 files choice

### ISSUE THREAD

**Issue by Santos2004** [moneytoo/Player#126]

**Comment by Santos2004** [comment]
sorry for the slight inaccuracy. we are only talking about multitrack mp4! everything is fine in mkv files. but maybe you can extract more complete information like windows or plex already does?

**Comment by moneytoo** [comment]
Do you have some sample of such mp4 or at least media info output (is it printed in that output?)?

**Comment by Santos2004** [comment]
> Do you have some sample of such mp4 or at least media info output (is it printed in that output?)?

![image](https://user-images.githubusercontent.com/78390645/122990189-580cc680-d3ac-11eb-9322-11a3c16defb1.jpeg)
![image](https://user-images.githubusercontent.com/78390645/122990215-61962e80-d3ac-11eb-8df0-1f54607e6f55.jpeg)

**Comment by moneytoo** [comment]
Looks like such details are stored in `handler_name` which may be allegedly something other than metadata/title.

**Comment by Santos2004** [comment]
How you going? :-)
