### ISSUE TITLE
Auto play last play progress 

### ISSUE THREAD

**Issue by aston314** [moneytoo/Player#128]
Now is stop,must click the play button to play.

**Comment by moneytoo** [comment]
Upon app open, playback resumes only if video was playing when leaving the player and the app wasn't killed by yet (either by using back button or by OS usually after few minutes in background)

**Comment by denon480** [comment]
yes, have this problem too, atv nvidia shield pro 2019
And if you start from begining is too hapens, must click button for start play.

**Comment by vladlenas** [comment]
Yes, it's annoying. Since when you start a video from another file manager (for example, by smb), the focus remains on the selection of files. And to start the video, you need to make an additional three clicks with the remote control.)

**Comment by moneytoo** [comment]
> Yes, it's annoying. Since when you start a video from another file manager (for example, by smb), the focus remains on the selection of files. And to start the video, you need to make an additional three clicks with the remote control.)

I can understand the thing with focus so I'm changing that.

**Comment by vladlenas** [comment]
> I can understand the thing with focus so I'm changing that.

I have a question?
Why not autoplay after changing the frame rate?
Or is it difficult?
Thanks in advance.)

**Comment by moneytoo** [comment]
Closing in favor of #176
