### ISSUE TITLE
Shows stereo instead of 5.1, can't resume content

### ISSUE THREAD

**Issue by pitrako** [moneytoo/Player#133]
Resume triggers infinite loading screen for mp4 content with dolby vision and dolby atmos, hdr10 content resumes correctly.

Language shows to the right "null" between parenthesis.

[Cruella1.mp4.txt](https://github.com/moneytoo/Player/files/6746310/Cruella1.mp4.txt)

**Comment by moneytoo** [comment]
What device are you using? I downloaded what I believe is the same file (only withoutm Spanish subtitle) but I'm unable to see the picture, probably because of related ExoPlayer issue: #132 Other than that, it seems to work fine. (However I will still check some other thing later)

**Comment by vladlenas** [comment]
> What device are you using? I downloaded what I believe is the same file (only withoutm Spanish subtitle) but I'm unable to see the picture, probably because of related ExoPlayer issue: #132 Other than that, it seems to work fine. (However I will still check some other thing later)

Because there is a single-layer DV in 5 profiles, such files can be played by Shield, Zidoo and Dune.

**Comment by vladlenas** [comment]
At me on this film Atmos audio track stutters and defines it as AC3 stereo. Plex plays well and identifies the audio track.

**Comment by moneytoo** [comment]
> At me on this film Atmos audio track stutters and defines it as AC3 stereo.

Seems like this is how ExoPlayer identifies the audio track `Format(3, null, null, audio/ac3, null, -1, en, [-1, -1, -1.0], [2, 48000])` - 2 channel AC3.

**Comment by pitrako** [comment]
> 
> 
> What device are you using? I downloaded what I believe is the same file (only withoutm Spanish subtitle) but I'm unable to see the picture, probably because of related ExoPlayer issue: #132 Other than that, it seems to work fine. (However I will still check some other thing later)

The device I'm using is PUS7304 Philips TV, i put the spanish subtitles myself with GPAC MP4Box, and it shows stereo for me too, but the atmos logo triggers on the TV.

**Comment by pitrako** [comment]
The subtitle format recognition was fixed, but the sound is recognized as stereo (but triggers atmos logo and sound works correct) and the few content I tried with this problem can't resume, I have to rewind to be able to watch the movie again (infinite loading screen), maybe the problem is the movie file itself?

**Comment by pitrako** [comment]
I tried on windows 10 "movies & tv" app and It says 2 channel too, I suppose It's the file's fault, I'm closing this, thanks.
