### ISSUE TITLE
Doesn't support seeking in local MP4 files

### ISSUE THREAD

**Issue by JohannBlake** [moneytoo/Player#135]
I selected a local MP4 file and then attempted to seek to a position in the video and play from there. This did not work.

**Comment by moneytoo** [comment]
"Regular" MP4 files (like [BigBuckBunny.mp4](http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4)) should work just fine. Seek may however not work in fragmented MP4 files: https://github.com/moneytoo/Player/issues/83#issuecomment-812834693 (as this is not currently supported by ExoPlayer).

**Comment by Pentaphon** [comment]
> I selected a local MP4 file and then attempted to seek to a position in the video and play from there. This did not work.

Try remuxing to mkv with https://play.google.com/store/apps/details?id=com.silentlexx.ffmpeggui

ffmpeg -i input.mp4 -c:av copy output.mkv
