### ISSUE TITLE
DTS-HD not working on Nvidia Shield

### ISSUE THREAD

**Issue by HDGuy** [moneytoo/Player#139]
As in title, I’m only getting the DTS core with Justplayer. With all other players, even ExoPlayer and Kodi, DTS-HD bitstreams just fine. TrueHD/Atmos does work.

**Comment by moneytoo** [comment]
I'm afraid it's same as #99

**Comment by HDGuy** [comment]
Any chance this could be resolved? I guess I am stuck with that build of Exoplayer in the meantime, but it doesn't switch refresh rates. Vimu (also Exoplayer based) is too buggy and doesn't really work right.

**Comment by moneytoo** [comment]
Share/link the version of ExoPlayer that works with DTS-HD, so I can inspect how they do that. The problem is basically only DTS-HD detection, which can be done by already included ffprobe. So there's a chance.

**Comment by HDGuy** [comment]
[https://forum.makemkv.com/forum/viewtopic.php?t=21937&start=915](url)
[https://drive.google.com/open?id=12nFLa67n3Jee1mGkRBxL2XSIyOIRSk4d](url)

I'm pretty sure this is the build I have installed on my Shield (I couldn't find the original download). I got it from that really long thread. You've probably already seen it, if not they go pretty deeply into Dolby Vision playback on the Shield Pro and getting it to work properly with modded versions of Exoplayer. 

I would use Vimu (it's also Exoplayer based) which has more features than JustPlayer (and works with DTS-HD) except it's buggy and very unstable.

**Comment by moneytoo** [comment]
The Google Drive link isn't public and the wetransfer link from the forum doesn't contain any file.

**Comment by vladlenas** [comment]
> The Google Drive link isn't public and the wetransfer link from the forum doesn't contain any file.

https://drive.google.com/file/d/17O1rGpAUAyc-q3PqNoQtQDXHgc3bjgUH/view?usp=sharing

**Comment by moneytoo** [comment]
This ExoPlayer apk used `DtsProbe` in MatroskaExtractor for DTS-HD detection (`isHD()`). Similar reimplementation would be probably even accepted by the upstream ExoPlayer.

**Comment by HDGuy** [comment]
[Exoplayer_Chapters_Support_03_08_2020_no_debug.zip](https://github.com/moneytoo/Player/files/6795523/Exoplayer_Chapters_Support_03_08_2020_no_debug.zip)

Try that.

**Comment by lollipop6969** [comment]
when can we expect dts hd support in justplayer?

**Comment by moneytoo** [comment]
I tried to reimplement DTS HD detection in a similar way as in the linked version of ExoPlayer (2.11.4) but then I found out than neither Just Player or ExoPlayer 2.11.4 actually play DTS HD for me. DTS HD tracks just do not play anything on my AV receiver, while DTS HD actually works at least in VLC.

So, could you share some sample that does play as DTS HD in the linked ExoPlayer version for you?

**Comment by HDGuy** [comment]
https://we.tl/whSFPBN6hT

Hmm. Everything I've tried with a DTS-HD track plays back properly on my Onkyo TX-NR676 receiver. This one works fine.

**Comment by HDGuy** [comment]
https://we.tl/whSFPBN6hT

Sorry about that- didn't mean to close it. 

Everything I've thrown at Exoplayer has worked fine in DTS-HD MA on my Onkyo TX-NR676 from my Shield. Try that demo file- I just tested it and it worked fine.

**Comment by lollipop6969** [comment]
dts hd now working in 0.46?

**Comment by HDGuy** [comment]
0.46 still DTS only.

**Comment by moneytoo** [comment]
Thank you for the sample. Unfortunately I got the same result as with other files I tried - no audio output at all. I have Onkyo TX-NR509 and currently testing the app on Geniatech ATV598Max. This Android TV device might be somewhat obscure (possibly requiring hacks to make things work?) so I will try it with Xiaomi Mi Box instead (will have access to it three weeks).

But please try this version: [Just.Player.v0.47-dtshd.apk](https://brouken.com/player/Just.Player.v0.47-dtshd.apk) 🤞 Ideally it should detect and output DTS HD, just like the previously ExoPlayer apk (though the list of audio tracks still shows DTS only for now).

**Comment by HDGuy** [comment]
Works! Congratulations! and thank you. :)

**Comment by vladlenas** [comment]
DTS X, DTS HD MA all good, DTS HD still plays like DTS.

**Comment by moneytoo** [comment]
> DTS HD still plays like DTS.

Do you have a sample you could share?

**Comment by vladlenas** [comment]
> > DTS HD still plays like DTS.
> 
> Do you have a sample you could share?

https://drive.google.com/file/d/17Ocw2Uddgze0cTPsFk8Z58t1Asxta5ss/view?usp=sharing

**Comment by HDGuy** [comment]
> DTS X, DTS HD MA all good, DTS HD still plays like DTS.

Despite the name, DTS HD is a lossy format and rarely used. I don’t think I’ve ever played a file that uses it.

**Comment by moneytoo** [comment]
@vladlenas This should hopefully work better: [Just.Player.v0.47-dtshd2.apk](https://brouken.com/player/Just.Player.v0.47-dtshd2.apk) (Previous version didn't necessarily load enough required data for detection.)

**Comment by vladlenas** [comment]
> @vladlenas This should hopefully work better: [Just.Player.v0.47-dtshd2.apk](https://brouken.com/player/Just.Player.v0.47-dtshd2.apk) (Previous version didn't necessarily load enough required data for detection.)

All is well now.

**Comment by moneytoo** [comment]
Does DTS-HD bitstream work for you on non Nvidia Shield devices as well? What is the lowest Android TV OS version it works? Because of issues with the one device I have, I'm considering limiting this DTS-HD detection to Android 8+.

**Comment by Koloss78** [comment]
Thank you for the DTS-HD fix, i tested 4 Files and all detected DTS-HD. Good Work.

**Comment by greymda** [comment]
> > @vladlenas This should hopefully work better: [Just.Player.v0.47-dtshd2.apk](https://brouken.com/player/Just.Player.v0.47-dtshd2.apk) (Previous version didn't necessarily load enough required data for detection.)
> 
> All is well now.

sorry to bring this up, but can you share this build?  Just.Player.v0.47-dtshd2.apk ?
