### ISSUE TITLE
Decoder init failed profile 7 just video player 0.42

### ISSUE THREAD

**Issue by pitrako** [moneytoo/Player#144]
Decoded init failed: OMX.dolby.vision.dvhe.dtb.decoder,
Format(1, null, null video/dolby-vision, dvhe.07.06, -1, en,
[3840, 2160, -1.0], [-1, -1])

PUS7304 TV, in just video player 0.42 says It can play profile 7 in unsuported devices, but I can't.

[P7_FEL_GIJoe_The_Rise_of_Cobra.mkv.txt](https://github.com/moneytoo/Player/files/6834587/P7_FEL_GIJoe_The_Rise_of_Cobra.mkv.txt)

**Comment by moneytoo** [comment]
Did it work in versions older than 0.42 or does it work when you install Just Play from [F-Droid](https://f-droid.org/packages/com.brouken.player/) (the F-Droid version lacks ExoPlayer patch related to mapping Dolby Vision)?

**Comment by pitrako** [comment]
No, It doesn't work on older or newer versions, I didn't try the F-Droid version but I suppose It's gonna go the same because I already tried It in version 0.45 when It was available on google play.

**Comment by pitrako** [comment]
I tried with latest version (0.57) and now profile 7 works with mkv.

**Comment by pitrako** [comment]
I tried again in 0.58 and It doesn't work, infinite loading screen, the video does not start.

**Comment by moneytoo** [comment]
I will add settings to allow enabling tunneled playback. I don't know much about DV as it's mostly handled directly by ExoPlayer.

**Comment by pitrako** [comment]
Ok, I understand, thanks.

**Comment by moneytoo** [comment]
Starting [v0.59](https://brouken.com/player/Just.Player.v0.59.apk) you can enable tunneled playback from settings. You can access settings from system App info screen (phones only) or by long pressing the gear (⚙️) icon (phones/TV).

**Comment by pitrako** [comment]
It works again enabling the option, thanks.
