### ISSUE TITLE
Add SMB/DLNA support

### ISSUE THREAD

**Issue by DokerLawyer** [moneytoo/Player#147]
Hi, any plans for added smb/dlna support for Android tv users?

**Comment by moneytoo** [comment]
There are at least two libraries that can accomplish SMB support and I would like to try:

- [android-smbfile-chooser](https://github.com/Guiorgy/android-smbfile-chooser)
- [NoNonsense-FilePicker](https://github.com/spacecowboy/NoNonsense-FilePicker) extended with [jcifs](https://github.com/codelibs/jcifs)

**Comment by moneytoo** [comment]
Even without built-in SMB support, it is still possible to play content over network when opening files from any file manager accessing this storage. (Just to be sure everyone is aware of that)

Another option is to integrate Just Player with Nova Video Player and gain media library as well as SMB/UPnP (etc.) support. See [FAQ](https://github.com/moneytoo/Player#i-prefer-using-media-library-instead-of-a-file-chooser).

**Comment by aluo-x** [comment]
I understand this is an old issue, but would it possible to add support for remote file systems using [Apache Common VFS (vfs2)](https://commons.apache.org/proper/commons-vfs/filesystems.html)?

**Comment by mailinglists35** [comment]
> Even without built-in SMB support, it is still possible to play content over network when opening files from any file manager accessing this storage. (Just to be sure everyone is aware of that)
> 
> Another option is to integrate Just Player with Nova Video Player and gain media library as well as SMB/UPnP (etc.) support. See [FAQ](https://github.com/moneytoo/Player#i-prefer-using-media-library-instead-of-a-file-chooser).

> 

the big problem I have with passing files from a third part file manager is impossibility to add external subtitles, since the file manager would only connect the video file to the player.

this is a big inconvenience as I run it on my android tv so I must first copy the video and subtitle to an external usb storage. opening directly from dlna/cifs/nfs would be much more convenient. 

sure I can use mkvtoolnix to integrate the subtitle into the mkv file, but then again this is a pain when needing it frequently.

**Comment by moneytoo** [comment]
> the big problem I have with passing files from a third part file manager is impossibility to add external subtitles, since the file manager would only connect the video file to the player, and not the subtitle file also

After you open a video file from the file manager, just return back to the manager and open the subtitle file in Just Player as well - the subtitle file will be attached to the last video now.

**Comment by mailinglists35** [comment]
hah, that's an unusual not intuitive but interesting method, will try, thanks!

I was just also going to suggest maybe examining the VLC for android source code and see how they are doing it. it seems to perform fast on my tv and instantly discovers the following types of bonjour advertised servers: sftp (over ssh), cifs, nfs, dlna.

https://code.videolan.org/videolan/vlc-android
