### ISSUE TITLE
Can't access external storage on Android TV 11 (TCL TV 65C825)

### ISSUE THREAD

**Issue by psychoboust** [moneytoo/Player#148]
Hello,
I can browse for the internal memory, but it doesn't provide any "SDCard Storage" or "Primary Storage" to be able to browse an external device.

The SOC for the TV is MediaTek MT9615 and it runs Android TV 11
I have check the Storage Permission and it's ok.

Can you help ?

**Comment by moneytoo** [comment]
Does browsing of your external device work with other video players or file managers?

**Comment by psychoboust** [comment]
yes, no problem, apps like VLC or KODI have no issue to access external device

**Comment by psychoboust** [comment]
I confirm it does work with Just.Player.v0.53-api29.apk.
I hope you will find a solution for the your next release, thanks again for your work.

**Comment by filip-spaldon** [comment]
I have problem access internal or external storage on Android 9, model of media box is Zidoo Z9X. I tested v54, v53 (google store version) and v53-api.29, but neither worked. 

Just get this error -
Intent { act=android.intent.action.OPEN_DOCUMENT cat=[android.intetn.category.OPENABLE typ=video/* (has extras) }

I enabled Storage Permission.
Can u help me? Thx

**Comment by moneytoo** [comment]
@filip-spaldon In your case it should "only" be a problem with detection of storage API. Please send me the full output of AIDA64 (System section) and I will fix that.

**Comment by filip-spaldon** [comment]
> @filip-spaldon In your case it should "only" be a problem with detection of storage API. Please send me the full output of AIDA64 (System section) and I will fix that.

![photo5866147873287157902](https://user-images.githubusercontent.com/36281812/131359030-bffa0e44-20bb-4eee-9b91-36a1ed0585c3.jpg)
![photo5866147873287157903](https://user-images.githubusercontent.com/36281812/131359035-f6e17926-a6a6-465a-b523-4547de1234f3.jpg)
![photo5866147873287157904](https://user-images.githubusercontent.com/36281812/131359037-794f1839-9425-40a0-b8c9-4bd6de94ac22.jpg)

**Comment by moneytoo** [comment]
@filip-spaldon Should be fixed in [Just.Player.v0.55.apk](https://brouken.com/player/Just.Player.v0.55.apk)

**Comment by filip-spaldon** [comment]
> @filip-spaldon Should be fixed in [Just.Player.v0.55.apk](https://brouken.com/player/Just.Player.v0.55.apk)

Yes, storage permission work, but another problem appears... Movies have lags and audio don't work (switching between PCM and Dolby Audii on soundbar), when I tested this movies via VLC everything is fine, but I want play some Dolby Vision movies.

Really thanks for you help, I like your work.

**Comment by mo123** [comment]
> @filip-spaldon Should be fixed in [Just.Player.v0.55.apk](https://brouken.com/player/Just.Player.v0.55.apk)

I try v0.55 on RK356x AndroidTV 11 but if clicking the folder button, the app just quits.
If I use v0.54 legacy then it works correctly with external storage.

**Comment by moneytoo** [comment]
> I try v0.55 on RK356x AndroidTV 11 but if clicking the folder button, the app just quits.
> If I use v0.54 legacy then it works correctly with external storage.

I'm not seeing any reported crashes about this in Google Play console (yet) so I will probably need a some log output from the device or [bugreport](https://developer.android.com/studio/debug/bug-report) to understand the issue and fix that.

**Comment by moneytoo** [comment]
I'm closing this as it should hopefully work. I also fixed a reported crash from Google Play console. If there are any other specific problems, please file a new issue with details.
