### ISSUE TITLE
Google Cast support

### ISSUE THREAD

**Issue by moneytoo** [moneytoo/Player#157]

**Comment by MattL0** [comment]
Hi , 

I take the opportunity to say that Nova and this player are what is the most  stable to watch dolby vision here  on ugoos am6b+. Thanks a lot!!

What I want to know is what does  google cast support mean more specifically for this player ?

**Comment by moneytoo** [comment]
@MattL0 I'm happy to hear that. ;-)

Google Cast support will allow local streaming of compatible on device stored videos (mov/mp4/mkv/webm) to Google Cast (Chromecast) devices.

**Comment by delltrak** [comment]
Where I find example source code of cast ? **Thank you** !👨🏻‍💻

**Comment by kevin4dhd** [comment]
Any update? :(

**Comment by moneytoo** [comment]
I lost enthusiasm once I realized one cannot just cast MKV with AC3. I should probably remux or transcode files on the fly to MP4 but I don't really know how to do that properly. Unfortunately I don't really use (nor have access to) Android TV very often so I have very little incentive to solve this.

**Comment by jpolstre** [comment]
Well, you are not interested, but do you know of any player with this functionality that is open source that you can recommend? Thanks.

**Comment by moneytoo** [comment]
> Well, you are not interested, but do you know of any player with this functionality that is open source that you can recommend? Thanks.

VLC supports Chromecast
