### ISSUE TITLE
Seeking in 1080p videos is slow

### ISSUE THREAD

**Issue by DhanabalKumar** [moneytoo/Player#161]
While seeking it takes upto 2 seconds to start playing again in 1080p movies which are about 3gb.

**Comment by moneytoo** [comment]
What device is that? Is it that slow only with some videos or all videos? (If possible, share a sample of a video)

**Comment by DhanabalKumar** [comment]
Check this one..
https://mega.nz/#!eCRHTQyI!CTmS3t7YuctFua0sugm4etuqZDXmXmDned73KDN2cUQ

**Comment by moneytoo** [comment]
Seems like this video is "heavily optimized" and doesn't have as many key frames as other files normally have. I tried modifying buffer sizes without any change to the seek in this video. Hopefully ExoPlayer will improve configuration of seek to allow better alignment to key frames in the future.
