### ISSUE TITLE
Broadcast right audio session to the system

### ISSUE THREAD

**Issue by rawlife56** [moneytoo/Player#163]
First of all thanks for this wonderful app which is simple and straight forward without requiring any broad permissions.

Coming to the issue,

**Background**- 

I use an app called [Wavelet](https://play.google.com/store/apps/details?id=com.pittvandewitt.wavelet) which can equalize audio of all apps which broadcast audio sessions like Spotify, vlc etc. Unfortunately it can't equalize Just player because your app doesn't broadcast the right audio session used to the system. 

It can be simply fixed by broadcasting the right session that is in use as per the [wavelet developer](https://imgur.com/a/VTWWIOm) 

I hope you can have a look into it as it helps to use any equalizer in an ideal way without forcing.

**Comment by moneytoo** [comment]
Closing as it's already available in stable v0.53.
