### ISSUE TITLE
Offline F-Droid version

### ISSUE THREAD

**Issue by ghost** [moneytoo/Player#164]
Hi i really like this player it's simple and it just works without asking for any permission, i wanted to ask it's dev if it's possible to make F-Droid version offline like before there are other projects that also make thier F-Droid version offline for security.

**Comment by moneytoo** [comment]
Closing, as commented in https://github.com/moneytoo/Player/issues/164#issuecomment-906637663. It would only make sense if the offline version would be on F-Droid, but the full featured online version should also be there. I view it as a too much hassle to manage/publish/explain. Still, anyone can maintain and distribute their offline fork.

**Comment by MattL0** [comment]
I see a new version on f droid. Is this version still have dolby vision mapped to hevc?

**Comment by moneytoo** [comment]
> I see a new version on f droid. Is this version still have dolby vision mapped to hevc?

Yep
