### ISSUE TITLE
Dolby Vision movies in MKV are oversaturated

### ISSUE THREAD

**Issue by magusone** [moneytoo/Player#165]
hello,
On my TV Sony X900F, Dolby Vision movies in MKV format are unfortunately oversaturated. You can see it very well on faces that are simply red/pink. What can I do with this issue?

Movie specs:
Video
ID                                       : 1
ID in the original source medium         : 4113 (0x1011)
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
HDR format                               : Dolby Vision, Version 1.0, dvhe.07.06, BL+EL+RPU, Blu-ray compatible / SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 2 h 16 min
Bit rate                                 : 82.6 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.415
Stream size                              : 78.9 GiB (98%)
Title                                    : MPEG-H HEVC Video / 64 + 82482 kbps / 2160p / 23.976 fps / 16:9 / Main 10 @ Level 5.1 @ High / 10 bits / Dolby Vision + HDR10 / BT.2020
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : BT.2020
Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2
Original source medium                   : Blu-ray

Thanks for help.

**Comment by moneytoo** [comment]
Please try uninstalling Just Player and installing the version from [F-Droid](https://f-droid.org/packages/com.brouken.player/). Any difference? (The F-Droid version lacks ExoPlayer patch related to mapping Dolby Vision.)

**Comment by magusone** [comment]
Unfortunately, nothing has changed :(

**Comment by MattL0** [comment]
Is the version  .45 on fdroid  different than the .45 here on github? 

All my equipement is dolby vision (ugoos am6b+ > lg c1. So I guess It would be better to get a non mapped version? 


Last question. If I tried to build a version with android studio on my own from .55 by only pointing the exoplayer dep.  to the officialnonmapped one , will it work without modifying any code?

**Comment by magusone** [comment]
Is there anything more I can do to fix my problem?

**Comment by moneytoo** [comment]
Try other ExoPlayer based players (ViMu, Fermata, Plex, Jellyfin etc.).

**Comment by magusone** [comment]
On Fermata was the same thing :(

**Comment by moneytoo** [comment]
I don't think I will be able to anything about this as I don't have any knowledge about Dolby Vison as well as don't have any DV capable hardware. Just Player can only be as good as ExoPlayer (& used hardware).
To resolve any DV problems, please reproduce your issues in the [ExoPlayer Demo](https://github.com/google/ExoPlayer/tree/release-v2/demos) app and report it directly to ExoPlayer on their [issue tracker](https://github.com/google/ExoPlayer/issues).
