### ISSUE TITLE
Is it possible to add a way to switch between HDR10+ and DolbyVision ?

### ISSUE THREAD

**Issue by psychoboust** [moneytoo/Player#166]
Hello,
There is some videos which contain HDR10+ and DolbyVision format in the same file (like Wonder Woman 1984), 
is there a way to choose between the 2 formats ?
Thks

**Comment by beeeeswax** [comment]
I don't pretend to know the ins and outs of DolbyVision and HDR but I do know on other players, these discs/remuxes with Dolby Vision will fall back to HDR10+ on TVs that don't support DV.  It seems JustPlayer doesn't honour this though and if it sees a DolbyVision file and a non-DV TV is just sets the display to SDR and everything is really washed out.  I'm seeing this on the Lord of the Rings UHD remuxes.

Discs/remuxes with just HDR10+ playback correctly with my TV displaying in HDR but DV files don't engage HDR as they should.

**Comment by moneytoo** [comment]
> It seems JustPlayer doesn't honour this though and if it sees a DolbyVision file and a non-DV TV is just sets the display to SDR and everything is really washed out. I'm seeing this on the Lord of the Rings UHD remuxes.

Is that with Dolby Vision Profile 7? Based on [these findings](https://github.com/google/ExoPlayer/issues/9139), I mapped DV profile 7 to HEVC to allow playback of these files on my device (phone with HDR10). I have no idea if the playback is SDR or HDR and even less idea if has any effect on DV (as I don't have any such equipment). Could you try installing Just Player from [F-Droid](https://f-droid.org/packages/com.brouken.player/) (which lacks such mapping) to see if it behaves any different?

**Comment by beeeeswax** [comment]
Hi moneytoo, yes proile 7.  Here's the MediaInfo for the video track on Lord of the Rings:

> Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
HDR format                               : Dolby Vision, Version 1.0, dvhe.07.06, BL+EL+RPU, Blu-ray compatible / SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 3 h 48 min
Bit rate                                 : 67.9 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Stream size                              : 108 GiB (95%)
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0050 cd/m2, max: 4000 cd/m2
Maximum Content Light Level              : 602 cd/m2
Maximum Frame-Average Light Level        : 184 cd/m2

I've removed the "proper" version of Just Player and installed the F-Droid version, same behaviour though.  HDR10+ discs (which just read "SMPTE ST 2086, HDR10 compatible" in MediaInfo) switch to HDR just fine but all three LOTR movies which use DV do not and as a result are very washed out.

I should have mentioned before, I'm on a Shield 2019 Pro and Samsung QE65Q7FN.

**Comment by moneytoo** [comment]
I don't think I will be able to anything about this as I don't have any knowledge about Dolby Vison as well as don't have any DV capable hardware. Just Player can only be as good as ExoPlayer (& used hardware).
To resolve any DV problems, please reproduce your issues in the [ExoPlayer Demo](https://github.com/google/ExoPlayer/tree/release-v2/demos) app and report it directly to ExoPlayer on their [issue tracker](https://github.com/google/ExoPlayer/issues).

**Comment by porterballs** [comment]
hope you dont mind but i referenced this issue over on the exoplayer github 

https://github.com/google/ExoPlayer/issues/9794.

**Comment by moneytoo** [comment]
Release [v0.125](https://github.com/moneytoo/Player/releases/tag/v0.125) includes ExoPlayer [r2.18.2](https://github.com/google/ExoPlayer/releases/tag/r2.18.2) which has some DV related improvements.
