### ISSUE TITLE
[Request] Support for m3u

### ISSUE THREAD

**Issue by VuzzyM** [moneytoo/Player#167]
Add support m3u

**Comment by VuzzyM** [comment]
@moneytoo ??

**Comment by VuzzyM** [comment]
@moneytoo Am I proposing this because there are torrserves that play m3u playlists.

**Comment by moneytoo** [comment]
It is an proposed enhancement for ExoPlayer: Google/ExoPlayer#4066

**Comment by VuzzyM** [comment]
@moneytoo Hello. Can you implement this parser for the m3u format?  It is compatible with kotlin and java. https://github.com/BjoernPetersen/m3u-parser

**Comment by VuzzyM** [comment]
@moneytoo Others want to work with m3u, because they can watch multiple sources directly automatically, without exiting the player and selecting everything manually.  For example, more http links.

**Comment by Pentaphon** [comment]
Now being tracked upstream at https://github.com/androidx/media/issues/1510
