### ISSUE TITLE
[Request] Automatic setting on track 1

### ISSUE THREAD

**Issue by VuzzyM** [moneytoo/Player#168]
Automatic setting on track 1, but not the player automatically select the track.

**Comment by VuzzyM** [comment]
@moneytoo ??

**Comment by moneytoo** [comment]
I'm afraid that such functionality is too specialized for this simple player with no settings.

**Comment by VuzzyM** [comment]
> I'm afraid that such functionality is too specialized for this simple player with no settings.

Every time player choose the second track, not the first, it's not ok. You can make it by default, without settings

**Comment by moneytoo** [comment]
It should already be selecting tracks at least based on track flags (default, forced) and language.

**Comment by VuzzyM** [comment]
> It should already be selecting tracks at least based on track flags (default, forced) and language.

in most cases it doesn't work for me, for example track 1 is Russian and English is selected

**Comment by moneytoo** [comment]
Please try sharing a video sample or Mediainfo ouput

**Comment by VuzzyM** [comment]
> Please try sharing a video sample or Mediainfo ouput

General
Unique ID : 245328523710554460885931241311233120949 (0xB8908E14A74A69B156F15982326C1AB5)
Complete name : F:VideoF9.The.Fast.Saga.2021.BDRip.1080p.seleZen.mkv
Format : Matroska
Format version : Version 4
File size : 7.93 GiB
Duration : 2 h 22 min
Overall bit rate : 7 950 kb/s
Movie name : F9: The Fast Saga 2021 from seleZen
Encoded date : UTC 2021-09-09 19:30:55
Writing application : mkvmerge v59.0.0 ('Shining Star') 64-bit
Writing library : libebml v1.4.2 + libmatroska v1.6.4

Video
ID : 1
Format : AVC
Format/Info : Advanced Video Codec
Format profile : High@L4.1
Format settings : CABAC / 5 Ref Frames
Format settings, CABAC : Yes
Format settings, Reference : 5 frames
Codec ID : V_MPEG4/ISO/AVC
Duration : 2 h 22 min
Bit rate : 6 547 kb/s
Width : 1 920 pixels
Height : 804 pixels
Display aspect ratio : 2.40:1
Frame rate mode : Constant
Frame rate : 23.976 (24000/1001) FPS
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Scan type : Progressive
Bits/(Pixel*Frame) : 0.177
Stream size : 6.53 GiB (82%)
Writing library : x264 core 146 -from seleZen
Encoding settings : cabac=1 / ref=5 / deblock=1:-2:-2 / analyse=0x3:0x133 / me=umh / subme=11 / psy=1 / psy_rd=1.02:0.03 / mixed_ref=1 / me_range=48 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-3 / threads=36 / lookahead_threads=6 / sliced_threads=0 / nr=0 / decimate=0 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=10 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=240 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=50 / rc=2pass / mbtree=0 / bitrate=6547 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=50000 / vbv_bufsize=62500 / nal_hrd=none / filler=0 / ip_ratio=1.40 / pb_ratio=1.30 / aq=3:0.80
Language : English
Default : Yes
Forced : No

Audio #1
ID : 2
Format : AC-3
Format/Info : Audio Coding 3
Commercial name : Dolby Digital
Codec ID : A_AC3
Duration : 2 h 22 min
Bit rate mode : Constant
Bit rate : 384 kb/s
Channel(s) : 6 channels
Channel layout : L R C LFE Ls Rs
Sampling rate : 48.0 kHz
Frame rate : 31.250 FPS (1536 SPF)
Compression mode : Lossy
Stream size : 392 MiB (5%)
Title : iTunes
Language : Russian
Service kind : Complete Main
Default : Yes
Forced : Yes

Audio #2
ID : 3
Format : AC-3
Format/Info : Audio Coding 3
Commercial name : Dolby Digital
Codec ID : A_AC3
Duration : 2 h 22 min
Bit rate mode : Constant
Bit rate : 384 kb/s
Channel(s) : 6 channels
Channel layout : L R C LFE Ls Rs
Sampling rate : 48.0 kHz
Frame rate : 31.250 FPS (1536 SPF)
Compression mode : Lossy
Stream size : 392 MiB (5%)
Title : Dub
Language : Ukrainian
Service kind : Complete Main
Default : No
Forced : No

Audio #3
ID : 4
Format : AC-3
Format/Info : Audio Coding 3
Commercial name : Dolby Digital
Codec ID : A_AC3
Duration : 2 h 22 min
Bit rate mode : Constant
Bit rate : 640 kb/s
Channel(s) : 6 channels
Channel layout : L R C LFE Ls Rs
Sampling rate : 48.0 kHz
Frame rate : 31.250 FPS (1536 SPF)
Compression mode : Lossy
Stream size : 654 MiB (8%)
Title : Original
Language : English
Service kind : Complete Main
Default : No
Forced : No

Text #1
ID : 5
Format : UTF-8
Codec ID : S_TEXT/UTF8
Codec ID/Info : UTF-8 Plain Text
Duration : 2 h 12 min
Bit rate : 55 b/s
Count of elements : 1419
Stream size : 53.2 KiB (0%)
Title : Full
Language : Russian
Default : No
Forced : No

Text #2
ID : 6
Format : UTF-8
Codec ID : S_TEXT/UTF8
Codec ID/Info : UTF-8 Plain Text
Duration : 2 h 9 min
Bit rate : 1 b/s
Count of elements : 40
Stream size : 1.41 KiB (0%)
Title : Forced
Language : Ukrainian
Default : No
Forced : No

Text #3
ID : 7
Format : UTF-8
Codec ID : S_TEXT/UTF8
Codec ID/Info : UTF-8 Plain Text
Duration : 2 h 15 min
Bit rate : 47 b/s
Count of elements : 1557
Stream size : 47.2 KiB (0%)
Title : Full
Language : English
Default : No
Forced : No

Menu
00:00:00.000 : Глава 01
00:04:47.746 : Глава 02
00:11:11.212 : Глава 03
00:20:36.569 : Глава 04
00:25:26.567 : Глава 05
00:30:26.867 : Глава 06
00:34:20.016 : Глава 07
00:42:13.489 : Глава 08
00:49:39.768 : Глава 09
00:55:46.343 : Глава 10
00:59:57.969 : Глава 11
01:07:58.866 : Глава 12
01:19:29.515 : Глава 13
01:28:47.113 : Глава 14
01:34:53.438 : Глава 15
01:40:27.688 : Глава 16
01:50:56.858 : Глава 

02:01:02.880 : Глава 18
02:05:22.265 : Глава 19
02:10:17.726 : Глава 20

**Comment by VuzzyM** [comment]
> Please try sharing a video sample or Mediainfo ouput

The track is selected in English, but the one in Russian should be

**Comment by moneytoo** [comment]
The English track is selected because of matching system English locale. The Russian track is set as forced and most players indeed use it as the initial one. However MX Player also ignores the forced flag and uses English.

**Comment by VuzzyM** [comment]
> The English track is selected because of matching system English locale. The Russian track is set as forced and most players indeed use it as the initial one. However MX Player also ignores the forced flag and uses English.

For me the system is set in English,  region as well, is a possible solution for that?

**Comment by VuzzyM** [comment]
> > The English track is selected because of matching system English locale. The Russian track is set as forced and most players indeed use it as the initial one. However MX Player also ignores the forced flag and uses English.
> 
> For me the system is set in English, region as well, is a possible solution for that?

@moneytoo solution for this ? I haven't received an answer in a long time.
