### ISSUE TITLE
Just (Video) Player + Kodi + Local Media

### ISSUE THREAD

**Issue by EXOSKELTON89** [moneytoo/Player#169]
I have a modified playercorefactory.xml and It seems that online streams work just fine opening with JustPlayer. However, media that is local (USB) refuses to open with JustPlayer, my other external players work fine but I want to play DV MKV's. 

I just get the "Click OK when Playback has ended" popup. I've tried everything to get this to work but it's not working at all. However, Exoplayer works just fine. This lead me to believe (after some research) it might be to do with permissions or the Android TV OS?

Is there any way to get my offline media working played through Kodi using Just (Video) Player?

There was an Offline and Online version of the app so I guess it worked back then, but it doesn't now after it's been merged. I've tried this on my android phone and my Nvidia Shield and it's still not working.

**Comment by moneytoo** [comment]
Could you share `playercorefactory.xml` that works on your phone with any other player (ExoPlayer, VLC etc.)? I already tried configuring it few days ago (to be able to provide clear instructions to others and verify whatever it works with Just Player) but I failed.

**Comment by EXOSKELTON89** [comment]
Hi,

Here is my XML attached. So to try and summarise what's working and what's not.....I've listed the below.

External Players: Playing Local Files (Offline)
Default Kodi Player: Working
Just Player: Not Working
ExoPlayer: Working
Vimu: Not Working
VLC: Working
MX Player Pro: Working

External Players: Playing Internet Streams (Online)
Default Kodi Player: Working
Just Player: Working
ExoPlayer: Working
Vimu: Working
VLC: Working
MX Player Pro: Working

If you need any more files etc, just let me know.

Thanks
________________________________

**Comment by moneytoo** [comment]
Please paste the content of the XML here or send it to directly to my email. 

Did you try granting Just Player storage permission from App info page (from the list of all installed apps)?

**Comment by EXOSKELTON89** [comment]
Here you go:

<playercorefactory> <players> <player name="JustPlayer" type="ExternalPlayer" audio="true" video="true"> <filename>com.brouken.player</filename> <playcountminimumtime>120</playcountminimumtime> </player> <player name="ExoPlayer" type="ExternalPlayer" audio="false" video="true"> <filename>com.google.android<http://com.google.android>.exoplayer2.demo</filename> <playcountminimumtime>120</playcountminimumtime> </player> <player name="Vimu" type="ExternalPlayer" audio="false" video="true"> <filename>net.gtvbox.videoplayer</filename> <playcountminimumtime>120</playcountminimumtime> </player> <player name="VLC" type="ExternalPlayer" audio="false" video="true"> <filename>org.videolan.vlc</filename> <playcountminimumtime>120</playcountminimumtime> </player> <player name="MXPlayerPro" type="ExternalPlayer" audio="false" video="true"> <filename>com.mxtech.videoplayer.pro<http://com.mxtech.videoplayer.pro></filename> <hidexbmc>true</hidexbmc> <playcountminimumtime>120</playcountminimumtime> </player> </players> <rules action="prepend">  <rule protocols="smb" player="JustPlayer" /> <rule dvdimage="true" player="JustPlayer"/> <rule protocols="rtmp" player="JustPlayer"/> <rule protocols="rtsp" player="JustPlayer" /> <rule protocols="file" player="JustPlayer" /> <rule protocols="file|smb|nfs" player="JustPlayer"/> <rule internetstream="true" player="JustPlayer" /> <rule video="true" player="dvdplayer"/>  </rules> </playercorefactory>

There is no storage permissions in the app page, if I go into all permissions, all that are listed is:
- Read the contents of your shared storage
- Modify or delete the contents of your shared storage
- Have full network access
- View network connections

So there is no actual option/permission to access storage files.
________________________________

**Comment by EXOSKELTON89** [comment]
Seems the open file button in Just Player works fine, it opens and plays any video format. However, if I open a file manager and select a video file to open with Just Video, it opens up Just Video with a black screen and crashes. This makes me think that this is related to why it doesn't open when using kodi.

**Comment by moneytoo** [comment]
This should work: [Just.Player.v0.56-kodi.apk](https://brouken.com/player/Just.Player.v0.56-kodi.apk)

**Comment by EXOSKELTON89** [comment]
Just checked it out. Its working. I've noticed if you open up a video through the Just Player app, the video plays at the refresh/frame rate of the video (matching framerate - 24fps etc), when I use 'open with' on the same video using kodi or a file manager, it doesn't change and plays at the refresh rate of the TV which is 60. 

Do I need to input some sort of rule or is this a bug.....or is it intended to do this?

**Comment by mo123** [comment]
> Wow, thanks for fixing this!
> 
> Just checked it out. Its working. I've noticed if you open up a video through the Just Player app, the video plays at the refresh/frame rate of the video (matching framerate - 24fps etc), when I use 'open with' on the same video using kodi or a file manager, it doesn't change and plays at the refresh rate of the TV which is 60.
> 
> Do I need to input some sort of rule or is this a bug.....or is it intended to do this?
Kodi should also play video at the video's refresh rate.
Did you set Kodi - System Settings - Enabled the whitelist resolutions and also in
Video Settings - 'Adjust Display Refresh rate to 'On Start/Stop' instead of 'Off'?

**Comment by EXOSKELTON89** [comment]
I did set that all up already. All those settings work with Kodi's inbuilt video player though....it changes all framerate etc but it doesn't go beyond kodi's default player. I'm not sure if all those settings are specific to kodi but I'm not sure, either way.....it seems to be not telling Just Player these settings.

**Comment by MattL0** [comment]
Works great here . This is a perfect replacement for nova player.

**Comment by mo123** [comment]
How do you add the playercorefactory.xml file to Kodi, on Android 11 it doesn't allow me to copy any file into the Android/data/*kodi*/.kodi/userdata folder, only on older Android OS's.

**Comment by moneytoo** [comment]
> How do you add the playercorefactory.xml file to Kodi, on Android 11 it doesn't allow me to copy any file into the Android/data/_kodi_/.kodi/userdata folder, only on older Android OS's.

Copy it from PC (over MTP) or use file manager from within of Kodi (copy from external mount point).

**Comment by MattL0** [comment]
It is not working here too with if kodi access files by itself via cifs/nfs etc etc. 

I forgot that I acess my file via an auto mounted cifs share at /mnt/cifs .

Justplayer does look at that path …But If I send a video to justplayer using kodi, I think just player now have direct acess to the file since the folder is now appearing in justplayer too (really meed to go that route to make this work: cifs> /mnt/cifs > kodi > just player)

I may be  wrong but I think Just player have access to the mounted cifs share directly after that.

**Comment by MattL0** [comment]
Also I am using media api to get the state of the media player via mqtt using termux etc.

since using kodi as a media player with ‘’my’’ method, I don’t received the play/pause/idle state correctly on my automation system. Maybe i should open another issue for this.

**Comment by moneytoo** [comment]
> It is not working here too if kodi access files by itself via cifs/nfs etc etc.

Seems like that in this case, Kodi sends uri `smb://...`. Just Player currently can only read local files or protocols like http/https/rtsp and has no Samba client (#147). Other file managers or even Nova Video Player usually proxy the Samba content through http so it works.

**Comment by moneytoo** [comment]
Closing in favor of #205 which is about specific other protocols (as local content should already work from Kodi).
