### ISSUE TITLE
Silence skip feature

### ISSUE THREAD

**Issue by barolo** [moneytoo/Player#17]
Exo provides great feature called [silence skip](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/audio/SilenceSkippingAudioProcessor.java) and I was amazed by its implementation in NewPipe, unfortunately it doesn't play local files. When you don't look at the video it's actually really hard to spot places where it is skipped. 
Thus I would like ask for inclusion of this feature [ possibly together with speedup functionality ].

**Comment by moneytoo** [comment]
Sounds interesting. I try that out. 

Can you point out your use case / with what video does this feature makes sense? Can you share a sample?

**Comment by moneytoo** [comment]
IMHO this is something that would be useful for podcasts instead of movies and TV shows. I would expect it to be more bound to online content. Just Player also currently doesn't have any background or music playback as it's originally intended for movies/shows.
Playback speed setting is already there (as it's provided by ExoPlayer UI).

**Comment by barolo** [comment]
It's great for any kind of educational content, classes etc. which many of us are in the midst of.
In one case this feature cut one of my videos from 2 hours to one, without speeding up, and it is far much pleasant to listen to.
Podcasts are pretty much covered by PocketCasts which have such feature too, it's closed source but oh well

**Comment by AkitoFire** [comment]
I would also advocate for the addition of this silence skip feature. Like barolo mentioned, it is very useful for educational content (for example, I'm currently watching recordings of my lectures and this feature would be much more helpful than simply increasing the playback speed). Also, I think no other player offers this feature (I only know about NewPipe, but that doesn't really count), neither on Android nor on Desktop platforms. There are ways to reencode those videos but that is time-consuming and costs much more space.

**Comment by moneytoo** [comment]
You can try builds available [here](https://brouken.com/player/) which have skip silence enabled (but lack UI to toggle that). See how well it works for your content.

**Comment by barolo** [comment]
@AkitoFire AntennaPod offers such feature, since it can play videos now, it's not intuitive since you need to add folder with videos first.

I'll check the new builds

**Comment by barolo** [comment]
@moneytoo That build works great!
In the future I would  love to have an option to 2x/3x fastforward through silence instead skipping.

**Comment by AkitoFire** [comment]
@moneytoo Thank you! I'm not entirely sure what the difference between both builds is, but it works really well! With quieter content, the output is a garbled mess though. One possible solution for this problem would be to check for a loudness standard and adjust accordingly (specifying target LUFS, for example), but I'm not sure how to implement something like this for a normal video player.

**Comment by barolo** [comment]
@moneytoo is there a plan to include this in release builds?

**Comment by moneytoo** [comment]
> @moneytoo is there a plan to include this in release builds?

Maybe in the future, but I can't promise anything. It would probably be available only after activating some advanced mode (I still need to think though that more).

**Comment by barolo** [comment]
> > @moneytoo is there a plan to include this in release builds?
> 
> Maybe in the future, but I can't promise anything. It would probably be available only after activating some advanced mode (I still need to think though that more).

Gotcha, thank you for updating the builds.

**Comment by barolo** [comment]
@moneytoo Could you please update the builds?

**Comment by barolo** [comment]
@moneytoo thank you for updates!

I have a request, could you perhaps tie playback speed to silence skip, instead of just skipping, e.g. 3x speed. It's much less jarring.
That's how the NewPipe guys [do it](https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/java/org/schabi/newpipe/player/Player.java).

**Comment by moneytoo** [comment]
Starting [v0.59](https://brouken.com/player/Just.Player.v0.59.apk) you can enable the basic audio skip from settings. You can access settings from system App info screen (phones only) or by long pressing the gear (⚙️) icon (phones/TV).

**Comment by barolo** [comment]
> Starting [v0.59](https://brouken.com/player/Just.Player.v0.59.apk) you can enable the basic audio skip from settings. You can access settings from system App info screen (phones only) or by long pressing the gear (gear) icon (phones/TV).

Marvelous! Just updated all of my devices. Thank you.

Will you consider my request of speeding up instead of cutting for skipping?

**Comment by theScrabi** [comment]
@moneytoo awesome 😍

**Comment by User087** [comment]
Am I correct in thinking that this: https://github.com/google/ExoPlayer/issues/6705 having been resolved should make it possible to enable the user to configure parameters of the skip-silence feature, so they can change the minimum duration of silence to be skipped, the threshold volume below which is classified as 'silence', and the duration of 'padding' on the edges of any silent portion?
