### ISSUE TITLE
Sub PGS transparent issue

### ISSUE THREAD

**Issue by psychoboust** [moneytoo/Player#170]
Hello,
I notice that most of my video with PGS subtitle read PGS but there is only the contour (the inside is transparent instead of fill with a color)
No issue with other player (like Kodi)

**Comment by moneytoo** [comment]
I believe I noticed some tiny issue with one PGS subtitles (not perfect outline/alpha of characters) in the past but please share a your sample media so we can test it and fix or report to ExoPlayer.

**Comment by psychoboust** [comment]
Do you know a tool to use to cut a small part of a MKV (HEVC Dolby Vision) ?

**Comment by EXOSKELTON89** [comment]
I have the same watching Quiet Place Part II in DV. It's like the font goes transparent and has a thin black outline instead.

**Comment by moneytoo** [comment]
![Screenshot_20210913-221330](https://user-images.githubusercontent.com/1071643/133150278-8fcbaa4e-9de3-4517-a02a-1d1654a3749f.jpg)

Like this?

**Comment by EXOSKELTON89** [comment]
Yeah, Exactly like that.

**Comment by moneytoo** [comment]
Seems like these are dual layer PGS; currently not supported by ExoPlayer: https://github.com/google/ExoPlayer/issues/7458

**Comment by moneytoo** [comment]
Closing as this is an upstream issue.
