### ISSUE TITLE
Audio bitrate shortly drops when seeking

### ISSUE THREAD

**Issue by UnlimitedCookies** [moneytoo/Player#174]
The bitrate drops very low for a split second when you for example jump 10 seconds back through a double tap.

I am on a Google Pixel 2 XL on Android 11 with app version 0.45

I experience the same issue with payback on the Google Files app, so it might be an upstream issue.

**Comment by UnlimitedCookies** [comment]
Info from ffprobe:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Airlines_ Business Travel Problem.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: mp41isomiso2
    creation_time   : 2021-09-08T17:55:52.000000Z
  Duration: 00:15:59.91, start: 0.000000, bitrate: 1586 kb/s
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 1534 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2021-08-27T03:47:56.000000Z
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: aac (HE-AAC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 48 kb/s (default)
    Metadata:
      creation_time   : 2021-08-27T02:58:22.000000Z
      vendor_id       : [0][0][0][0]
[
```

**Comment by moneytoo** [comment]
I can duplicate that. Seems like it's related to HE-AAC as when downloaded with Opus (using NewPipe or youtube-dl), it has no such glitches. I tried configuring TrackSelector (setExceedAudioConstraintsIfNecessary, setForceHighestSupportedBitrate setAllowAudioMixedSampleRateAdaptiveness etc.) and LoadControl (buffer sizes) without any difference. Could be ExoPlayer or hw decoder thing (I guess I could try switching to sw decoder or using different device).

**Comment by UnlimitedCookies** [comment]
What device were you testing on? Not using HW decoding should be avoided imo.

**Comment by UnlimitedCookies** [comment]
@moneytoo Would it make sense to open an issue upstream? You are probably better suited for providing the exact details.

**Comment by moneytoo** [comment]
I considered reporting it but I wasn't sure if such behavior is a bug or something expected because of the format. But feel free to report it there. Providing such description and sample should be enough.
