### ISSUE TITLE
After update, videos doesn't works.

### ISSUE THREAD

**Issue by joaopedromfigueiredo** [moneytoo/Player#175]
After update in play store, I can't play videos anymore. Before it worked, but now It doesn't.

![IMG_20210909_214530-01.jpeg](https://user-images.githubusercontent.com/76779567/132781040-545f86f7-9cb5-4b5a-aee7-43ac42359e05.jpeg)

**Comment by moneytoo** [comment]
Can you verify if it works with https://github.com/moneytoo/Player/releases/tag/v0.53 and stopped working with https://github.com/moneytoo/Player/releases/tag/v0.54 ? Version 0.54 enables tunneled playback. What device (model) are you using?

**Comment by joaopedromfigueiredo** [comment]
0.53 works, 0.54 not. I'm using a Philco Android TV 9 PTV50G71AGLS.

**Comment by moneytoo** [comment]
Reverting tunneled playback in [v0.58](https://github.com/moneytoo/Player/releases/tag/v0.58)
