### ISSUE TITLE
Auto resume playback after afr switch.

### ISSUE THREAD

**Issue by vladlenas** [moneytoo/Player#176]
Hello, it has been a long time since the implementation of the AFR. But until now, after switching the frequency it is necessary to unpause.
It would be nice to resolve this issue.)

**Comment by vladlenas** [comment]
hi, i checked 0.60, it does not pause if played from the player. If you run from outside the player, you have to unpause.

**Comment by moneytoo** [comment]
There were fixes related to this issue since the last feedback so it should be fixed now. Reopen or create new issue if necessary.
