### ISSUE TITLE
[Feature request] More information about playing video.

### ISSUE THREAD

**Issue by vladlenas** [moneytoo/Player#177]
It would be nice to see more information of the video file:
-video resolution (video not display)
-video frequency
-codec h264, h265 etc
-video format HDR, HDR10+, Dolby Vision
-bitrate
-audio track
Thanks for your attention.)
![IMG_20210911_183421_218](https://user-images.githubusercontent.com/54670862/132954590-c5a6a31d-53b6-4c84-a9b1-eae2df706ec0.jpg)

**Comment by moneytoo** [comment]
For now the "work around" is:

> [How to view detailed video information (like resolution, bitrate etc.)?](https://github.com/moneytoo/Player#how-to-view-detailed-video-information-like-resolution-bitrate-etc)
> Install app like [MediaInfo](https://play.google.com/store/apps/details?id=net.mediaarea.mediainfo) (or APK from [MediaArea.net](https://mediaarea.net/en/MediaInfo/Download/Android)). Then, to quickly open MediaInfo from Just Player, long press the video name/title.

**Comment by vladlenas** [comment]
This is the way I know.))
I do not open files from Just, most often Samba or online torrents.
Maybe in the future you will come to this.
Thanks.)

**Comment by denon480** [comment]
> For now the "work around" is:
> 
> > [How to view detailed video information (like resolution, bitrate etc.)?](https://github.com/moneytoo/Player#how-to-view-detailed-video-information-like-resolution-bitrate-etc)
> > Install app like [MediaInfo](https://play.google.com/store/apps/details?id=net.mediaarea.mediainfo) (or APK from [MediaArea.net](https://mediaarea.net/en/MediaInfo/Download/Android)). Then, to quickly open MediaInfo from Just Player, long press the video name/title.

You made an excellent player for a smartphone which is gaining popularity among the owners of TV boxes for viewing online torrents, and it works much better than others, including vimu
Maybe someday you will do it, we hope

**Comment by shockergit** [comment]
> For now the "work around" is:
> 
> > [How to view detailed video information (like resolution, bitrate etc.)?](https://github.com/moneytoo/Player#how-to-view-detailed-video-information-like-resolution-bitrate-etc)
> > Install app like [MediaInfo](https://play.google.com/store/apps/details?id=net.mediaarea.mediainfo) (or APK from [MediaArea.net](https://mediaarea.net/en/MediaInfo/Download/Android)). Then, to quickly open MediaInfo from Just Player, long press the video name/title.

please add more information in the app

**Comment by DrHurt** [comment]
+1 for this (if it wouldn't affect the efficiency of the app)
