### ISSUE TITLE
Auto play

### ISSUE THREAD

**Issue by aston314** [moneytoo/Player#179]
It can play a video automatically in 0.49 version.
But in 0.59 version I must click the play button to play a video after opening a video.
How can I set up it to play automatically.

**Comment by moneytoo** [comment]
Is that on a TV? Auto play may not work after refresh rate switch (this will be fixed in the next version #176).

**Comment by aston314** [comment]
Yes,it is on the TV.

**Comment by moneytoo** [comment]
Auto play should work in [v0.60](https://github.com/moneytoo/Player/releases/tag/v0.60) even when switching refresh rate. (Though auto play only starts when the file was never played before / position is at the beginning.)

**Comment by aston314** [comment]
Not work yet. Must click the play button.

**Comment by aston314** [comment]
I play the online m3u8 file.

**Comment by vladlenas** [comment]
> Auto play should work in [v0.60](https://github.com/moneytoo/Player/releases/tag/v0.60) even when switching refresh rate. (Though auto play only starts when the file was never played before / position is at the beginning.)

I understand, but it only works with videos that are launched from Just player. If you start it from the outside, after switching the frequency, it still pauses.

**Comment by denon480** [comment]
> > Auto play should work in [v0.60](https://github.com/moneytoo/Player/releases/tag/v0.60) even when switching refresh rate. (Though auto play only starts when the file was never played before / position is at the beginning.)
> 
> I understand, but it only works with videos that are launched from Just player. If you start it from the outside, after switching the frequency, it still pauses.

Yes, i have this problem too, version 0.60 not fixed this.

**Comment by moneytoo** [comment]
I'm unable to duplicate the issue as it seems to be working for me so please provide detailed steps to replicate the issue and/or share a [bug report](https://developer.android.com/studio/debug/bug-report).

**Comment by Poker354** [comment]
Nvidia Shield pro for me. I use Just Player as an external player. When using with Kodi or calling to “open with” through a file browser etc. the video is paused after frame rate switching. Using v.61.

**Comment by moneytoo** [comment]
> Nvidia Shield pro for me. I use Just Player as an external player. When using with Kodi or calling to “open with” through a file browser etc. the video is paused after frame rate switching. Using v.61.

What file browser are you using?

**Comment by vladlenas** [comment]
I also have Shield 2019 Pro, I use FX file manager and Nova Player to open videos in Just. After switching afr, the video is paused.

**Comment by Poker354** [comment]
Xplore file manager for me.

**Comment by denon480** [comment]
> I'm unable to duplicate the issue as it seems to be working for me so please provide detailed steps to replicate the issue and/or share a [bug report](https://developer.android.com/studio/debug/bug-report).

try look online torrent movie via **torrserv+just player** by default, and no difference you look from beginning or continue from the moment you stop is always need to press dpad center button or media button play, is happend with afr and without them

**Comment by moneytoo** [comment]
> try look online torrent movie via **torrserv+just player** by default, and no difference you look from beginning or continue from the moment you stop is always need to press dpad center button or media button play, is happend with afr and without them

I already tried TorrServe in the past but trying it again on a phone with or without auto frame rate option (but without any actual switching) it still works just the same as with other local media and auto plays when on beginning.

I might have to add some logging to help understand this issue.

**Comment by vladlenas** [comment]
> but without any actual switching
this is the problem, if it does not switch, then the video starts without a pause
but if it switches the frequency, the video always pauses

**Comment by vladlenas** [comment]
Interestingly, I am a beta tester of Nvidia Shield. Recently I got a new beta firmware and now autoplay works great.

**Comment by denon480** [comment]
> Interestingly, I am a beta tester of Nvidia Shield. Recently I got a new beta firmware and now autoplay works great.

can you please share this version?

**Comment by vladlenas** [comment]
> can you please share this version?
it's impossible

**Comment by denon480** [comment]
> Interestingly, I am a beta tester of Nvidia Shield. Recently I got a new beta firmware and now autoplay works great.

Is android 9 or 11?

**Comment by vladlenas** [comment]
> Is android 9 or 11?

9

**Comment by SubZero77** [comment]
I have the same problem in 0.82. 
The player does not automatically start playing the video.  For example, if you make it the default player in LazyMedia Deluxe.  And in other programs too ... ((

**Comment by denon480** [comment]
> I have the same problem in 0.82. The player does not automatically start playing the video. For example, if you make it the default player in LazyMedia Deluxe. And in other programs too ... ((

Ты так и не ответил на 4 пда, если у тебя тоже шилд то в 11 андроиде это уже исправили, по крайней мере в бетке

**Comment by moneytoo** [comment]
Just Player starts playback only at the beginning of the video. If this doesn't work and frame rate switch is the reason, you can install this version: [Just.Player.v0.84-afr.apk](https://brouken.com/player/Just.Player.v0.84-afr.apk), replicate the issue and capture a [bug report](https://developer.android.com/studio/debug/bug-report). You can send me it to my email (see profile). This might help me understand what's going on.

**Comment by moneytoo** [comment]
Thanks to received bug reports, I believe I fixed two specific cases when auto play didn't work. You can check [Just.Player.v0.87-autoplay.apk](https://brouken.com/player/Just.Player.v0.87-autoplay.apk) or wait for a push to beta channels (I'm still waiting for some confirmation from the person who send me these reports).

**Comment by moneytoo** [comment]
There were fixes related to this issue since the last feedback so it should be fixed now. Reopen or create new issue if necessary.
