### ISSUE TITLE
Have the option to disable/enable profile 7 mapped to hevc.

### ISSUE THREAD

**Issue by MattL0** [moneytoo/Player#180]
Hi , @moneytoo . When you have the time to check, would it be possible to have an option for user to disable /enable this function?

**Comment by MattL0** [comment]
https://github.com/moneytoo/Player/commit/a6dba432d8f62936a90c685c2355312a84f61f78

**Comment by moneytoo** [comment]
Are you saying that having this mapping enabled causes something? Is DV profile 7 content played incorrectly?

I know next to nothing when it comes to this issue and have no access to DV TV so I have never tested this.

**Comment by MattL0** [comment]
First I would need to correctly understand the implication of mapping hevc to dovi p7 . 

Dovi p7 is two stream , and is send as is to the tv after decoding . I am wondering if the mapping is adding anything in the process. 
+ the video is sent to the tv via rgb tunneling method , not sure I understand the mapping correctly, and not if it is beneficial or not. Is there any document website you can send me? 


I have a lg c1 so sending the dv p7 tunnelled rgb untouched would be more prudent I think. The tv is already mapping values..  and knows how to do it.


Personally I thing some things are clipped, and others a too saturated . Does hevc to p7 works with another colorspace?

**Comment by moneytoo** [comment]
This is the change: https://github.com/moneytoo/ExoPlayer/commit/c62e85818fa26ac173d860171d7a3f3806118cb8 
Based on info from: https://github.com/google/ExoPlayer/issues/9139 to allow DV profile 7 playback without DV

**Comment by moneytoo** [comment]
I don't think I will be able to anything about this as I don't have any knowledge about Dolby Vison as well as don't have any DV capable hardware. Just Player can only be as good as ExoPlayer (& used hardware).
To resolve any DV problems, please reproduce your issues in the [ExoPlayer Demo](https://github.com/google/ExoPlayer/tree/release-v2/demos) app and report it directly to ExoPlayer on their [issue tracker](https://github.com/google/ExoPlayer/issues).
