### ISSUE TITLE
Pip on mi tv stick

### ISSUE THREAD

**Issue by islam2hamy** [moneytoo/Player#182]
How can i activate pip on mi tv stick ?

**Comment by moneytoo** [comment]
Tap the picture-in-picture icon to activate it: ![baseline_picture_in_picture_alt_black_24dp](https://user-images.githubusercontent.com/1071643/133554125-5de6a79a-9d9e-42f7-a149-0076bbeac5b9.png)

The icon may not be available on all devices. Some devices are too low powered and PiP isn't available (for example on Chromecast with Google TV devices).

**Comment by islam2hamy** [comment]
:(
 I can activate it on "NewPipe" , so can it be available here later ?

**Comment by moneytoo** [comment]
So, there's not PiP icon in the bottom bar?

Does Just Player have Picture in picture permission? It should be in:
> Android settings > Apps & notifications > Advanced > Special app access > Picture-in-picture.

**Comment by islam2hamy** [comment]
Sorry for that "NewPipe" is just provide popup window , not a pip
