### ISSUE TITLE
Double click to fast forward or rewind with media buttons

### ISSUE THREAD

**Issue by denon480** [moneytoo/Player#185]
Hi, can you please fix this, when i want quick to rewind or fast forward on 10 second i must press media button 2 times, first press is show status line, second is make rewind or fast forward,  it would be great make this in one click

**Comment by moneytoo** [comment]
I'm not sure what you mean - what media button? To skip 10 seconds ahead, you can double tap on the right side without activating the UI or just swipe horizontally.

**Comment by denon480** [comment]
> I'm not sure what you mean - what media button? To skip 10 seconds ahead, you can double tap on the right side without activating the UI or just swipe horizontally.

Sorry I forgot write, is on Android TV Nvidia shield pro 2019

**Comment by moneytoo** [comment]
FF and RW buttons should work even without activating UI and should also report seek progress in [v0.63](https://github.com/moneytoo/Player/releases/tag/v0.63). Thanks for reporting this!

**Comment by denon480** [comment]
> FF and RW buttons should work even without activating UI and should also report seek progress in [v0.63](https://github.com/moneytoo/Player/releases/tag/v0.63). Thanks for reporting this!

thanks a lot now it works perfectly
