### ISSUE TITLE
m2ts online torrents

### ISSUE THREAD

**Issue by denon480** [moneytoo/Player#187]
Hi, m2ts video from bluray not work in torrents online, can you make support this format?

**Comment by moneytoo** [comment]
Unfortunately, ExoPlayer doesn't support m2ts - https://github.com/google/ExoPlayer/issues/1488.

However there's a quite small patch listed in the issue so I will try applying it.

**Comment by moneytoo** [comment]
Try using this version: [Just.Player.v0.64-m2ts.apk](https://brouken.com/player/Just.Player.v0.64-m2ts.apk)

It should generally work, though there might be possibly issues with seek (?). I also had trouble playing files containing 8 channel E-AC-3 but that applies to TS files as well (so I reported this issue to ExoPlayer).

If you find any issues, please provide a video sample.

**Comment by denon480** [comment]
> Try using this version: [Just.Player.v0.64-m2ts.apk](https://brouken.com/player/Just.Player.v0.64-m2ts.apk)
> 
> It should generally work, though there might be possibly issues with seek (?). I also had trouble playing files containing 8 channel E-AC-3 but that applies to TS files as well (so I reported this issue to ExoPlayer).
> 
> If you find any issues, please provide a video sample.

Thank you, is work but not in all movies, for exemple Terminator 2 have message " unexpected rutime error" 
here video on youtube https://youtu.be/VkqzUsoIpaE
In vimu media player this movie play fine.

**Comment by denon480** [comment]
here is audio from this movie
(AC3, 6 ch, 448 kb/s)
 (AC3, 2 ch, 192 kb/s)
 (DTS-HD MA, 6 ch, ~4000  kb/s)
 (DTS-HD MA, 6 ch, 4084 kb/s)
