### ISSUE TITLE
Not showing all Folders/Videos on External Storage to Play on Android 11

### ISSUE THREAD

**Issue by mo123** [moneytoo/Player#189]
If you have a lot of folders with videos inside on external storage(flash drive, external hard-drive) on Android 11 then Just Video Player just shows 2 or 3 folders with files to play, it ignores other folders and video files and you can't select or open then except from a file manager app.

**Comment by moneytoo** [comment]
On Android TV running Android 11, Just Player shows only files indexed by MediaStore. For video files, MediaStore requires them to be stored in `DCIM/`, `Movies/` or `Pictures/` directories. Can the files/directories you see be from these top level directories?

(Try putting your video files in `Movies/` directory on your flash drive and reboot your device. Reboot should be the foolproof way to trigger an update and re-index of files.)

**Comment by moneytoo** [comment]
Or you could try other players using the MediaStore - for example [Wiseplay](https://play.google.com/store/apps/details?id=com.wiseplay). Do you see your videos in there? 

(The majority of other players are still using the legacy storage API, but they will have to switch eventually as it won't be possible to distribute such apps through Google Play starting this November.)

**Comment by moneytoo** [comment]
Version [0.77](https://github.com/moneytoo/Player/releases/tag/v0.77) should again allow browsing of file system, including external storage volume.
