### ISSUE TITLE
[Bug] videos not opening

### ISSUE THREAD

**Issue by nothing223** [moneytoo/Player#19]
I recently discovered this video player and it looks very promising however videos wont open. My device is samsung galaxy s9 android 10 and it also doesent work on galaxy tab A android 10. When i press the select files option it brings me to the select file screen and when i select it it brings me to the player screen and nothing happens. I have granted the app storage and it is still not working. A fix would be greatly appreciated.

**Comment by moneytoo** [comment]
1. What video are you trying to play? Some formats may not be supported (like .avi etc). Currently there is no report of unsupported formats - but it will be in the next release (following v0.12).
2. Are you using any third party file browser and you are picking one after you tap the open video action in Just Player? It may not work right now (fix is also coming in the next release).

You could also try opening video file directly from some file manager (like Solid Explorer for example).

**Comment by nothing223** [comment]
1. i have tried to play an .mp4 file, a .mkv file and .flac file

2. Yes i am using a third party file manager. I have tried opening the files from mixplorer and the default file manager in the your app. I have also tried opening videos directly from the file manager app and it is still not working. What you mentioned is probably why it is not working. I will inform you if it still is not working after the update.

**Comment by moneytoo** [comment]
You can try this build to see if it reports any errors: [Just.Player.v0.12-test.apk.zip](https://github.com/moneytoo/Player/files/5793389/Just.Player.v0.12-test.apk.zip)

**Comment by nothing223** [comment]
It is working fine now. Thank you.

**Comment by moneytoo** [comment]
Releasing version 0.13 on Play Store so it should be available soon.
