### ISSUE TITLE
Frame drops while Playing AV1 10bit media on confirmed workable hardware.

### ISSUE THREAD

**Issue by hehenaice** [moneytoo/Player#191]
Okay so [this](https://down.mdiaload.com/zpjavxoltnif) is the media of concern.
On using exoplayer to stream it from an http server it causes frame drops. I downloaded it and it was pretty much the same.
On using [this](https://drive.google.com/file/d/17uK9CVQYSKb0zsmqo-KDaLrJLErwos7e/view) , I had no frame drops as such.
I know this might be a long shot. But I would like to hear your opinion or future pathways for this improvement.

**Comment by moneytoo** [comment]
I'm afraid I won't be able to do much about this as the device in this case uses only software decoder which obviously cannot handle that. Maybe external decoder (libgav1) would help but let's track its 10 bit support in #190.
