### ISSUE TITLE
Bug in 30hz 3840x2160

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [moneytoo/Player#194]
Hello,

bravo for this player which has a very nice video quality, but here is my worry, it is that on the mibox of Xiaomi, the player is put in 24hz 3840x2160 instead of 30hz 3840x2160 and in 24hz, the image lag and is in slow motion, and impossible to check a setting in just player because no menu is available on the application. The videos I watch are in 1080P/720P 50FPS or 25FPS.  I don't have this lag on vlc and mxplayer. Thanks

Translated with www.DeepL.com/Translator (free version)

**Comment by moneytoo** [comment]
So try disabling the Auto frame rate matching in [advanced settings](https://github.com/moneytoo/Player#:~:text=Some%20advanced%20features%20can%20be%20configured%20in%20settings).

If the frame rate is incorrectly detected, provide MediaInfo output and eventually some video sample as well.
