### ISSUE TITLE
make interface dismissable when video is paused

### ISSUE THREAD

**Issue by dikasetyaprayogi** [moneytoo/Player#195]
currently when we paused a video the interface (button,seekbar,status,etc..) is persistent and without a way to dismiss it expect if play/pause button is pressed again.

related to #149, i agree sometimes people want to take clean screenshot of video at paused time.

a simple fix would be to make the interface dismissable at pause time (stock aosp video player is a good example), usually by tapping outside of play button once the video is paused.

thanks for your concern.

**Comment by the-badmannn** [comment]
It would be cool if you would make the player to be closed with double press of the back button, that way the interface will be dismissed with the first one.

**Comment by JacenBridger** [comment]
Hello dev ! 
Just an query. Since the issue seems open, will it be implemented in next update, or it will be delayed ?

**Comment by moneytoo** [comment]
@JacenBridger The non dismissible UI (when paused) is actually a distinguishable feature of Just Player. There are other players for those looking for more customization anyway.

**Comment by KaKi87** [comment]
Hello,

I would like to insist : the UI should be togglable when paused on short press, like when playing.

However, it wouldn't necessarily need to be dismissed after a timeout like when playing, as I'm guessing that's what you're actually against.

Thanks

**Comment by Etim-Orb** [comment]
I agree, I always stop content to see details but the UI is in the way. Adding this would be deeply appreciated.

**Comment by sombresu** [comment]
The non dismissible UI is distinguishable yes but served no purpose beside blocking view. It doesn't need to be shown at all time on pause.

**Comment by NowDev** [comment]
If you also don't want that "distinguishable feature", just remove this check on `CustomPlayerView.java`
```diff
public boolean tap() {
        if (PlayerActivity.locked) {
            Utils.showText(this, "", MESSAGE_TIMEOUT_LONG);
            setIconLock(true);
            return true;
        }

        if (!PlayerActivity.controllerVisibleFully) {
            showController();
            return true;
-        } else if (PlayerActivity.haveMedia && PlayerActivity.player != null && PlayerActivity.player.isPlaying()) {
+        } else if (PlayerActivity.haveMedia && PlayerActivity.player != null) {
            hideController();
            return true;
        }
        return false;
}
```

**Comment by KaKi87** [comment]
Would you generate APKs containing that change ?
Thanks

**Comment by TheDcoder** [comment]
If anyone still cares I have [forked](https://github.com/TheDcoder/JustPlayer) this repo with @NowDev's patch and a patch of my own to make the UI dismissable on Android TV as well.

It also has automated builds powered by GitHub actions so you can download the latest APKs from the [release page](https://github.com/TheDcoder/JustPlayer/releases/tag/latest) :)

**Comment by KaKi87** [comment]
Yes, I will definitely try it, because right now this inconvenience is one of the few reasons why I'm still using a proprietary video player. Thank you !

**Comment by KaKi87** [comment]
Uh, there are a lot of APKs, which one should I download ? Thanks

**Comment by TheDcoder** [comment]
@KaKi87 You can try any of the `*-signed.apk` files, if in doubt just go with `*-latest-universal-lite-release-unsigned-signed.apk`

**Comment by woj-tek** [comment]
> The non dismissible UI (when paused) is actually a distinguishable feature of Just Player. There are other players for those looking for more customization anyway.

@moneytoo 
Sadly the alternatives are "so so" hence me using Just Player. And sometimes I watch some conferences using it and pause to read the slides so the UI (especially huge play/pause button in the middle) makes reading more difficult…

Looking at the issue history:

<img width="1022" height="379" alt="Image" src="https://github.com/user-attachments/assets/371e6b5b-8eef-499f-bee1-20718da1054f" />

it seems it's quite popular and not unusual…

------



> If anyone still cares I have [forked](https://github.com/TheDcoder/JustPlayer) this repo with [@NowDev](https://github.com/NowDev)'s patch and a patch of my own to make the UI dismissable on Android TV as well.
> 
> It also has automated builds powered by GitHub actions so you can download the latest APKs from the [release page](https://github.com/TheDcoder/JustPlayer/releases) :)

@TheDcoder it seems the repo is not updated anymore?

Alas - would you consider making it available on f-droid? :)

**Comment by KaKi87** [comment]
On my end, I ended up encountering another issue that is due to Just Player being based on MPV : mpv-player/mpv#7070

So despite the fork I had to go back to MX Player. 😭

**Comment by TheDcoder** [comment]
@woj-tek Oops, seems I missed the latest stable release, will push an update soon. I intend to keep updating it as long as I can, but I generally avoid pre-release versions.

Regarding F-Droid, I am not an app developer, I just did the basic minimum patching in code and let GitHub's CI/CD pipeline do the rest of the compilation work. But feel free to open an issue on F-Droid's tracker and see what they think about it, I won't mind if they decide to distribute the fork there.

If what you're after is auto-updates, then Obtainium also does a good job and it works with any app on GitHub with releases.



> On my end, I ended up encountering another issue that is due to Just Player being based on MPV.

It's not based on mpv though, Just Player uses the Exo framework, it's completely independent from mpv.

**Comment by KaKi87** [comment]
> It's not based on mpv though

I must have confused it with a different app then.

My bad, I'll try it out again !
