### ISSUE TITLE
no DTS audio in Bluetooth headphones on Shield TV 2019

### ISSUE THREAD

**Issue by tostervic** [moneytoo/Player#198]
When I watch a movie with DTS audio through my BT headphones Microsoft Wireless Headphones or Samsung Galaxy Buds Live there is no sound. Everything is OK if I switch to my soundbar. AC3 audio works correctly in both cases. I use Nvidia Shield TV 2019 as a mediaplayer. Vimu player works with headphones OK. So, I guess it is no hardware problem rather someting broken in  Just Player probably.

**Comment by moneytoo** [comment]
Reported in https://github.com/google/ExoPlayer/issues/9588
