### ISSUE TITLE
AUDIO files cannot be played 

### ISSUE THREAD

**Issue by Natalia-Oreiro** [moneytoo/Player#199]
Hi, I can't start playing .mp3 and .flac files on my mobile (is this a standard thing)?
https://i.imgur.com/QFOcard.png
does it have to be a container video? 

PS:
my telegram never worked, doesn't telegram want to connect you to matrix.org (bridge)? 
https://matrix.org/bridges/#telegram

**Comment by moneytoo** [comment]
Playback of audio files isn't supported: #55

**Comment by Natalia-Oreiro** [comment]
ok i have to say your player is perfect, 

it would be enough for me absolute basic support of .mp3, .acc, .flac (without metadata).
hopes to change your mind to basic audio file support :-)
