### ISSUE TITLE
can't passthrough DTS to soundbar

### ISSUE THREAD

**Issue by greymda** [moneytoo/Player#201]
i have a Sony HT-X8500 soundbar capable of decoding DTS/DTS-HD audio.
so when trying to playback a video with DTS sound, Just Player fails with error`MediaCodecAudioRenderer error, index=2, format=Format(11, Original....), format_supported=YES`

if it says format_supported=YES, then why failing on playback?
hope you can help me out

cheers

**Comment by moneytoo** [comment]
What Android device do you use. Is that issue with any video containing DTS audio or only some?

**Comment by greymda** [comment]
> What Android device do you use? Is that issue with any video containing DTS audio or only some?

Amazon Firetv Stick 4K. 
any video containing DTS/DTS-HD. 

same video if played by PLEX client with direct play sends audio to external sound workout issue.

**Comment by greymda** [comment]
@moneytoo can i help with understanding the issue?

**Comment by moneytoo** [comment]
This is probably more of an ExoPlayer & device issue. (As generally DTS decoding as well as bitstream works.) Amazon also has their own ExoPlayer port which makes me wonder how well the upstream ExoPlayer actually works on Amazon devices.

**Comment by moneytoo** [comment]
I don't think I will be able to anything about this as this is probably specific hardware related issue (as DTS output works with my devices). Just Player can only be as good as ExoPlayer.
To resolve any such problem, please reproduce your issues in the [ExoPlayer Demo](https://github.com/google/ExoPlayer/tree/release-v2/demos) app and report it directly to ExoPlayer on their [issue tracker](https://github.com/google/ExoPlayer/issues).
