### ISSUE TITLE
API / Intent definition

### ISSUE THREAD

**Issue by brentonv** [moneytoo/Player#203]
Hi

Just curious to know if there are any plans to implement activity results such as in [MX](https://sites.google.com/site/mxvpen/api) , [VLC](https://wiki.videolan.org/MediaControlAPI) , or [Vimu](https://www.vimu.tv/player-api)

Thanks

**Comment by moneytoo** [comment]
Part of the MX Player API (which includes Activity result) is already implemented to allow integration with Nova Video Player - #158.

What specific API methods/parameters you have in mind (only Activity results or also something else)? What other software uses this API and in what use cases? (This also helps when testing the integration)

**Comment by brentonv** [comment]
Oh cool thanks, MX activity results are fine. I'm just looking to see how this integrates with another player that also handles MX activity results so I'll do some tests and let you know how it goes

Thanks

**Comment by brentonv** [comment]
I did see there are MX intents used in JustPlayer which is absolutely brilliant but as you said it’s only part of the MX API. The only functions I could get to work were play and resume. External subtitles do not load and there seems to be no results returned for resume position other than “playbackFinished”, as there is no “intent.result.VIEW" only “intent.action.VIEW" implemented. It would be greatly appreciated if you could please consider using the following MX intents:

```
"android.intent.action.VIEW"
__"video_list"
__"video_list.name"
__"video_list.filename"
__"subs"
__"subs.enable"
__"title"
__"filename"
__"position"
__"return_result"
__"headers"

"com.mxtech.intent.result.VIEW"
__"position"
__"duration"
__"end_by"
____"user"
____"playback_completion"
```

**Comment by brentonv** [comment]
Nice to see some updates here. I'll test it out and let you know. Thanks @moneytoo

**Comment by brentonv** [comment]
Around version 0.67 when I logged this issue I created a Just Player test build as a default player with the Syncler app, and API support was limited.

I see by version 0.99 the requested changes have been implemented which I really appreciate, and this has also made way for the Syncler developer to include Just Player as a new default player which will also please many others.

The player position intent works which now enables resume playback from the Syncler app which is excellent, but as you're aware there are still issues with downloaded subtitles in the Syncler BETA so I'm still unable to fully confirm this part.

However one thing I did notice in the meantime is Just Player doesn't display the subtitle language for the downloaded subtitle and instead shows "Unknown". The split screen image compares the current Syncler/BETA/Exo player with Just Player

![BrokenSuntitles](https://user-images.githubusercontent.com/2313757/153742743-3835c101-c01d-43bf-8f24-2a63108201db.png)

**Comment by brentonv** [comment]
Around version 0.67 when I logged this issue I created a Just Player test build as a default player with the Syncler app, and API support was limited.

I see by version 0.99 the requested changes have been implemented which I really appreciate, and this has also made way for the Syncler developer to include Just Player as a new default player which will also please many others.

The player position intent works and now enables resume playback from the Syncler app which is excellent, but as you're aware there are still issues with downloaded subtitles in the Syncler BETA so I'm yet to fully confirm this part.

However one thing I did notice in the meantime is Just Player doesn't display the subtitle language for the downloaded subtitle and instead shows "Unknown". The split screen image compares the current Syncler/BETA/Exo player with Just Player

![BrokenSuntitles](https://user-images.githubusercontent.com/2313757/153742881-42af0063-751f-4b8e-a160-d9db1cad7aa5.png)

**Comment by brentonv** [comment]
Around version 0.67 when I logged this issue I created a Just Player test build as a default player with the Syncler app, and API support was limited.

I see by version 0.99 the requested changes have finally been implemented which I really appreciate, and this has also made way for the Syncler developer to include Just Player as a new default player which will also please many others.

The player position intent works and now enables resume playback from the Syncler app which is excellent, but as you're aware there are still issues with downloaded subtitles in the Syncler BETA so I'm yet to fully confirm this part.

However one thing I did notice in the meantime is Just Player doesn't display the subtitle language for the downloaded subtitle and instead shows "Unknown". The split screen image compares the current Syncler/BETA/Exo player with Just Player

![BrokenSuntitles](https://user-images.githubusercontent.com/2313757/153743258-7b1064ec-6f81-4978-bdcc-6d29c55e4959.png)

**Comment by moneytoo** [comment]
> However one thing I did notice in the meantime is Just Player doesn't display the subtitle language for the downloaded subtitle and instead shows "Unknown". 

Does it work with other players?

**Comment by brentonv** [comment]
> Does it work with other players?

With the downloaded subtitle feature being so problematic at the moment I can't really test anything. The language flag is probably missing from the Syncler app when it sends details to the player so I'll post this to /r/SynclerApp also

**Comment by moneytoo** [comment]
It doesn't seem like there's a field for language in the [MX Player API](https://mx.j2inter.com/api). For example Jellyfin puts the language name as a label to `subs.name`.

**Comment by brentonv** [comment]
> Jellyfin puts the language name as a label to `subs.name`.

I've posted the issue to /r/SynclerApp so hopefully the Syncler developer can implement something similar for you to use.

Thanks again for all the great work you do

**Comment by TheBeastLT** [comment]
Also it would be great if Just Player would pass a unique action string when creating the result intent (`new Intent(uniqueResultAction)`, so that it would be possible to identify that the result is coming from Just Player. Here are a few action names used by other player:

`MX` - `com.mxtech.intent.result.VIEW`
`MPV` - `is.xyz.mpv.MPVActivity.result`
`VLC` - `org.videolan.vlc.player.result`
