### ISSUE TITLE
[Feature Request] “Toggle Resume playback ON or OFF"

### ISSUE THREAD

**Issue by Jpersh27** [moneytoo/Player#204]
Hello @moneytoo 

I have a suggestion for a necessary new feature that I feel as though would go great under the General settings tab within the app. 

It would allow users to chose whether they want to resume the same playback position for any video they stopped playing in the app.

For example: 

Toggle Resume Playback “ON or OFF"-

1st option- “Yes" or “ON”

2nd option- “No" or “OFF"

• Why I feel as though this addition would be a necessary feature to have is because anytime you resume playback of any video on your device the app automatically resumes where you left off last.  

It's definitely a hassle and an annoyance having to scroll back everytime since there isn't any “On Screen playback controls" other than a Stop playback button. 

The only current option to rewind or fast forward any video playback is by having to “Double Tap on the left or right of your screen" numerous times to go back and forth by 10 second increments.

I hope you do consider adding this feature in the near future with a upcoming release of the application.

**Comment by Jpersh27** [comment]
@moneytoo Have you had the opportunity to look over my feature request yet? And if so what are the chances this feature gets added in the future?

**Comment by Jpersh27** [comment]
So... @moneytoo ??

**Comment by moneytoo** [comment]
https://github.com/moneytoo/Player/blob/master/README.md
> Just Player is something like ~~80%~~ 90% feature complete. It will probably never have dozens of options or some rich media library UI. It will never truly compete with feature rich VLC. It just attempts to provide functional feature set and motive others to create greater players based on amazing ExoPlayer.

It isn't really my intention to add every possible feature and maintain that over time.
