### ISSUE TITLE
Kodi integration problem (SMB, FTP)

### ISSUE THREAD

**Issue by magusone** [moneytoo/Player#205]
hello,
I'm trying to play video in Kodi (Jarvis 16.1) useing JustPlayer (v0.67) . I'm useing FTP local server (hdd conected to router rt-ac86u). I prefer FTP becouse I can load external subtitles (srt file) and it's faster then SMB. JustPlayer seems to play file only when I'm connected via UPnP, but it can't via FTP or SMB.

Thx for any help.

**Comment by moneytoo** [comment]
[This applies](https://github.com/moneytoo/Player/issues/169#issuecomment-922519344):
>Seems like that in this case, Kodi sends uri smb://.... Just Player currently can only read local files or protocols like http/https/rtsp and has no Samba client (#147). Other file managers or even Nova Video Player usually proxy the Samba content through http so it works.

**Comment by magusone** [comment]
Thx for reply but what about FTP? Same as SMB?

**Comment by moneytoo** [comment]
>Same as SMB?

Yes

**Comment by magusone** [comment]
Is there a chance to make it work with FTP in the near future?

**Comment by sigma2017** [comment]
Frankly there is no need. Why are you using kodi in order to establish network connection? use Solid Explorer instead for windows folder sharing or linux samba, or older es file explorer pro for ssh(sftp). Kodi is not anymore what it was.

**Comment by magusone** [comment]
Thx for sugestions.
Kodi from v18 is not very good when it comes to smooth playback. That's why I'm useing older 16.1v, wich in my case plays all files very good except DV (thats why I'm here). I'm useing ftp (works nicely in Kodi). I don't have sftp server on my router so I will stick to ftp for now, but I will check some file explorers to open DV files that way.

Btw, I use Kodi becouse I got used to it (customization etc.).

**Comment by moneytoo** [comment]
Closing in favor of #147 as it is about support of additional protocols.
