### ISSUE TITLE
Default option to disable subtitles

### ISSUE THREAD

**Issue by brentonv** [moneytoo/Player#207]
Could you please consider an option to set the default embedded subtitle selection to "None" or disabled🙏

Thanks

**Comment by brentonv** [comment]
@moneytoo could you please indicate where in your code to disable forced subtitles?

**Comment by moneytoo** [comment]
https://github.com/google/ExoPlayer/issues/6677

**Comment by brentonv** [comment]
Thanks for the developer reference but I don't think I'm smart enough to figure that out😂

**Comment by moneytoo** [comment]
I'm afraid I can't help you much more than that. Subtitles are selected because this is the behavior of ExoPlayer as Just Player doesn't change it. Disabling it will probably require adding some code. And I'm not exactly sure what as I never needed this.
