### ISSUE TITLE
First run show long tap settings options

### ISSUE THREAD

**Issue by brentonv** [moneytoo/Player#209]
On first run of the app it shows the tap/long tap functions for files/subtitles.

Can you please include a second view for tap/long tap the player/settings functions🙏

I've tried experimenting and it seems to require a TapTargetSequence rather than a single TapTargetView

Thanks

**Comment by moneytoo** [comment]
These settings include mostly some really advances options so I'm not sure it would be much of a use to the most of users.

**Comment by brentonv** [comment]
I know some advanced users that installed from Play Store and weren't even aware there were advanced options.

```
// TODO: Explain gestures?
//  "Use vertical and horizontal gestures to change brightness, volume and seek in video"
```

Please consider adding a TapTargetSequence to demonsstrate some of the extra features available.
