### ISSUE TITLE
Allow resizing in such a way that the video doesn't play over a phone's front camera notch.

### ISSUE THREAD

**Issue by creesch** [moneytoo/Player#21]
I'll be frank and admit first thing that I am not entirely sure how other players do it but both youtube, VLC and a few others account for the camera notch in my phone.  From some quick googling it [seems it is possible to do account for](https://developer.android.com/guide/topics/display-cutout) as there is a `LAYOUT_IN_DISPLAY_CUTOUT_MODE_NEVER`  option though I am not sure it can be changed on the fly.

**Comment by moneytoo** [comment]
Just Player intentionally covers whole screen including the area around notch/cutout. I feel strongly about that. Doing this ensures that the picture is centered and symmetrically affected by the rounded screen corners (if there are any).

**Comment by creesch** [comment]
But it isn't symmetrically for me though, there is a hole in the left part of my screen that disrupts the symmetry. 
I'd be absolutely fine if for this to work both sides of the screen are cut off, yes it is less space to play the video in but at least I get to see the entire video.
