### ISSUE TITLE
Adjust Refresh rate doesn't work on Android TV 9

### ISSUE THREAD

**Issue by ZEPLUMBER1** [moneytoo/Player#214]
Even with the option enabled, it stays at 60hz instead of 24

**Comment by brentonv** [comment]
AFR works fine for me on Android TV 9

( NVIDIA Shield Pro 2019 / Samsung UN55C7000 )

**Comment by ZEPLUMBER1** [comment]
Doesn't work on my LG CX, shield 2019 pro. If I use the beta option on the shield or the Refresh Rate app it works tho

**Comment by Poker354** [comment]
I have Nvidia Shield 2019 pro with LG CX. Auto fresh rate works fine except for internet streams. The only time it does not work is if I called up a streaming app (Debrid), like Syncler, Stemio etc. in those cases I use the Match Frame Rate beta feature.

**Comment by ZEPLUMBER1** [comment]
This is still an issue, but yeah I only use debrid services

**Comment by moneytoo** [comment]
There were fixes related to this issue since the last feedback so it should be fixed now. Reopen or create new issue if necessary.
