### ISSUE TITLE
"Play with Just Player" through Share intent

### ISSUE THREAD

**Issue by DarremMolko** [moneytoo/Player#217]
VLC has this feature and I thought it would be a handy addition for Just Player.
![Screenshot_20211119-135235](https://user-images.githubusercontent.com/70179709/142662126-7525a6ad-fd11-46f5-ae95-f6f876759e8a.jpg)
![Screenshot_20211119-135252](https://user-images.githubusercontent.com/70179709/142662156-75f61592-41c3-4e9c-a2e3-aa249fef4634.jpg)

**Comment by hehenaice** [comment]
@moneytoo I second this feature because often opening links within an app is not always forwarded to open with options.
If I can just share it directly, it'll be pretty sweet and easy to use.

**Comment by moneytoo** [comment]
Since something as simple as tapping `https:// ... .mkv` in Google Keep is no longer possible to be handled by a video player on [Android 12](https://www.xda-developers.com/android-12-will-always-open-non-verified-links-in-the-default-browser/), I will support the sharing as an alternative.
