### ISSUE TITLE
Http headers

### ISSUE THREAD

**Issue by aston314** [moneytoo/Player#219]
How I can add custom http headers (eg Referer) for a url?
![227610C9-B687-45A0-B15C-58009B83DA4E](https://user-images.githubusercontent.com/2224932/143569724-120a4d9f-f47c-4726-824f-e07178de34fd.jpeg)

**Comment by aston314** [comment]
Add an option to set referer?

**Comment by jrd-rocks** [comment]
Custom headers would be very useful when using just player as an extremal player with kodi when streaming videos from sources that require authentication

**Comment by aston314** [comment]
yes

**Comment by jrd-rocks** [comment]
> > Passing custom headers in the url like mxplayer would be very useful when using just player as an extremal player with kodi when streaming videos from sources that require authentication
> 
> HTTP Basic Auth should work (#247). What other auth method do you have in mind? Really changing any headers including user agent or cookies?

Thanks, that's part of the puzzle, i was so focused on custom headers i didn't consider where they came from. Full custom headers would be more ideal (as that's how things are passed to kodi's internal player (http://url.com/file.mkv|[headername]=[headervalue %-escaped]&[headername]=[headervalue %-escaped])
