### ISSUE TITLE
Ogg Theora support

### ISSUE THREAD

**Issue by EchedeyLR** [moneytoo/Player#22]
I have several videos in that format and I saw that I could not play them using the player.

**Comment by moneytoo** [comment]
Unforrunately, Theora isn't supported by ExoPlayer. https://github.com/google/ExoPlayer/issues/4970

**Comment by EchedeyLR** [comment]
Thank you for the information, so let's wait for upstream support first.

**Comment by moneytoo** [comment]
Closing as it's tracked at ExoPlayer and there's not really much I can do.
