### ISSUE TITLE
Release build video push error & And if the position is restored then the video does not play

### ISSUE THREAD

**Issue by Th4Park** [moneytoo/Player#220]
When I play video from url in release build, So the video play push button was not working, And the position was being restored in the second video but the play button was not happening.
When playing video from url in release build, there were a lot of problems

‐-------- I have put the video url in this -------------

String mediaOrg1;
Uri mediaOrg;

mediaOrg = "sample.mkv"
mediaOrg = Uri.parse(mediaOrg1)
mPrefs.mediaUri = mediaOrg;

------- Error --------‐---------

https://user-images.githubusercontent.com/76167203/144397140-7b948629-cf96-430b-9941-83863dee4eec.mp4

https://user-images.githubusercontent.com/76167203/144397225-c4d3969c-0ac0-432a-be0e-99656247a15d.mp4

---------------------------------------------------------------------

I debugged it a bit and I see this error

Java.lang.NoSuchMethodException: com.google.android.exoplayer2.ui.d.dispatchPlay [interface q5.e2]

----------------- Device -----------------

Realme 6 
Android 11 
& 
One plus 8t
Android 11

And some devices 

---------------------------------

**Comment by moneytoo** [comment]
This player is just a standalone app. Any other usage is not supported (it's not a library). Feel free to use the code as you wish though.
