### ISSUE TITLE
Autoplay next file?

### ISSUE THREAD

**Issue by wennaspeedy** [moneytoo/Player#222]
It is possible to enable autoplay next file in actual folder?

**Comment by moneytoo** [comment]
Currently there is a button (visible when the playback is near the end) for skipping to a next file in a folder.

**Comment by wennaspeedy** [comment]
It will be great to dont press button while you are watching short video series...

**Comment by Pranab009** [comment]
Please sir add this feature.
This app is too good but some important features are missing Please add this
See this
![Screenshot_20220601-133427_1_1_1k](https://user-images.githubusercontent.com/65340361/186889175-bf5bc1e8-f8d3-4063-ba29-6a0d7a621b6c.png)
