### ISSUE TITLE
Allow locking video orientation in portrait mode

### ISSUE THREAD

**Issue by selurvedu** [moneytoo/Player#227]
Currently the auto-rotation switch button is only displayed in landscape mode. A good example is VLC that auto-rotates by default, but lets you lock the orientation at any time.

**Comment by moneytoo** [comment]
All controls are accessible in portrait as well - the panel is scrollable horizontally.

**Comment by selurvedu** [comment]
Oh, I didn't know that. But I don't see how I can use the rotation button to lock in portrait mode.

**Comment by CodeCubeNeo** [comment]
I agree, it should also have a lock option in portrait mode.

**Comment by selurvedu** [comment]
@moneytoo Thank you!
