### ISSUE TITLE
Allow resizing pop-up player

### ISSUE THREAD

**Issue by selurvedu** [moneytoo/Player#228]
See NewPipe and VLC for reference. NewPipe handles PiP resizing better, since the picture gets resized as you drag it, while the VLC pop-up window gets resized only after you let it go.

**Comment by moneytoo** [comment]
Just Player uses native Android PiP feature which already allows resizing (since Android 11).

**Comment by selurvedu** [comment]
Oh, I see. Though NewPipe uses ExoPlayer as well and allows resizing on Android < 11.

**Comment by DarremMolko** [comment]
> Oh, I see. Though NewPipe uses ExoPlayer as well and allows resizing on Android < 11.

NewPipe uses an overlay (pop-up player) and requires the permission "Draw over other apps" for it to work.

**Comment by selurvedu** [comment]
> NewPipe uses an overlay (pop-up player) and requires the permission "Draw over other apps" for it to work.

@DarremMolko I thought this was the same thing, turns out it isn't. Thanks for explaining.

@moneytoo feel free to close this if you don't intend to overhaul the pop-up player in sake of people who use older Android versions.
