### ISSUE TITLE
Same subtitles different shot in mpv and "just video"

### ISSUE THREAD

**Issue by laraib07** [moneytoo/Player#230]
Same scene with same subtitle are different in mpv and just video.

# mpv
![Screenshot_20211218-235640_mpv](https://user-images.githubusercontent.com/25507825/146652144-ccc91da6-7d84-4364-9d23-fddddb17633f.png)

# just
![Screenshot_20211218-235723_Just_Player](https://user-images.githubusercontent.com/25507825/146652154-48a72aff-2df4-42d3-b26b-961ac752d5fd.png)

**Comment by moneytoo** [comment]
Is that really the same subtitle (language) track in both cases?

**Comment by laraib07** [comment]
Yes, I double checked

The version I am using right now is 0.73 from fdroid. Let me check it on the latest version.

**Comment by moneytoo** [comment]
It looks like SSA/ASS subtitles. Please note that support for this format is still pretty limited: Google/ExoPlayer#8435

**Comment by laraib07** [comment]
okk
I guess I should close this issue now.
