### ISSUE TITLE
special characters like "ã,á" are not rendered correctly

### ISSUE THREAD

**Issue by Luiz-bro** [moneytoo/Player#235]
the player is not rendering special characters present in the caption correctly
![Screenshot_20211226-175257](https://user-images.githubusercontent.com/67080890/147419806-a173777f-c177-4e2f-9940-23c1e5d6700f.png)

**Comment by moneytoo** [comment]
Please share a video/subtitle sample.

**Comment by Luiz-bro** [comment]
as I can't send the dot srt subtitle file, I'll share the link to the site where I downloaded the file:
https://www.opensubtitles.org/pt/ssearch/sublanguageid-por,pob/idmovie-31623

**Comment by Luiz-bro** [comment]
the specific subtitle is from the first episode

**Comment by moneytoo** [comment]
Please describe in more details (step by step), how you open video/subtitle (locally or over network using some client etc.). Because when I try the subtitle file, the file encoding is correctly detected.

![Screenshot_20211227-071416](https://user-images.githubusercontent.com/1071643/147441090-5666e250-6622-4e81-88e6-5142358dc2d9.jpg)

**Comment by Luiz-bro** [comment]
I open the video and then the subtitles all locally from my smartphone memory

**Comment by Luiz-bro** [comment]
first I do the video player, then I activate the subtitles, all files opened directly from the cell phone memory, I downloaded the two files in the internal memory

**Comment by moneytoo** [comment]
Could you try to install this version of [Just.Player.v0.79-debug.apk](https://brouken.com/player/Just.Player.v0.79-debug.apk) and load subtitle again? Do you see any dialog with an error message? If so, please share a screenshot (just beginning of that message should be enough).
