### ISSUE TITLE
Stopped loading

### ISSUE THREAD

**Issue by ampsu** [moneytoo/Player#237]
Hello. 

Player stopped loading files overnight. Everything worked perfectly, but now it wont load a thing. Doesnt matter which format or size, simply keeps loading and if I try to forward in time, it gives codec errors even though those files worked before.

Any insight? Ive cleared data, cache, reinstalled etc. Its running on Android TV, newest version.

**Comment by moneytoo** [comment]
Try restarting your device. Some video decoder related resources may be exhausted (by this or other app).

**Comment by ampsu** [comment]
I restarted and force stopped all apps. Still not loading anything. It loads runtime and subtitles data but nothing else.
