### ISSUE TITLE
unable to play video (Decoder init failed exception) 

### ISSUE THREAD

**Issue by appsoft124** [moneytoo/Player#238]
Som specific video file will not play on a some devices when i play next or prev video from list from local storage after 5 or 6  six videos video is not playing  com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed:
some other devices work fine.
can u solve this issue?

**Comment by moneytoo** [comment]
Share more details, what exact media (MediaInfo output or sample) and what devices.

**Comment by appsoft124** [comment]
i am getting all video list from my local device then i am playing video in just player i am passsing the list to my player screen and getting path from position video is playing fine now the issue is when i click on next video after 6 , 7 videos video not playing got stuck coming this issue >com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed:

**Comment by appsoft124** [comment]
can u add one more function take screen shot from playing video from
current position using custom button

**Comment by appsoft124** [comment]
?????

**Comment by moneytoo** [comment]
I'm afraid I'm unable to help with issues which I cannot duplicate.
