### ISSUE TITLE
subtitles look changes on Firestick 4k Max problem

### ISSUE THREAD

**Issue by magusone** [moneytoo/Player#239]
On my Firestick 4k Max when I change subtitles (size for example) in Fire OS, nothing changes in JustPlayer.

**Comment by moneytoo** [comment]
Does it work with [ExoPlayer Demo](https://brouken.com/player/ExoPlayer-demo-v2.16.1.apk)? In this case, you have to enable the system captions. Then, at least subtitle color and background color should be styled according to selected style (testing the first Subtitle track - "TTML positioning"). Is it working?

**Comment by magusone** [comment]
It's working. Didn't check all options. Sorry for this one, my fault.
