### ISSUE TITLE
4k video seekbar is not working

### ISSUE THREAD

**Issue by RanbirSingh** [moneytoo/Player#24]
Hi Marcel, 
I was testing 4k video but seekbar is not working 
If you seek it keeps restarting the video and click on any position on seekbar is not responding..all other 1080 videos are working perfactly but this 4k MKV video is not working i will test another 4k video but this is working perfectly in MX player!

Thanks

**Comment by moneytoo** [comment]
Hi. Only way to find out what's going on is to examine the video (sample) so try sharing it here (or send me an email - link in profile). What device (and OS version) are you using?
