### ISSUE TITLE
external subtitles not loading through smb or ftp

### ISSUE THREAD

**Issue by magusone** [moneytoo/Player#240]
I'm using X-plore File Manager to load my movies through smb or ftp and play in JustPlayer on my Firestick 4k max. It's working nice but my external subtitles (.srt) not loading.

**Comment by moneytoo** [comment]
The combination of X-plore and SMB works and loads subtitle file on my phone. How about some other device of yours, does it work from your phone? What are the filenames of the video and subtitle?

**Comment by magusone** [comment]
Same thing on my phone. Filenames are the same (video and sub). Maybe this is SMB1 problem? Strange, in Kodi everything is ok.

**Comment by moneytoo** [comment]
It could be SMB1 thing. It depends on the path structure / how file managers expose the path in uri. Kodi manages SMB on its own so it's something different. You could try other player that loads external subtitles over network (I know MX Player does) and check if that works with X-plore.

**Comment by magusone** [comment]
Ok I've done some testing and for me it was X-plore fault. For example with MiXplorer everything is ok, so I'll stick with it. 
Anyways, thx for help!
