### ISSUE TITLE
Load external .srt (and remembering it as a track)

### ISSUE THREAD

**Issue by mycek91** [moneytoo/Player#242]
Hello,
Please can you add an option to load external .srt from different folder?And remember the external srt after opening video again.
Many thanks for this wonderful player!

**Comment by moneytoo** [comment]
Do you mean like to have one central folder for all subtitles or just to have an automatic lookup not in the current folder but some (defined?) nested folder like `sub`/`subs`? You can already load the subtitle file manually but you want to achieve that automatically, right?

**Comment by mycek91** [comment]
Yes i would  like to have the ability to set default folder for subtitles e.g internal storage/subtitles.
And when i open again video JVP to remember previosly selected external .srt.
Sorry for my english.
And again thanks for this great player 🙂
I doesn't mean automatic selection.This can be quite problematic.
