### ISSUE TITLE
Support for loading more subtitle format files through the network

### ISSUE THREAD

**Issue by 0x79696e67** [moneytoo/Player#243]
v0.69 supports loading subtitles over the network, but only .srt subtitles are supported. 
Please support .ass, .ssa, .vtt subtitle format files.

**Comment by moneytoo** [comment]
I was waiting whatever someone will actually request this. So you actually use these types of subtitles in your use case? Do you know if any other video player support loading of such subtitle formats over network.

**Comment by 0x79696e67** [comment]
In my practical use, srt and ass are used most often. Nova Video Player supports loading srt and ass from the network.
