### ISSUE TITLE
App crashes on TCL 65R646 (Google TV)

### ISSUE THREAD

**Issue by TonivaSD** [moneytoo/Player#245]
Hi,

First of all, great app!  Its the only player (app) that will play my Dolby Vison files on my TCL 65R646 (Google TV), however, it crashes all the time. My screen will go blank and the TV doesn't respond to the remote. It happens mostly when I navigate to a new file and try to play it.  The screen will go blank and I have to unplug it to get the TV restarted. I typically use Plex but notice my DV movies fall back to HDR10 and not show the DV tag.

Any help would be appreciated.  

-Peter

**Comment by moneytoo** [comment]
How do you navigate to this new file? Using the file browser from within Just Player?

I personally never tried DV but I hear that a special version of [Kodi](https://forum.kodi.tv/showthread.php?tid=360018) should handle that. Maybe you could also try Vimu (or possibly Jellyfin/Emby).

The standard way of analyzing that would be capturing and sharing a [bug report](https://developer.android.com/studio/debug/bug-report) but that would require doing that after the problem occurs. Do I understand that you're saying that in your case the system is not responding and you cannot even "press home" and exit Just Player?

**Comment by TonivaSD** [comment]
> How do you navigate to this new file? Using the file browser from within Just Player? **Yes.  Open the app and use the File icon on the bottom right**
> 
> I personally never tried DV but I hear that a special version of [Kodi](https://forum.kodi.tv/showthread.php?tid=360018) should handle that. Maybe you could also try Vimu (or possibly Jellyfin/Emby). **I'm pretty sure there is only one version of Kodi available to install from the Apps section of the TV.  I will try to see if Vimu is available.  Jellyfin/Emby are both server based and I will check to see if I can install on my Netgear NAS.  I already have Plex installed on my NAS and thats my main media streamer**
> 
> The standard way of analyzing that would be capturing and sharing a [bug report](https://developer.android.com/studio/debug/bug-report) but that would require doing that after the problem occurs. Do I understand that you're saying that in your case the system is not responding and you cannot even "press home" and exit Just Player?  **Yes correct.  The screen will go blank and the TV doesnt respond at all to any buttons on the remote when I get a crash.**

**Comment by moneytoo** [comment]
Do regular non DV videos work?

Maybe you could try toggling the options _Auto frame rate matching_ and _Tunneled playback_ options in advanced settings (see the readme of this repository on how to access it).

**Comment by TonivaSD** [comment]
> Do regular non DV videos work?
> 
> Maybe you could try toggling the options _Auto frame rate matching_ and _Tunneled playback_ options in advanced settings (see the readme of this repository on how to access it).

Thanks again for the support and quick replies.  I'm playing them off a powered USB external HD connected to the TV and only testing DV files right now. I will add some regular HDR 4K on there and see if they play without issues.  I will check the options you mention and report back.

FYI... I installed Vimu last night and it played the files without issues and with the DV tags!  Thx for the recommendation.  I want to continue to see if I can get Just Player working, but at least I have a backup appp for now.  

Thanks!
