### ISSUE TITLE
Dolby Vision Purple Screen TCL and iFFalcon TV

### ISSUE THREAD

**Issue by Rubarius** [moneytoo/Player#246]
Hello.

On TCL 615 or IFFalcon TV, when watching movies, the Dolby Vision mode is activated, but since. it is not supported picture purple or green. In Vimu player, there is a switch in the settings that disables Dolby Vision and such films receive HDR. Is it possible to screw such a switch, I can’t watch almost all films in normal quality on JustPlayer. I hope for you!

**Comment by moneytoo** [comment]
I will track related option for HDR playback in #270. Not sure if your video is also DV profile 7 or something else though.
