### ISSUE TITLE
VTT subtitles embedded don't appear

### ISSUE THREAD

**Issue by MasterDudess** [moneytoo/Player#249]
Just player is able to load the following subtitles: * Subtitles: SRT, SSA, TTML, VTT. Normally I load the video file and then longpress to load the VTT subtitle and it works perfectly. Only when I embed the subtitle in the videocontainer (for example mkv) then it doesn't appear to load in the player. SSA and SRT files do work embedded. Is it possible to make this workable for VTT subtitles too?

Many thanks in advance!

**Comment by moneytoo** [comment]
Could you provide a sample? Do embedded VTT subtitles work with other players?

**Comment by MasterDudess** [comment]
I have tested it in multiple players: Kodi, Vimu, Nova Player but those players do not support VTT at all. Exo player may support it but does not have a sideload subtitle function. It seems your Just Player is one of a view that support it. Normally its not a problem because I longpress and load the VTT file but since the Android TV 11 I don't see any files anymore  (other topic). Thats why for now I wanted to embed it. I made a test file (DV) so maybe you can test it yourself. Ik hope you can support it

Here is the link (Expires in 7 days): 
https://easyupload.io/ce1r1r

**Comment by moneytoo** [comment]
Re upload of sample: https://brouken.com/tmp/dolby-vision.mkv

**Comment by marek22k** [comment]
I would also like this feature. yt-dlp, for example, downloads all subtitles in vtt format. I have the following options for watching the videos with subtitles:
1. convert subtitles to .srt with ffmpeg.
2. use VLC Media Player.

Both options are not really nice.
