### ISSUE TITLE
Filter option in file selection disappearing when activating filter for files from "This week"

### ISSUE THREAD

**Issue by engelhro** [moneytoo/Player#25]
Hello,

Just a few minutes after discovering "Just Player" I came across a first bug ☺.

# Background information

- **Device**: OnePlus 7 Pro
- **OS**: Oxygen OS 10.0.10.GM21BA (Android 10)

The problem might be specific to OnePlus' file selection dialogue, but I haven't seen the behavior described below in any other app so far. So maybe it's a combination of both, OnePlus tooling and the movie player app.

# Description

- In the file (movie) selection dialogue there are two filter buttons at the top, one for big files and the other one for recent files (from this week). For me the dialogue starts with the "Most recent used" view ("Zuletzt verwendet" in the screenshots, as these show the German UI).
- The first toggle (for big files) can be selected and deselected just normally (with appropriate effect on the list of files shown below, cropped in the screenshots).
- The second toggle however kind of "disappears" (together with the first one, the whole row seems to be redrawn) when you try to click it. I think I can still recognize a shifted/distorted part of the button edge, but that's it.
- The toggle cannot be deselected anymore afterwards. You actually have to close the dialogue (return to the current movie) and re-open it prior to be able to continue (the filter itself cannot be applied).

# Screenshots

1. The "big files" filter active, this works:

	![Screenshot_20210113-213152_cropped](https://user-images.githubusercontent.com/7052132/104616963-32f08b00-568b-11eb-980c-5bfcb426ec29.jpg)

2. Now I selected the "this week" filter, result:

	![Screenshot_20210113-213200_cropped_annotated](https://user-images.githubusercontent.com/7052132/104617234-7e0a9e00-568b-11eb-9447-43aef6b99ad8.jpg)

	 As you can see, the filter panel looks a little bit empty and unexpected now…  The red rectangle (added by me) highlights the area where I think a part remains of the original button.

Thanks for having a look!

**Comment by moneytoo** [comment]
Unfortunately this is an issue in Google's Files app. It is used as system file chooser which this player uses. So try describing this on OnePlus or Android issue tracker.

I also have OnePlus 7 (non-Pro) and I also noticed that sometimes the "This week" label/action sometimes weirdly jumps but it has never glitched like you describe. I'm also not able to replicate it every time.
