### ISSUE TITLE
Frame rate switching nVidia Shield TV

### ISSUE THREAD

**Issue by Renoria** [moneytoo/Player#252]
Glad I found this app and I have used it extensively since I came across it. Couldn’t help but notice that frame rate switching is not working anymore. Unsure if it’s a bug with Just Player or my device

**Comment by moneytoo** [comment]
Since v0.85, the switching is off by default. Do you have it enabled in advanced settings (long press the ⚙️ gear icon to access it)?

**Comment by Renoria** [comment]
> Since v0.85, the switching is off by default. Do you have it enabled in advanced settings (long press the ⚙️ gear icon to access it)?

works now! thank you 😄 curious to know, why is it off by default?

**Comment by moneytoo** [comment]
Right now the top reason for me is that as more people use Just Player, some people just don't know about AFR and complain that when launching/exiting the app screen switches to black for a few seconds. Those who are searching for it can find it (it's on the home page) and I am eventually thinking about making the secret settings screen more visible.

**Comment by Renoria** [comment]
> Right now the top reason for me is that as more people use Just Player, some people just don't know about AFR and complain that when launching/exiting the app screen switches to black for a few seconds. Those who are searching for it can find it (it's on the home page) and I am eventually thinking about making the secret settings screen more visible.

thought it was some limitation or a technical thing. it actually makes perfect sense 😄 thanks for the awesome app and for being so responsive!
