### ISSUE TITLE
Problem with E-AC-3

### ISSUE THREAD

**Issue by rudnypc** [moneytoo/Player#253]
Hi,

When I play some mkv with the format E-AC-3, the audio is muted. Is it normal?

Audio
ID                             : 2
Format                         : E-AC-3
Format/Info                    : Enhanced AC-3
Commercial name                : Dolby Digital Plus
Codec ID                       : A_EAC3
Duration                       : 55 min 52 s
Bit rate mode                  : Constant
Bit rate                       : 640 kb/s
Channel(s)                     : 6 channels
Channel layout                 : L R C LFE Ls Rs
Sampling rate                  : 48.0 kHz
Frame rate                     : 31.250 FPS (1536 SPF)
Compression mode               : Lossy
Stream size                    : 256 MiB (10%)
Language                       : English
Service kind                   : Complete Main
Default                        : Yes
Forced                         : No

My system is:
Android 7.1.2
Kernel 3.14.29
Model Tx3 Mini

**Comment by mo123** [comment]
@rudnypc  Android 7 is too old to support all the audio formats most likely.

**Comment by rudnypc** [comment]
> @rudnypc Android 7 is too old to support all the audio formats most likely.

But I can play using the vlc and Fermata Media Player

**Comment by mo123** [comment]
@rudnypc Tested now, seems to also be a problem on newer Android.

@moneytoo E-AC3 audio is silent on AndroidTV 10/11.
In Kodi & Nova Video player it plays correctly.
Anyway to fix it?

**Comment by moneytoo** [comment]
Has your device/TV E-AC3 decoding capability? Could be an issue related to passthrough. However Just Player doesn't really do anything related to that on its own as this is mostly handled by the default behavior of ExoPlayer. So any such issue would be best to replicate (in ExoPlayer demo) and report directly to the ExoPlayer team.

**Comment by rudnypc** [comment]
But is the exoplayer with ffmpeg shouldn't fix that problem?

**Comment by moneytoo** [comment]
Just Player is configured in a way to prefer device decoders. If your device is reporting E-AC3 capability, the audio output is sent directly without decoding (bitstream/passthrough). Otherwise it's decoded by the FFmpeg extension.

**Comment by rudnypc** [comment]
Can I force the ffmpeg?

**Comment by mo123** [comment]
Can't Just Player use IEC61937 passthrough with ffmpeg like Kodi then all audio formats will play correctly?
Add a setting so you can choose the passthrough method you want to use?
90% of devices don't have hardware audio codecs, only Nvidia Shield and some others, most use IEC61937 and not RAW passthrough.

**Comment by moneytoo** [comment]
Try this version: [Just.Player.v0.97-decoders.apk](https://brouken.com/player/Just.Player.v0.97-decoders.apk) (or wait a few days for a release in the beta channel on Google Play). Long tap the ⚙️ gear button and switch _Decoder priority_ to _Prefer app decoders_.

**Comment by edwrap** [comment]
Sorry to bump this, but is it possible to get an updated apk with the decoders included, or ideally just built with every release?

This wasn’t an issue on a Samsung Tab S6, but over the past few weeks I’ve tried Just Player on a few low end Android TV devices (Hisense A6G, Hisense U6HF, Dynalink 4K box) and all of them error out when decoding various audio formats.

**Comment by Learner00100** [comment]
> Try this version: [Just.Player.v0.97-decoders.apk](https://brouken.com/player/Just.Player.v0.97-decoders.apk) (or wait a few days for a release in the beta channel on Google Play). Long tap the ⚙️ gear button and switch _Decoder priority_ to _Prefer app decoders_.

@moneytoo @mo123 
Is this apk has IEC61937 passthrough with ffmpeg?
