### ISSUE TITLE
 add sound

### ISSUE THREAD

**Issue by TeaqariaWTF** [moneytoo/Player#254]
Sometimes the videos I download come with embedded English audio. I want to play them with a different audio file just like in mx player, I wonder if such a feature can be added.

**Comment by TeaqariaWTF** [comment]
> Sometimes the videos I download come with embedded English audio. I want to play them with a different audio file just like in mx player, I wonder if such a feature can be added.

Likewise, subtitle files should also be added.

**Comment by moneytoo** [comment]
> To load external (non-embedded) subtitles, long press the file open action in the bottom bar. The first time you do that, you will be offered to select root video folder to enable automatic loading of external subtitles.

**Comment by TeaqariaWTF** [comment]
> > To load external (non-embedded) subtitles, long press the file open action in the bottom bar. The first time you do that, you will be offered to select root video folder to enable automatic loading of external subtitles.

Thank you, I have solved the subtitle issue, can I add an audio file in the same way?

**Comment by TeaqariaWTF** [comment]
video stays on black screen there is sound but no picture

https://gofile.io/d/QD4S24

**Comment by moneytoo** [comment]
> video stays on black screen there is sound but no picture
> 
> https://gofile.io/d/QD4S24

Looks like a video in VC-1 format. Unfortunately, this is not natively supported by Android and therefore also not available in ExoPlayer and Just Player.
