### ISSUE TITLE
Load external subtitles issues

### ISSUE THREAD

**Issue by Eisa01** [moneytoo/Player#258]
SolidExplorer sometimes is unable to detect external subtitles with language prefix to them, e.g.: `video.en.srt`, `video.ar.srt` and pass them to Just Player

Also the player is unable to detect multiple external subtitles and only shows the first detected subtitle. e.g.: I have  `video.en.srt`, `video.ar.srt`, `video.es.srt`. Player only detects `video.ar.srt`

**Comment by moneytoo** [comment]
> SolidExplorer sometimes is unable to detect external subtitles with language prefix to them, e.g.: video.en.srt, video.ar.srt and pass them to Just Player

Try finding the specific case. There are various conditions in play - whatever you are using local storage (is the video and subtitle within the folder of granted scoped access) or remote (also what kind of service is that).

> Also the player is unable to detect multiple external subtitles and only shows the first detected subtitle. e.g.: I have video.en.srt, video.ar.srt, video.es.srt. Player only detects video.ar.srt

Yes, currently only one subtitle file is supported. It's partly because of a limitation in the current version of ExoPlayer but they already fixed that so I should be able to improve that after the next update of ExoPlayer.

**Comment by Eisa01** [comment]
That is really great to hear! It will make my Android TV get back to its glory when the update is out.

Also, to pinpoint the exact case of the issue (when subtitles are not loading) it will take me a lot of time as the case is not clear. 

I will be checking different encodings / extensions / languages / apply more tests to know what exactly is triggering the issue and will update you once it is clear.

**Comment by Eisa01** [comment]
I believe I found some use cases when subtitles are not detected when using SolidExplorer

1- Any `.ass` subtitle with language prefix before it, is not detected. **Examples:**
- `video.es.ass` is not detected.
- `video.en.ass` is not detected. 
- `video.ass` is detected.

2- Any `.srt` subtitle with language prefix other than `.en` is not detected. **Examples:**
- `video.ar.srt` is not detected.
- `video.jpn.srt` is not detected.
- `video.en.srt` is detected.
- `video.srt` is detected.

**Comment by moneytoo** [comment]
1. The language variants are currently enabled only for SRT subtitles. As I use this the most, I know that this is the convention and I was also able to find it documented on the web. Is this even documented anywhere for SSA/ASS? (I understand that I can always try some apps or look into the source code...)
2. The search is limited to languages defined in the OS settings, including its priority.

**Comment by Eisa01** [comment]
From what I tested so far, usually players apply the same logic for loading external subtitles to all supported types (so whatever applies to .srt, applies to all other supported formats). Though that is only possible, if Just Player has the capability to do that. 

The support of language prefixes usually extends to ISO 639-1 and ISO 639-2 universal standards. (I am not sure if current implementation of OS settings allow for that)
https://www.loc.gov/standards/iso639-2/php/code_list.php

So prefix support extends to `video.en.ass`, `video.eng.ass`. To make it more user friendly, players also support the native name as prefix `video.english.ass`.

Also, players add further capability, such as Emby for forced/default subtitle `video.en.forced.srt`. Hearing impaired `video.en.sdh.srt` along with much more as seen below:
https://support.emby.media/support/solutions/articles/44001159160-subtitles

**Comment by ShareASmile** [comment]
Has this issue been resolved by above commit, if yes then close?
