### ISSUE TITLE
Can not use remote control on TV BOX

### ISSUE THREAD

**Issue by aston314** [moneytoo/Player#26]

**Comment by moneytoo** [comment]
Can you be more specific? What box (model) are you using? What controls are you trying? Are you able to pause playback when Just Player is playing in foreground?

Generally remote controls should work (as the player uses mediasession), for example buttons on Bluetooth headset etc.

**Comment by aston314** [comment]
I use ZIDOO X9S.
When the toolbar dispear,I can not use the remote control do anything.Just can exit.
Can not forward or control the sound.

**Comment by moneytoo** [comment]
It should work with pure media buttons (play/pause, volume) but it doesn't work with navigation/arrow keys. I tried the player on Android TV (mi box) and it's probably the same case. Currently only touchscreen is supported, but this is something I would like to improve.

**Comment by aston314** [comment]
Thank you.

**Comment by Pentaphon** [comment]
I don't think this player is really meant for remote control aka Android TV use. There's other players that already do that like Nova, VLC and KM and it took a LOT of work for those players to get to that point. I think of this player as a tiny but capable player for touchscreens only. I see JustPlayer as an alternative to mpv-android and that's fine with me because they have different backends.

**Comment by aston314** [comment]
My wrong.
Have uninstalled.

**Comment by moneytoo** [comment]
Supporting TV boxes based on pure Android should be doable and I will try that eventually. UI should be controllable already if focus is working (might needs tweaking here and there) and then there are only missing playback controls using navigation keypad.

Android TV is a bit complicated as there's no system file chooser built in but a single library can fix that.

**Comment by Pentaphon** [comment]
> Android TV is a bit complicated as there's no system file chooser built in but a single library can fix that.

If you do support Android TV, you will definitely get people who ask for FireTV support since there's way more users of those devices but it shouldn't be hard to make sure both are supported. 

Thanks for opening this player up to more devices.

**Comment by moneytoo** [comment]
Latest version (v0.20 - [currently pre-release here](https://github.com/moneytoo/Player/releases/tag/v0.20-wip4)) includes improvement that should make it usable on Android TV. Though:

Android TV is missing native file chooser so opening files from within Just Player isn't currently supported. If you install [Material Files](https://github.com/zhanghai/MaterialFiles), you will be able to open files, but from internal storage only. If you need to open file from external storage, select and open it from a file manager. Pretty good and simple is this [File manager](https://play.google.com/store/apps/details?id=com.hitv.explore).

Let me know what could be improved (except for adding file chooser, obviously). I may eventually add built in file chooser but the only device I have (Mi Box S) is actually pretty buggy and resizing picture doesn't work correctly so that's something I want to resolve first.

**Comment by joaopedromfigueiredo** [comment]
> Latest version (v0.20 - [currently pre-release here](https://github.com/moneytoo/Player/releases/tag/v0.20-wip4)) includes improvement that should make it usable on Android TV. Though:
> 
> Android TV is missing native file chooser so opening files from within Just Player isn't currently supported. If you install [Material Files](https://github.com/zhanghai/MaterialFiles), you will be able to open files, but from internal storage only. If you need to open file from external storage, select and open it from a file manager. Pretty good and simple is this [File manager](https://play.google.com/store/apps/details?id=com.hitv.explore).
> 
> Let me know what could be improved (except for adding file chooser, obviously). I may eventually add built in file chooser but the only device I have (Mi Box S) is actually pretty buggy and resizing picture doesn't work correctly so that's something I want to resolve first.

Thanks for that!

**Comment by moneytoo** [comment]
I'm adding [android-file-chooser](https://github.com/hedzr/android-file-chooser) to the `-online` builds (starting `v0.36`) so you can properly open files on Android TV. Comparing to using Material Files, the new file chooser is able to access USB storage and navigation starts in the last opened folder so it should be more pleasant to use.

There's also support for auto frame rate switching: https://github.com/moneytoo/Player/issues/98

If you want to test it early, download a build from https://brouken.com/player/

**Comment by Santos2004** [comment]
no disk selection

in version 0.36 you can choose either internal storage or disk in Fat32.  the disk in exfat is not listed at all

**Comment by Santos2004** [comment]
correction.  
it's about the master boor record.  Only! if the disk partitions are in it, then everything is fine.  if in GUID Partition Map then your explorer does not see either exFAT or Fat32.  But all other programs and Android see everything correctly.

**Comment by moneytoo** [comment]
@Santos2004 Is that Android TV device or some other Android box? Did you use file chooser in the previous versions? If yes, then download newer version from: https://github.com/moneytoo/Player/releases/tag/v0.36

**Comment by moneytoo** [comment]
As I wrote in https://github.com/moneytoo/Player/releases/tag/v0.36

> Right now the changes related to better support for TV boxes are only in the -online version. After more testing/feedback, it will be probably unified. (I will attempt to include Android TV in distribution on Google Play.)

Finally, I think that Just Player should be usable on Android TV / TV boxes. I'm personally starting to use it as my primary player even on Android TV. I made lots of improvements and feel good about that (at least within the limits of this simple player and my abilities 😜). So let me know about your experience.

**Comment by Santos2004** [comment]
Thank you so much ended. Last version working correctly with usb disk exfat on GUID Partition Map. 
But. Files on mp4 with Dolby Vision playing with drop frames. Files mkv playing on same disk correctly. It's very old problem. 0.34 too. May be early. It's just player problem only. Other players working correctly
Please fix it too! Thank you

**Comment by aston314** [comment]
Can not switch subtitles on TV.

**Comment by moneytoo** [comment]
> Can not switch subtitles on TV.

What Android OS version has your device? There's an issue with older OS versions (at least on 7.0): https://github.com/google/ExoPlayer/issues/9061 Could that be this case?

**Comment by aston314** [comment]
Android 6

**Comment by moneytoo** [comment]
> Android 6

Thats probably the mentioned ExoPlayer issue. I reported this to them only two days ago so lets wait for their response.

**Comment by Santos2004** [comment]
Beautiful file manager here.
Hire is good file manager as part of Torrserve

https://github.com/YouROK/TorrServe/tree/master/app/src/main/java/ru/yourok/torrserve/ui/dialogs

**Comment by vladlenas** [comment]
I support, in 0.37 the manager opens the file in com.android.documentsui. On boxes with Android TV, this does not work from the remote control.

> > Android 6
> 
> Thats probably the mentioned ExoPlayer issue. I reported this to them only two days ago so lets wait for their response.

I support, in 0.37 the manager opens the file in com.android.documentsui. On boxes with Android TV, this does not work from the remote control.

**Comment by Santos2004** [comment]
Yes it's true

**Comment by MadAndron** [comment]
Perhaps the best solution would be to make a system file open dialog. That is, make a choice which file manager to open

**Comment by moneytoo** [comment]
> I support, in 0.37 the manager opens the file in com.android.documentsui. On boxes with Android TV, this does not work from the remote control.

I try detecting whatever there's documentsui even on Android TV as I believe I read somewhere that some devices like Nvidia Shield actually support that. This worked for me on my Xiaomi Mi Box S and Android TV emulators (as they don't have such [stubs](https://stackoverflow.com/questions/64082063/on-some-devices-action-open-document-tree-doesnt-show-the-chooser#comment113318551_64082063)). However I also had a problem on other Android TV box (from Geniatech) and the only option was to blacklist that.

I guess I will switch to using the custom file chooser on all the Android TV devices and boxes (if at least the detection will work correctly). Offering choice from multiple file choosers would be the last resort (as it brings one more step, probably requires new translatable strings etc.).

**Comment by vladlenas** [comment]
> I try detecting whatever there's documentsui even on Android TV as I believe I read somewhere that some devices like Nvidia Shield actually support that.
Shield 2019 Pro - opens in documentsui and it doesn't work.
Tivo 4K Stream and Chromecast with Google TV - "You don't have an app that can do this".
Fire TV Stick 4K - opens in the Fire OS manager, but there I have a root and froze the documentsui.))

**Comment by moneytoo** [comment]
@vladlenas Please try [Just.Player.v0.38.apk](https://brouken.com/player/Just.Player.v0.38.apk). The system file chooser (documentsui) shouldn't be used on these devices at all. (If device is either `television` or `notouch`.)

**Comment by vladlenas** [comment]
> @vladlenas Please try [Just.Player.v0.38.apk](https://brouken.com/player/Just.Player.v0.38.apk). The system file chooser (documentsui) shouldn't be used on these devices at all. (If device is either `television` or `notouch`.)

Now on all my devices opens the file chooser.

**Comment by vladlenas** [comment]
But I still don't use Just to open files, since I have all the content on Nas. I don’t have any problems to open in another manager and select Just. But for those who have a hard drive connected, this is a very useful feature.

**Comment by vladlenas** [comment]
And yet, the bad thing is that when you open the player, the last video starts immediately. If opened from another manager or using TorrServe, we always get a "resource error" after closing opening of the player. 
It would be nice to be able to disable this feature.)

**Comment by Santos2004** [comment]
and the choice of file also does not work quite correctly.  I have an sd card and a usb disk in the console.  I see only sd.  when I remove sd I start to see the disk.  but not both at once !!!  but must see both !!! '  here's a much better file chooser:

https://github.com/YouROK/TorrServe/tree/master/app/src/main/java/ru/yourok/torrserve/ui/dialogs

**Comment by moneytoo** [comment]
@Santos2004 I will look into that.

**Comment by moneytoo** [comment]
@Santos2004 I'm adding a workaround to list the content of `/storage` where are the mount points of all removable volumes.

**Comment by Santos2004** [comment]
> @Santos2004 I'm adding a workaround to list the content of `/storage` where are the mount points of all removable volumes.

Cool. Where new release?😀

**Comment by moneytoo** [comment]
@Santos2004 You can try it here: [Just.Player.v0.38b.apk](https://brouken.com/player/Just.Player.v0.38b.apk)

**Comment by Santos2004** [comment]
> @Santos2004 You can try it here: [Just.Player.v0.38b.apk](https://brouken.com/player/Just.Player.v0.38b.apk)

This release working perfect. 
Great work!
Thank you so much!!!

**Comment by Santos2004** [comment]
Can you add more details in sound tracks choice? Name of translater for example...

**Comment by moneytoo** [comment]
@Santos2004 Thanks for confirming. I can eventually improve it to list all individual volumes but that should be enough at least for now.

> more details in sound tracks choice

If you can, create separate issue and share same details about the media (and provide at least Media info output). Cause I'm not really sure if there is some info like that in general - as I already print the track label.

**Comment by Santos2004** [comment]
sorry for the slight inaccuracy.  we are only talking about multitrack mp4!  everything is fine in mkv files.  but maybe you can extract more complete information like windows or plex already does?

**Comment by moneytoo** [comment]
> Can not switch subtitles on TV.

ExoPlayer devs already already fixed the underlying issue so I included it in [v0.38](https://github.com/moneytoo/Player/releases/tag/v0.38). That should allow full usage on Android TV/boxes.

**Comment by moneytoo** [comment]
Just Player is now available on Google Play even for Android TV devices. I believe that the original issue is resolved now so I'm going to close this one. But feel free to create any new issue. Thank you all for all the feedback and patience!
