### ISSUE TITLE
[Feature Request] External subtitle support through INTENT for Media Servers Capabilities

### ISSUE THREAD

**Issue by Eisa01** [moneytoo/Player#262]
Let me just say this before proceeding with the request.. "Your player is beautiful"
I intend to use this player as the default for my **Jellyfin Server** on Android TV due to its capabilities and all. 

This will allow Just Player to support external subtitle for videos loaded through media servers.

Currently the only feature I need for that is subtitle support through INTENT, because servers pass any external subtitle through INTENT and from there the player should be able to detect it.

Here you can see pull request for Jellyfin that adds support of INTENT towards external players in Android.
https://github.com/jellyfin/jellyfin-android/pull/177/files
And for Android TV, this line might be interesting:
https://github.com/jellyfin/jellyfin-androidtv/blob/8c01a3d0ebd98355c4f068767f6ed4920a664767/app/src/main/java/org/jellyfin/androidtv/data/compat/StreamInfo.java#L342

Let me know if there is anything else I can provide to help with the request.

**Comment by moneytoo** [comment]
Try this build: [Just.Player.v0.99-api-subs.apk](https://brouken.com/player/Just.Player.v0.99-api-subs.apk)
Just Player should show the subtitle file selected in Jellyfin.

**Comment by Eisa01** [comment]
Amazing, how this works. However, it requires the subtitle to be pre-selected in Jellyfin, which is not available in Android TV as a regular option. 

Is it also possible to have an implementation similar to mpv player where I can cycle through all available subtitles shown in Jellyfin?

**Comment by moneytoo** [comment]
This one should list all subtitles: [Just.Player.v0.99-api-subs2.apk](https://brouken.com/player/Just.Player.v0.99-api-subs2.apk)

**Comment by Eisa01** [comment]
This works beautifully..
It is listing all subtitles without issues and I can cycle through them. It even saves the duration for continuing playback. I am thankful =)

The android client works fine though. However, there is bug in Jellyfin Android TV client (it doesn't pass subtitles to MX Player or Just Player) (only MPV player works). I think I will be opening an issue with them and track it there.
However, I have shifted to Synology DS Video for my Android TV and tested. It immediately worked out fine with all subtitles listed and duration.

Thank you once again, my family and I can now enjoy watching together. =)

**Comment by Root-FTW** [comment]
None of the above works on a Fire Stick 4k, I keep insisting that it should have support to be able to download subtitles from OpenSubtitles
