### ISSUE TITLE
Android TV can't play LAN video, android phone can play

### ISSUE THREAD

**Issue by GYT-cool** [moneytoo/Player#263]
No problem with local playback , but If you open a video on the LAN through the file manager, the following error will occur. 
![20220204140846](https://user-images.githubusercontent.com/45682244/152549445-4552bc4f-02b8-4aee-8ce6-8624ef405179.jpg)

**Comment by moneytoo** [comment]
What file manager & device & OS version is that?

**Comment by GYT-cool** [comment]
ES File Explorer & CHANGHONG Android TV & Android 8.0.0 API level 26 (kernel: Linux 4.9.44)
This is the version I use: [ES File Explorer v4.2.4.5.0 Derrin.zip](https://github.com/moneytoo/Player/files/8008179/ES.File.Explorer.v4.2.4.5.0.Derrin.zip)
Google Cloud Drive: [ES File Explorer v4.2.4.5.0 Derrin.apk](https://drive.google.com/file/d/1ovH9OMqQCPHzd625JEs5jPPnkqwEQ34F/view?usp=sharing)

**Comment by moneytoo** [comment]
Trying the latest version of ES File Explorer version 4.2.8.7.1 from [apkmirror](https://www.apkmirror.com/apk/es-global/es-file-explorer/es-file-explorer-4-2-8-7-1-release/) on my phone and it works just fine with SMB. Just like with any other file explorer, as long it runs in the background.

**Comment by Pentaphon** [comment]
I suggest using https://github.com/nova-video-player/aos-AVP if LAN play is important to you you can also configure Nova to use Just as an external player. Or you may want to try other file managers with better SMB support in conjunction with Just.

**Comment by GYT-cool** [comment]
Thanks a lot, after I set ES File Explorer to run in the background, the above error does not appear again.
Compared with SMB, I prefer to use ftp, the speed of ftp is obviously faster than that of SMB.
