### ISSUE TITLE
Enable-disable dolby vision in setting

### ISSUE THREAD

**Issue by denon480** [moneytoo/Player#270]
Marcel can you **please** make switch in setting disable-enable dolby vision?
I have nvidia shield 2019 pro with dolby vision, tv sony without dolby vision, some movies with dolby vision and hdr10 can't switch to hdr mode on my tv. For example  this setting appeared in vimu player and when i disable dolby vision i can watch movie with hdr10 because my tv switch to hdr mode
I don't know how it happens but it works.
Thank you for this great player.

**Comment by moneytoo** [comment]
I will add option to allow playback of DV profile 7 videos as HDR/HEVC.

**Comment by vegedb** [comment]
>Duplicate of https://github.com/moneytoo/Player/issues/270. Is this about DV profile 7 or some other profile?

I'll answer it here.

Apparently what we're trying to play are Dual Layer.
This is a quote from makemkv website, hope it helps.

`All UHD discs use Dolby Vision Profile 7, which is dual layer. The first, base layer is standard HDR10. The second layer is known as the "Enhancement layer." Enhancement Layers come in two varieties. Some titles use a so-called "Full Enhancement Layer" aka FEL. A FEL contains dynamic tone mapping metadata (aka "RPU"), as well as residual information that boosts the video bit depth from 10 to 12 bit. Other titles use a so-called "Minimum Enhancement Layer" aka MEL. A MEL only contains the RPU and does not contain any residual information.`

`The current version of MakeMKV creates .mkv files that retain all of the information stored in the Dolby Vision Enhancement Layer. However, few players are capable of playing back the Enhancement Layer, and even fewer players are capable of decoding the residual color information contained in a FEL.`

**Comment by moneytoo** [comment]
Available in [v0.126](https://github.com/moneytoo/Player/releases/tag/v0.126).
