### ISSUE TITLE
Error when playing a video. Plays fine on VLC.

### ISSUE THREAD

**Issue by Some1ls** [moneytoo/Player#271]
![Imgur](https://i.imgur.com/A9uWSZR.jpg)

![Imgur](https://i.imgur.com/5xUSpcp.jpg)

**Comment by moneytoo** [comment]
What is your device/model? Does it have HDR display?
Unlike VLC, Just Player uses ExoPlayer which doesn't bundle any external video decoders and relies solely on device decoders. If device has no decoders for 10 bit HEVC, then there's not really much to do.
