### ISSUE TITLE
[Request] Dolby Digital AC3 Transcoding option

### ISSUE THREAD

**Issue by Nuklear92** [moneytoo/Player#272]
Greetings, loving the player and it's my go to for playing all my media ever since I discovered it and tried it out.

There's a small request I wanted to ask and see if it's possible for such implementation. I don't if you had ever used Kodi in the past, but there's an optional toggle feature under Settings, Audio, Passthrough which lets users who are using an Optical Audio connection also known as **TOSLINk or S/PDIF** which only supports Dolby Digital or DTS in rare cases. When having this feature ON in Kodi anything that's beyond Dolby Digital/AC3 5.1 e.g: Dolby TrueHD/Digital Plus with ATMOS 7.1, DTS/DTS-HD 5.1,7.1ch, DTS-X 7.1, etc. Will get transcoded into AC3 5.1 for seamless playback and no loss of Surround Audio for when the user is using this type of audio connection given if using an older A/V Receiver or Soundbar which doesn't has HDMI ARC connection.

Here's an screenshot of the option in Kodi. 

![image](https://user-images.githubusercontent.com/76958541/154161484-f1c764db-4df8-438e-bd46-46c57231fd48.jpeg)

I definitely don't know if this is possible to implement or not in a media player like this one. I understand Kodi is a really big application which can perform a lot of tasks simultaneously in the background. I just wanted to throw the request to see if a feature like this can actually be possible to make happen, IF not that's totally fine. Again, I still appreciate all the work you've been doing with this Player. Definitely one of the bests right now in terms of reliability.

**Comment by moneytoo** [comment]
This is surely technically possible (https://github.com/google/ExoPlayer/issues/5817) but I'm afraid that there's a too little interest in such feature.

**Comment by Nuklear92** [comment]
> This is surely technically possible (https://github.com/google/ExoPlayer/issues/5817) but I'm afraid that there's a too little interest in such feature. 

That's great that such feature can be possible. I understand it's not a highly requested, at least I found out a positive answer overall. 

Thanks for the response either way, keep the good work. 👍
