### ISSUE TITLE
Disable Subs Permanently?

### ISSUE THREAD

**Issue by EXOSKELTON89** [moneytoo/Player#274]
Anyway to permanently have the subs turned off when playing a video? Just so we don't have to keep turning them off on every video we play :)

Thanks

**Comment by EXOSKELTON89** [comment]
😬

**Comment by luniz7** [comment]
Came here to ask the same thing.

**Comment by EXOSKELTON89** [comment]
Haha I don't even know if these messages get read to be honest 😂

**Comment by luniz7** [comment]
> Haha I don't even know if these messages get read to be honest 😂

Maybe, maybe not. You never know.

**Comment by moneytoo** [comment]
Duplicate of #390

This option is now in the latest release
