### ISSUE TITLE
Feature request / information request

### ISSUE THREAD

**Issue by Bechrissed** [moneytoo/Player#275]
Hi,

Awesome project! I've been struggling to get my HDR/Dolby Vision encoded videos playing correct on VLC Android on my Nvidia Shield. I would like to use the player for our new TV Screen in our office to shuffle 4K HDR/DV from video's in a folder. Preferably with our logo (transparent png image) centered over the video. With VLC this is possible through the video effects settings. A feature like this with the possibility to select the image, and set position would be awesome.

As the project is opensource I was thinking of adding the feature myself. I more a JavaScript dev myself. I can read and understand Java but I'm not really familiar with Android apps. Can you give me a hint on where to start implementing? Eg. what is the main screen/file to edit when the player is in fullscreen mode? Thank for any help!

Cheers

**Comment by moneytoo** [comment]
You could just use [ExoPlayer](https://exoplayer.dev/) directly (start with its Demo) as this is what Just Player uses. All you need is basically to put one overlay over the video view. I believe you could also use some ExoPlayer wrapper for frameworks like Cordova, Ionic etc. and code in JS. If it wasn't Android TV, but some Android device with a web browser, you could just create PWA as the system video player is basically what ExoPlayer uses anyway.

**Comment by Bechrissed** [comment]
Your are right! Thank you. I see react-native-video is using ExoPlayer, that should work.
