### ISSUE TITLE
Just player logo missing on fire tv

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [moneytoo/Player#278]
Hello, on the launcher of my fire tv, the Just Player logo does not appear, I just have a black frame, is it possible to fix the problem? Thanks to you!

[IMG_20220219_183258.jpg](https://user-images.githubusercontent.com/42807552/154812318-6756f338-3663-4678-9c01-dfe965373777.jpg)

**Comment by moneytoo** [comment]
How did you install that version? From Amazon Appstore? What version is that (v0.73)?

Little over a month ago I submitted an updated version there but received an email about a failure but the web dashboard kept showing status as under review. I have just resubmitted the current version there so it should be processed within a week. But I'm still not sure how this could be related as the latest published version has icon/banner specified.

<img width="522" alt="Screenshot 2022-02-19 at 22 21 36" src="https://user-images.githubusercontent.com/1071643/154819476-80178925-f864-4399-85a3-ed1b40fc57c6.png">

**Comment by TechComputerServiceDunkerque** [comment]
I downloaded it on github, on amazon, I don't download it because it's not updated, they are so slow on this store.

**Comment by moneytoo** [comment]
Do other sideloaded apps show correct banner/icon?

**Comment by TechComputerServiceDunkerque** [comment]
For some yes, like Tivimate or Nova Player, there I just went on the amazon fire tv store, just player is not found on the store.

**Comment by moneytoo** [comment]
What device model & generation do you have?

**Comment by TechComputerServiceDunkerque** [comment]
> What device model & generation do you have?

Amazon Fire Cube

**Comment by moneytoo** [comment]
So that's a device with 64-bit CPU. I guess it could be related to an issue with 64-bit detection in Just Player on the Amazon Appstore. I will get back to this once the 64-bit issue is resolved.

**Comment by TechComputerServiceDunkerque** [comment]
Okay thanks, let me know about the progress, I also know that the fire cube will be updated to Android 12 soon.

**Comment by moneytoo** [comment]
There was an issue with the app not being available to Fire TV device because of a Amazon Content Policy Compatibility:

> We consider a variety of factors as we evaluate each app, including the customer experience offered on the device and compatibility with the device. While our goal is to offer a broad and compelling assortment of apps to Amazon customers, not all apps available through Amazon Appstore are currently available on Amazon devices. Because your app overrides or alters the native user experience (e.g., with a lockscreen, widget, wallpaper, picture-in-picture or other on-screen element that impacts the native user interface), it has not been published on Fire TV devices. In limited circumstances, overlay widgets will be permitted on Tablet devices if they are unobtrusive, integral to the app, and do not further alter the device. You can view our guidelines on the Appstore Developer Portal.

I had to disable the Picture-in-picture feature on Fire TV devices. With this change, it was approved. So v0.102 should be available on all compatible Amazon devices and hopefully it should resolve the icon issue as well.

**Comment by TechComputerServiceDunkerque** [comment]
Yes the logo is there and the application is now available on fire tv. Thanks
