### ISSUE TITLE
Not loading on Firestick

### ISSUE THREAD

**Issue by DCCG101** [moneytoo/Player#279]
Side loading the version currently on play store (.101?)  to my Firestick 4k Max and it won't load?

An older version .73 (from Amazon store) loads ok but doesn't enable frame rate matching.

**Comment by moneytoo** [comment]
Where did you get the v0.101 from?

**Comment by DCCG101** [comment]
That's the version on Google play store
![Screenshot_20220220-152828_Google Play Store](https://user-images.githubusercontent.com/100067577/154850323-831684af-d55e-4a3a-8086-c447eea74132.jpg)

**Comment by moneytoo** [comment]
But there's no Google Play Store on Fire TV so I'm asking where did you get the app from / how did you install it.

**Comment by DCCG101** [comment]
Install on my phone from play store then install to Firestick with Easy Fire Tools

**Comment by moneytoo** [comment]
You shouldn't use the version from Play Store as it may not be the same architecture and configuration as your Fire TV device. Install full apk from https://github.com/moneytoo/Player/releases.

**Comment by DCCG101** [comment]
Thanks that version works and so does frame rate switching. Great stuff 😀
