### ISSUE TITLE
Add video locking feature.

### ISSUE THREAD

**Issue by Pranab009** [moneytoo/Player#28]
Please add video locking feature.
You can't change anything (slider & volume & brightness bar) until you unlock.

**Comment by Pentaphon** [comment]
Yeah, this is even more useful if gestures are enabled.

**Comment by moneytoo** [comment]
In version 0.22 (currently [pre-release](https://github.com/moneytoo/Player/releases)) I'm adding related feature that partly deals with accidental touches: [Seek in time bar only using scrubber (thumb)](https://github.com/moneytoo/Player/commit/fce7ca89ab1cb30820945f46867f28702a8b4676). This doesn't lock any other gestures but it should prevent the worst kind of accidental taps in my opinion (like skipping somewhere in the video without remembering previous position).

**Comment by moneytoo** [comment]
Here's a preview version with temporary touch locking feature: [Just.Player.v0.42-touch_lock.apk](https://brouken.com/player/Just.Player.v0.42-touch_lock.apk)

To **lock**, do a **long press** (anywhere outside other controls) when video plays. To **unlock**, just **long press** anywhere again.

Do you think it can work like that? This is how I prefer it (I do not want to hunt small button on a screen when I want/need to quickly stop the playback). I have almost never used such functionality... But with such seamless activation/deactivation, I see myself using it when wiping dirt of the screen now.

**Comment by Pentaphon** [comment]
> To **lock**, do a **long press** (anywhere outside other controls) when video plays. To **unlock**, just **long press** anywhere again.

That's more than enough as long as there's an gesture icon/text that shows "Locked" when you lock it. 

I agree with not adding another button.

**Comment by moneytoo** [comment]
Yes, there are padlock icon indicators for locking/unlocking. I also added one more unlock method - tapping the lock icon. This should serve as a backup unlock for users who inadvertently activate the lock (without realizing they long tapped).

(I don't feel like the app should necessarily describe all the control gestures during onboarding but I would like to have one screenshot explaining all the possible touch gestures - some common like swipes and double taps as well as this little awkward long press for locking.)

**Comment by moneytoo** [comment]
Already fully available in the release `v0.42`.
