### ISSUE TITLE
stuck at 1080p playback with 4K hdr files

### ISSUE THREAD

**Issue by KyleSanderson** [moneytoo/Player#281]
Sony does weird things with AndroidTV, they have an allow-list for certain apps to run properly, and others are relegated to 1080p (apps vs apps video). I'm playing back tunneled content through Nova on Just - the picture quality is substantially worse than using a STB.

https://forum.kodi.tv/showthread.php?tid=350932

**Comment by moneytoo** [comment]
On pre-Android TV 12 the UI is limited to 1080p but video rendering (done using SurfaceView) should be in native resolution (4K).

**Comment by KyleSanderson** [comment]
Something's off. when playing media back there's these grey bars on the TV where it should be complete darkness. Additionally when attempting to play back TrueHD content the player errors out, and there's no option to select track 2 or track 3 which are AC3.

FfmpegAudioRenderer error, index=4, format=Format(null, null, null, audio/raw, null, -1, [-1, -1, -1.0], [8, 48000]), format_supported=NO_UNSUPPORTED_TYPE

**Comment by kenzoka24** [comment]
> Something's off. when playing media back there's these grey bars on the TV where it should be complete darkness. Additionally when attempting to play back TrueHD content the player errors out, and there's no option to select track 2 or track 3 which are AC3.
> 
> FfmpegAudioRenderer error, index=4, format=Format(null, null, null, audio/raw, null, -1, [-1, -1, -1.0], [8, 48000]), format_supported=NO_UNSUPPORTED_TYPE

your device doesn't support that audio codec


since exosplayer only supports hardware decoding, that's why it shows that error

**Comment by KyleSanderson** [comment]
indeed - thanks DS.
