### ISSUE TITLE
Make the scrollable controls in portrait mode always visible

### ISSUE THREAD

**Issue by CodeCubeNeo** [moneytoo/Player#282]
It would be awesome to make the whole interface just like vlc (meaning that you move those controls in a menu bar rather then making them scrollable.

**Comment by moneytoo** [comment]
I wouldn't mind that as well. Currently the whole player UI is using the default ExoPlayer style with only few tweaks. It's not really made to be redesigned much. It works fine in the landscape so the state of portrait is the tradeoff (for the ease of maintenance).
