### ISSUE TITLE
Possible to add subtitle scroll feature like in MX player?

### ISSUE THREAD

**Issue by rohitghali** [moneytoo/Player#284]

**Comment by rohitghali** [comment]
It is basically --sub-seek where if you scroll over the subtitles, it'll seek the subtitles back and forth.

**Comment by rohitghali** [comment]
If you don't mind, why won't it be implemented? Any particular explanation?

**Comment by moneytoo** [comment]
As stated in the [readme](https://github.com/moneytoo/Player#other-open-source-android-video-players), Just Player's feature set is mostly complete. Personaly I don't really need that feature.
