### ISSUE TITLE
Dolby Vision no longer works since v0.104

### ISSUE THREAD

**Issue by tofu-dreg** [moneytoo/Player#286]
Playing DV files on Sony X90J since v0.104 results in fallback to HDR10. Picture mode doesn't change to "Dolby Vision Dark/Bright" but rather stays on "Custom for Pro 1/2" modes that HDR10 files use. Downgraded app to v0.101 and DV playback works again with correct "Dolby Vision Dark/Bright" picture modes engaging during playback.

**Comment by moneytoo** [comment]
What DV profile is it? It seems related to a change in [ExoPlayer 2.17.0](https://github.com/google/ExoPlayer/releases/tag/r2.17.0):

> Video: Fix decoder fallback logic for Dolby Vision to use a compatible H264/H265 decoder if needed.

I suggest reporting this directly to ExoPlayer, along with a captured bug report.

**Comment by Nuklear92** [comment]
> Playing DV files on Sony X90J since v0.104 results in fallback to HDR10. Picture mode doesn't change to "Dolby Vision Dark/Bright" but rather stays on "Custom for Pro 1/2" modes that HDR10 files use. Downgraded app to v0.101 and DV playback works again with correct "Dolby Vision Dark/Bright" picture modes engaging during playback.

That's odd, it's working perfectly fine on my Nvidia Shield TV via my LG C1 OLED. Using same latest build.

**Comment by ThorvinV** [comment]
Hello I have exactly the same problem with a lg cx and a Nvidia Shield TV pro...

**Comment by Koloss78** [comment]
Same problem with Shield Pro (2019), no DV detect.

**Comment by moneytoo** [comment]
Please state what DV profiles are you trying to play.

**Comment by moneytoo** [comment]
Share the output from MediaInfo (at least the line "HDR format").

**Comment by ThorvinV** [comment]
Sorry I can't do it now but what I remember is "HEVC Main 10@L5.1@High DoVi" something like that

it's a Dolby vision profile coming from a 4K bluray REMUX version (100% lossless)

So the same profile you can find in a real 4K dolby vision bluray

They are all working at 100% on your previous version of Just Player with previous version of ExoPlayer


I can't help you more

**Comment by moneytoo** [comment]
Closing as this is probably the same as #293.
