### ISSUE TITLE
Double tab to pause or restart

### ISSUE THREAD

**Issue by Pranab009** [moneytoo/Player#29]
Sir Please add this features.
Double tab to pause or restart.
Double tab (both sides) to Seek (10 sec).
These are very basic features Please work on it.

**Comment by Pentaphon** [comment]
Double tap to seek is already requested here: https://github.com/moneytoo/Player/issues/3

**Comment by moneytoo** [comment]
Added in latest [pre-release](https://github.com/moneytoo/Player/releases)
