### ISSUE TITLE
No Dolby Vision in 105

### ISSUE THREAD

**Issue by rew81** [moneytoo/Player#293]
Video falls back to hdr10- Nvidia shield tv pro 2019.
Media info:
HDR format 
Dolby Vision , Version 1.0 , dvhe . 07 .0 6 , BL 
EL+RPU, Blu-ray compatible / SMPTE ST 208 
6 , HDRI0 compatible 
Codec ID 
V_MPEGH/lsO/HEVC 

Was working fine in previous versions!?

**Comment by moneytoo** [comment]
Try this version: [Just.Player.v0.106-no_mapping](https://brouken.com/player/Just.Player.v0.106-no_mapping.apk) (or [Just.Player.v0.106-legacy-no_mapping.apk](https://brouken.com/player/Just.Player.v0.106-legacy-no_mapping.apk) if you are using the legacy variant) Any difference?

**Comment by gogo200777** [comment]
After installation of 0.106 the problem fixed.

DV is working fine.

Thanks :)

**Comment by rew81** [comment]
Thank you for your support!
Dolby vision is working fine in  v0.106.
