### ISSUE TITLE
black screen when trying to play dual layer dovi videos

### ISSUE THREAD

**Issue by kenzoka24** [moneytoo/Player#295]
### Describe the bug
Here is a clear and concise description of what the problem is:

black screen on Redmi Note 10 Pro Max after upgrading to Android 12 MIUI 13 (non rooted stock)
>>
when playing dual layer dovi videos(with hdr10 as fallback available)
_____
videos with hdr10 metadata only, work as expected

these same dual layer dovi videos were playing correctly before upgrading to Android 12

I have tried tunnelled playback option in settings, tried after reducing refresh rate to 60hz, the videos just show black screen everytime

this device does NOT have dolby vision support, only hdr10 certified

## Expected Behavior
video playing normally

## Actual Behavior

black screen with audio and subtitles

### To Reproduce
sample video
https://drive.google.com/file/d/1-gvmW3AHqBoruuBB1uPjysoFVI_YcKTR/view?usp=drivesdk

 - Operating system version/name: Android 12
 - just player (version 0.106) play store

**Comment by moneytoo** [comment]
Until version 0.106, there was a fallback to HEVC from DV profile 7. Unfortunately, it caused issues with latest ExoPlayer so I had to revert that as mentioned in #293. However I probably won't be experimenting with any more changes as I cannot test the actual DV playback without capable device.

**Comment by kenzoka24** [comment]
> Until version 0.106, there was a fallback to HEVC from DV profile 7. Unfortunately, it caused issues with latest ExoPlayer so I had to revert that as mentioned in #293. However I probably won't be experimenting with any more changes as I cannot test the actual DV playback without capable device.

so I should use older version of the app for now?

**Comment by moneytoo** [comment]
Yes, using v0.105 should be a work around for you.
