### ISSUE TITLE
Dolby Vision Profile 7 doesn't Trigger on TCL C825

### ISSUE THREAD

**Issue by psychoboust** [moneytoo/Player#297]
Hello,

I have an issue with MKV Dolby Vision Profile 7, it doesn't trigger the Dolby Vision on my TV TCL C825 (mt9615 (arm cortex-a73))
Only HDR10 is triggering.

Using a Nvidia Shield 2019 connected to this TV, I don't have any issue with the same MKV

**Comment by psychoboust** [comment]
I just found one MKV which trigger the Dolby Vision

Here is the informartion : 

Don't trigger :
Video
ID                          : 4
ID in the original source m : 4113 (0x1011)
Format                      : HEVC
Format/Info                 : High Efficiency Video Coding
Format profile              : Main 10@L5.1@High
HDR format                  : Dolby Vision, Version 1.0, dvhe.07.06, BL+EL+RPU, Blu-ray compatible / SMPTE ST 2086, HDR10 compatible
Codec ID                    : V_MPEGH/ISO/HEVC
Duration                    : 1 h 47 min
Bit rate                    : 46.8 Mb/s
Width                       : 3 840 pixels
Height                      : 2 160 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 23.976 (24000/1001) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0 (Type 2)
Bit depth                   : 10 bits
Bits/(Pixel*Frame)          : 0.235
Stream size                 : 35.1 GiB (91%)
Language                    : English
Default                     : No
Forced                      : No
Color range                 : Limited
Color primaries             : BT.2020
Transfer characteristics    : PQ
Matrix coefficients         : BT.2020 non-constant
Mastering display color pri : Display P3
Mastering display luminance : min: 0.0010 cd/m2, max: 1000 cd/m2
Maximum Content Light Level : 1000 cd/m2
Maximum Frame-Average Light : 1000 cd/m2
Original source medium      : Blu-ray

Trigger OK : 
Video
ID                          : 1
ID in the original source m : 4113 (0x1011)
Format                      : HEVC
Format/Info                 : High Efficiency Video Coding
Format profile              : Main 10@L5.1@High
HDR format                  : Dolby Vision, Version 1.0, dvhe.07.06, BL+EL+RPU, Blu-ray compatible / SMPTE ST 2086, HDR10 compatible
Codec ID                    : V_MPEGH/ISO/HEVC
Duration                    : 2 h 28 min
Bit rate                    : 54.3 Mb/s
Width                       : 3 840 pixels
Height                      : 2 160 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 23.976 (24000/1001) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0 (Type 2)
Bit depth                   : 10 bits
Bits/(Pixel*Frame)          : 0.273
Stream size                 : 56.2 GiB (92%)
Default                     : Yes
Forced                      : No
Color range                 : Limited
Color primaries             : BT.2020
Transfer characteristics    : PQ
Matrix coefficients         : BT.2020 non-constant
Mastering display color pri : BT.2020
Mastering display luminance : min: 0.0001 cd/m2, max: 1000 cd/m2
Maximum Content Light Level : 9978 cd/m2
Maximum Frame-Average Light : 867 cd/m2
Original source medium      : Blu-ray

The only difference I figure out here is : 

Mastering display color pri : BT.2020 = TRIGGER
Mastering display color pri : Display P3 = Doesn't TRIGGER

**Comment by moneytoo** [comment]
Release [v0.125](https://github.com/moneytoo/Player/releases/tag/v0.125) includes ExoPlayer [r2.18.2](https://github.com/google/ExoPlayer/releases/tag/r2.18.2) which has some DV related improvements. Does it work any better?

**Comment by moneytoo** [comment]
Possibly related to #293?

**Comment by psychoboust** [comment]
I tried both Just.Player.v0.125-legacy and Just.Player.v0.125 and still it doesn't trigger the Dolby vision on Dolby Vision Profile 7.06 mkv media.

**Comment by psychoboust** [comment]
OK now I have understand (I think) which Dolby Vision Profile 7 file are triggered and which are not.
I test several files : and my conclusion is that Profile 7 with subprofile MEL trigger the Dolby Vision on my  TV TCL C825 and Profile 7 with subprofile FEL are not.

Does it help ?
