### ISSUE TITLE
Avi support

### ISSUE THREAD

**Issue by sombresu** [moneytoo/Player#298]
Even though avi is an ancient video file format that you think shouldn't be used anymore by people, avi was once the most popular video format. So many old videos are in avi. Please consider supporting avi format.

**Comment by brentonv** [comment]
AVI support was added some months ago:

> v0.98 Pre-release
> AVI container support (work of dburckh, google/ExoPlayer#2092)
> May not work with OpenDML files (dburckh/ExoPlayer#8)

**Comment by sombresu** [comment]
> AVI support was added some months ago:

Oh, great thanks. 

But I get this error message opening avi video and looking online I found posts that says Just Player doesn't support that format. 

![error_popup.jpg](https://user-images.githubusercontent.com/62043417/162187836-f8c79979-7409-44d9-9099-f1cd51525afa.jpg)

Anyone can help me?

**Comment by moneytoo** [comment]
While the AVI container is somehow supported, it is mostly paired with older audio and video codecs which often may not be playable on current Android devices. To confirm this, state your device model and ideally share a video sample (or at least MediaInfo output).

**Comment by Allin78** [comment]
On mp4 container some issue. Ac3 sound track

**Comment by moneytoo** [comment]
Latest [version 0.128](https://github.com/moneytoo/Player/releases/tag/v0.128) includes [Media3Avi](https://github.com/dburckh/Media3Avi), which is the most what can be done regarding support of Avi as of today.
