### ISSUE TITLE
[Bug] HEVC videos not playing

### ISSUE THREAD

**Issue by nothing223** [moneytoo/Player#30]
MediaCodecVideoRenderer error, index=0, format(1, Ep 1 | 1080p | BD | x265 10bit, null, video/hevc, -1, ja [1920, 1080, -1.0], [-1, -1]), format_supported=YES                     Details

When pressing on Details it gives this message

Decoder failed: OMX.qcom.video.decoder.hevc

I have tried multiple HEVC videos and none of them seem to work. They play fine on other video players.

**Comment by moneytoo** [comment]
What device do you use? Please also try sharing a sample (here or privately). 

Does this sample (1 second) HEVC video plays for you? https://github.com/chromium/chromium/raw/master/media/test/data/bear-hevc-frag.mp4

**Comment by nothing223** [comment]
The video you sent plays fine on all my devices. I just noticed that the videos i could not play are working fine on my phone which is an samsung galaxy s9 but not my Galaxy Tab A android 10. By sample i presume you mean the video i was trying to play? https://mega.nz/file/BKZRDSrR#4aCkMeyV3Oh2anjX8Oez8Gdaej_aIq5MENhN2Ir0vEc

**Comment by moneytoo** [comment]
Looks like that chip/decoder in Galaxy Tab A does not handle HEVC 10 bit (quick Google search seems to confirm that). As Just Player / ExoPlayer use only system decoders (except for AV1), the playback fails. The only hope would be software decoder such as https://github.com/michalliu/exoplayer2-hevc-extension but it's old and not maintained so it's really long, long stretch (if it even handles 10 bit or compiles).

**Comment by nothing223** [comment]
Thank you.

**Comment by moneytoo** [comment]
Closing as I don't think this is actually something feasible for me to "fix" - include unmaintained HEVC extension for sw decoding with a fallback from device decoder without access to actual device.
