### ISSUE TITLE
Long press to change video speed.

### ISSUE THREAD

**Issue by kebinzhi** [moneytoo/Player#303]
When you watch a video, you might want to speed up some boring part of the video, and some important part you want a regular speed.
Some video players can speed up a video with a long press. When you release your finger, it restores former speed. The speed of long press is set by the user, like 2x or 3x speed, whatever the user wants.

I think this feature is a great idea for watching videos faster.
Is it possible to add this feature to just player down the road? That would be great.

**Comment by Noitarud** [comment]
Could make it work like a DJ's console 🤣

**Comment by kangpou** [comment]
I hope so too.

**Comment by rohitghali** [comment]
MX Player has this. I love it. Unfortunately MX Player is shit. Would be cool if this feature is added here.

**Comment by jinggqu** [comment]
Hi @kebinzhi @kangpou @anuraag488 @rohitghali , I have forked this repo and implemented 2x speed on long press. If you are interested, you can download from https://github.com/jinggqu/Player/releases. Enjoy.
