### ISSUE TITLE
expand playback speeds

### ISSUE THREAD

**Issue by ykuksenko** [moneytoo/Player#307]
Hello,
Could the playback speed options be expanded to go up 3x? Use the same .25x increments.

**Comment by Noitarud** [comment]
While you're at this, I would like
A) to see a 1/ option - to play a file that has had its speed altered to undo the author's alteration accurately.
B) I felt I needed subtle speed drop while listening to teaching lesson, your program jumps the pauses and this makes the facts get spoken too fast to think!
C) display revised length/dual clock after speed adjustment

**Comment by moneytoo** [comment]
If you need more fine scale or faster speeds, use [Next Player](https://github.com/anilbeesetti/nextplayer/). Just Player uses only the default range from ExoPlayer and I do not plan on extending that.
