### ISSUE TITLE
"Source error" when trying to stream video from SMB via Solid Explorer

### ISSUE THREAD

**Issue by Pentaphon** [moneytoo/Player#31]
1) Connect to SMB share via Solid Explorer and try to play a video with Just Player 0.14
2) Title of video will load into Just Player but then it shows me a "source error". 

Tested the same steps with mpv-android and it works fine. Something on Just Player simply won't connect. 

![Screenshot_20210120-141515_1](https://user-images.githubusercontent.com/49374058/105248130-b9ddb180-5b2a-11eb-9e77-9d946fce2d13.png)

**Comment by moneytoo** [comment]
Looks like this feature actually might need the Internet permission. During development I added and removed the permission and it somehow got cached and worked even after removal.

**Comment by moneytoo** [comment]
It should work in the `-online` [version](https://github.com/moneytoo/Player/releases/latest). F-Droid and Google Play will keep the `-offline` builds.

**Comment by Pentaphon** [comment]
@moneytoo Is the online version going to be on Github only? I was hoping to get it from Play since I can keep it updated there.

**Comment by moneytoo** [comment]
For now, yes. I haven't decided yet on how/if/when to release separate build on Google Play. I guess some middle ground could be custom F-Droid repository which would provide notification about an update and quicker install.
