### ISSUE TITLE
MediaCodecAudioRenderer error

### ISSUE THREAD

**Issue by Ellypsis63** [moneytoo/Player#311]
![IMG_20220514_224226.jpg](https://user-images.githubusercontent.com/29355624/168447715-8d704dcf-33e9-4428-b9fc-e1e5c833802d.jpg)

File won't load because of this error.

It seems to mostly affect my movies in AAC

The only solution i found is to disable tunnel mode, but the image Quality is reduced and there is a slight zoom issue.

Using Xiaomi Mi TV Q1 75.

Thanks.

**Comment by moneytoo** [comment]
Unfortunately these are reportedly device specific bugs as stated by ExoPlayer devs and there's nothing to do with that except not to enable tunneling: https://github.com/google/ExoPlayer/issues/9133
