### ISSUE TITLE
Online streaming not working!!!

### ISSUE THREAD

**Issue by jack009j** [moneytoo/Player#312]
Hi thanks for wonderful app.

Recently online streaming through just player not working properly.
I usually play videos stored in my gdrive through mixplorer via just player, it playing without problem until i update just player .
I don't know exactly from which version this issue occur , I uninstalled v0.114 and installed v.088 and checked , in this older version online streaming works fine.
I think recent updates have some problem, also sometimes MP4 container videos in my gdrive is playing, but mkv not playing in latest version.
Please fix this issue.

**Comment by moneytoo** [comment]
Hi. I uploaded mkv file ([test5.mkv](https://github.com/ietf-wg-cellar/matroska-test-files/raw/master/test_files/test5.mkv)) to Google Drive and can play it from there using the latest version of Just Player just fine.

**Comment by DarremMolko** [comment]
I can reproduce this with my movies (1,5 to 2gb in size), but as you have not tell what kind of error are you getting I'm not sure if it's the same. I leave a screenshot below:
![Screenshot_20220528-111930](https://user-images.githubusercontent.com/70179709/170829597-b7d13492-2c8c-420f-b602-0a5f4958574f.png)

**Comment by jack009j** [comment]
> Hi. I uploaded mkv file ([test5.mkv](https://github.com/ietf-wg-cellar/matroska-test-files/raw/master/test_files/test5.mkv)) to Google Drive and can play it from there using the latest version of Just Player just fine.

May I know did you selected file from gdrive using mixplorer or any other cloud explorer?

**Comment by jack009j** [comment]
> @jack009j I selected the file using the default file chooser of Just Player, in the Google Drive section.

Thanks for replying,
But while playing gdrive file through default file chooser of just player have some drawbacks like the file should completely downloaded before start playing, so it very time consuming for large size file, also file cached is not cleared frequently.
That why using mixplorer.
Don't know mixplorer-justplayer streaming issue caused due to update of just player or mixplorer.
But other player playing without any issues via mixplorer.

**Comment by moneytoo** [comment]
I'm able to use MiXplorer just as well.

**Comment by DarremMolko** [comment]
Maybe the problem is with the MiXplorer version? I got the error from the screenshot above using version 6.58.4 Silver.
