### ISSUE TITLE
won't install on Pie jeter

### ISSUE THREAD

**Issue by galenthurber** [moneytoo/Player#313]
Installing from fdroid results unknown error

**Comment by moneytoo** [comment]
Try verifying the integrity of downloaded apk (F-Droid provides GPG signatures) or installing using adb to see more details. Normally, the F-Droid release should just work.

**Comment by galenthurber** [comment]
I think my fdroid is acting up some apps install others will not, no way to debug--Sent from my Android phone with GMX Mail. Please excuse my brevity.On 5/29/22, 4:13 PM Marcel Dopita ***@***.***> wrote:

   
  Try verifying the integrity of downloaded apk (F-Droid provides GPG signatures) or installing using adb to see more details. Normally, the F-Droid release should just work.
