### ISSUE TITLE
Just updated to 0.114 and now my movies have judder

### ISSUE THREAD

**Issue by looloo86** [moneytoo/Player#315]
I'm using the Nvidia Shield Pro and just updated Just Player to 0.114. I am now experiencing judder every few seconds when watching a 4K remux mkv file. I already have match frame rate enable, so I don't know what else I can do. Please help!

**Comment by looloo86** [comment]
> What version were you using before updating?

Sorry, I'm not sure. But I installed it a long time ago. I believe it was last year. If there is a way for me to check my history, you can let me know.

**Comment by moneytoo** [comment]
You could try testing previous versions from https://github.com/moneytoo/Player/releases to find out what change caused this
