### ISSUE TITLE
Chapter navigation

### ISSUE THREAD

**Issue by PacoBell** [moneytoo/Player#318]
I see that Just Player can display chapter markers on the timeline, but there does not seem to be any kind of UI to discretely move forward or backward through them. The haptics when scrubbing through the timeline are a nice bonus, but I feel the app really needs those buttons flanking the play/pause button.

**Comment by Noitarud** [comment]
A a button to bring up a list (since chapters have titles) would be great. Either show chapter length or file time beside.

**Comment by t05t3r** [comment]
thumb up for chapters list button (useful when watching concert shows on android tv)
in rest this is the best player for android I've tried
