### ISSUE TITLE
Volume boost, subtitles selection

### ISSUE THREAD

**Issue by the-badmannn** [moneytoo/Player#319]
I saw in features list that volume booster is listed, how can we activate that? because on my Shield tv pro the videos have really low sound and I have to crank up the volume and then on others apps it's too loud.
And also the player doesn't load subtitles automatically from syncler for example and if the tv goes to Screensaver I have to pick the subtitle again, it doesn't remember my selection.

**Comment by moneytoo** [comment]
See [this for volume boost](https://github.com/moneytoo/Player/discussions/273#discussioncomment-2190934)

**Comment by the-badmannn** [comment]
yup, I have no idea how to implement that and I think I speak for some other users too, it should be an option when we press ⚙️ next to audio selection and video speed

**Comment by the-badmannn** [comment]
Also in this last build seek function doesn't work properly on Android TV, when we press more than one time on forward or backward key on the remote it doesn't seek only first click, after that the UI keeps popping and you circle through UI, instead of seeking within the video..
