### ISSUE TITLE
Find designer who can create a better app icon?

### ISSUE THREAD

**Issue by Pentaphon** [moneytoo/Player#32]
The neon green app icon is a bit too plain so maybe this issue can be used to find somebody willing to make you a better one?

**Comment by moneytoo** [comment]
I don't see any need to change that. The icon is plain and simple, just like the few functions provided by this app. Why complicate things if this is easy to understand. The icon of MX Player is not much more complicated (only the inner triangle has rounded corners).

**Comment by Pentaphon** [comment]
Fair enough. Just thought I'd bring it up in case you agreed. Closing.
