### ISSUE TITLE
HDR10+ Playback Fails

### ISSUE THREAD

**Issue by timcoop3r** [moneytoo/Player#320]
Hi,

I have noticed recently certain video files seem to fail when trying to play back. Upon digging further this seems to be certain HDR10+ titles. This issue is resolved if I roll back to an early version of the player. 0.70 works fine, but if I upgrade to 0.76 or the latest versions playback fails. This may be related to the change to ExoPlayer 2.16.1 from 0.71 onwards?

**Comment by timcoop3r** [comment]
Not resolved with 0.118 and ExoPlayer 2.18. Hopefully in the next ExoPlayer release :(

**Comment by moneytoo** [comment]
Please share a sample of such video file.

**Comment by timcoop3r** [comment]
@moneytoo  Here is an example clip. I can provide others if needed from different content from the same studio, but all examples are 4K HDR10+. I didn't mention before, this happens on the 2019 Shield Pro, I don't have any other Android devices to see if the same happens on those also.

https://file.io/d8b8M6B9iqgd  (Link expires in 72 hours)

**Comment by moneytoo** [comment]
Thanks for the file. I can duplicate the issue on my device. I will look into that.

**Comment by moneytoo** [comment]
Indeed the fix is in dev-v2: https://github.com/google/ExoPlayer/commit/d86bc1078c8f95f8420253e8e8ad7550d09b03f1

I will cherry pick this change.

**Comment by moneytoo** [comment]
Could you try the [v0.120](https://brouken.com/player/) just to be sure it works for you as well?

**Comment by timcoop3r** [comment]
> Could you try the [v0.120](https://brouken.com/player/) just to be sure it works for you as well?

Yep, 0.120 working for me now also! Much appreciated!
