### ISSUE TITLE
A feature that must be added

### ISSUE THREAD

**Issue by Habal1990** [moneytoo/Player#321]
Please add 16:9، Fill، 4:3, center, Fit screen,  Best fit

**Comment by moneytoo** [comment]
Properly encoded videos should be in the correct aspect ratio (16:9, 4:3 etc.) and shouldn't need special mode to override the aspect ratio. I don't think I came across any bad aspect ratio with mkv or mp4 videos.

**Comment by kenderipa** [comment]
> Properly encoded videos should be in the correct aspect ratio (16:9, 4:3 etc.) and shouldn't need special mode to override the aspect ratio. I don't think I came across any bad aspect ratio with mkv or mp4 videos.

Aaand mpv it is. Or another player, which may or may not receive this very useful function. And yes, I've seen .mkv's with incorrect aspect ration.

**Comment by Pentaphon** [comment]
> Properly encoded videos should be in the correct aspect ratio (16:9, 4:3 etc.) and shouldn't need special mode to override the aspect ratio. I don't think I came across any bad aspect ratio with mkv or mp4 videos.

Can we get this re-opened? The reason many players have aspect ratio correction is because there's a lot of videos that actually do have bad aspect ratio. Especially older videos and current Youtube videos like https://www.youtube.com/watch?v=F75aDabKUdo&list=PLB367SvY1ItK5EeGv3tVwfZdt0X6tRfgK

**Comment by moneytoo** [comment]
- YouTube doesn't allow changing aspect ratio
- If you're downloading such videos off YouTube, why not reencode it in correct aspect ratio than to fix it in all the players without fiddling with options?
- The list of possible aspect ratios can be quite long, possibly requiring support for custom aspect ratios. Dealing with saving aspect ratio, dealing with reseting aspect ratio when another video in line is started...

Problems should be fixed at their source. But most importantly, I like the simplicity of the current fit/crop toggle that works perfectly for my files.

**Comment by Pentaphon** [comment]
>YouTube doesn't allow changing aspect ratio

Sure, but they aren't a local player. Youtube is just one example. There's many more local files out there that 

>If you're downloading such videos off YouTube, why not reencode it in correct aspect ratio than to fix it in all the players without fiddling with options?

It's easier and faster to just cycle through aspect ratios. Re-encoding takes time and loses quality. Passing it to an external player like yours is also faster. 

>The list of possible aspect ratios can be quite long

Not really. Only the most common ones are needed. Less than half of these, really. 

![7mrui](https://github.com/moneytoo/Player/assets/49374058/8a4f0ea1-fb37-4bcb-b8ca-e5f74d6065ba)

>I like the simplicity of the current fit/crop toggle that works perfectly for my files.

Can we have an option in the settings to make that toggle have more aspect ratios? Then it will work for you and all your users.
