### ISSUE TITLE
Fade play GUI if playback is stopped.

### ISSUE THREAD

**Issue by Etim-Orb** [moneytoo/Player#322]
When we pause a video the play GUI (such as the scrollbar and the icons) stay on the screen. Sometimes I stop video to check a detail and often the big white play button covers the content I want to see. I think it would be better for this interface to disappear after a few seconds just like when playing.

**Comment by Etim-Orb** [comment]
Perhaps not even fade automatically but fade when tapped. This may also be an option.

**Comment by moneytoo** [comment]
Duplicate of #195
