### ISSUE TITLE
Please add online subtitles

### ISSUE THREAD

**Issue by GoluLiliput** [moneytoo/Player#323]
Please add online subtitles finding feature in the app🥺🥺

**Comment by Root-FTW** [comment]
> [SubHub](https://github.com/FunkyMuse/SubHub), [sublite](https://github.com/M4trixtm/sublite), [Get Subtitles](https://play.google.com/store/apps/details?id=sunnyappz.GetSubtitles)

Has this already been tested to work (using SubHub, sublite, Get Subtitles )? in case the file is a link (streaming) like streamio, would these extra applications like SubHub, sublite, Get Subtitles work?

Or do they only work if the file is located locally on our device?

**Comment by moneytoo** [comment]
> in case the file is a link (streaming) like streamio, would these extra applications like SubHub, sublite, Get Subtitles work?

If the video is coming from other apps, they can already provide extra subtitle using the commonly used (MX Player) API. This already works (#262) when the sender app supports that.
