### ISSUE TITLE
Android TV (Nvidia Shield) back button doesn't go back

### ISSUE THREAD

**Issue by Rochey** [moneytoo/Player#325]
I think this is a bug in the new version of Just Player - but I might be wrong could others confirm?

I'm sure on the old version of Just Player that while I was playing a video if I hit the back button Just Player would go back to the previous screen. 
What I have to do now is on the Shield remote hit the button in the middle of the circle (enter), this brings up the Just Player menu and THEN I can hit the back button to go back, If I hit the back button during playback of a video nothing happens. 
The first time this happened I thought the batteries on my remote weren't working, I kept hitting the back button and nothing happened. 

Cheers,
Rochey

**Comment by moneytoo** [comment]
Yes, you are right. It's an issue0.118 (after updating to an ExoPlayer 2.18.0). I will fix that.
