### ISSUE TITLE
add ima ads support please

### ISSUE THREAD

**Issue by gelipondas** [moneytoo/Player#326]
add ima ads support please

**Comment by gelipondas** [comment]
https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side

It is to use ads like youtube does, video ads, I have sent you documentation that may help you, I am a beginner developer and I have not been able to integrate that sdk in my application

**Comment by moneytoo** [comment]
I believe ExoPlayer supports that but I do not understand what would be the use in Just Player.

**Comment by wgetge** [comment]
because he didn't know how to do that. he wants you add the ads support so that he can just copy the code.
