### ISSUE TITLE
Dolby Vision magenta/green issue

### ISSUE THREAD

**Issue by eamon360** [moneytoo/Player#328]
Hi there,

I'm trying to play a video on Just Player on my Sony BRAVIA KD55AG8 OLED TV (via USB3 hard drive) and when playing I experience a problem with the colours where there is an overload of magenta and green colours saturated across the screen. 

I tried a different video, this time one that doesn't have any HDR10 fallback and it played fine but with correct colours. 

Both times, the Dolby Vision logo appeared, so it was definitely triggered.

I am unsure if the problem with the first video is simply the way it was ripped or whether Just Player has an issue with DV videos that include fallback?

Apoligies in advance for my ignorance. I'm quite new to HDR and stuff. Thanks!

**Comment by moneytoo** [comment]
I don't think I will be able to anything about this as I don't have any knowledge about Dolby Vison as well as don't have any DV capable hardware. Just Player can only be as good as ExoPlayer (& used hardware).
To resolve any DV problems, please reproduce your issues in the [ExoPlayer Demo](https://github.com/google/ExoPlayer/tree/release-v2/demos) app and report it directly to ExoPlayer on their [issue tracker](https://github.com/google/ExoPlayer/issues).
