### ISSUE TITLE
Auto load external subtitles with language tag (and prefer over internal subtitles)

### ISSUE THREAD

**Issue by DecalicatanDecalicatan** [moneytoo/Player#331]
Hi,

Thanks for the player, perfect playback of Dolby Vision matroska files with my Shield Pro 2019.

Would it be possible to add auto load of external subtitles with language tag at the end of the file name i.e. for a file named movie.mkv to auto load subtitles movie.eng.srt (or any movie.*.srt)? and also to prefer external subtitles files over internal subtitles.
I name my subtitles files this way because I also use the Language Preference Manager addon with Kodi (and I am sometimes too lazy to remux everything ^^ )

edit: the auto-load of external subtitles does not work when Just Player is launched from kodi as an external player. Its work when a file is started from with Just player 
My playercorfactory is like that:
    <player name="JustPlayer" type="ExternalPlayer" audio="false" video="true">
        <filename>com.brouken.player</filename>
        <hidexbmc>true</hidexbmc>
        <playcountminimumtime>120</playcountminimumtime>
    </player>

Thanks in advance

**Comment by moneytoo** [comment]
Such lookups are really hacky and prone to breakage (as newer versions of OS tighten security and access to files). However things like you mention normally work with other player (IIRC - Nova Video Player, Jellyfin, Emby etc.) when they implement the MX Player or VLC API (which Just Player supports to some extend).
