### ISSUE TITLE
Sound Volume Problem

### ISSUE THREAD

**Issue by bilektugrul** [moneytoo/Player#335]
Sound volume always stays the same. Even though I open the app with full volume, the app just uses a fixed volume. Changing volume doesn't do anything. I'm on Android 12.1 CrDroid 8.7 (was the same on 8.4) using Mi A2 Lite. App is on the latest version (just updated).

**Comment by moneytoo** [comment]
As you are not using a stock ROM, I would suspect this could pretty much be the cause. Anyway, you can share a logcat output.

**Comment by bilektugrul** [comment]
Hey, sorry for the late reply. It works now, after a clean ROM setup.
