### ISSUE TITLE
Unable to use volume booster on Android TV

### ISSUE THREAD

**Issue by jpants36** [moneytoo/Player#338]
I have noticed on the mobile version there is an option to boost the volume. However, on Android TV,  whenever I use the buttons on the remote to change volume, it just changes system volume rather than the player's volume.

Is there a way that I can make it change the player volume rather than system volume?

Thanks

**Comment by moneytoo** [comment]
See https://github.com/moneytoo/Player/discussions/273#discussioncomment-2190934

**Comment by jpants36** [comment]
Alright, thanks. Are there any plans on implementing this on Android TV at some point, maybe in settings like the guy mentioned?
