### ISSUE TITLE
Ffmpegaudiorenderer  not used?

### ISSUE THREAD

**Issue by RexSuper** [moneytoo/Player#340]
Why is ffmpegaudiorenderer not used? Defaultrenderersfactory is used during initialization. When is ffmpeg associated with exo? Please answer my questions when you have time. Thank you

**Comment by RexSuper** [comment]
![image](https://user-images.githubusercontent.com/38449675/184316253-5b6d79da-428b-4f8f-9a2f-452ff921051b.png)

**Comment by RexSuper** [comment]
I generally understand that the following codes are the same. I can't find similar codes. It's strange and confusing

class FfmpegRenderersFactory extends DefaultRenderersFactory {

    public FfmpegRenderersFactory(Context context) {
        super(context);
        setExtensionRendererMode(EXTENSION_RENDERER_MODE_PREFER);
    }

    @Override
    protected void buildAudioRenderers(Context context, int extensionRendererMode, MediaCodecSelector mediaCodecSelector, boolean enableDecoderFallback, AudioSink audioSink, Handler eventHandler, AudioRendererEventListener eventListener, ArrayList<Renderer> out) {
        out.add(new FfmpegAudioRenderer());
        super.buildAudioRenderers(context, extensionRendererMode, mediaCodecSelector, enableDecoderFallback, audioSink, eventHandler, eventListener, out);

    }
}

ExoPlayer.Builder(MyApp.instance.applicationContext,new FfmpegRenderersFactory())

**Comment by moneytoo** [comment]
Ffmpeg is used as unsupported audio codecs are decoded. See the 1st usage in https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg#using-the-module

**Comment by RexSuper** [comment]
![image](https://user-images.githubusercontent.com/38449675/184587224-9d1e8c1a-b6c6-4c75-ac73-c4b7ca428403.png)

Do you mean that it will automatically reflect the implemented sub lines, as shown in the figure

**Comment by RexSuper** [comment]
OK, I seem to know their relevance, but this seems to be audio, not video. That is to say, ffmpeg only expands audio without video. HDR video is not supported, right? My core requirement now is to support HDR and Dolby, so I found your code base

**Comment by moneytoo** [comment]
Just Player doesn't really do much more than ExoPlayer which uses FFmpeg only for some audio codecs.
