### ISSUE TITLE
Can't Play media files stored in "/Android/data/"

### ISSUE THREAD

**Issue by hehenaice** [moneytoo/Player#344]
This is something not that I need everyday, but once in a while when I download an archive, and play the video files from solid explorer, the files that get cached in `/storage/emulated/0/Android/data/pl.solidexplorer2/cache/temp/` don't get played.
I think it'll be fixed if just player can recognise that the media is being played from the now restricted data folder, and raise the request to get access to the folder, it'll be great.
Thanks in Advanced.

**Comment by moneytoo** [comment]
As you have said, this is a restricted location and regular apps do not have access to it. Only some file explorers incorporate workarounds to access this location. Can other video players access files in this location at all? Anyway, these workarounds no longer work on latest Android (13).

**Comment by hehenaice** [comment]
Oh. I guess google is taking scoped storage really seriously.
I'm still on a11 lol.
Will have to resort to xplayer or vlc in these niche instances.
