### ISSUE TITLE
A couple of issues and improvement suggestions for ANDROID TV version

### ISSUE THREAD

**Issue by ChristianWaits** [moneytoo/Player#346]
First of all, thank you very much for this outstanding player. It's simple and straightforward, with few settings, but nevertheless, much better than the market leaders (VLC and MX Player). In my opinion, its strength lies precisely in its minimalism. No need to touch or configure anything, it plays ALL audio and video formats currently available. Even Audio EAC, Dolby Vision and Atmos, etc. Of course you must have compatible hardware. I only use the ANDROID TV version, installed from the Google Play Store on a Philips 70" 4K Dolby Vision Smart TV.

However, there are small improvements that I understand could and should be made to the player. And a couple of things I found that don't work quite well, at least on my device.

1) When you open the app, it automatically searches and opens the last movie played. This doesn't make much sense, since you have already watched that movie. When you open the player the next time, it is to watch ANOTHER movie. Following a minimalist concept, the app should open showing the empty player or the root directory of the storage that was used the last time to select a video.

2) When a video is paused, the interface appears (a top banner with the file name, the Play button in a large circle in the middle of the screen and the progress bar and settings buttons at the bottom). All that SHOULD AUTOMATICALLY DISAPPEAR after a couple of seconds, but it does not. And it's not even possible to manually hide that interface. This is particularly annoying because when you pause a movie, it's usually to take a closer look at some detail. Or to read something that appears on the screen. With Just Player it's difficult or impossible to do so, since the player interface always covers the paused image.

Consider what happens in other players like MX or any of the streaming platforms (Youtube, Netflix, Prime, HBO, Mubi, etc.). In all of them, when the video is paused, one of two things happens: either the player interface is automatically hidden (after a couple of seconds) or it's possible to hide it by pressing the Back button on the remote control, or the ESC or arrow down keys on the keyboard. The interface should NEVER remain on the screen without being able to be removed. That´s what currently happens in Just Player.

3) The player "remembers" the progress of movies that were already partially played. When you reopen that movie, it automatically starts from where it left off the last time. BUT, you don't always want to do that. Sometimes you want to start again from the beginning. That's why streaming platforms ALWAYS have both options: Resume Play or Restart (play from the beginning). In Just Player, when opening a previously opened movie, it should display the option "Resume Play or Restart" on the screen. As most other players do.

4) Remember that Smart TVs are often operated with a keyboard and mouse. It is a common flaw in many apps (and streaming platforms) not being prepared to receive mouse clicks or text inputs from a keyboard. With Minimalist Just Player, both work fine. It receives mouse clicks (even the long press for the settings button) and you can also pause and unpause the video with the enter or space bar on the keyboard. The only thing to improve, would be that a mouse click ANYWHERE ON THE IMAGE should pause or unpause the video, without the need for that click to be exactly on the circle of the Play button.

Things that don't work entirely well:
-At least on my device you can't change the speed of the video when the audio is Dolby Digital or Atmos. If you choose for example Speed 2X, the video doesn't change and when you go back into the speed setting, it says 1X again. With stereo audio, on the other hand, the speed change operates normally.

-Subtitles: Although the player redirects to the system configuration and takes the subtitle settings from there, it doesn't do it entirely well. In my case, in Just Player the subtitles appear smaller than they should. I have to choose "Extra Large" to make the subtitles appear in a size just "Normal". This causes that when I use other apps (like Mubi or Live Channels) that also take the subtitle settings from the system, the font looks huge. And then I have to modify it again. In other words, it forces me to modify the system subtitle settings every time I use Just Player. Except for the font size, the other settings are well recognized (background or font color, font outline or shadow, etc).

Thanks again for this player and I hope that in future updates you can implement the improvements I suggest.

**Comment by moneytoo** [comment]
>-Subtitles: Although the player redirects to the system configuration and takes the subtitle settings from there, it doesn't do it entirely well. In my case, in Just Player the subtitles appear smaller than they should. I have to choose "Extra Large" to make the subtitles appear in a size just "Normal". This causes that when I use other apps (like Mubi or Live Channels) that also take the subtitle settings from the system, the font looks huge. And then I have to modify it again. In other words, it forces me to modify the system subtitle settings every time I use Just Player. Except for the font size, the other settings are well recognized (background or font color, font outline or shadow, etc).

Based on my experience configuring subtitle size in Captioning preferences as well as received feedback, I tweaked the actual sizes as the range of available sizes seemed possibly too wide and it didn't allow more precise fine tuning near the recommended size range (based on https://www.bbc.co.uk/accessibility/forproducts/guides/subtitles/#Presentation-font-size).

I feel that this is something to possibly improve so if you know any other apps that use the system Captioning preferences (other than the apps you mentioned), please let me know.

> The only thing to improve, would be that a mouse click ANYWHERE ON THE IMAGE should pause or unpause the video, without the need for that click to be exactly on the circle of the Play button.

Do any 1st party apps (or possibly other apps) work like this?

**Comment by ChristianWaits** [comment]
Thank you for your quick reply.

In MX Player, for example, you can pause or unpause the video with a mouse click anywhere on the image. Anyway, it's not a big problem, since I can do it by simply hitting the space bar on the keyboard as well.

Even the subtitles thing, I don't worry too much, since I can handle it by modifying each time the system settings. Among the apps I use and have installed, the only other ones that use the system settings for subtitles are Mubi and Live Channels (for IPTV). Both of them grab the font size according to what the system settings show. Just Player doesn't. It shows the font much smaller than the selected in system preferences. But again, I managed to handle it.

In my opinion, the most important things to be modified are the first three: 1) The way the app opens by default. 2) being able to hide the interface in the paused video. 3) To have an option for "Resume or Restart" a previously opened movie.

Thank you very much again and keep up the good work.
