### ISSUE TITLE
Cant play videos

### ISSUE THREAD

**Issue by shockergit** [moneytoo/Player#349]
cant play videos that are partially downloaded. the same file is working fine till the downloaded part in mx, vlc and samsung video players.

**Comment by shockergit** [comment]
![Uploading Screenshot_20220819-112311_Just Player.jpg…]()

**Comment by shockergit** [comment]
![Screenshot_20220819-112311_Just Player](https://user-images.githubusercontent.com/63154802/185577420-e7a469bf-632e-4dca-a41c-df7e1d61e83e.jpg)

**Comment by moneytoo** [comment]
Unfortunately ExoPlayer does not handle incomplete or invalid media so there's not much to do.

**Comment by Noitarud** [comment]
Try playing them after repairing, run:

…ffmpeg -i input.mp4 -c copy output.mp4
