### ISSUE TITLE
Request to implement more screen settings

### ISSUE THREAD

**Issue by PaulM278017** [moneytoo/Player#35]
![Screenshot_20210122_194722_com brouken player](https://user-images.githubusercontent.com/56556552/105565135-da546a00-5cea-11eb-918a-25754b54c41c.jpg)

/ The subtitles are cut off since the video implements it with its default dimension (They are not subtitles that are added as an extension) 👇 /
![Screenshot_20210122_194712_com brouken player](https://user-images.githubusercontent.com/56556552/105565150-ea6c4980-5cea-11eb-9fa5-5ce6da174171.jpg)

Here I show you the example of the two video settings that the player has, what I mentioned in the play store was the implementation of another screen setting where the video can be filled in the entire screen

VLC player example
 / What I want to show is that the cut subtitles are not seen here like in the example above since the video is filled on the screen with devices of larger dimensions /
![Screenshot_20210122_195458_org videolan vlc](https://user-images.githubusercontent.com/56556552/105565287-bc3b3980-5ceb-11eb-9613-ec4b61a63a37.jpg)

**Comment by moneytoo** [comment]
Thank you for describing the issue. Unfortunately I'm not a fan of fill/stretch format option as it distorts the image. Also having just two format options make it super easy and quick to switch. Nevertheless I would still like to add pinch to zoom for more precise sizing.

**Comment by moneytoo** [comment]
Version 0.19 (currently available here on Github and shortly also in testing on Google Play) adds pinch to zoom (#1 ). This should cover all the uses I want to support. I really do not want to replicate all the (too many) options like VLC (Fit screen, Fill, 16:9, 4:3, Centre, Best fit, Fit screen).

**Comment by PaulM278017** [comment]
Thanks for informing me, in fact, you just tried the new function and I
liked it, The player is on the right track and I see a lot of potential

 He apologized for being insistent
 But you should take into consideration the
 Function "fill video on screen" because remember that most devices today
are as standard 6.22 inch screen more or less

 Also a couple of gestures on the screen would not be too much (Forward and
Back) I know that it has the vision of a useful player few simple functions
 and that's fine, but there are functions that may be needed in the future


 That is a small suggestion.


 I look forward to contributing what I can to this project as player
development progresses ❤️

 -Greetings from El Salvador 🇸🇻
