### ISSUE TITLE
AVI Video not playing at all

### ISSUE THREAD

**Issue by Noitarud** [moneytoo/Player#354]
Black and stays on spinning circle. Shows length at bottom.
Suspect parent problem (exoplayer) again…

General
Complete name                            : F:\Content\Auxi\BBC wild weather cold - Quinzhee.avi
Format                                   : AVI
Format/Info                              : Audio Video Interleave
File size                                : 12.1 MiB
Duration                                 : 4mn 14s
Overall bit rate                         : 400 Kbps
Writing application                      : Lavf51.12.2

Video
ID                                       : 0
Format                                   : MPEG-4 Visual
Format profile                           : Simple@L1
Format settings, BVOP                    : No
Format settings, QPel                    : No
Format settings, GMC                     : No warppoints
Format settings, Matrix                  : Default (H.263)
Codec ID                                 : FMP4
Duration                                 : 4mn 14s
Bit rate                                 : 261 Kbps
Width                                    : 480 pixels
Height                                   : 272 pixels
Display aspect ratio                     : 2.222
Frame rate                               : 14.985 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.134
Stream size                              : 7.93 MiB (65%)
Writing library                          : Lavc51.41.0

Audio
ID                                       : 1
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Mode                                     : Joint stereo
Mode extension                           : MS Stereo
Codec ID                                 : 55
Codec ID/Hint                            : MP3
Duration                                 : 4mn 14s
Bit rate mode                            : Constant
Bit rate                                 : 128 Kbps
Channel count                            : 2 channels
Sampling rate                            : 44.1 KHz
Compression mode                         : Lossy
Stream size                              : 3.88 MiB (32%)
Alignment                                : Aligned on interleaves
Interleave, duration                     : 26 ms (0.39 video frame)

**Comment by mailinglists35** [comment]
I'm getting similar issue on my android 9 tv, except player directly shows error and does not play.

i've narrowed down the cause to be exoplayer not supporting mp3.

````
10-16 02:00:48.175  2446 14831 E SoftMP3 : mp3 decoder returned error 2
10-16 02:00:48.183 14769 14829 E ACodec  : [OMX.google.mp3.decoder] ERROR(0x80001001)
10-16 02:00:48.191 14769 14799 E ExoPlayerImplInternal:   Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecDecoderException: Decoder failed: OMX.google.mp3.decoder
````
I don't think the author can do much about it - the app relies on exoplayer to do it's job

**Comment by mailinglists35** [comment]
![image](https://user-images.githubusercontent.com/2054302/196011016-f378c969-4373-46ca-b8f3-924a86460f9e.jpeg)

**Comment by mailinglists35** [comment]
````
Format                                   : AVI
Format/Info                              : Audio Video Interleave
File size                                : 353 MiB
Duration                                 : 50 min 3 s
Overall bit rate                         : 984 kb/s
Writing application                      : Nandub v1.0rc2
Writing library                          : Nandub build 1853/release

Video
ID                                       : 0
Format                                   : MPEG-4 Visual
Codec ID                                 : DIV3
Codec ID/Hint                            : DivX 3 Low
Duration                                 : 50 min 3 s
Bit rate                                 : 847 kb/s
Width                                    : 512 pixels
Height                                   : 384 pixels
Display aspect ratio                     : 4:3
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.172
Stream size                              : 303 MiB (86%)

Audio
ID                                       : 1
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Format settings                          : Joint stereo / MS Stereo
Codec ID                                 : 55
Codec ID/Hint                            : MP3
Duration                                 : 50 min 3 s
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Compression mode                         : Lossy
Stream size                              : 45.8 MiB (13%)
Alignment                                : Split accross interleaves
Interleave, duration                     : 40  ms (1.00 video frame)
Interleave, preload duration             : 445  ms
````

**Comment by moneytoo** [comment]
@mailinglists35 
```
Format                                   : MPEG-4 Visual
Codec ID                                 : DIV3
Codec ID/Hint                            : DivX 3 Low
```
Devices usually do not have decoder for this old format so such videos won't play.

**Comment by mailinglists35** [comment]
divx was quite popular at that time. 
I'm surprised it wouldn't be supported.

However for my case if you loon at logcat snippet, it is exisplayer being let down by android mp3 decoder - it doesn't seem to be able to process the audio. no error about the video in my case.

**Comment by Noitarud** [comment]
@mailinglists35  Try what I wrote in my second post in #350 if you must see it work
