### ISSUE TITLE
Playback instructions

### ISSUE THREAD

**Issue by Noitarud** [moneytoo/Player#356]
This is remotely like file chapters (or subtitles) only rather advanced (some parts maybe somewhat sophisticated for this program, but leave up, maybe someone will implement in theirs!). I wish to tailor what is shown when a file is played (without reencode), reccomend separate config file (unless becomes standard!) Or multiple config files (playback options).

- volume/equalizer adjustment
Some places ultra quiet can increase (as far as limits permit) to compensate without user intervention. May need to warn to drop volume to fit maximum in.
Mute during chirps

- slideshow
Show pictures for audio files

- For censoring or alerting
Repeat, Skip, mute (or look away)
Put image or draw shape on top
(For viewer) add annotations (allow return to here), and importance.

- alter speed
Eg if files have multiple media add pause between
Eg motion not smooth, user can specify points and program can vary speed to make more linear

- for focus
When and how long and where to crop/shift area/subject into view.
Instead of just stretching XY, If you can tell the hardware to de-trapezoid it would be greater.
(Extra) Consider smooth transitions as scaling is performed, can infer acceleration with at least three points.

**Comment by moneytoo** [comment]
This is indeed too advanced.
