### ISSUE TITLE
Allow subtle speed hitching (eg for Faux 3D, DJing)

### ISSUE THREAD

**Issue by Noitarud** [moneytoo/Player#357]
I already suspect Two Video 3D cannot be done because I have noticed android does not play multiple files. So if you want to see something neat, try this on your PC or multiple android devices (move away so images are similar size):
Play a video, preferably with good motion, on both with a fraction of time difference, then look at them with your eyes crossed (align to see three images, centre image will appear 3D if right time apart). Due to the single viewpoint, a pendulum will appear to draw an ellipse.

Maybe a DJ-like speed control will help align just right, to function similar to the cue gesture, maybe put it across the bottom.

**Comment by moneytoo** [comment]
This is too obscure feature for simple video player.
