### ISSUE TITLE
See this UI design

### ISSUE THREAD

**Issue by Pranab009** [moneytoo/Player#36]
![Screenshot_20210124-200032_1](https://user-images.githubusercontent.com/1071643/105881496-e1d68480-6004-11eb-8cd8-8ebf9db8a3a7.png)

![20210124_223556](https://user-images.githubusercontent.com/1071643/105881518-e9962900-6004-11eb-85bd-696cd552dd29.jpg)

**Comment by Pranab009** [comment]
![Uploading 20210124_223556.jpg…]()

**Comment by moneytoo** [comment]
Try uploading it again, it's not visible.

**Comment by Pranab009** [comment]
I can't understand why it is not uploading.
I send it to you via email.

**Comment by Pranab009** [comment]
Make it  like this.

**Comment by moneytoo** [comment]
Currently I reuse the UI of ExoPlayer and extend it here and there just a little to add few more features or gestures. I keep a list of small things to tweak but I don't think I will do anything major. It's good enough for me and I'm pretty happy with the current setup.
