### ISSUE TITLE
UPDATE: iPhone Dolby Vision video recordings play in fallback HDR mode (but correctly play as DoVi in native TV player & MX)

### ISSUE THREAD

**Issue by DrHurt** [moneytoo/Player#363]
Update: see post number 2

I have an iPhone 13 which records videos in h.265 DoVi and outputs streams in MOV containers as is typical of Apple. 

The videos I have work on my TV's native media player and MX when in HW mode and I see the TV popup saying DoVI. (making me think the underlying exoplayer supports the file)

Same file played in Just Player, TV says HDR (and contrast looks a bit different).

That said, for comparison, Just Player works absolutely fine with non-Apple DoVi files and the TV correctly shows the DoVi logo when videos start playing. So it's an MOV container/demux issue. 

Thanks and hope to see this fixed to make the best player even better.

**Comment by DrHurt** [comment]
Did some testing and here's an important update: It's not the MOV container, it's the actual stream / metadata.

I remuxed the MOV file to MP4 and Just Player still uses the fallback HDR metadata as opposed to main DoVi metadata. MX and native TV player both play in DoVi.

Not a deal breaker but as I said in my previous post, if an excellent player can be made better, then I'm all in to try and help.

Happy to share the recording from the iPhone.

**Comment by moneytoo** [comment]
Yes, please do share a short sample. There used to be an issue with DV from earlier iPhones in the past  https://github.com/google/ExoPlayer/issues/8530
Also, are the files referenced in that issue playing correctly on your TV?

**Comment by DrHurt** [comment]
Here's an untouched short recording from my (regular) iPhone 13 using stock iOS camera app.

On the TV's built-in "media" app, it plays as DoVi
On MX player (HW mode), it plays as DoVi
On Just player, it plays as HDR (and looks a bit washed out, but definitely still useable)

https://drive.google.com/file/d/1Se79BLnirh3Wfk5ebhw8EqCurwWw-JFb/view?usp=sharing
