### ISSUE TITLE
Android TV 11 gets stuck in HDR/DoVi mode if home/back buttons pressed on remote. Must press "stop" to return to SDR

### ISSUE THREAD

**Issue by DrHurt** [moneytoo/Player#364]
Hello,

I've been testing this app on my high end Philips Android TV and I must say it's awesome so far.

One issue that took me a while to understand is that if I press "home" or "back" buttons on the remote while watching an HDR video, the TV remains in HDR mode which causes colors to be off on the home screen and other apps.

The only way to ensure that TV returns to SDR mode is to press STOP on the remote before pressing home/back to leave the app.

I would appreciate if the app implements a mechanism to return to SDR if home/back detected. Alternatively, though not ideal, force stop session if either button detected. TVs aren't multitasking devices anyway so home/stop usually imply user stopping video playback.

Thanks for reading

**Comment by DrHurt** [comment]
FWIW, enabled tunneled playback and that fixed it. Probably still needs fixing. Or maybe tunnel by default.

**Comment by moneytoo** [comment]
> Or maybe tunnel by default.

Unfortunately that causes different bunch of problems: https://github.com/google/ExoPlayer/issues/9661, https://github.com/google/ExoPlayer/issues/9133

**Comment by DrHurt** [comment]
Tunneled mode working perfectly so far with all videos I've tried on my TV. Seamless refresh rate switching too!
