### ISSUE TITLE
[REQUEST] Settings for "Skip silence"

### ISSUE THREAD

**Issue by MaZED-UP** [moneytoo/Player#365]
First of all, thank you for this great app.

Please make a list of settings for the "Skip silence" option to make the watching experience more suitable for low-volume videos.

The feature doesn't work perfectly with such videos of lectures and vlogs for example.

[This project](https://github.com/WofWca/jumpcutter) clarifies what I mean.

**Comment by MaZED-UP** [comment]
Can't these be adjusted by user? Or we might have presets.

![exoplayer.png](https://user-images.githubusercontent.com/59477548/190891907-6b17333c-936b-4e54-a494-c98e773d9df9.png)

Source:
https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/audio/SilenceSkippingAudioProcessor.html

**Comment by moneytoo** [comment]
Already requested in [#17 ](https://github.com/moneytoo/Player/issues/17#issuecomment-984220708)
