### ISSUE TITLE
Black Screen No Sound.

### ISSUE THREAD

**Issue by MinorX** [moneytoo/Player#369]
I've been using Just player on my TV and it's working fine but that same video clip does not work on my android device (Android 12). It's just showing a black screen with subtitles and audio is playing. What could be the issue?

**Comment by moneytoo** [comment]
Share details about the file (MediaInfo output). My guess is it could be HDR video when TV is capable decoding that but phone isn't.

**Comment by MinorX** [comment]
>  My guess is it could be HDR video when TV is capable decoding that but phone isn't.

Yes the file is HDR+ with Dolby vision. The TV supports HDR and Dolby vision and my phone supports HDR too but I'm not certain about the DV part of my phone.
