### ISSUE TITLE
SMB connection ends after 16/17min

### ISSUE THREAD

**Issue by jaqarll** [moneytoo/Player#373]
I have a very specific error using Nova Video Player with just player as the one actually playing the files. This issue does not occur when I start SMB videos from the Just Video Player itself, but when starting them from NOVA player.

After 16-17min (every time) the video stops playing with the following error: "java.net.ConnectException: Failed to connect to localhost/127.0.0.1:42057".

This error occurs on the Samsung Tab A7 tablet.

**Comment by moneytoo** [comment]
This looks really like Nova Video Player stops (or Android suspends the app) streaming/proxying video. I'm not sure what's the suspend policy when launching apps handling some intents but maybe it posting ongoing notification would help Nova. I'm afraid there's not much Just Player can do.
