### ISSUE TITLE
Improved it's main UI designs.

### ISSUE THREAD

**Issue by Pranab009** [moneytoo/Player#375]
I love this app. This is too good but it's UI is not Simple like any other player. Make it simple and handy.

All timer show one side one after another it is confusing.

If you want to play(switched) next videos then you have no any option until wait for the end or move slider to end.

If every tabs are fixed then it is easy to tap(habit like keyboard)
 horizontal scrolling is take some time.

Please Improved it's main UI designs.

See this 
![Screenshot_20220601-133427_1_1_1k](https://user-images.githubusercontent.com/65340361/195411884-2c02757a-bf70-44e9-9ecd-d7019a4de3bd.png)
![Screenshot_20220601-133427_1_1_1k_1_1](https://user-images.githubusercontent.com/65340361/195411905-87aa3a34-3d96-40f0-a27f-e1bd31b08b96.png)
![Screenshot_20220816-112839_1](https://user-images.githubusercontent.com/65340361/195411939-29fc4bb1-764b-4492-8fbb-fd38a9f48e30.png)
![DocScanner 12-Sep-2022 9-27 pm](https://user-images.githubusercontent.com/65340361/195411951-85b99b6f-e698-43c7-94f6-9fad8816b681.jpg)

**Comment by moneytoo** [comment]
I'm mostly using the default ExoPlayer UI and not planning any major changes.
