### ISSUE TITLE
Change brightness on Android TV

### ISSUE THREAD

**Issue by abskmj** [moneytoo/Player#376]
### Discussed in https://github.com/moneytoo/Player/discussions/370

<div type='discussions-op-text'>

<sup>Originally posted by **abskmj** September 25, 2022</sup>
First of all, thanks for such a great video player. I have been using this as the primary video player on my Android TV with Kodi.

I would like to know if there is a way to change the brightness of the video. On an android phone one would swipe to change the brightness but how would I do the same on an Android TV?</div>

**Comment by moneytoo** [comment]
This is quite specific. As Android TV remotes lack buttons, there are not really any empty ones to map. Just Player doesn't have any system for configuring actions/button mappings so I don't really see this feature would fit anywhere in Just Player.
