### ISSUE TITLE
Implement Same Look for File Picker and Subtitle Picker

### ISSUE THREAD

**Issue by Fmoment1** [moneytoo/Player#382]
Is there a way we can have the same look for file picker as the one we have for choosing subtitles? Screenshots for reference:

![Screenshot_20221101-180610](https://user-images.githubusercontent.com/28984045/199510134-63da4bff-0715-4aca-acf7-41cbe7c165b1.png)
![Screenshot_20221101-180626](https://user-images.githubusercontent.com/28984045/199510144-3cea579d-4c76-4c74-b77c-3f61bd29a9f1.png)

The first is the file picker, and here you can't see more of the file names because of that icon on the right. However, the subtitle picker doesn't have that issue, so we can see the file names more clearly. Is it possible to have the same look for both, as in, without that icon on the right? It'll make it easier to select episodes, because we can see more of the names.

**Comment by moneytoo** [comment]
This is the UI of the system file chooser and there are no options to change things like that.
