### ISSUE TITLE
Intent Documentation?

### ISSUE THREAD

**Issue by michalss** [moneytoo/Player#388]
Hi,

Like you player and i would like to support it also in mine streaming application, but im looking for intents documentation. So far im supporting vlc  and works great, but i would like to add some alternative and this player seems as a good choice. My project is not public yet but it is written in Maui. Below examples how im handling vlc intents. Please help

```csharp
 var uri = Android.Net.Uri.Parse(data.url);
            Intent intent = new Intent(Intent.ActionView);

            int vlcRequestCode = 42;
            intent.SetPackage("org.videolan.vlc");
            intent.SetDataAndNormalize(uri);
            intent.PutExtra("from_start", data.from_start);
            intent.PutExtra("position", data.position_in_seconds * 1000);
            intent.PutExtra("extra_duration", data.extra_duration_in_seconds * 1000);
            intent.SetComponent(new ComponentName("org.videolan.vlc", "org.videolan.vlc.gui.video.VideoPlayerActivity")); // this is essential :)
            StartActivityForResult(intent, vlcRequestCode);
```

Can you please provide some documentation for intents ?

**Comment by moneytoo** [comment]
See #203. This portion of MX Player api is supported:

- `position`
- `duration`
- `return_result`
- `subs`
- `subs.enable`
- `subs.name`
- `title`
- `end_by`

**Comment by michalss** [comment]
super partially it works, but my problem is that i cannot start video with position...

intent.SetComponent(new ComponentName("com.brouken.player", "com.brouken.player.PlayerActivity"));

is this correct ?

**Comment by moneytoo** [comment]
In addition to that, there's also a version with package name `com.brouken.player.legacy`.

**Comment by michalss** [comment]
no luck to make it work :(

```csharp
            var uri = Android.Net.Uri.Parse(data.url);
            Intent intent = new Intent(Intent.ActionView);

            int vlcRequestCode = 50;
            intent.SetPackage("com.brouken.player");
            intent.SetDataAndNormalize(uri);
            //intent.PutExtra("from_start", data.from_start);
            intent.PutExtra("position", data.position_in_seconds * 1000);
            intent.PutExtra("duration", data.extra_duration_in_seconds * 1000);
            intent.SetComponent(new ComponentName("com.brouken.player", "com.brouken.player.PlayerActivity")); // this is essential :)
            StartActivityForResult(intent, vlcRequestCode);
```

**Comment by michalss** [comment]
never mind i made it all work :) thx for help
