### ISSUE TITLE
[Suggestion] Do not open new player session and replace old one when opening the same media

### ISSUE THREAD

**Issue by ghost** [moneytoo/Player#389]
~~When using local media, the subtitles are reset when miminizing the app. When sharing media from Jellyfin android app as an external player to Just player, both the subtitles and the audio are reset to their automatic settings.~~

**Comment by moneytoo** [comment]
I believe that in this case the selection is controlled by Jellyfin.

**Comment by moneytoo** [comment]
Please describe the steps (ideally with a media sample) to reproduce this issue.
