### ISSUE TITLE
[Feature Request] Default language for audio stream / subtitles

### ISSUE THREAD

**Issue by xfzv** [moneytoo/Player#390]
Some videos have multiple audio streams and subtitles for different languages.

It would be nice if we could specify a default language so that they're picked automatically when opening a video.

[mpv-android has this](https://github.com/mpv-android/mpv-android/blob/e78de69669433e8dcd44cca9548e8903773cea2a/app/src/main/res/xml/pref_general.xml#L10-L22) for reference.

**Comment by vegedb** [comment]
I've checked your player seems to enable "Forced" streams to be the Default.

If there's no "Forced" streams, no subtitles will be enabled.
How do we ALWAYS enable subtitles?

**Comment by DarremMolko** [comment]
This was requested here https://github.com/moneytoo/Player/issues/200 (at least the audio part). I completely agree with this request, it would be nice not to have to choose the audio/subtitle track all the time.

**Comment by meltryllis-git** [comment]
Created an account just to +1 this, especially the subtitles part. I love this player, more than MX and Exo even, and my only gripe is having to manually choose subtitles every episode/movie.

**Comment by HDGuy** [comment]
Could you please add the option for “none” or at least a setting to default to off on the Android TV version? Subtitles are always on, and even when I turn them off they will turn back on after a pause goes into a screensaver. 

This is on a Nvidia Shield.

**Comment by moneytoo** [comment]
Available now in the latest release.

**Comment by moneytoo** [comment]
> Could you please add the option for “none” or at least a setting to default to off on the Android TV version? Subtitles are always on, and even when I turn them off they will turn back on after a pause goes into a screensaver.
> 
> This is on a Nvidia Shield.

Something like that shouldn't happen. Unless the app is instantly killed by the system, subtitle selection should be saved and restored when relaunching the app. Last few stable versions have issue with forced subtitle tracks. It's resolved now in latest betas as well as you should be able to use these new options. However let me know if you have something more I could go on (as so far it works fine for me).

**Comment by HDGuy** [comment]
The issue appears to be resolved with .132. Video starts with no subtitles enabled- paused into screensaver came back, still off.
