### ISSUE TITLE
High battery consumption

### ISSUE THREAD

**Issue by Lucky390163** [moneytoo/Player#393]
Sir just video player is consuming more batter than i expected it consumes 3 percent battery in 15 minutes while my Samsung video library player consumes 2 percent battery in 35 minutes.

Device - SM-M127G battery - 6000mah

**Comment by moneytoo** [comment]
Consumption of Just Player on my Samsung phone (S21 FE with 4500 mAh) is about 1.2% per 10 minutes. I will try Samsung video player to see if there's any significant difference. Are you sure there were no differences in screen brightness etc? What video/formats did you play (to know if hardware decoders were used)?

BTW: Here are some notes about battery consumption: https://github.com/moneytoo/Player/discussions/50#discussioncomment-355599 Generally, there is definitely some overhead but it shouldn't consume that much more.

**Comment by Lucky390163** [comment]
Samsung video library player is too much optimized i tested 50 times

**Comment by Lucky390163** [comment]
I use app decoders.

**Comment by Lucky390163** [comment]
![Screenshot_20221124-122616_Device care.jpg](https://user-images.githubusercontent.com/115852216/203714601-8e8c2fce-4bd6-4b7b-8b43-22c6d3f7a76c.jpg).

See here.

**Comment by Lucky390163** [comment]
In 18 minutes 3 percent battery.

**Comment by moneytoo** [comment]
> I use app decoders.

Well, the default is to prefer device decoders for a reason - hardware accelerated device decoders should be the more efficient than bundled ffmpeg audio decoders (which are normally used only as a fallback). This could be the reason for that.

**Comment by Lucky390163** [comment]
No but my phone has more optimized decoder.

**Comment by Lucky390163** [comment]
For example while listening music my music player only consumes 2 percent battrry in 30 minutes.

**Comment by Lucky390163** [comment]
Sir ffmpeg decoder is a system decoder or not?

**Comment by moneytoo** [comment]
> Sir ffmpeg decoder is a system decoder or not?

FFmpeg is decoder bundled with Just Player so it's not system decoder.

**Comment by Lucky390163** [comment]
I have a request for an feature can u add it?

**Comment by moneytoo** [comment]
When I compare several different Just Player sessions with Samsung's player, I do not find it any more battery hungry. (Playing Full HD the same brightness, H.264, E-AC3 content in all cases.)

![image](https://user-images.githubusercontent.com/1071643/207983665-f93dd856-a4bf-4bb6-9685-c586027973cd.png)

**Comment by Lucky390163** [comment]
No when i turned on hidden settings and enable some it use battery even i turned it off properly and restart the app.
