### ISSUE TITLE
[Feature Request] App shortcut for Player Settings

### ISSUE THREAD

**Issue by DarremMolko** [moneytoo/Player#394]
This request is something minimal but I thought it would make it easier for some people to find the settings.
In case it's not clear this is what I mean with shortcut:
![Screenshot_20221125-083057](https://user-images.githubusercontent.com/70179709/203977646-ea09adc5-2738-48ff-99dc-911e635441c0.jpg)

**Comment by moneytoo** [comment]
I considered this previously but decided against it. People often break playback in Just Player just by enabling tunneled playback or messing with decoders priority. This makes me not wanting to make the settings more visible. Also, there is a shortcut to settings also from the App info screen (`android.intent.action.APPLICATION_PREFERENCES`).
That reminds me that one of my todos is to add ⚠️ to these options (and also improve figuring out default options).

**Comment by DarremMolko** [comment]
I didn't know about the shortcut in the info screen. Should I close this issue then? Or will you reconsider it after adding the warning/caution to the options?
