### ISSUE TITLE
None under subtitles doesn't work. 

### ISSUE THREAD

**Issue by ImBigmOOse** [moneytoo/Player#396]
Just.Player.v0.114-legacy was the last version that would let you select none under subtitles and turn them off. I just tried Just.Player.v0.125-legacy and it doesn't work. I like subtitles on but there are some shows that have hard coded titles in them,  mostly shows when someone is speaking in a different language so subtitles needed to be turned off because they are on top of the hard coded ones. I have tried every new version since v.114 and none will not stay selected. They will change to other languages but not none. Could you please fix this. Thank you.

**Comment by moneytoo** [comment]
Your described issue matches the changes in ExoPlayer 2.18.0 (and Just Player releases you mention). However I modified that in my fork and it is working with my test media files. So please share at least media info output of such file or ideally video sample to duplicate that issue.

**Comment by ImBigmOOse** [comment]
I use Syncler app on my 2019 NVIDIA Shield Pro and have shows streaming from my Premiumize and Real-Debrid accounts.  I just tried the show The-Morning-Show S01E01 and it works correctly in Just.Player.v0.114-legacy but soon as I upgrade to Just.Player.v0.125-legacy and select None under subtitles it does nothing and subtitles keep playing. https://kickasstorrent.cr/the-morning-show-2019-season-1-s01-1080p-atvp-web-dl-x265-hevc-10bit-eac3-atmos-5-1-t3nzin-qxr-t4560421.html

**Comment by moneytoo** [comment]
When I download and play the linked video locally, it works fine and I can disable any subtitles. I tried few free sources in Syncler and it also seems to be working fine. So I'm not really sure how to replicate that issue.

**Comment by ImBigmOOse** [comment]
moneytoo,
So I downloaded the video right to my shield and bypassed Syncler app to see if that was causing the issue. Uninstalled Just player and ran a cleaner. Installed Just.Player.v0.126-legacy and played video off of shield. Same problem it will not let me select none subtitles and stay none. Pic 1 is Just.Player.v0.126-legacy showing None selected and not staying and pic 2  is back using Just.Player.v0.114-legacy and it working correctly. https://imgur.com/a/VKmFt2R

**Comment by moneytoo** [comment]
Does it work in [Just.Player.v0.127-legacy.apk](https://brouken.com/player/Just.Player.v0.127-legacy.apk)?

**Comment by ImBigmOOse** [comment]
moneytoo,
Thank you for all your hard work, Just.Player.v0.127-legacy fixed the issue. I really appreciate what you do.
Moose
