### ISSUE TITLE
Display P3 (DCI-P3) vs BT.2020

### ISSUE THREAD

**Issue by vegedb** [moneytoo/Player#398]
Ever since [v0.126](https://github.com/moneytoo/Player/releases/tag/v0.126) released today, I've been testing a bunch of android tv players. 
Seems like Nvidia Shield TV, Xiaomi TV Stick 4K and Mi Box S works as intended! Thanks for this!

However I've been having issues on Fire TV 4K AND 4K MAX devices. Tried a bunch of different (on device) display settings and justplayer settings. Same black screen problem for SOME DV videos.

The only difference I found between the 2 video test file,

[DCI-P3.zip](https://github.com/moneytoo/Player/files/10131019/DCI-P3.zip)
`Mastering display color primaries        : Display P3`

[BT.2020.zip](https://github.com/moneytoo/Player/files/10131018/BT.2020.zip)
`Mastering display color primaries        : BT.2020`

BT.2020 plays PERFECTLY. But videos that have `Mastering display color primaries        : Display P3`, just doesn't playback.

Of course the usual video players, VLC/MX/MPV/KODI all play DCI-P3 without problems.

**Comment by moneytoo** [comment]
It works on my devices (phones) so I'm afraid I won't be able to much about this. If you're playing it on DV display, you can try replicating it in the ExoPlayer Demo app and submitting it along with a bug report to ExoPlayer issue tracker. I'm afraid this is one of many quirks on Amazon devices.
