### ISSUE TITLE
Red Color Seekbar

### ISSUE THREAD

**Issue by ghost** [moneytoo/Player#4]
Change color RED seekbar. (YouTube red)

![ghhj_1](https://user-images.githubusercontent.com/75672019/102685848-6b768380-4209-11eb-9f95-c9eae98bd0d6.jpg)

**Comment by moneytoo** [comment]
I'm not sure about red (maybe system default tint color) but in general I agree it should be accented more (instead of current white). I'm also a fan of previous MX Player taller rectangular seekbar.

**Comment by moneytoo** [comment]
I tried using the green color from the icon but I'm not really liking it. It stands out too much (without any other same colored element visible on the screen). The current white is neutral and matches the other UI controls.

**Comment by moneytoo** [comment]
I currently do not plan any changes to the seekbar color.
