### ISSUE TITLE
Unexpected SecurityException

### ISSUE THREAD

**Issue by DarremMolko** [moneytoo/Player#401]
I'm getting this error from time to time since I updated to version 0.129 (now 0.130), it never happened prior to that. The video eventually plays normally but that error is kinda annoying.
**Edit**: I just managed to reproduce it. This pop ups after deleting a video and opening the player next time.
![IMG_20221208_200833_408](https://user-images.githubusercontent.com/70179709/206587147-c9430f2a-e30a-4222-8ada-3b2ea5994827.jpg)

**Comment by moneytoo** [comment]
Before you opened the details, was the exception type "Source error"?

**Comment by moneytoo** [comment]
Thanks for your notice. I removed some file checks on startup (as they cause quite a lot of ANR among users) and let the ExoPlayer handle it. I will disable it for all the source errors so it won't show useless warnings on startup.
