### ISSUE TITLE
bug: repeat toggle resets on device sleep/wake

### ISSUE THREAD

**Issue by mailinglists35** [moneytoo/Player#407]
enable repeat toggle in settings
open a clip
toggle the repeat indicator
sleep the tv
wake the tv

result: tv wakes with just player in the point in video where it was, playback resumes, repeat toggle is off, video stops at the end
expected: repeat toggle persists the sleep/wake cycle, video restarts at the end

**Comment by mailinglists35** [comment]
updated result/expected in case you read issues by mail and don't receive notification

**Comment by moneytoo** [comment]
Repeat toggle setting is intentionally not persistent.
