### ISSUE TITLE
[Question] Shield Dolby Vision Profile 7 Compatibility

### ISSUE THREAD

**Issue by george-emerald** [moneytoo/Player#412]
I recently purchased an Nvidia Shield TV Pro and I've read around the internet that it doesn't properly support DV P7. It disregards the EL, which most likely doesn't affect MEL DV, but could affect FEL DV. JVP states it fully supports all profiles, so I wonder what this means. Can the hardware itself tamper with the proper processing that's done by JVP, or am I worrying over nothing?

**Comment by moneytoo** [comment]
I would suggest looking into something like https://www.reddit.com/r/ShieldAndroidTV/comments/zouqxy/dv_for_dummies_and_fel_layer_handling/
Just Player doesn't really do anything to DV as it uses ExoPlayer defaults so it really depends what [ExoPlayer](https://exoplayer.dev/supported-formats.html#hdr-video-playback) and the device are capable. I never had a chance to test a DV so I don't know much about that.

**Comment by george-emerald** [comment]
As I understand it, it ignores the 12-bit master and plays the 10-bit master. Shouldn't make a difference since there are no 12-bit panels afaik.
