### ISSUE TITLE
Subtitles rendered with border and no fill color

### ISSUE THREAD

**Issue by ti-guru** [moneytoo/Player#413]
**Describe the bug**
Some subtitles are rendered with border only and no fill color. 

**To Reproduce**
1. Force direct play in Jellyfin for current user. 
2. Open movie with Just Player as external app in Jellyfin Android TV.
3. Select a subtitle, e.g. English or a foreign language. 
4. See subtitles not rendered correctly; only border color is rendered with no fill color. 

**Expected behavior**
Subtitles should be rendered with both border and fill color. The default Exoplayer that ships with the Jellyfin Android TV renders the subtitles correctly (but not consistently and does not trigger DV). 

**Device (please complete the following information):**
 - Model: Nvidia Shield pro
 - OS: Android 11, Shield Android TV SW version: 9.1.1
 - Just Player version: 0.136
 - Jellyfin server: 10.8.8

**Actual result**

![IMG_20230101_205511145_HDR](https://user-images.githubusercontent.com/31796171/210894033-b635bd20-b55a-4715-aa0d-b8403ffe8612.jpg)

**Additional context**
<details>
  <summary>MediaInfo output of example file</summary>
General
Unique ID                                : *****************
Complete name                            : D:\Video\*****************.mkv
Format                                   : Matroska
Format version                           : Version 2
File size                                : 62.6 GiB
Duration                                 : 2 h 43 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 54.8 Mb/s
Movie name                               : *****************
Encoded date                             : UTC 20**-**-** **:**:**
Writing application                      : MakeMKV v1.17.2 win(x64-release)
Writing library                          : libmakemkv v1.17.2 (1.3.10/1.5.2) win(x64-release)
Cover                                    : Yes
Attachments                              : cover.jpg

Video
ID                                       : 1
ID in the original source medium         : 4113 (0x1011)
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
HDR format                               : SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 2 h 43 min
Bit rate                                 : 49.5 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.249
Stream size                              : 56.5 GiB (90%)
Language                                 : English
Default                                  : No
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0050 cd/m2, max: 4000 cd/m2
Maximum Content Light Level              : 457 cd/m2
Maximum Frame-Average Light Level        : 179 cd/m2
Original source medium                   : Blu-ray

Audio #1
ID                                       : 2
ID in the original source medium         : 4352 (0x1100)
Format                                   : MLP FBA 16-ch
Format/Info                              : Meridian Lossless Packing FBA with 16-channel presentation
Commercial name                          : Dolby TrueHD with Dolby Atmos
Codec ID                                 : A_TRUEHD
Duration                                 : 2 h 43 min
Bit rate mode                            : Variable
Bit rate                                 : 4 597 kb/s
Maximum bit rate                         : 5 022 kb/s
Channel(s)                               : 8 channels
Channel layout                           : L R C LFE Ls Rs Lb Rb
Sampling rate                            : 48.0 kHz
Frame rate                               : 1 200.000 FPS (40 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossless
Stream size                              : 5.25 GiB (8%)
Title                                    : Surround 7.1
Language                                 : English
Default                                  : Yes
Forced                                   : No
Original source medium                   : Blu-ray
Number of dynamic objects                : 11
Bed channel count                        : 1 channel
Bed channel configuration                : LFE

Audio #2
ID                                       : 3
ID in the original source medium         : 4352 (0x1100)
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 2 h 43 min
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 748 MiB (1%)
Title                                    : Surround 5.1
Language                                 : English
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #1
ID                                       : 4
ID in the original source medium         : 4776 (0x12A8)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 2 h 42 min
Bit rate                                 : 14.3 kb/s
Frame rate                               : 0.213 FPS
Count of elements                        : 2074
Stream size                              : 16.6 MiB (0%)
Title                                    : *A foreign language*
Language                                 : *A foreign language*
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Text #2
ID                                       : 6
ID in the original source medium         : 4768 (0x12A0)
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 2 h 32 min
Bit rate                                 : 14.9 kb/s
Frame rate                               : 0.213 FPS
Count of elements                        : 1950
Stream size                              : 16.3 MiB (0%)
Title                                    : English
Language                                 : English
Default                                  : No
Forced                                   : No
Original source medium                   : Blu-ray

Menu
00:00:00.000                             : en:Chapter 01
00:12:36.172                             : en:Chapter 02
00:23:29.116                             : en:Chapter 03
00:37:00.885                             : en:Chapter 04
00:42:50.234                             : en:Chapter 05
00:49:24.503                             : en:Chapter 06
00:58:35.553                             : en:Chapter 07
01:04:10.638                             : en:Chapter 08
01:15:47.251                             : en:Chapter 09
01:25:12.482                             : en:Chapter 10
01:36:15.060                             : en:Chapter 11
01:50:54.773                             : en:Chapter 12
02:01:36.789                             : en:Chapter 13
02:08:40.379                             : en:Chapter 14
02:16:42.319                             : en:Chapter 15
02:27:46.941                             : en:Chapter 16

</details>

**Comment by moneytoo** [comment]
These are double layer PGS. Unortunately, ExoPlayer doesn't fully handle those: https://github.com/moneytoo/Player/issues/170, https://github.com/google/ExoPlayer/issues/7458

[Jellyfin actually transcodes](https://github.com/jellyfin/jellyfin-androidtv/issues/1254#issuecomment-1069703668) files with embedded PGS.
> We currently don't use exoplayer to render subtitles. Currently with exoplayer, graphical subtitles need to be burned in via transcoding.
