### ISSUE TITLE
can't play videos from external

### ISSUE THREAD

**Issue by thepaleguy** [moneytoo/Player#415]
![20230111_075930](https://user-images.githubusercontent.com/96138215/211720337-42dcc753-bc09-4516-a146-8962c80764d7.jpg)
![20230111_075848](https://user-images.githubusercontent.com/96138215/211720352-1d609108-99f1-4d65-a7d4-339fd6056790.jpg)
![Screenshot_20230111-075442_Just Player](https://user-images.githubusercontent.com/96138215/211720370-257f0245-c739-4638-96cd-01e8905c282d.jpg)

**Comment by moneytoo** [comment]
Cannot replicate. Opening files from Termux (even external storage) works fine for me. If you still facing the issue, share a bug report or post a logcat output.
