### ISSUE TITLE
Playback Speed Broken

### ISSUE THREAD

**Issue by jarvis-98** [moneytoo/Player#417]
When attempting to change playback speed, it just won't work. I will hit 1.25x etc and it will still only play media at 1.00x speed.

I am using 0.136 release on an Nvidia shield pro 2019 model

**Comment by moneytoo** [comment]
It works for me on a phone. Speed control may not work when bitstreaming audio. If this is the case, you may work around that by setting "Decoder priority" to "Prefer app decoders" in the advanced settings (after long tapping the gear). Though this may degrade the audio, depending on your configuration.
