### ISSUE TITLE
No automatic change of audio source when using BT headset during playback

### ISSUE THREAD

**Issue by ti-guru** [moneytoo/Player#418]
**Describe the bug**
Just Player does not change automatically from incompatible to compatible audio source when direct playing mkv file with Jellyfin on Nvidia Shield when BT headset is connected to Shield. Player opens, but does not start streaming. Error message is briefly displayed. When manually changing audio source from e.g. TrueHD 7.1 to DD 5.1 i player menu, direct play resumes.

**To Reproduce**
1. Force direct play in Jellyfin for current user. Connect BT headset to Nvidia Shield. 
2. Open movie that has both a TrueHD 7.1 audio source and a DD 5.1 track with Just Player as external app in Jellyfin Android TV.
3. See error with message _MediaCodecAudioRenderer_ error, index=2, format=Format(2, Surround 7.1, null, audio/true-hd, null, -1, en, [-1, -1, -1, 0], [8, 48000]), _format_support=YES_

**Expected behavior**
Just Player should automatically switch to compatible audio stream (if present in file) when using direct play with BT headset. 

**Device (please complete the following information):**
 - Model: Nvidia Shield pro
 - OS: Android 11, Shield Android TV SW version: 9.1.1
 - Just Player version: 0.136
 - Jellyfin server: 10.8.8

**Media**
NA

**Additional context**
NA

**Comment by moneytoo** [comment]
Please try long pressing the gear and changing "Decoder priority" to "Prefer app decoders". Does it work then?

**Comment by ti-guru** [comment]
> Please try long pressing the gear and changing "Decoder priority" to "Prefer app decoders". Does it work then?

This works. However, when streaming mkv files with soundbar with "prefer app decoder" setting, the TrueHD stream does not trigger the soundbar (should see rolling text with "TrueHD - Dolby Atmos"). Not really sure what source the soundbar gets (TrueHD or DD?).
