### ISSUE TITLE
Decoder failed: OMX.MTK.VIDEO.DECODER.AVC

### ISSUE THREAD

**Issue by 01soni247** [moneytoo/Player#419]
**Describe the bug**
Decoder failed: OMX.MTK.VIDEO.DECODER.AVC

**To Reproduce**
1. Open Open mkv videos from the application media files
2. It says "Decoder failed: OMX.MTK.VIDEO.DECODER.AVC
"

**Expected behavior**
It says "Decoder failed: OMX.MTK.VIDEO.DECODER.AVC
"

**Device (please complete the following information):**
 - Model: Redmi 9
 - OS: Android 13
 - Version 0.136

**Media**
Video contains copyright, which is clear Video 1080p 300-400mb with a duration of 24-30 minutes

**Additional context**
N/A.

**Comment by brentonv** [comment]
You should provide the developer with more information about the media file using [MediaInfo](https://mediaarea.net/en/MediaInfo) and also explain if this happens on all files or just this one

**Comment by 01soni247** [comment]
> You should provide the developer with more information about the media file using [MediaInfo](https://mediaarea.net/en/MediaInfo) and also explain if this happens on all files or just this one


General
Complete name :	[Doronime.id] Bidadari Samping Rumah - Episode 02 [1080p] [95B60F8A].mkv
Format :	Matroska
Format version :	Version 4
File size :	377 MiB
Duration :	23 min 40 s
Overall bit rate :	2 227 kb/s
Movie name :	[Doronime.id] Otonari no Tenshi-sama ni Itsunomanika Dame Ningen ni Sareteita Ken - Episode 02 [Hi10p] [AC-3] [1080p]
Encoded date :	UTC 2023-01-14 22:44:59
Writing application :	mkvmerge v56.1.0 ('My Friend') 32-bit
Writing library :	libebml v1.4.2 + libmatroska v1.6.4
Attachments :	AVALONTYPEBOLD.TTF / FOT-GMARUGOPRO-B.OTF / FOT-MatissePro-B-Toaru.ttf / GosmickSans.ttf / GosmickSansBold.ttf / KozGoPro-Light.otf / KozMinPr6N-Light.otf

Video
ID :	1
Format :	AVC
Format/Info :	Advanced Video Codec
Format profile :	High 10
Format level :	5.2
Format settings, CABAC :	Yes
Format settings, Reference frames :	5 frames
Codec ID :	V_MPEG4/ISO/AVC
Duration :	23 min 40 s
Bit rate :	1 919 kb/s
Width :	1 920 pixels
Height :	1 080 pixels
Display aspect ratio :	16:9
Frame rate mode :	Constant
Frame rate :	23.976 FPS
Color space :	YUV
Chroma subsampling :	4:2:0
Bit depth :	10 bits
Scan type :	Progressive
Bits/(Pixel*Frame) :	0.039
Stream size :	325 MiB (86%)
Writing library :	x264 core 146 r2538 121396c
Encoding settings :	cabac=1 / ref=6 / deblock=1:2:2 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=0.40:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=5 / b_pyramid=1 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=240 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=18.0 / qcomp=0.60 / qpmin=0 / qpmax=81 / qpstep=4 / vbv_maxrate=300000 / vbv_bufsize=300000 / crf_max=0.0 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:0.60
Default :	Yes
Forced :	No

Audio
ID :	2
Format :	AC-3
Format/Info :	Audio Coding 3
Commercial name :	Dolby Digital
Format settings :	Big
Codec ID :	A_AC3
Duration :	23 min 40 s
Bit rate mode :	Constant
Bit rate :	192 kb/s
Channel(s) :	2 channels
Channel layout :	L R
Sampling rate :	48.0 kHz
Frame rate :	31.250 FPS (1536 SPF)
Compression mode :	Lossy
Stream size :	32.5 MiB (9%)
Language :	Indonesian
Default :	Yes
Forced :	No

Text
ID :	3
Format :	ASS
Codec ID :	S_TEXT/ASS
Duration :	23 min 39 s
Bit rate :	12.3 kb/s
Frame rate :	4.863 FPS
Count of elements :	6901
Compression mode :	Lossless
Stream size :	2.09 MiB (1%)
Language :	Indonesian
Default :	Yes
Forced :	No

Menu
_00_00_00_000 :	[Doronime.id] Prolog
_00_00_46_020 :	[Doronime.id] OP
_00_02_15_990 :	[Doronime.id] Bagian 1
_00_12_19_960 :	[Doronime.id] Bagian 2
_00_22_05_010 :	[Doronime.id] ED
_00_23_34_970 :	[Doronime.id] Preview

**Comment by moneytoo** [comment]
> Format : AVC
> Bit depth : 10 bits

10 bit AVC is not supported by device decoders and therefore also not by ExoPlayer and Just Player.
