### ISSUE TITLE
Delete button not appearing

### ISSUE THREAD

**Issue by VasilisKos** [moneytoo/Player#422]
**Describe the bug**
The "delete" button doesn't appear after the end of a newly opened video. 

**To Reproduce**
1. Open a video file. 
2. When it ends only the "next" button appears, not the "delete". Tap the "next" button. 
3. After the end of the next video, the delete button appears as supposed to. 

**Expected behavior**
The delete button should appear after the end of the first opened video. 

**Device:**
 - Model: Nokia 6.2
 - OS: Android 11 
 - Version: 0.136

**Anyway, it'd be much more handy, if the "next"  and "delete"  buttons appeared when the pause button is pressed.**

**Comment by moneytoo** [comment]
Works for me, stale, so closing.
