### ISSUE TITLE
Dolby Vision

### ISSUE THREAD

**Issue by NexuSBresT** [moneytoo/Player#423]
Какая последняя версия в которой ещё НЕТ поддержки Dolby Vision? Или как отключить Dolby Vision?
What is the latest version that does NOT support Dolby Vision yet? Or how to disable Dolby Vision?

**Comment by moneytoo** [comment]
Check the "Dolby Vision profile 7 fallback" in [advanced settings](https://github.com/moneytoo/Player#features).

**Comment by NexuSBresT** [comment]
Doesn't help, still reproduces in Dolby Vision.

**Comment by moneytoo** [comment]
What Dolby Vision profile is that then (MediaInfo output)? Ideally share a sample.

**Comment by NexuSBresT** [comment]
My TV TCL P725 only supports 5, 7 Mell and 8 Dolby Vision profiles, but displays incorrectly (brightness changes earlier than necessary). So I want to disable Dolby Vision but keep HDR10+. Most likely you will have to use Vimu, because it is possible there. But I like Just player more.

**Comment by moneytoo** [comment]
So it doesn't work for profile 7? Does even playback of profile 5 work with the right color space? Provide some specific samples.

**Comment by NexuSBresT** [comment]
I was misunderstood. Everything works well, I just need to disable Dolby Vision in the player.

**Comment by moneytoo** [comment]
You are asking for something too general. Some fallback is already there and to my limited knowledge some other specific profile may not be possible to downgrade to HDR. So I need details about specific video / sample.

**Comment by brentonv** [comment]
@moneytoo here's some feedback on the mapDV7ToHevc function.

### Question:

> Brenton Venables
> Can some members please test a setting in Just Player. If you have a Dolby Vision capable device and a HDR display that's not Dolby Vision capable, can you play a Dolby Vision file which shows the green/purple tint? And if so then please try the same file using the latest Just Player and long press on the gear icon to open settings and turn on "Dolby Vision profile 7 fallback" and report if this displays colors correctly.

### Response:

> Tim Blair
> My TCL 75 inch 8K is Dolby Vision capable but I’m having the same green tint problem…
> Dolby vision file on Shield Pro 2019
> Dreaded green tint
> Found the desired setting (mapDV7ToHevc)
> Yahtzee!!! Color is correct; I’m an avid user of Just Player…
> 
> Brenton Venables
> Yeah ok, but your display is actually Dobly Vision capable so this just means Dolby Vision is turned off in Just Player. I still need someone to test on a HDR display that's not Dolby Vision capable. In your case there may be a display setting you're missing for Dobly Vision to work.
> 
> Tim Blair
> Here’s the same file on a Shield Tube with a HDMI 2.0 cable and a 75 inch TCL 4K TV not Dolby Vision and the result is the green tint persists…
> 
> Brenton Venables
> It seems to only disable Dolby Vision on Dolby Vision capable displays. What happens when you turn off Dolby Vision in the device, and in the player? It should display the correct colours..
> 
> Tim Blair
> Ok Dolby Vision off on the Shield Pro and the desired setting in Just played on and the purple tint returned which is different from the green tint with Dolby Vision in the Shield Pro on and the Just player setting off…

### Response:

> Bob Armstrong
> It doesn’t seem to work on with Nvidia Shield, on Samsung TV

Hope this helps🤷🏼‍♀️

**Comment by brentonv** [comment]
@moneytoo here's some feedback on the mapDV7ToHevc function.

### Question:

> Brenton
> Can some members please test a setting in Just Player. If you have a Dolby Vision capable device and a HDR display that's not Dolby Vision capable, can you play a Dolby Vision file which shows the green/purple tint? And if so then please try the same file using the latest Just Player and long press on the gear icon to open settings and turn on "Dolby Vision profile 7 fallback" and report if this displays colors correctly.

### Response:

> Tim
> My TCL 75 inch 8K is Dolby Vision capable but I’m having the same green tint problem…
> Dolby vision file on Shield Pro 2019
> Dreaded green tint
> Found the desired setting (mapDV7ToHevc)
> Yahtzee!!! Color is correct; I’m an avid user of Just Player…
> 
> Brenton
> Yeah ok, but your display is actually Dobly Vision capable so this just means Dolby Vision is turned off in Just Player. I still need someone to test on a HDR display that's not Dolby Vision capable. In your case there may be a display setting you're missing for Dobly Vision to work.
> 
> Tim
> Here’s the same file on a Shield Tube with a HDMI 2.0 cable and a 75 inch TCL 4K TV not Dolby Vision and the result is the green tint persists…
> 
> Brenton
> It seems to only disable Dolby Vision on Dolby Vision capable displays. What happens when you turn off Dolby Vision in the device, and in the player? It should display the correct colours..
> 
> Tim
> Ok Dolby Vision off on the Shield Pro and the desired setting in Just played on and the purple tint returned which is different from the green tint with Dolby Vision in the Shield Pro on and the Just player setting off…

### Response:

> Bob
> It doesn’t seem to work on with Nvidia Shield, on Samsung TV

Hope this helps🤷🏼‍♀️

**Comment by sigma2017** [comment]
Hello, I have opened a different thread as an issue talking about Dolby Vision profile 7 FEL. My Philips OLED tv can read any mkv DoVi over the network (profiles 5, 7 MEL and 8) but not 7FEL. This profile is present on the original 4k BD and on the remuxed variant of those. It is double track double layer, something like this. All of the time the files are hybrid, either original m2ts files or mkv files(remux). Ok, I understand that DoVi doesn't trigger with 7 FEL but why HDR doesn't as well? I really don't understand how dedicated players like ZIDOO or Dune can correctly read these files but smart Tvs can't. What is so "special" to those players ? All of them are using some "special" soc which is not present in any smart tv or it is just a software "feature"?
Thank you.
