### ISSUE TITLE
Fingerprint Sensor bring up UI element

### ISSUE THREAD

**Issue by Monirzadeh** [moneytoo/Player#424]
**Describe the bug**
when I touch fingerprint sensor, UI element (bottom, menu, etc.) show up

**To Reproduce**
1. Play a video
2. touch fingerprint sensor

**Expected behavior**
it shouldn't show Ui element if you touch fingerprint sensor

**Device (please complete the following information):**
 - Model: Pocophone F1
 - OS: Android 13
 - Version 0.123

**Comment by moneytoo** [comment]
Probably related to resolved issue #427. Reopen if it's still valid.
