### ISSUE TITLE
Incorrect sorting

### ISSUE THREAD

**Issue by Archeix7** [moneytoo/Player#425]
![IMG_20230125_183037_538](https://user-images.githubusercontent.com/51048550/214621461-98c1707f-4553-4d8e-bd66-70e04622f8e2.jpg)

**Comment by moneytoo** [comment]
This is the system file chooser so there's only lexicographical sorting. Prepend zeros to have it in the expected order.

**Comment by Archeix7** [comment]
https://user-images.githubusercontent.com/51048550/214896119-d0679d57-f929-4cd0-93b2-e08d3c53c6f3.mp4

**Comment by Archeix7** [comment]
After I added 0, those 2 videos do not want to open, lol
