### ISSUE TITLE
UI appearing randomly on landscape mode

### ISSUE THREAD

**Issue by VasilisKos** [moneytoo/Player#427]
The UI appears on my device randomly while playing videos on landscape mode, without touching the screen at all, even when the screen is locked (the lock icon appearing on the center of the screen). This happens only when I hold the device on my hands, not when it's completely still, like e.g. on a table. By the moment I move the device the UI appears. This doesn't happen on portrait mode.

**Device:**
 - Model: Nokia 6.2
 - OS: Android 11
 - Version: 0.137

**Comment by VasilisKos** [comment]
The issue is not happening on my wife's Xiaomi Redmi 9C... 🤔

**Comment by moneytoo** [comment]
Sound like a faulty touchscreen.

**Comment by VasilisKos** [comment]
> Sound like a faulty touchscreen.

Faulty only with this app? 😁

**Comment by VasilisKos** [comment]
> I guess it's possible. As a video player, it may use the phone resources and draw power in a special way that triggers some (touchscreen) problem. Just Player already ignores taps near the edges of the screen to prevent accidental touches. Try enabling "Pointer location" in phone's "Developer options" to see if it's really something like this.

Unfortunately, "power location" doesn't show any "accidental" taps. So, that's not the case...

**Comment by minh3339** [comment]
My newly purchased Lenovo P11 Pro Gen 2 tablet has the same problem as you. That proves that the player is having problems

**Comment by VasilisKos** [comment]
By the way, Next Player [,](https://github.com/anilbeesetti/nextplayer) which is also Exoplayer based, doesn't have that bug on my device, so it's certainly a bug.

**Comment by moneytoo** [comment]
Are you able to replicate it? The UI is only triggered at media end, by touchscreen or any unknown key event. I Would you be able to capture a bug report (or logcat output only) if I provide a debug build?

**Comment by VasilisKos** [comment]
> Are you able to replicate it? The UI is only triggered at media end, by touchscreen or any unknown key event. I Would you be able to capture a bug report (or logcat output only) if I provide a debug build?

It's always replicated. Give a debug built, and I'll probably be able to send a report.

**Comment by moneytoo** [comment]
Try this version: [Just.Player.v0.146-controller-debug.apk](https://brouken.com/player/Just.Player.v0.146-controller-debug.apk) Does anything (what text?) pop up on the screen when the UI appears?

**Comment by VasilisKos** [comment]
> Try this version: [Just.Player.v0.146-controller-debug.apk](https://brouken.com/player/Just.Player.v0.146-controller-debug.apk) Does anything (what text?) pop up on the screen when the UI appears?

Yes. A message "Key: 0" pops up. On the contrary, when I do tap the screen the message "Tap" appears.

**Comment by moneytoo** [comment]
In this case this should fix it: [Just.Player.v0.147.apk](https://brouken.com/player/Just.Player.v0.147.apk)

**Comment by VasilisKos** [comment]
> In this case this should fix it: [Just.Player.v0.147.apk](https://brouken.com/player/Just.Player.v0.147.apk)

Yes! Bug killed! So, it actually was a bug.
