### ISSUE TITLE
[Feature-request] Force auto-load subtitles with the same name. Remember the playback speed

### ISSUE THREAD

**Issue by song2daodao** [moneytoo/Player#435]
**Description**
The "Skip Silence" feature is awesome, so I started using Just Player on my pc via WSA.

While I was watching the online class video ( mkv format with internal subtitles ). The player can't recognize the subtitles as a specific format ( probably because I'm using Chinese subtitles and they are ai recognized by 剪映 ), so the subtitles can't be loaded automatically, if the player can force to load the same name subtitles that would be great.
![屏幕截图 2023-02-16 004440](https://user-images.githubusercontent.com/99074946/219095344-46f86f0c-a81e-4171-9603-a9cf14420916.png)

And I hope to add the function of remembering the playback speed, whenever I switch to the next video, I have to choose the playback speed again.

**Expected feature**
Force auto-load subtitles with same name. Remember the playback speed

**Device (please complete the following information):**
 - OS: Windows11，WSA
 - Version [0.137]

**Comment by sherpajosh** [comment]
Will the feature to remember playback speed be added?

**Comment by sherpajosh** [comment]
Which of these is not planned? The force auto-loading of subtitles or remembering of playback speed?

**Comment by moneytoo** [comment]
Automatic loading of external subtitles is already supported.

**Comment by sherpajosh** [comment]
Ok, so remembering of playback speed is not possible?
