### ISSUE TITLE
Dolby Vision Profile 7 FEL sometimes doesn't Trigger on any AndroidTV

### ISSUE THREAD

**Issue by sigma2017** [moneytoo/Player#439]
Hello,
This is a very well known issue related to this special Dolby Vision profile, any mkv file using this profile simply doesn't activate DoVi when you start the video file. Even if the file have HDR as well (hybrid) nothing will be triggered either DoVi or HDR.
The issue is present on https://github.com/google/ExoPlayer/issues/10846 as well. Since this project started as a ExoPlayer fork and added a ton of improvements over it, any chances for this issue to be fixed? The dedicated players like Dune, Zidoo etc don't have this problem so obviously this is software related. I refuse to believe that those players are using some special SoCs which somehow can hardware deal with this special format. Should be software related.
Thank you.
LE: just noticed the option to fallback to HDR10 for profile 7.

**Comment by sigma2017** [comment]
Hello again, I don't want to open a new issue, I will explain here.
I have noticed something weird related to how justplayer deals with metadata inside mkv on 3 Philips OLED TVs (2021 and 2022 models). If you play the mkv locally from a usb drive directly on tv, justplayer will detect all the time correctly HDR or DoVi but if you play same mkv file over the network (via vsftpd or webdav) sometimes triggers HDR/DoVi, sometimes it doesn't. Tested with more than 10 separate mkv files, all 4k, some of them web-dl files, some other remuxes. I have to mention that I used usb3 to rj45 so the LAN connectivity is around 700 mbps, no network bottleneck. 
Last week I have discovered Nova Player which detects metadata all the time over the network, so it doesn't have this issue. Is more polished than justplayer with so many options. It is indeed a good alternative.
The power of justplayer is its footprint, I have appreciated all the time how light it is and how can deal with very large mkv files with high bitrate. Nova is good as I said but sometimes drops some frames (with hardware decoding btw) when dealing with very large files, never happened with justplayer. I don't need all the options Nova have, ok, interesting but all these features comes with a cost: is not as lightweight as justplayer is.
Can you take a look over this problem? I can provide more feedback if necessary.
Thanks in advance.

**Comment by moneytoo** [comment]
I'm afraid there's nothing I can do. Just Player still uses ExoPlayer/Media3 with only few specific patches that do not change but nothing else.
