### ISSUE TITLE
Add background playback (audio/video)

### ISSUE THREAD

**Issue by lavaplanetmircomposerspirit** [moneytoo/Player#44]
Hello is it currently possible to add an option where the user can activate the background playback?

**Comment by Pentaphon** [comment]
I think this would be a good feature to have, but it would need to have a new UI element. There has to be a notification with a play/pause button at least so you can go back to the player while using your phone for something else.

**Comment by moneytoo** [comment]
Currently background playback isn't supported, so the closest option is using PiP (Picture-in-Picture). There's one related hidden feature - **Auto PiP**. Long press the PiP icon to activate this feature. Then, when you exit Just Player through the home button and video is playing, PiP will be activated automatically.

**Comment by PoetAnderson1** [comment]
+1

This would help to prevent a lot of battery drain.

**Comment by JacobTravers** [comment]
I'd like to bump this, I want to use this app for lectures and audiobooks and it's "skip-silence" ability. The background play feature is great for audio/video content that doesn't necessarily need to be watched. Right now I'm stuck using PiP and sacrificing a small black box on my phone's display in order to listen to books.

**Comment by ShareASmile** [comment]
Yes to a feature to enable playing the video in background while the device screen is turned off. It would be a great thing if such a feature is implemented.

This will allow playing documentaries or such shows to be enjoyed like podcasts.
 so such an addition would be greatly appreciated and I believe there are other users who would also want such an option.

**Comment by ShareASmile** [comment]
any updates on this?

**Comment by C8opmBM** [comment]
Could be difficult to implement, but this is a must for me as well.
Watching a video and falling asleep while turning off the screen often is the norm. :)
Thanks!

**Comment by NanyangTaiji** [comment]
Actually, only need to add playback service, a good example is NewPipe, which can switch between background notification player, UI player and Pip Player, also use exoplayer. Similar features can be found in VLC player.

**Comment by Pentaphon** [comment]
> Yes to a feature to enable playing the video in background while the device screen is turned off. It would be a great thing if such a feature is implemented.

Yes. Background Playback is way more useful than PIP.

**Comment by gschurck** [comment]
Also highly interested by this feature (to switch between video and background audio for video podcasts).
Any suggestions for the implementation ?

**Comment by Charles7z** [comment]
It's a very nice player, but this single feature keeps me using MX Player or VLC. On my phone most videos are only partially watched as video and generally listened while the phone is off while i I'm doing other things and most audio players won't play videos and don't have speed control.

So this would be a great feature 😁

**Comment by Pentaphon** [comment]
@moneytoo can you add some tags to this highly requested feature like "pr welcome" and "help wanted"? 

Maybe then somebody can submit a PR.

**Comment by throwaway242685** [comment]
@moneytoo 

can you please tell us what's preventing this feature from being added?

this issue has 18 thumbs-up.

**Comment by moneytoo** [comment]
> @moneytoo
> 
> can you please tell us what's preventing this feature from being added?
> 
> this issue has 18 thumbs-up, so it's not just a minority.

I personaly don't need that feature so I have no interest in adding that. Also I'm not really looking into supporting features that other players already do (and probably do better).

**Comment by jtrv** [comment]
The combo of "skip-silence" and "background play" is really useful for long form content with a primary audio component and occasional visual components.

For streaming youtube / soundcloud content I use https://github.com/TeamNewPipe/NewPipe in this way.
For Audiobooks https://github.com/PaulWoitaschek/Voice can skip silence.
For Podcasts https://github.com/AntennaPod/AntennaPod can skip silence.

However I haven't found a player to do this with local media, I dont mean to be rude after you mentioned not wanting to support this feature, just commenting in case someone else might benefit or if anyone else finds a player they can post it here 👍🏽

**Comment by Pentaphon** [comment]
> I personaly don't need that feature so I have no interest in adding that. Also I'm not really looking into supporting features that other players already do (and probably do better).

I'd like to let people here know they can use https://github.com/anilbeesetti/nextplayer/pull/1103 which is working on background playback and is very similar to Just Player in terms of focusing on Exoplayer-based playback since you don't intend on adding this.

**Comment by nadir121** [comment]
Don't use this app, it has nothing special to add. Just use the native player in android. You will miss nothing. They both play videos and don't support background play.
I am leaving a comment to get notifications in case this changes and background play is added.

**Comment by rafnov** [comment]
Why this issue is closed?

**Comment by Pentaphon** [comment]
> Why this issue is closed?

Because the Dev doesn't want to overcomplicate his player.  

If you want this feature, switch to https://github.com/anilbeesetti/nextplayer/
