### ISSUE TITLE
Option to kill HDR10+

### ISSUE THREAD

**Issue by KyleSanderson** [moneytoo/Player#440]
**Describe the bug**

My ATV player bricks when I playback HDR10+ AND DoVi content (both in the same file). The panel goes to a black screen and I can't even exit the content, resulting in me having to remove the power from the device to get the display eventually back. It's frustrating because it's almost like stepping on a landmine each time.

**To Reproduce**
1. Open '...' HDR10+
2. Select '....' nothing because the screen is black.
3. See error and cry.

**Expected behavior**

Looneytoons plays back.

**Device (please complete the following information):**
 - Model: [e.g. Samsung Galaxy S22] Firestick 4K Max
 - OS: [e.g. Android 13] yes
 - Version [e.g. 0.134] latest 

**Media**
If applicable, add a short media sample which triggers the problem.

**Additional context**

This guy straight up ignores HDR10+... I think a switch to toggle might be fine.
https://github.com/quietvoid/xbmc/releases/tag/v21-dovi

**Comment by bobaoapae** [comment]
Also having issue with hdr10+.

I have a tcl c825 and firestick 4k max


on the firestick players cannot play this media:

General
Unique ID                                : 287260790794359083915345060219622240757 (0xD81C6A775E611494CE0759D557FFB1F5)
Complete name                            : G:\Downloads\Filmes\Cocaine Bear\Cocaine Bear - Get in line..mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 16.7 GiB
Duration                                 : 1 h 35 min
Overall bit rate                         : 25.0 Mb/s
Frame rate                               : 23.976 FPS
Encoded date                             : 2023-03-14 13:49:23 UTC
Writing application                      : mkvmerge v73.0.0 ('25 or 6 to 4') 64-bit
Writing library                          : libebml v1.4.4 + libmatroska v1.7.1

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@High
HDR format                               : Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2094 App 4, Version 1, HDR10+ Profile B compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 1 h 35 min
Bit rate                                 : 24.3 Mb/s
Width                                    : 3 836 pixels
Height                                   : 1 602 pixels
Display aspect ratio                     : 2.40:1
Frame rate mode                          : Constant
Frame rate                               : 23.976 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.165
Stream size                              : 16.2 GiB (97%)
Language                                 : English (US)
Default                                  : Yes
Forced                                   : Yes
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0050 cd/m2, max: 4000 cd/m2
Maximum Content Light Level              : 461 cd/m2
Maximum Frame-Average Light Level        : 305 cd/m2

Audio
ID                                       : 2
Format                                   : E-AC-3 JOC
Format/Info                              : Enhanced AC-3 with Joint Object Coding
Commercial name                          : Dolby Digital Plus with Dolby Atmos
Codec ID                                 : A_EAC3
Duration                                 : 1 h 35 min
Bit rate mode                            : Constant
Bit rate                                 : 768 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 525 MiB (3%)
Language                                 : English (US)
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : Yes
Complexity index                         : 16
Number of dynamic objects                : 15
Bed channel count                        : 1 channel
Bed channel configuration                : LFE


This happend on all mkv files that have dolby vision 8.1 /hdr10+

Kodi solution to disable hdr10+ fix the issue, without this i have full black screen or duplicate image ([see here](https://preview.redd.it/vt2p4ee0c2oa1.jpeg?width=4032&format=pjpg&auto=webp&v=enabled&s=606052d50a1bf4922cf1951cc532a63c737beeca))

Also TV it's self can play without any issue, just have issue when using firestick

**Comment by sigma2017** [comment]
On Philips OLED807 HDR10+ any 4k web-dl works perfect with justplayer.

**Comment by KyleSanderson** [comment]
> On Philips OLED807 HDR10+ any 4k web-dl works perfect with justplayer.

Great. The majority of devices do not with this combination of metadata.

**Comment by samuraisword0** [comment]
@moneytoo 
I hope you add this Feature becaues we have problom with UHD BDRemux 2160p [HYBRID] movies, Hybrid that has 2 or 3 HDR profile HDR10 and Dolby Vision or HDR10+ or both of them with HDR10. 

Nova player and Vimu player they Add option to disable Dolby Vision, But I prefer to use Just Player.
I hope you add option to disable Dolby Vision, all profile of dolby vision not only profile 7.
And option to disable HDR10+.

**Comment by moneytoo** [comment]
I think having DV/HDR related options would be reasonable. However I said to myself that I won't modify code which I cannot test. I already broke DV playback in the past so I don't want to repeat that. It there was such API in ExoPlayer/Media3, I would consider using it but otherwise I don't want to experiment.

**Comment by KyleSanderson** [comment]
Well that's disappointing. I guess for anyone trying to playback DV/HDR in JustPlayer, use Kodi... :\
