### ISSUE TITLE
Volume Up and Down Doesn't Work

### ISSUE THREAD

**Issue by bilektugrul** [moneytoo/Player#444]
**Describe the bug**
In some videos (torrent stream), changing volume doesn't work. There is a fixed volume and no way to change it.

**To Reproduce**
1. For example, open DDP5.1 Atmos version of the movie You People via Stremio
2. Change volume
3. You won't hear any difference in the sound volume.

**Expected behavior**
Sound volume must change.

**Device (please complete the following information):**
 - Model: Xiaomi Mi A2 Lite
 - OS: A12 CrDroid 8.7 (official old version for Mi A2 Lite)

**Additional context**
Been having this since I started using the app. I'd appreciate if you could fix it.

**Comment by moneytoo** [comment]
Sounds like a CrDroid issue. I read about similar issues on devices with CrDroid. It would be helpful if you could share specific sample though I'm afraid it's really an issue in CrDroid.

**Comment by bilektugrul** [comment]
> Sounds like a CrDroid issue. I read about similar issues on devices with CrDroid. It would be helpful if you could share specific sample though I'm afraid it's really an issue in CrDroid.

I will try to switch A13 Lineage, will let you know.
