### ISSUE TITLE
Feature Request: Play when downloading

### ISSUE THREAD

**Issue by Archeix7** [moneytoo/Player#447]
https://user-images.githubusercontent.com/51048550/224535799-7ed96b0b-0a48-47c7-adda-363824c7ec5a.mp4

**Comment by brentonv** [comment]
A torrent doesn't fill data from start to finish, so you can't play from start to finish until the download has completed

**Comment by Archeix7** [comment]
> start to finish
![IMG_20230313_065512_166](https://user-images.githubusercontent.com/51048550/224611468-c00d2d16-b661-4b08-aa05-9d0501ed3567.jpg)

**Comment by moneytoo** [comment]
ExoPlayer does not handle incomplete or invalid media.

**Comment by Archeix7** [comment]
Sad
