### ISSUE TITLE
Add ExoPlayer version number

### ISSUE THREAD

**Issue by lavaplanetmircomposerspirit** [moneytoo/Player#45]
It would be very helpful if the ExoPlayer version number is displayed e.g under gear icon when the user clicks on this button.

**Comment by moneytoo** [comment]
I don't think that it's something that majority of users want/need to know. Normal users do not care and advanced users can read changelogs or find detailed info here.

**Comment by Pentaphon** [comment]
moneytoo seems to keep this player's Exoplayer backend very up to date since it's very simple and reliant on Exoplayer. Plus we don't even have a settings page to put it on.
