### ISSUE TITLE
play pause not working with proguard

### ISSUE THREAD

**Issue by milansevenseasol** [moneytoo/Player#456]
**Describe the bug**
When I set proguard in app. play pause video not working in release apk.
how can i solve ?

**Comment by brentonv** [comment]
>"For most situations, the default ProGuard rules file is sufficient for R8 to remove only the unused code. However, some situations are difficult for R8 to analyze correctly and it might remove code your app actually needs

>To fix errors and force R8 to keep certain code, add a -keep line in the ProGuard rules file"

https://developer.android.com/studio/build/shrink-code

**Comment by brentonv** [comment]
>For most situations, the default ProGuard rules file is sufficient for R8 to remove only the unused code. However, some situations are difficult for R8 to analyze correctly and it might remove code your app actually needs

>To fix errors and force R8 to keep certain code, add a -keep line in the ProGuard rules file

https://developer.android.com/studio/build/shrink-code

**Comment by moneytoo** [comment]
This is expected as the play pause buttons are modified with reflection.
