### ISSUE TITLE
[Feature] Intent for external subtitles

### ISSUE THREAD

**Issue by michalss** [moneytoo/Player#458]
Hi,

Can you please add intent to load external subtitles(from local storage, url ??) ?

Regards

P.S: Psal sem Vám i email, bez odpovědi. Nevím, či přišel. Nicméně předem děkuji..

**Comment by moneytoo** [comment]
This shoudl be covered by the already partially implemented [MX Player API](https://mx.j2inter.com/api). The `subs` parameter is supported (I believe I tested it with something like Jellyfin or Emby).

**Comment by michalss** [comment]
works thx, i finally figure it out from code..
