### ISSUE TITLE
The text styles from subtitles does not works

### ISSUE THREAD

**Issue by nthtimes** [moneytoo/Player#459]
This player always uses custom text styles, even the subtitles with text styles.
I suggest that default to use the text style from subtitles, and add an option to force custom text styles.

**Comment by moneytoo** [comment]
https://github.com/moneytoo/Player#how-do-i-change-subtitle-font-size-or-color

> If you want to apply additional formatting defined in subtitles, leave this option off.

**Comment by plum7x** [comment]
Thanks. But some param from subtitles does not works, like fontname, even I added the font file into the mkv file.

**Comment by nthtimes** [comment]
Thanks. But some param from subtitles does not works, like fontname, even I added the font file into the mkv file.

**Comment by moneytoo** [comment]
What subtitle format is that? In case of SSA the support is quite limited: https://github.com/google/ExoPlayer/issues/8435#issuecomment-762449001

**Comment by nthtimes** [comment]
ASS subtitles and TTF font in MKV file

Part of reporting from MediaInfo
```
General
Format                         : Matroska
Attachments                    : jf-openhuninn-1.1.a.ttf
```

**Comment by moneytoo** [comment]
In this case it's indeed limited by the support of ExoPlayer/Media3.
