### ISSUE TITLE
Feature Request: Indicator to show if HW decoding is being used or not?

### ISSUE THREAD

**Issue by Pentaphon** [moneytoo/Player#463]
Would it be possible to add some kind of HW decoding indicator?

**Comment by moneytoo** [comment]
I don't see this as having much usefulness. Almost all device decoders are hardware accelerated (at least covering the most used formats today) and this does't change. As long you are using the same device. Even though you can just lookup specs for that device.

**Comment by Pentaphon** [comment]
Ok just thought I'd ask since mpv has it but I guess you're not interested. Closing.
