### ISSUE TITLE
Any way to change subtitle position?

### ISSUE THREAD

**Issue by ANONIMNIQ** [moneytoo/Player#464]
I want to change subtitle vertical position on screen, but can't find any option on my fire stick, is there any way to do this?

**Comment by DarremMolko** [comment]
It is not currently possible, and it has been requested before: #301 
I tagged the dev there recently to see if he has plans to implement it.

**Comment by Pentaphon** [comment]
There's no way to do it on JustPlayer but Nova can do it easily on TV. 

https://github.com/nova-video-player/aos-AVP

**Comment by ANONIMNIQ** [comment]
> There's no way to do it on JustPlayer but Nova can do it easily on TV.
> 
> https://github.com/nova-video-player/aos-AVP

I use nova most of the time, but for some reason not every DV file work on it, so I switch to Just player for these files, but lack of subtitles positioning on it make it impossible to watch on my projector.
