### ISSUE TITLE
Проброс звука в TCL телевизорах. 

### ISSUE THREAD

**Issue by Warius999** [moneytoo/Player#465]
Может разработчик сделать проброс звука, как в другом  известном плеере(авто+) для ТСЛ телевизоров? Фильмы в 4к только в Джаст идут плавно без дëрганья👍, а вот с пробросом звука проблема, не пробрасывает AC-3, только pcm.

**Comment by moneytoo** [comment]
I'm afraid this is a device or upstream (ExoPlayer) issue: #285, https://github.com/google/ExoPlayer/issues/9671

**Comment by Warius999** [comment]
> Я боюсь, что это проблема устройства или восходящего потока (ExoPlayer): [# 285](https://github.com/moneytoo/Player/issues/285) , [google/ExoPlayer # 9671](https://github.com/google/ExoPlayer/issues/9671)

Да это в ТСЛ что-то намутили, что пробрасывает только в DD +. Но в плеере виму как то смогли обойти эту проблему, но он мне не подходит. Жаль если ничего не поделать.

**Comment by moneytoo** [comment]
It's definitely possible to add workarounds but it would require too much back and forth to debug it and add some error prone fixes. One should really intent to fix this issue at its source. Just Player is only a wrapper around ExoPlayer / Media3.
