### ISSUE TITLE
Ability to add external files

### ISSUE THREAD

**Issue by Archeix7** [moneytoo/Player#466]
Like sounds or subtitles

![Screenshot_20230420-193804_Material Files~01](https://user-images.githubusercontent.com/51048550/233432617-541b96e8-f16a-4966-a9f9-ba4a75aac055.png)
![Screenshot_20230420-193819_Material Files~01~01](https://user-images.githubusercontent.com/51048550/233432653-9b49e9f8-e2c2-4c55-9520-45fc82d4517d.png)
![Screenshot_20230420-194005_Material Files~01](https://user-images.githubusercontent.com/51048550/233432676-cb36d8df-4547-4810-a01d-75a84b58609f.png)

**Comment by moneytoo** [comment]
Subtitles are supported: https://github.com/moneytoo/Player#how-do-i-open-subtitle-file-eg-srt
External audio support is out of scope for this player.

**Comment by Archeix7** [comment]
Thx
