### ISSUE TITLE
Turn off display

### ISSUE THREAD

**Issue by shockergit** [moneytoo/Player#467]
Please add an option to turn off display after the video is paused for the default timeout for phone.

It may reduce battery consumption.

**Comment by moneytoo** [comment]
It already works like that.

**Comment by Archeix7** [comment]
> It already works like that.

How yo do that?

**Comment by moneytoo** [comment]
> > It already works like that.
> 
> How to do that?

1. Pause video
2. Wait for the system timeout

The screen is kept on only during playback. When playback is stopped, the screen should turn off (if configured like that in system).

**Comment by Archeix7** [comment]
Oops, I'm sorry, I misread the subject, I wanted to know how you can listen to video with the screen off
