### ISSUE TITLE
Feature Request: Show Next video button when you get to 90% of the video and onwards

### ISSUE THREAD

**Issue by Pentaphon** [moneytoo/Player#468]
Especially on TV shows, we need to skip the end credits instead of waiting for the end of the video. 

Can we have the "next video" button show up when the duration gets to 90% so we only see the button in the last 10% of the video, which is where the credits will be? So we can easily skip those credits instead of having to watch them?

**Comment by Pentaphon** [comment]
@moneytoo any thoughts on this functionality? I think it's a good solution for skipping to the next file without having to see credits.

**Comment by moneytoo** [comment]
I don't think that value such as 90% would work universally. However the next/delete buttons should already be visible during credits if the video file contains chapters (last chapter = most probably credits). Anyway, skipping credits should generally be resolved by a single swipe.

**Comment by Pentaphon** [comment]
> I don't think that value such as 90% would work universally.

Sure it would. That's the point before the credits appear and it would work even if a video has no chapters, which is most videos. 

>Anyway, skipping credits should generally be resolved by a single swipe.

That's a long process. 

1) Bring up the scrollbar
2) Swipe until you get to the end. 
3) Tap the next button

Here's a shorter process. 

1) When you get to 90% bring up the UI
2) Tap the next button which appears at 90% and onward

Done. Much faster. I think it will work and it will be well received by users.
