### ISSUE TITLE
Remove long press to unlock to touch the unlock icon

### ISSUE THREAD

**Issue by shockergit** [moneytoo/Player#469]
please remove the unlock mode from long press to press the lock icon. its more practical and please move the lock icon to a corner.
The issue is the newer tablets have less bezels so if we hold the tablet and accidentally touch the screen it just unlocks.
unlock by touching the lock icon is much more practical.

**Comment by Pentaphon** [comment]
How about slide to unlock?

**Comment by rohitghali** [comment]
Long press to play at 2x speed instead would be fantastic.
