### ISSUE TITLE
Feature: Make the back button hide the UI when paused

### ISSUE THREAD

**Issue by TheDcoder** [moneytoo/Player#471]
By back button I mean the button my TV remote, the UI obstructs a significant portion of the image when paused.

Better yet, maybe don't show the UI at all until the user navigates down to it.

**Comment by moneytoo** [comment]
This is intentional #195

**Comment by TheDcoder** [comment]
Why though? There doesn't seem to be any rationale behind it.

**Comment by moneytoo** [comment]
It's simply about the fact that I'm customizing the player only around my needs and wishes. The usage on TV might be slightly different but at least on phones, I ended up strongly disliking the tap to toggle UI controller feature. I realized I don't need that extra tap and do not watch any content that would require that. There are hundreds other players out there so I went all in on being different.

**Comment by TheDcoder** [comment]
I understand your stance, and it is perfectly valid because it's your project after all.

However I would like to request addition of the functionality dismiss it by using the back button, that way both you and us the users would be satisfied :smile:

When watching a video or a movie, some scenes show text only for a brief moment, and sometimes we want to read it by pausing. Currently this is impossible... but we can easily make this possible by making the UI dismissable with the back button, and I'm assuming it would be a very easy task to implement!

I assure you that many users will be delighted to have this feature, thank you in advance! :pray:

> There are hundreds other players out there so I went all in on being different.

Indeed, but in my experience none of them even come close to the perfection and simplicity in this player! Especially for a TV, this is one of the few players which can properly send Dolby Atmos audio without transcoding it.
