### ISSUE TITLE
Inconsistent UI hiding behavior when you tap to hide as opposed to letting it hide itself

### ISSUE THREAD

**Issue by Pentaphon** [moneytoo/Player#472]
1) When allowing the UI to hide itself, most of the UI (the video overlay) goes away, but the progress line at the bottom, the nav buttons and the taskbar remain, and then they all finally hide. This is not preferred and just makes the UI hiding process last even longer by giving it 2 steps. The entire UI should vanish in 1 step, leaving only the video.

https://user-images.githubusercontent.com/49374058/235105695-d4a08a8c-0978-4af1-9a64-97dc76c1960a.mp4

2) When you tap to hide the UI, the entire UI vanishes, It happens in 1 step. This is the preferred behavior and should always be how the UI is hidden. 

https://user-images.githubusercontent.com/49374058/235105609-8f21b610-dd35-4513-b2f8-03ba8febdf27.mp4

The entire UI should hide itself in 1 step when tapped or when allowed to hide itself. This makes the UI hide behavior more consistent. Please make the UI hide itself in 1 step when allowing the UI to hide itself. Allowing the UI to hide itself is what most people will do anyway when watching fullscreen video, so making that process happen in 1 step is important and saves the viewer from having to see the UI for more than they should have to.

**Comment by moneytoo** [comment]
This is how the default ExoPlayer/Media3 player UI works. There are only methods `hideController()` and `showController` that work as you see in Just Player (as well as in the ExoPlayer demo app). There is no API to customize it any further.

**Comment by Pentaphon** [comment]
>This is how the default ExoPlayer/Media3 player UI works. There are only methods hideController() and showController that work as you see in Just Player (as well as in the ExoPlayer demo app). There is no API to customize it any further.

Reported upstream in https://github.com/androidx/media/issues/366

**Comment by moneytoo** [comment]
Anyway, I actually like how the hiding works. With gesture navigation it looks pretty symetrical and the partially visible ui (progressbar) gives user hint that it's about to hide but user can still make it show when iteracting with it.

https://user-images.githubusercontent.com/1071643/236290423-d8ebceb7-79fa-4d0a-912b-c439c99596d1.mp4

**Comment by Pentaphon** [comment]
> Anyway, I actually like how the hiding works. With gesture navigation it looks pretty symetrical and the partially visible ui (progressbar) gives user hint that it's about to hide but user can still make it show when iteracting with it.

I think it just makes the hiding process much slower. I expect every element on top of the video to be gone in 1 step. This current behavior makes me wait for the player overlay to hide, then wait for the taskbar and navigation to hide. I just want everything to hide quickly so I can see my video. The fact that leaving it alone is slower than tapping it seems odd to me. I can't think of any video player that does this.
