### ISSUE TITLE
Implement VLC like screencasting 

### ISSUE THREAD

**Issue by thenameissasi** [moneytoo/Player#475]
Title.
VLC allows "remote control" type screencasting.

**Comment by moneytoo** [comment]
Do you mean Chromecast or something else?

**Comment by thenameissasi** [comment]
Yes Chromecast, but the way VLC implements it.

**Comment by moneytoo** [comment]
Reimplementation of Chromecast is out of scope. Even just supporting Chromecast (#157) properly would require transcoding or at least remuxing videos so it won't happen without some ready made solution.
