### ISSUE TITLE
Gray bars on Sony Bravia TV HDR (Fix inside)

### ISSUE THREAD

**Issue by Kristijan1001** [moneytoo/Player#478]
Problem has been fixed a year ago on exo player here is the git issue:

https://github.com/google/ExoPlayer/issues/8803#issuecomment-817110543

Basically the bars are gray instead of black when playing hdr content.

**Comment by Kristijan1001** [comment]
Is this going to get fixed ? The app is sadly  unusable at the current state for me :( .

**Comment by moneytoo** [comment]
As trivial this solution sounds, I better avoid changing that as as I cannot verify it actually helped. I also worry this could uncover other device issues. Better if Sony fixes its firmware or ExoPlayer merges tested fix in the ui library.
