### ISSUE TITLE
ASS Subtitle support issue

### ISSUE THREAD

**Issue by Anthorty** [moneytoo/Player#479]
**Describe the bug**
when play a video with `.ass` subtitle file,if in this `.ass` file has some annotation.The annotation displays very quick,like a flash.Or display incorrectly.

**To Reproduce**
1. Open 'Any Video with `.ass` files which has some annotation'
2. Just play normally
3. See error

**Expected behavior**
The annotation in `.ass` file display right time and right place.

**Device (please complete the following information):**
 - Model: Nubia Z50 Ultra
 - OS: Android 13
 - Version 0.141

**Media**
Any video will reproduction that bug.

**Comment by moneytoo** [comment]
SSA/ASS support is quite limited (https://github.com/google/ExoPlayer/issues/8435). The issue you are describing looks like a side effect of that - for example when it SSA tries to display multiple captions at different positions at the same time.
