### ISSUE TITLE
Hyperdrive playback

### ISSUE THREAD

**Issue by Noitarud** [moneytoo/Player#481]
Some files do not seek due to exoplayer, yes we get it.
Since we can clearly see that the program can playback that media at faster speeds (without restarting), then take advantage of this to seek forward as fast as feasible until the target time. Sometimes length is unavailable, here i would like some space ahead of seek bar cursor. To seek backwards exoplayer would need to permit reverse playback (or backstep/trace) otherwise would need to restart and run at speed.

Presently, the program restarts when user habitually tries to seek. A short term solution would be if the program realises exoplayer would only restart then just keep it playing or pause, since restarting is likely an inconvenience to the user (i have never appreciated it*), only restart if bar is moved to there or by a decisive distance (or ultimately necessary to "reverse").

*Well, since the seek bar is inactive, maybe once.

(4Jul. Did a major edit to improve readability)

**Comment by brentonv** [comment]
@moneytoo just curious if there anything known about this issue on google/ExoPlayer because I didn't find anything in search

**Comment by moneytoo** [comment]
What files do not seek? Anything other than fragmented mp4?

**Comment by Noitarud** [comment]
FLV files #350, I also like to play some AAC files with your player (that have not been fixed up). Yeah I know I can reprocess the flv files losslessly with 'ffmpeg -c copy' but have kept these as is.
