### ISSUE TITLE
HEVC Play Error

### ISSUE THREAD

**Issue by oceanpredator** [moneytoo/Player#482]
![IMG_20230528_162040.jpg](https://github.com/moneytoo/Player/assets/116612749/b6430126-6676-49fb-b89d-75a338b9e9c5)

HEVC 10 bit videos are bot not playing. Getting the Error. In "Just Player"
But VLC can play it!

"Decoder failed: OMX.qcom.video.decoder.hevc"

**Expected behavior**

How to play HEVC Videos 
Please add HEVC videos support.

**Device

 - Model: Redmi 8A Dual
 - OS: Android 10
 - Version MIUI 12.5

**Comment by Pentaphon** [comment]
Sounds like your device has a broken HEVC codec.

**Comment by oceanpredator** [comment]
But VLC can play it. How? Even ”Just Player” have all the codecs!
