### ISSUE TITLE
Subtitles 

### ISSUE THREAD

**Issue by JonathanAkaJD** [moneytoo/Player#486]
Not really a bug but curious if it would be possible for you to add a toggle in settings to disable subtitles by default? It's frustrating that subtitles turn on automatically every time I start something.

**Comment by moneytoo** [comment]
I'm planning on changing that behavior. Meanwhile you should be able to disable that in [advanced settings](https://github.com/moneytoo/Player#:~:text=Some%20advanced%20features,App%20info%20screen.)).

> Some advanced features can be enabled or configured in settings. To access it, long press the ⚙️ gear icon. (Alternatively, you can also enter this settings from App info screen.)

**Comment by VasilisKos** [comment]
> I'm planning on changing that behavior. Meanwhile you should be able to disable that in [advanced settings](https://github.com/moneytoo/Player#:~:text=Some%20advanced%20features,App%20info%20screen.)).
> 
> > Some advanced features can be enabled or configured in settings. To access it, long press the gear gear icon. (Alternatively, you can also enter this settings from App info screen.)

I think it should be kept as it is. It's probably more convenient for most users. The respective advanced setting is just fine.

**Comment by moneytoo** [comment]
@VasilisKos I will disable automatic selection only for default subtitle tracks if system captioning preferences are turned off. This should make it work just like YouTube. Forced subtitles will still be always selected.

**Comment by VasilisKos** [comment]
> @VasilisKos I will disable automatic selection only for default subtitle tracks if system captioning preferences are turned off. This should make it work just like YouTube. Forced subtitles will still be always selected.

I think it'll be even better, if only the subs of the language that is chosen as default in the app settings are loaded automatically.
