### ISSUE TITLE
External srt subtitles not displaying

### ISSUE THREAD

**Issue by vikingloudmouth** [moneytoo/Player#490]
**Describe the bug**
External subtitles (srt) are shown in the list of subtitles and selected, but don't display onscreen 

**To Reproduce**
1. Open a video (from a network source, tested using both smb and webdav)  with external subtitles through Nova Video Player using the "Allow using another video player" option
2. Confirmed that external subtitle track is shown and selected in list of subtitles in Just (Video) Player
3. Subtitles don't display onscreen

**Expected behavior**
The selected subtitles displays onscreen.

**Device (please complete the following information):**
 - Model: Sony X90J
 - OS: Google TV

**Media**
Any external srt subtitle track

**Comment by marcelloinfoweb** [comment]
+1

**Comment by vikingloudmouth** [comment]
Has been solved by nova video player https://github.com/nova-video-player/aos-AVP/issues/1146.
