### ISSUE TITLE
Fomat issue

### ISSUE THREAD

**Issue by Lucky390163** [moneytoo/Player#491]
Bro .mkv 10 bit hevc video not supported, but it is working in mx and vlc player i tried to change decoder to app but issue persists.https://github.com/moneytoo/Player/assets/115852216/8f619b7b-301a-44b2-ae53-4f9096916458

**Comment by Lucky390163** [comment]
I will send you a mail of video recording.

**Comment by moneytoo** [comment]
What is your device? It needs to support HDR (as Just Player uses device decoders only for video).

**Comment by Lucky390163** [comment]
SM-M127G

**Comment by Lucky390163** [comment]
Mpv player is too good, then just video itself is also open source and gives more battery performance than this.

**Comment by Lucky390163** [comment]
The app is dead 💀 overall, and even the app decoder is not working. wtf bro, even my built-in video player is so good it drains 1 percent in 20 minutes.

**Comment by moneytoo** [comment]
Just Player relies on AndroidX Media / ExoPlayer which uses system decoders. It doesn't seem like that SM-M127G has HDR display so most likely device decoders do not handle HDR content.

**Comment by Lucky390163** [comment]
Ok, thanks for the clarification. But vlc maintains it properly.

**Comment by Lucky390163** [comment]
Give me the latest version of 0.149. Please, arm 8 core
