### ISSUE TITLE
Manual downshift to 2.0 stereo

### ISSUE THREAD

**Issue by sunlouder** [moneytoo/Player#492]
**Describe the bug**
Player can't playback multichannel audio on Android multimedia host in the car. It's shows 5 (or more if it's 7.1) different tracks and i cannot downmix it to 2.0 stereo. Can't hear central channel 

**Expected behavior**
Ability to manual set of an audio out mode to 2.0 stereo

**Device (please complete the following information):**
 - Model: Harman Gwmv2
 - OS: AOSP on Harman platform Android 8.1
 - CPU: Intel Atom A3940
 - Arch: х86
 - GPU: Mesa DRI Intel HD Graphics 500 (Broxton 2x6)
 - RAM: 4 Gb
 - Memory: 16 Gb

**Media**
Problem appears from streaming sources, which have multichannel audio 

**Additional context**
Other than that it's a great player.

**Comment by moneytoo** [comment]
All the downmixing is handled by ExoPlayer so I'm afraid it's either issue with that or some device specific issue. I'm afraid I can't do much here so the only chance is to provide logs/bugreports and media samples to [ExoPlayer devs](https://github.com/androidx/media/issues).
