### ISSUE TITLE
Player crashes on Hisense 4K ATV4 when launched from API

### ISSUE THREAD

**Issue by brentonv** [moneytoo/Player#494]
This is being reported on behalf of another user who observed that the player fails to launch from API on _Hisense 4K ATV4_.

I have attached a video showing the issue, and a screenshot of the device information. I can't provide media information but the user advised that this occurs on all media, not anything specific.

It seems that the crash is caused by the initial buffering but it's strange that the player fails completely

https://github.com/moneytoo/Player/assets/2313757/e7cbfe0a-a8da-4abf-a5e0-aae7a2c94166

![356844290_10210261141360564_1093736836320099233_n](https://github.com/moneytoo/Player/assets/2313757/d8c5fa78-dd5c-4ede-9e73-6a488d0cf4ad)

![357028757_10210261141720573_5109357866226703509_n](https://github.com/moneytoo/Player/assets/2313757/76697bc1-ae10-4258-9eb2-00fdbe583edb)

![357057334_10210261142120583_5299243909730039672_n](https://github.com/moneytoo/Player/assets/2313757/5f87da00-b336-4b6e-be63-da2c6b4cf58c)

**Comment by moneytoo** [comment]
Maybe it's ok already 🤞, otherwise I don't see much to do without a bugreport.
