### ISSUE TITLE
Dolby TrueHD and Dolby TrueHD Atmos detection and display bug !!!

### ISSUE THREAD

**Issue by Philofil92** [moneytoo/Player#495]
Hello everyone, if at the video metadata level HLG, HDR, HDR10, HDR10, Dolby Vision is perfect apart from the automatic detection of IMAX videos, it seems that there are still some problems with Dolby TrueHD and Dolby TrueHD Atmos tracks, these videos in playback do not detect this format and do not trigger the information and the Dolby TrueHD and Dolby TrueHD Atmos decoder on the TV screen, my TV is DTS compatible, Dolby AC-4, Dolby TrueHD , Dolby Atmos and the display of these tracks are correctly displayed and detected by the TV.   Could you look into this problem?

TV TCL65C825 Android 11
I'll give you an example of a file with encoding information, but all files of this type cause problems!!!

The Super Mario Bros Movie (2023) MULTi VFF 2160p 10bit 4KLight DV HDR BluRay TrueHD Atmos 7.1 x265-QTZ.mkv

AUDIO #1
Format              : Dolby TrueHD with Dolby Atmos
Title                   : FR VFF : TrueHD Atmos 7.1
Language          : French
Channel(s)         : 8 channels
Bitrate               : 2 925 kb/s
Sampling rate    : 48.0 kHz

AUDIO #2
Format              : Dolby TrueHD with Dolby Atmos
Title                   : ENG VO : TrueHD Atmos 7.1
Language          : English
Channel(s)         : 8 channels
Bitrate               : 2 912 kb/s
Sampling rate    : 48.0 kHz

**Comment by DecalicatanDecalicatan** [comment]
I have the same issue with Nvidia Shield Pro (2019) connected to an AVR (Marantz NR1711):
files with audio streams:
-  Dolby TrueHD (with or without Dolby Atmos), 
- E-AC3 (with / without JOC) 
are not recognized directly (bitstream/passthrough) by the AVR, they are played as PCM ("Multi in" is displayed by the AVR).

With kodi internal player, the same files are played as expected (bitstream/passthrough)

**Comment by Philofil92** [comment]
Hello and thank you for your feedback! I finally see that I am not alone...But, obviously, this problem of detecting and sending the right audio track does not interest many people apart from you and me...However, it is not not the "Dolby TrueHD and Dolby TrueHD Atmos" tracks that are missing in UltraHD 4K movie productions today! What to do in the meantime, other than wait for someone to look into the problem!

**Comment by DecalicatanDecalicatan** [comment]
The issue is also with DTS-HD MA 5.1 audio stream.

Also, I have made several tests with "Just Player (Legacy)" older releases
-  v0.144 works fine, as intended 
-  with v0.147, the issue (no bitstream/passthrough) is there

I will use v0.144 of  "Just Player (Legacy)" for now.

**Comment by moneytoo** [comment]
You could try testing it in other ExoPlayer based players like [Next Player](https://github.com/anilbeesetti/nextplayer). If you will still experience your issues, next step would be replicating these in the [ExoPlayer Demo app](https://developer.android.com/guide/topics/media/exoplayer/demo-application) and reporting it [upstream](https://github.com/androidx/media/issues).

**Comment by Philofil92** [comment]
Hello and thank you for your feedback and advice. I tried two movies in "Dolby TrueHD ATMOS" track on both JustPlayer 0.144 and Nexplayer 0.8.1. and I have the same result on these two versions of software.
On the first film, the audio track is detected as "DTS" instead of Dolby Atmos.
On the second film, no sound track detection information.
This is quite strange, because these are "Dolby TrueHD with Dolby Atmos / 8 channels / 2,925 kb/s / 48.0 kHz" tracks.
So, nothing very special.
Given my "large" collection of films, I mainly use Nova Video Player, because there is no better software for "library management" but in terms of sound, it's a hassle depending on the version...
I'm going to look at Exoplayer Demo to explain the problem.
Thank you again for all this information!
Good day to you.

**Comment by DecalicatanDecalicatan** [comment]
Weird.
On my side I have tested with latest Next Player and all is working as intended

**Comment by Philofil92** [comment]
If we tested the same version Next Player 0.8.1, for me, it's not good! Too bad, for the future, I'm going to stop loading "True HD Dolby Atmos" tracks even if, to my ear, there was a plus in audio quality! Finally, DTS and especially Dolby Digital Plus Atmos is already quite good and that works 100%!!! And to my knowledge, no video media software supports this format which is nevertheless a native format on "Bluray UltraHD 4K" films and when we see the time it took for some software to take Dolby Vision into account ...The TrueHD Atmos detection problem is not for today...

**Comment by DecalicatanDecalicatan** [comment]
For information, files with audio streams like
- Dolby TrueHD (with or without Dolby Atmos),
- E-AC3 (with / without JOC)

Are now well bitstreamed to my avr and recognized as such (not PCM anymore) with the latest release v0.154

**Comment by Philofil92** [comment]
Hello, thank you for your feedback and this good news! Unfortunately this problem has persisted since July 2023, I got rid of my trueHD and trueHD Atmos films and for greater safety I now load my films in Dolby Digital and Dolby Digital Plus Atmos format, but I will do a test occasionally. What's more, the 0.154 release makes no mention of trueHD and trueHD Atmos support.
Thank you again and have a great day.
Philip

**Comment by Philofil92** [comment]
Bonjour, me voilà revenu dans ma résidence secondaire...j’ai installé la dernière version juste player 0.160 et le décodage trueHD Dolby Atmos ne fonctionne toujours pas.
 
DTS (toute version) et Dolby Atmos sont parfaitement décodés avec l’affichage à l’écran du logo Dts ou Dolby Atmos sur le téléviseur

**Comment by moneytoo** [comment]
I confirm there is a regression since Just Player v0.155 (AndroidX Media v1.2.1). I didn't notice earlier as my test TrueHD files still work fine and this issue is related to specific ones. I will bisect changes in Media to find the bug.

**Comment by moneytoo** [comment]
Here's a version containing TrueHD fixes: https://brouken.com/player/
It resolves issues with my files. If you still have issues, please share a sample.
