### ISSUE TITLE
Moto Dolby effect not applying in justplayer.

### ISSUE THREAD

**Issue by thanveeralisayed** [moneytoo/Player#501]
Moto Dolby effect is not applying in justplayer meanwhile other players including Nova video player work with it. There is no way to  force it from the Dolby sound manager app. 

 - Model: Poco F5
 - OS: Android 13 Evolution X custom rom.
 - Version 0.149

**Comment by moneytoo** [comment]
Unfortunately I have no clue what something like that wouldn't work and have no way to test it. Just Player doesn't do anything to audio at all as it's handled by the ExoPlayer library (except for some extra configurations like supporting equalizers, audio focus).
