### ISSUE TITLE
[Feature] Deep link Callback

### ISSUE THREAD

**Issue by michalss** [moneytoo/Player#502]
Hi, 
can you please imoplement deep linking callback function ? I would need to know then current position, state when aplication stop, pause, onhold, exit. In this states  to callback url with position please.

Curently using this deeplink url:
`
intent:http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4#Intent;package=com.brouken.player;S.title=New%20title;i.position=15025;end
`

it does work nicely but i would like to see callback url function as well pls.. Something like this 

`
intent:http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4?callback-url=https://server.com/45asdew8erfsd3/15000.22/pause#Intent;package=com.brouken.player;S.title=New%20title;i.position=15025;end
`

Where callback url parsing:
`https://server.com/{guid_or_id}/{current_postion_ms}/{state}`

**Comment by moneytoo** [comment]
I'm afraid this is too obscure feature for this video player. I don't know much about MPV but I read that it supports plugins/scripts so that may maybe work for you.
