### ISSUE TITLE
video stops responding to player after seeking a few times

### ISSUE THREAD

**Issue by Noitarud** [moneytoo/Player#503]
I did try again and it didnt trigger this time. Happens with screen sweep or seek bar.

I obtained this video using Seal:
https://www.youtube.com/playlist?list=PL434B62D7DD754FCA
Has happened with the first, but thats the whole playlist if you need more opportunities to make it happen, this is interesting content (to me), hence issue when I want to find something.

I would give up on it and close the app, and on doing this the sound would momentarily emit, app will continue where I left it after restart. I later noticed the same happens if I press app folder icon, and after escaping that I can continue without restart.

I have not had this happen with any other video as far as I am aware.

Lenovo TB-X505F - Lenovo/TB-X505F/TB-X505F:10/QKQ1.191224.003/X505F_S001142_210804_ROW:user/release-keys
Android 10
App 0114

**Comment by Noitarud** [comment]
My old computer didn't like it:

LAV Splitter Source::Video

Media Type 0:
--------------------------
Video: VP09 654x480 29.97fps 344kbps

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Video {73646976-0000-0010-8000-00AA00389B71}
subtype: Unknown GUID Name {39307076-0000-0010-8000-00AA00389B71}
formattype: FORMAT_VideoInfo {05589F80-C356-11CE-BF01-00AA0055595A}
bFixedSizeSamples: 0
bTemporalCompression: 1
lSampleSize: 1
cbFormat: 88

VIDEOINFOHEADER:
rcSource: (0,0)-(654,480)
rcTarget: (0,0)-(654,480)
dwBitRate: 344645
dwBitErrorRate: 0
AvgTimePerFrame: 333667

BITMAPINFOHEADER:
biSize: 40
biWidth: 654
biHeight: 480
biPlanes: 1
biBitCount: 24
biCompression: vp09
biSizeImage: 942720
biXPelsPerMeter: 0
biYPelsPerMeter: 0
biClrUsed: 0
biClrImportant: 0

pbFormat:
0000: 00 00 00 00 00 00 00 00 8e 02 00 00 e0 01 00 00 ........Ž...à...
0010: 00 00 00 00 00 00 00 00 8e 02 00 00 e0 01 00 00 ........Ž...à...
0020: 45 42 05 00 00 00 00 00 63 17 05 00 00 00 00 00 EB......c.......
0030: 28 00 00 00 8e 02 00 00 e0 01 00 00 01 00 18 00 (...Ž...à.......
0040: 76 70 30 39 80 62 0e 00 00 00 00 00 00 00 00 00 vp09€b..........
0050: 00 00 00 00 00 00 00 00                         ........

**Comment by moneytoo** [comment]
I downloaded that video and played and seeked in it just fine. So I'm afraid it looks like a device or ExoPlayer related issue.
