### ISSUE TITLE
Custom override SSA/ASS styling

### ISSUE THREAD

**Issue by kalekad** [moneytoo/Player#51]
- Hello, thank you very much for a nice project.

In version v0.19, when I set my own font, color, etc. via Settings-> Accessibility-> Captions, it is applied to subtitles.

In version v0.20-wip the set color is not applied (color from subtitles yes, this is a change compared to v0.19).

I think it's due to changes in ExoPlayer 2.13.0 https://github.com/google/ExoPlayer/pull/8490 , https://github.com/google/ExoPlayer/issues/8435

Is it possible to ensure in future versions that user-set values are applied? 

- Dobrý den, moc děkuji za pěkný projekt.

Ve verzi v0.19, když nastavím vlastní font, barvu, atd. přes Settings->Accessibility->Captions dojde k aplikování na titulky.

Ve verzi v0.20-wip se neaplikuje nastavená barva (barva z titulků ano, to je změna oproti v0.19).

Myslím, že je to díky změnám v ExoPlayer 2.13.0 https://github.com/google/ExoPlayer/pull/8490 , https://github.com/google/ExoPlayer/issues/8435

Je možné v budoucích verzích zajistit, že budou uživatelem nastavené hodnoty aplikovány?

**Comment by moneytoo** [comment]
Při čtení [RELEASENOTES](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md):

> Add support for the SSA primaryColour style attribute ([#8435](https://github.com/google/ExoPlayer/issues/8435)).

jsem si říkal, že tam potenciálně nastane situace, kdy budou titulky v jiné barvě než chtěné uživatelem. Doposud byly jen dva stavy (výchozí styl definovaný aplikací a styl z Accessibility -> Captions), ale teď se přidává potenciální třetí (nastavení titulků samotných). 

Chci se na to podívat a rozmyslet, jaké jsou možnosti nastavení uživatelem a jak se to má v různých případech chovat.

**Comment by moneytoo** [comment]
Mělo by to být pořešeno (a dostupné v posledním pre-release buildu). Při zaplém Captions v systému se aplikují čistě tyto styly. Pokud je vyplý, aplikuje se barva titulků na styl používaný aplikací. Protože přímo pracovat (detekovat) se stylem z titulků nejde, tak mi toto vychází jako nejlepší jednoduché a univerzální řešení.

**Comment by kalekad** [comment]
Vyzkoušeno a chová se to jak píšete, děkuji.
