### ISSUE TITLE
Regarding Decoder HW, HW+ and SW

### ISSUE THREAD

**Issue by kisandas** [moneytoo/Player#511]
I have tried to download video and video has been downloaded now I want to play Video, When I play with JUST Player Video is Playing and Frames shown but Audio is not audible. 

Same thing Happen In MX Player but When I switch decode from HW to SW or HW+ Audio is playing fine with Video
In VLC by Default Its Playing Fine 

So I want to set HW+ Decoder or SW Decoder By default in JUST Player. So How Can I set Decoder into JUST Player.

**Comment by moneytoo** [comment]
Share media sample or Media info output to understand what the audio format is. Also, what is your device model?
