### ISSUE TITLE
Cache and ftp

### ISSUE THREAD

**Issue by hapishyguy** [moneytoo/Player#513]
Hi,

If we use an external link to play the video will it be saved in cache? Reason is that sometimes we are are travelling and pass through a not good network area. So if we can cache it would be good. 
Also, can we add somehow to look for a specific folder and then play from it eg. if I put all my videos in an ftp folder then can it itself pick from there and play? It would be a great feature. 

Thanks
harp

**Comment by moneytoo** [comment]
Sounds more like a job for the intermediary (provider of access to that service). Maybe something like [rcx](https://github.com/x0b/rcx)?

**Comment by hapishyguy** [comment]
I will check what is rcx.
Well, need to have something built in the app so its less chances of something breaking up
