### ISSUE TITLE
How to get bold subtitles in version 0.152?

### ISSUE THREAD

**Issue by stekzero** [moneytoo/Player#516]
After update 0.152, is there a way to get bold subtitles? I'm more used to using the bold ones. In the caption preferences there is no option to change the subtitle style to bold.

![Screenshot_2023-10-03-18-17-35-278_com.android.settings.jpg](https://github.com/moneytoo/Player/assets/108440782/8c4e750f-2222-483f-9e5b-0404edc15115)

**Comment by moneytoo** [comment]
Long press the ⚙️ gear icon in Just Player, there's a new option for enabling bold style.

**Comment by stekzero** [comment]
> Long press the ⚙️ gear icon in Just Player, there's a new option for enabling bold style.

Ok, thanks
