### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ibyb007** [moneytoo/Player#519]
**Describe the bug**

**To Reproduce**
1. Open '...'
2. Select '....'
3. See error

**Expected behavior**
Add colour adjustment settings like vlc windows . This will improve muted colours in hdr content/stream.

**Device (please complete the following information):**
 - Model: [Xiaomi tv 4x]
 - OS: [ Android 9]
 - Version [0.151]

**Media**
If applicable, add a short media sample which triggers the problem.

**Additional context**

**Comment by moneytoo** [comment]
Could you be more specific? I believe that right now the colors should be as accurate as possible. Do you want to play HDR on SDR displays? I'm not aware of any tonemapping options.

**Comment by ibyb007** [comment]
I want you brings this setting in your app.. This improve HDR contents colour immensely in budget HDR TV's.
![Screenshot (43)~2](https://github.com/moneytoo/Player/assets/58368196/5b327748-8508-41d5-834e-494af5a4c9a0)

**Comment by VasilisKos** [comment]
> I want you brings this setting in your app.. This improve HDR contents colour immensely in budget HDR TVs. ![Screenshot (43)~2](https://user-images.githubusercontent.com/58368196/275247132-5b327748-8508-41d5-834e-494af5a4c9a0.png)

Definitely disagree. Just Player should be kept simple as it is. That's the concept of it. If you want something more like VLC or MX Player, you're free to install them.
