### ISSUE TITLE
Pozice titulků SSA/ASS

### ISSUE THREAD

**Issue by kalekad** [moneytoo/Player#52]
Všiml jsem si, že při titulcích, které mají být na různých pozicích v obraze ve stejný čas,  dochází k zobrazení v jedné pozici přes sebe.

**Comment by moneytoo** [comment]
Podpora SSA/ASS v ExoPlayeru je bohužel velice omezená a (zatím) nezvládá pozicování, viz [komentář v issue](https://github.com/google/ExoPlayer/issues/6320#issuecomment-524299571):

> We don't parse the position tag of the subtitles to place it at the right position.

**Comment by Pentaphon** [comment]
@moneytoo Looks like Exoplayer is moving towards adding full support with 2.13.2

>Parse SSA/ASS font size in Style: lines 

https://github.com/google/ExoPlayer/releases/tag/r2.13.2

https://github.com/google/ExoPlayer/issues/8435
