### ISSUE TITLE
Playback

### ISSUE THREAD

**Issue by Lucky390163** [moneytoo/Player#520]
It can't play 1080p videos 265 Hevc videos.

Please add compatibility to play it.

**Comment by moneytoo** [comment]
HEVC should generally everywhere. If you have issues, please attach sample of such media to replicate the issue.

**Comment by Lucky390163** [comment]
Media is much bigger around 200mb. So i can't upload if you have a telegram i can do it.

**Comment by Lucky390163** [comment]
Please close the topic.I will send you later.
