### ISSUE TITLE
Fire stick 4k customised subtitles

### ISSUE THREAD

**Issue by Blueybarnes** [moneytoo/Player#521]
Hi. There is no way to customise subtitles on Fire Stick 4K. When long pressing the gear icon then scrolling to caption preferences, the screen goes to blank video playing screen. Any workaround for this or just a shortcoming of Fire OS?

**Comment by moneytoo** [comment]
According to this video it looks like there's setting for customizing subtitles: https://www.youtube.com/watch?v=V1KorM8A9kw

**Comment by Blueybarnes** [comment]
Thanks pal. I thought you had to customise within the player settings. Didn't realise you could customise with the fire stick settings and it would work within app. Do you know how to make the player stop playing when you exit a stream? For me the audio can be heard for about 5-10 seconds after stopping. Thanks.
