### ISSUE TITLE
4k video playing 

### ISSUE THREAD

**Issue by Ridayjrz800** [moneytoo/Player#522]
**Describe the bug**

**To Reproduce**
1. Open '...'
2. Select '....'
3. See error

**Expected behavior**

**Device (please complete the following information):**
 - Model: [e.g. Samsung Galaxy S22]
 - OS: [e.g. Android 13]
 - Version [e.g. 0.134]

**Media**
If applicable, add a short media sample which triggers the problem.

**Additional context**

**Comment by moneytoo** [comment]
4k should play if the hardware and system decoders are capable decoding 4k in specific format. Please be more descriptive.
