### ISSUE TITLE
REMUX MKV RIP Playback - DoVi Profile 7 Issues - Multiple Devices / Android Versions

### ISSUE THREAD

**Issue by dmosimmonsYTZ82** [moneytoo/Player#524]
**Describe the bug**
I have multiple Android TV boxes and/or Smart TVs in our home. I am using Just Player 1.51 as the primary player across all my devices. DoVi Profile 7 failback only works on my devices that support the full range of DoVi encoded profiles. 

With my Sony Bravia Android TV we can natively play DoVi Profile 7 videos. On some rips the videos default to HDR anyways without an error and there is no way, that I am aware of, to run a debug to find out why this is happening. This issue exists regardless of the switch turned in the advanced settings is toggled to play it unchanged or play it in HDR mode. Using the prefer decoder settings toggles doesn't impact the failover functionality. Tunneling also does not impact or change this functionality. No combination of Tunneling on/off, combined with decoder preferences, or DoVi failback. I went through a rigorous testing process to verify each combination. 

With my RockTek G2 Android TV I cannot run DoVi Profile 7 videos in Just Player. I get the error code saying that the video file exceeds the limit of the supported format. This issue exists regardless of the switch turned in the advanced settings is toggled to play it unchanged or play it in HDR mode. Using the prefer decoder settings toggles doesn't impact the failover functionality. Tunneling also does not impact or change this functionality. No combination of Tunneling on/off, combined with decoder preferences, or DoVi failback. I went through a rigorous testing process to verify each combination. Oddly enough on this device DoVi failback and/or DoVi pass through of Profile 7 work in Nova Player on this same machine. I have Nova Player setup to use the Android Media Library, basically the same as Just. Just Player can play and passthrough other DoVi profiles to the my Sony Bravia, and I can verify this by checking the HDR/Picture settings the picture works fantastic. Dolby Vision Bright and Dolby Vision Dark display perfectly. With this box there is also no issue playing any Dolby Audio formats. The DolbyVision rips that work are MKV UHD 2160P x/h264 or HEVC. Web-DL, WEB, and x/h264 HEVC DoVi haven't been an issue. 

**Expected behavior**
DoVi Profile 7 movies failback to HDR 10 when opening Hybrid REMUXs that include DoVi Profile 7 and HDR10 / 10+.
(Nova Player's implementation works better) 

**Device (please complete the following information):**
Sony Bravia Android TV
 - Model: Sony X950H (XBR-65950H) 
 - Processor: MediaTek Mt8993
 - OS: Android 9
 - Version: Bravia_UR3_UC-user 9 PTT1.190515.001.S104 650661

RokTek G2
- Model: RT-G2 / SEI804RT (YYJ)
- Processor: Amlogic S905X4
- Android 11
- Version: RTT0.211009.001.53100

*** WILLING TO PAY TO GET THIS BUG RESOLVED ***
$150-200 CAD

**Comment by moneytoo** [comment]
I'm afraid I won't be able to help here. As fallback of hybrid DV/HDR10(+) files work fine on my devices and it's fully in control of ExoPlayer.
