### ISSUE TITLE
Update f-droid version 

### ISSUE THREAD

**Issue by Stu75e** [moneytoo/Player#525]

**Comment by luke-2136** [comment]
Came here for same issue (11-22-23) - the F-Droid build is quite a few versions behind github..

so I'm wondering does this mean the F-Droid version is no longer being maintained?

- if so need to switch to github i reckon

anyway thanks

**Comment by moneytoo** [comment]
Not much really changed since the last F-Droid version. The only notable change is the bump to Media 1.2.0. I will update the F-Droid version in about 2 to 4 weeks (based on data from Google Play).

**Comment by luke-2136** [comment]
..thanks for the response/info

and player works great btw.. thanks for that
