### ISSUE TITLE
Translation strings are not updated on Weblate

### ISSUE THREAD

**Issue by VasilisKos** [moneytoo/Player#530]
Some new ones, about the subtitle settings, are not added.

**Comment by VasilisKos** [comment]
I didn't mean that the Greek translation wasn't updated. Some NEW strings are not included in Weblate, thus CANNOT be translated.
These are:
1. Subtitle
2. Embedded styles
3. Bold style
Please keep Weblate updated with every new strings added. It doesn't have so many.

**Comment by ShareASmile** [comment]
@moneytoo , I have fully updated Punjabi, Hindi Indian language strings on weblate, please pull from weblate.
