### ISSUE TITLE
Feature Request: Simplified APK Generation and Local Installation for 'Player'  

### ISSUE THREAD

**Issue by 9cat** [moneytoo/Player#532]
I'm a dedicated user of the 'Player' GitHub project and would like to suggest a feature that could significantly improve its usability. Currently, the APK generation process involves several manual steps. I believe that a one-click Docker-based APK builder could streamline this process, making it more user-friendly and accessible.

Key Feature Request:

Docker-Based APK Builder:
Create a one-click solution to generate the APK directly from the project's GitHub repository.
Enable local installation without reliance on the Android Market (Google Play Store).
I believe that this feature would greatly benefit the project and its users. Please let me know if you have any questions or need further details.

Thank you for your consideration.

**Comment by moneytoo** [comment]
What's the problem with the standard Android build system? Any other app uses the same system. Developers already have IDEs and it only takes a few clicks or a command to generate a release. Who would actually need a container for building? End users can just use F-Droid as some kind of trust of matching source to binary.

>Enable local installation without reliance on the Android Market (Google Play Store).

Right now you have apks and adb to install them localy or some other source. What else is missing?
