### ISSUE TITLE
Android TV subtitle size setting is ignored, subtitles are always too small. Some setting to override that would be great. 

### ISSUE THREAD

**Issue by Zizou3000** [moneytoo/Player#536]
**Describe the bug**

Android TV's subtitle size setting is ignored and subtitles arent the same size as it is shown in the settings. They are way smaller. 
**To Reproduce**
1. Open '...'
2. Select '....'
3. See error

**Expected behavior**

A setting that overrides android's setting would be great, like in some other apps.  Just Player shoulg have precise and granular subtitle size setting. 

**Device (please complete the following information):**
 - Model: [e.g. Samsung Galaxy S22]
 - OS: [e.g. Android 13]
 - Version [e.g. 0.134]

**Media**
If applicable, add a short media sample which triggers the problem.

**Additional context**

**Comment by moneytoo** [comment]
Changing subtitle size works for me so I guess this could be related to your media and sample file would be handy than.
