### ISSUE TITLE
Add player to an existing project

### ISSUE THREAD

**Issue by AbreuY** [moneytoo/Player#54]
Is there a problem if I want to add the player to an existing project?

**Comment by moneytoo** [comment]
You can do anything you want, as [the Unlicense](https://github.com/moneytoo/Player/blob/master/LICENSE) allows basically any usage. However the code is messy and any heavy lifting is done by ExoPlayer which you usually need to learn on how to work with anyway. So I would suggest starting with clean ExoPlayer and probably reusing parts from NewPipe and/or [other players](https://github.com/moneytoo/Player#other-open-source-android-video-players).
