### ISSUE TITLE
Please support ffmpeg av3a

### ISSUE THREAD

**Issue by FongMi** [moneytoo/Player#540]
Please support audio/av3a format for ffmpeg(avs3)
![image](https://github.com/moneytoo/Player/assets/3471963/4dc3965f-b55e-4bab-b569-579b6f8e1a13)

**Comment by johin528** [comment]
@moneytoo please support it as soon as possible,it's important to us

**Comment by moneytoo** [comment]
Just Player enables all decoders supported by [ExoPlayer using FFmpeg](https://developer.android.com/guide/topics/media/exoplayer/supported-formats#ffmpeg-library). To add support for this decoder, it would be best to include it in the upsteream ExoPlayer.
