### ISSUE TITLE
Low quality content smoothing not working

### ISSUE THREAD

**Issue by candybit** [moneytoo/Player#542]
**Describe the bug**
When using Just Player to play 480p content, the LG C3 low resolution content smoothing is not working, resulting in a picture with a lot of noise

**To Reproduce**
With a recent TV supporting low quality content smoothing (tested on LG C3):

- Open a 480p content in Just Player (firestick tv 4k max): content is *not smoothed*
- Open a 480p content in the Jellyfin (firestick tv 4k max) or via a USB drive connected to the TV: content is correctly smoothed

**Expected behavior**
Content smoothing should work properly, as it happens with the Jellyfin app

**Device (please complete the following information):**
 - Model: Fire Tv Stick 4k Max 1st gen 2021, LG C3
 - OS: Fire Os 7.6.6.4 (Android 9)
 - Version: 0.143

**Additional context**
In my understanding, the issue is that the stream information is not passed correctly to the TV, which thinks that a native 4k stream is being played instead of 480p. Enabling "Tunneled playback" or "Auto frame rate matching" does not fix this.

**Comment by moneytoo** [comment]
I'm afraid that I can't replicate such issue nor that I have a slight idea of what is going on. The Fire TV devices are often problematic though.
