### ISSUE TITLE
Amazon Fire TV Stick 2nd generation no more AC3 5.1

### ISSUE THREAD

**Issue by NguoiPhap** [moneytoo/Player#545]
Amazon fire TV stick 4K 2nd generation don't passthroughs AC3 5.1 anymore, DTS 5.1 passthrough perfectly.
Can you please passthrough AC3 5.1
Best regards.

**Comment by moneytoo** [comment]
Just Player doesn't really do anything with passthrough as it's fully in control of ExoPlayer - and there are often issues with Fire TV devices.
