### ISSUE TITLE
MediaCodecAudioRenderer error when playing videos with DD+ on Pixel 7

### ISSUE THREAD

**Issue by jddecker** [moneytoo/Player#547]
**Describe the bug**
When opening a video file that as a Dolby Digital Plus audio track, the video doesn't play and displays the error:

`MediaCodecAudioRenderer error, index=2, format=Format(2, null, null, audio/eac3, null, -1, en, [-1, -1, -1.0, null], [6, 48000]), format_supported=YES`

There is a details button after the error that displays:

`Decoder failed: c2.dolby.eac3.decoder`

**To Reproduce**
1. Open video file that has a Dolby Digital Plus audio track ([for example one of the videos with a Dolby Digital Plus audio track on the Dolby page](https://ott.dolby.com/OnDelKits/DDP/Dolby_Digital_Plus_Online_Delivery_Kit_v1.4.1/Test_Signals/muxed_streams/MP4/MP4_Muxed_Streams.html))
2. Video doesn't play and error on screen displays: `MediaCodecAudioRenderer error, index=2, format=Format(2, null, null, audio/eac3, null, -1, en, [-1, -1, -1.0, null], [6, 48000]), format_supported=YES`

**Expected behavior**
Video should play with audio

**Device (please complete the following information):**
 - Model: Google Pixel 7
 - OS: Android 14
 - Version: 0.154

**Media**
Any media that has an audio format listed by MediaInfo as `E-AC-3 JOC`

**Additional context**
I found a workaround where the video will play by toggling the decoder priority in the video settings. Steps for the workaround:
1. Open video with Dolby Digital Plus audio track
2. Audio decoding error on screen
3. Go to settings by long pressing the cog button
4. Change `Decoder priority` from `Prefer device decoders (default)` to `Prefer app decoders`
5. Exit settings
6. Try to play video again and get the same audio decoding error
7. Go back to settings by long pressing the cog button
8. Change `Decoder priority` back to `Prefer device decoders (default)`
9. Exit settings
10. Play video again and video will play with audio and video

I've attached a screen recoding of the workaround (I removed the audio in the recording, but the audio does play)

https://github.com/moneytoo/Player/assets/6766805/d34c978d-5e12-488b-94a1-92a08f831de0

**Comment by seankim2398** [comment]
This issue doesn't occur on my Samsung Tab S8+, but does on my Pixel 8 Pro. The workaround works thanks, hopefully there is fix for this in the near future.

**Comment by ProTechnomancy** [comment]
Same issue on pixel 6 (GrapheneOS) - workaround works! Thx

**Comment by moneytoo** [comment]
Trying `ChID_voices_1280x720p_25fps_h264_6ch_256kbps_ddp.mp4`, it plays fine on my Samsung phone. Can't do much then so I suggest  replicating this issue with ExoPlayer demo and reporting upstream.
