### ISSUE TITLE
Scripting/shaders support — adding new features while keeping the base app simple, and getting the community involved

### ISSUE THREAD

**Issue by jan-kleks** [moneytoo/Player#548]
Take a look at the mpv-android app, its GUI is as simple as in Just Player, but you are able to extend mpv-android’s feature-set with scripts and shaders.

I am writing about this because it would have also been great to have an ExoPlayer-based app with scripting support (for instance, with Lua and Python).

This could get more people into Just Player development, and allow for adding useful features without making the app feel generally bloated. Such as automatic subtitles downloading, custom sharpening algorithms, [inventive stretching options](https://github.com/androidx/media/issues/857), and so on.

Every user would simply choose what they need for their particular use case.

**Comment by moneytoo** [comment]
> adding new features while keeping the base app simple, and getting the community involved

Honestly, I don't think that this would work. 😉 

> I am writing about this because it would have also been great to have an ExoPlayer-based app with scripting support (for instance, with Lua and Python).

I agree that this would be great. However it's not really suited for Just Player in its poor state. Maybe use gathered knowledge in a new project.

> automatic subtitles downloading

My opinion is that such feature could exist outside of a video player.
