### ISSUE TITLE
[Feature Request] Allow playback or local audio files that ExoPlayer supports

### ISSUE THREAD

**Issue by Logicdemon** [moneytoo/Player#55]
Hi, what is the reasoning for not allowing local playback of audio files which Exoplayer already supports? I've been trying to ditch VLC with something more lightweight and quite like this, however it doesn't allow listening to music which is a shame.

Thank you

**Comment by moneytoo** [comment]
While audio playback is technically possible, it would require significant additions for it to be minimally usable (background playback with a service and notification, ui to view all the metadata, navigation for files in the playback queue, better files/folder selection, etc.).

There are already some great open source audio players and I don't thing that this player would be able to compete with them. (Also today, storage space or RAM shouldn't be a problem, right?)

Even after that I thought and tried adding some limited audio support. However it still led to adding complexity to the video player that I wanted to keep simple. With just video playback, it's ideally something that I should be able to maintain in the long run.

**Comment by Logicdemon** [comment]
Thanks for the reply.

I was just looking for something to 'play' audio, don't need playlists or to navigate within the app. I avoid players that try and act as any kind of media library or try to do too much with the UI. I navigate my files with a proper file manager, when I click a file my file manager knows what app to call too an open the file.

>>There are already some great open source audio players...
I use F-droid as I'm trying to keep as much as I can opensource, I've looked but found there is 'very little' choice of basic light weight audio players. I tried Bop-musicPlayer, it just crashes when I try navigating to my SDcard, and when navigating to the internal memory card will not recognise .ogg or opus files. Currently using VLC for audio but its very slow and tries to scan whole directories where I might have 2000+ audio files in when all I want it to do is just play a file, its very clunky.

>>Also today, storage space or RAM shouldn't be a problem, right?
Storage / RAM will always a problem :) When choosing an app to use, if I find two apps that are close enough in functionality I'll always ditch the bigger. I use storage for my movies, music, images etc, these will always grow. Some phones don't have the option of SD cards, even when they do there very easy to fill, plus the phones OS and all other apps on a phone with constant updates make them grow over time.

I like my programs minimal, they load faster, use less power, update quicker on a contested connection. Less code generally means less vectors of attack for security and shows an artistry of programming like you find in the demoscene, this in turn gives me a lot more confidence in the creator of the app when using their software.

Anyway, I appreciate your work on the app and like using it.

**Comment by moneytoo** [comment]
My first obstacle to audio support was that I like that currently the file chooser is configured to list video files only. Adding audio files to the filter would only extend (more complex) the selection. If audio files would be selected from external file manager, than it would be fine.

I like that I can launch the player and continue watching the last selected video. Should the last opened audio file be also remembered...?

Anyway, I guess one would probably expect the audio to play even with the screen turned off so there would still need to be some extra logic for handling this (foreground service therefore creating notification which would like to have some actual metadata...).

Just trying to evaluate what the minimal usable support should look like.

**Comment by Logicdemon** [comment]
>> If audio files would be selected from external file manager, than it would be fine.

I think its the cleanest way to do it. Let the file managers deal witht the complexity of listing files.


>> Should the last opened audio file be also remembered...?

Yeah I would just keep the same action. Handy if a single MP3 happened to be +10hr long audio book, useful to just start off where you had gotten to in the story. Newpipe acts similar to this.

**Comment by ocaeon** [comment]
oh thanks, moneytoo!  sorry i failed to find this, i checked closed issues to see you had not said no. 

 i believe i do have very similar needs to logicdemon.  my use case is: sorting many small voice and sound effect recordings of various formats without any metadata.  i use smt simple file manager and most files i just listen a moment and delete, or rename and move, so indexing and metadata would be meaningless and wasteful. 

 where you mention screen off: i would not treat any different from videos, i prefer to keep screen awake if the file is open so long anyway, as i need to stop or jump back or ahead at any moment. 

 at the moment i can already open these files in justplayer if i use 'open as' in simple file manager, this just doesn't work by tapping the files ("no app available") and not showing in share list from editers or browsers.  finding and opening a sound often take longer than the sound plays!  before justplayer i used my desktop pc to do these things, which was noisy and wasteful. 

 you said "are already some great open source audio players", i will try any on fdroid but i do not use g**g and have recently had problems with my amazon account.  if you have other recommendations though i'd be interested.  thanks again, and i still continue to use and recommend your app without this!

**Comment by moneytoo** [comment]
> you said "are already some great open source audio players", i will try any on fdroid but i do not use g**g and have recently had problems with my amazon account. if you have other recommendations though i'd be interested. thanks again, and i still continue to use and recommend your app without this!

https://f-droid.org/en/packages/com.poupa.vinylmusicplayer/
https://f-droid.org/en/packages/com.simplemobiletools.musicplayer/
https://f-droid.org/en/packages/com.maxfour.music/
https://f-droid.org/en/packages/com.iven.musicplayergo/
https://f-droid.org/en/packages/org.gateshipone.odyssey/
https://f-droid.org/en/packages/fr.nihilus.music/
https://f-droid.org/en/packages/ch.blinkenlights.android.vanilla/
https://f-droid.org/en/packages/com.hardcodecoder.pulsemusic/
https://f-droid.org/en/packages/com.simplecity.amp_pro/
https://f-droid.org/en/packages/com.sahdeepsingh.Bop/
...

The sheer volume of pretty good designed and actively developed audio players...

Anyway, if all you need is just to open audio files, try the builds with `-audio` suffix available here: https://brouken.com/player/

**Comment by barolo** [comment]
There's also mpv, [not on f-droid yet I think?],  https://github.com/mpv-android/mpv-android/releases ,
if that's not minimal enough for ya just use ffplay from ffmpeg, from terminal...

**Comment by wiryls** [comment]
I found a quite minimalistic audio player on f-droid, [Dialog Music Player](https://f-droid.org/en/packages/phone.vishnu.dialogmusicplayer/), and it just looks like an embedded player that comes with the file manager.

**Comment by Vasehar** [comment]
Can you make the app to allow Dolby digital Plus to Dolby digital which usually done in Kodi app,which will be very useful cause lot of av receivers do not support Dolby Digital Plus
