### ISSUE TITLE
Feature Request:  Move the controls to the side and do not shade when paused.  Sometimes we are trying to study a frame.

### ISSUE THREAD

**Issue by buffalopilot** [moneytoo/Player#550]
Feature Request:  Move the controls to the side, and make smaller, and do not shade the video when paused.  Sometimes we are trying to study a frame.

**Comment by moneytoo** [comment]
Such changes are not planned. As a slight workaround, you may use pinch-to-zoom (out) to temporarily hide the UI when paused.
