### ISSUE TITLE
Decoder issues

### ISSUE THREAD

**Issue by Lucky390163** [moneytoo/Player#552]
Device - SM-M127G
Download link - https://driveseed.org/file/cH8FkqwKwdJhp9NxxIJ1

You can download it from here from that im getting issues
Just click instant download

This video is currently unsupported please take a look by downloading . Thanks.

**Comment by moneytoo** [comment]
The video is HDR HEVC so it's the same issue as in [#491](https://github.com/moneytoo/Player/issues/491#issuecomment-1631309042). You might have better luck trying [Next Player](https://github.com/anilbeesetti/nextplayer) which includes extra decoders for AVC and HEVC.

**Comment by Lucky390163** [comment]
But you have add a support for this videos mostly all foss app plays this like vlc.

**Comment by Lucky390163** [comment]
Bro did you understand please respond.Because Samsung inbuilt player is same as good.

**Comment by moneytoo** [comment]
> But you can add a support for this videos mostly all foss app plays this like vlc.

Just Player uses ExoPlayer which relies basically only on device video decoders. Nothing more is planned beyond that.
