### ISSUE TITLE
"Skip to next" not showing up

### ISSUE THREAD

**Issue by Fmoment1** [moneytoo/Player#556]
**Describe the bug**

The feature list mentions "Post-playback actions (delete file/skip to next)" - the ability to skip to the next video in a folder, but I'm not seeing anything like that. There is no "next" button, nor does the next video automatically start playing after the current video has reached its end. Only the delete button shows up beside the play/pause button near the end.

**To Reproduce**

1. Open a folder with videos in it
2. Select a video 
3. Watch till the end
4. Get no option to play next video

**Expected behavior**

I should be able to play the next video without going out of the player, or the next video should start playing automatically if it's inside the same folder as the other video.

**Device:**
 - Model: Motorola One Fusion+
 - OS: Android 11
 - Version: 0.155

**Other details:**

I installed this from the Play Store.

**Comment by moneytoo** [comment]
Works for me.
