### ISSUE TITLE
Volume controls don't work

### ISSUE THREAD

**Issue by ProficientTroll** [moneytoo/Player#559]
**Describe the bug**
Volume up and don't change the volume, only works when I switch to a different app (such as Poweramp Music volume) , play and pause the music and then come back to player , the volume control works as expected 

**To Reproduce**
1. Open Just Player
2. Play video , it'll play at default volume , and volume controls don't work
3. Now switch to music player such as Poweramp 
4. Play and Pause the music
5. Switch back to Just Player
6. Resume video
7. Gestures now work

**Expected behavior**
The volume should change when using gesture or volume buttons initially 

**Device (please complete the following information):**
 - Model: OnePlus 7T 
 - OS: Android 14 (Custom ROM : Derpfest 14)
 - Version : 0.155
 
[file_688374741514390880.zip](https://github.com/moneytoo/Player/files/14232946/file_688374741514390880.zip)

**Comment by moneytoo** [comment]
Volume controls do work on stock roms so I'm afraid this issue is related to your custom rom (similar to #444).
