### ISSUE TITLE
Video loop

### ISSUE THREAD

**Issue by Kali273** [moneytoo/Player#56]
cau, libi se mi player ale chybi mi tam to co u vetsiny android video playeru a to opakovani videa. Ma to snad jen vlc prehravac, ale ten nechci pouzivat. Je moznost to nejak zprovoznit?

**Comment by moneytoo** [comment]
V rámci jednoduchosti tuto volbu přehrávač zatím nenabízí. Mohu se zeptat na případ použití? (Hudební video?)

**Comment by Kali273** [comment]
Aha ok.. Pripad pouziti mam velmi specificky :), rad si testuju jak vypadaji barvy na standardnim nezkalibrovanem pristroji. Videa 2-10 sec z after effects. Pisu jen pro zajimovast, chapu ze takova vec pro tebe rozhodne neni duvod aby si to tam pridal :).. Treba casem..

**Comment by moneytoo** [comment]
Díky za vysvětlení. Zatím je to spíše okrajovější záležitost, spíše až pokud přehrávač bude nějak elegantně pracovat s frontou videí... Ale na druhou stranu tuto funkcionalitu ExoPlayer již nabízí a tlačítko pouze neaktivuji. Na to by pak stačilo nějaké schovanější nastavení na povolení pokročilejšího módu, který by toto genericky aktivoval.

**Comment by moneytoo** [comment]
Duplicate of #193
