### ISSUE TITLE
[Bug] External Subtitles

### ISSUE THREAD

**Issue by githottub** [moneytoo/Player#563]
Per description for Version 0.155 "To load external (non-embedded) subtitles, long press the file open action in the bottom bar. The first time you do that, you will be offered to select root video folder to enable automatic loading of external subtitles."

Unless I'm misunderstanding, this implies that after the first time, it will automatically load external subtitles. However, that is not what I have experienced. After selecting the external subtitle for a video it does make it available the same as internal ones. But, if you exit the player then return and resume the video, the external subtitle previously selected is no longer shown/available. User must go through the manual selection process again. (This issue is always reproduceable for me.) My suggestion would be to code the app like other player apps which, when loading a video file automatically check for a subtitle file with the same name in the same folder. That way the subtitles would truly be automatically available without any additional manual interaction from the user. 

App Version: 0.155
OS: Android 12
Device: 2023 model TV running Google TV

**Comment by moneytoo** [comment]
Works for me. If you still have the issue, share steps to replicate it.
This player is build primarily for phones where it uses system file chooser and doesn't have access to other files than the selected single video file.
