### ISSUE TITLE
[Feature Request[ Folder File List Improvement

### ISSUE THREAD

**Issue by githottub** [moneytoo/Player#564]
If there is a long list of video files in the folder, it is needlessly tedious and time consuming if you reach the last file and want to go back to the first. As currently implemented, you must reverse direction and go back up through all the files but, if you could keep going down after the last file and have it loop back to the first (and vice-versa) it would be much more useful.

Thank you for your continued improvement of this great video player and for taking time to consider this suggestion. It is truly appreciated. 

P.S. The way you handle long file names (like a ticker tape) so they can be seen if too wide for the window is a good idea. However, it would be helpful to also make the window wider. It currently only uses approximately fifty percent of the screen width. I think expanding it to 80 or 90 percent would allow almost all file names to be seen in full immediately.

**Comment by HaithamDesouky** [comment]
Also to add to this - actual folder exploration would be nice. 

At the moment all my tv shows are under the name 'season 1', it's impossible to know which one is which.

**Comment by githottub** [comment]
> Also to add to this - actual folder exploration would be nice.
> 
> At the moment all my tv shows are under the name 'season 1', it's impossible to know which one is which.

You can just make subfolders for each show. On mine, it can see and then go into a subfolder within the main folder and play videos from within it. Alternatively, if you prefer more of a media explorer type interface, some other apps (such as Kodi) have have a UI focused on that but can designate another video player app (such as this one) to perform the actual playback of the file.

**Comment by moneytoo** [comment]
See #13 for more info.

This player doesn't have any library functionality and the file picker (at least on phones) is a system interface that has its limits. If you are looking into more pronounced library features, try other players like Nova Video Player or Next Player.
