### ISSUE TITLE
[Bug] MediaInfo

### ISSUE THREAD

**Issue by githottub** [moneytoo/Player#565]
Per description: "Install app like [MediaInfo](https://play.google.com/store/apps/details?id=net.mediaarea.mediainfo) (or APK from [MediaArea.net]. Then, to quickly open MediaInfo from Just Player, long press the video name/title."

I installed MediaInfo but long pressing on the video name/title from the folder list (I don't see anywhere else to long press the name/title) doesn't do anything. Tried rebooting TV but still not working. 

App Version: 0.155
OS: Android 12
Device: 2023 model TV running Google TV

**Comment by moneytoo** [comment]
This is not supported on TVs.
