### ISSUE TITLE
External PGS subtitles won't load

### ISSUE THREAD

**Issue by ktheticdev** [moneytoo/Player#569]
**Describe the bug**
Opening external PGS subtitles in .sup format does nothing.

**To Reproduce**
1. Grab some PGS subs
2. Try opening them

**Expected behavior**
Subtitles should display

**Device (please complete the following information):**
 - Model: Sony Xperia 1 V
 - OS: Android 14
 - Version 0.155

**Comment by moneytoo** [comment]
I don't think that's possible with ExoPlayer. In addition to that PGS support is not really full.
