### ISSUE TITLE
framerate switching creates judder

### ISSUE THREAD

**Issue by chromosomez** [moneytoo/Player#574]
Hello

**Describe the bug**
When activating the auto frame rate matching on Chromecast 4k with Google TV, strong judder happens when playing any mkv UHD Dolby Vision movies (which is the reason I use Just Player). Whereas this issue is only slighly present with the option off and refresh rate at 60Hz. Netflix doesn't have this problem, no judder at all after switching framerate, which leads me to believe it may have a better implementation.
EDIT 05/14/2024: as of now the best result is achieved when activating tunneled video playback in the advanced options.

**To Reproduce**
1. Set frame rate matching on "non smeamless" in the chromecast 4k options while having a general refresh rate of 60Hz.
2. Open any uhd dolby vision mkv movie with Just Player from NOVA Video Player interface.
3. Open advanced options long pressing the cog
4. Turn on Auto frame rate matching
5. Return to playing the movie, the frame rate of my "laser TV" (Hisense PL1) adjusts accordingly.
6. Judder is immediately there

**Expected behavior**
No judder at all as in Netflix app

**Device:**
 - Model: Chromecast 4k with Google TV plugged in Hisense PL1 laser TV
 - OS: Android TV 12
 - Chromecast 4k firmware : 1.68.374976, software up to date

Thank you for your time and effort

**Comment by moneytoo** [comment]
Yeah, the framerate matching switches display mode so it's slow and creates a judder. However it shouldn't be neede on newer devices / OS as ExoPlayer [already supports](https://github.com/androidx/media/issues/1318) all the fancy features:

> ExoPlayer does support seamless frame rate switching by default.

When playing videos on my phone, display refresh rate matches the video framerate. So I don't really know what else to do.
