### ISSUE TITLE
Real Improvement.txt (Streamable link)

### ISSUE THREAD

**Issue by MinorX** [moneytoo/Player#580]
Despite being an amazing player , Just Player some how misses the most basic , level 1 of any media player - "THE PASTE YOUR STREAM LINK HERE" button here. 
Android TV lacks the capability to share media links as much easy it is for Android phones. 
You know what I had to do to play a media file with a stream link ? Create a .html file on my phone , share with my TV , use Html viewer , and then it would show Just Player.
I mean , why ? What is the purpose of this?

```<!DOCTYPE html>
<html>
<head>
    <title>Media Player Link</title>
</head>
<body>
    <h1>Click the link below to play the media file:</h1>
    <a href="STREAMABLE LINK HERE">Play Media</a>
</body>
</html>```

**Comment by Pentaphon** [comment]
You may have to use https://github.com/anilbeesetti/nextplayer for this but I agree there should be an "open stream link" function.

**Comment by MinorX** [comment]
Yeah , but does it have same features such as that of JVP ?
Like Dolby vision etc?

**Comment by Pentaphon** [comment]
> Yeah , but does it have same features such as that of JVP ? Like Dolby vision etc?

It is like Just Player but more than just a simple player. It has the same AndroidX media back end but with more features.
