### ISSUE TITLE
Not able to play video with this codec Stream 0: Codec: H264 - MPEG-4 AVC (part 10) (avc1), Stream 1 Codec: PCM MU-LAW (mlaw)

### ISSUE THREAD

**Issue by Tejas-Kanani** [moneytoo/Player#581]
**Bug:**

I am attempting to play a video using the codec listed below but am not able to play it.

Stream 0 Codec: H264 - MPEG-4 AVC (part 10) (avc1)
Type: Video
Video resolution: 2560x1440
Buffer dimensions: 2560x1440

Stream 1 Codec: PCM MU-LAW (mlaw)
Type: Audio
Sample rate: 8000 Hz

**Device:**
 - Model: Samsung Galaxy M series, Nokia, MotoG73
 - OS: Android 11, 12, 14

**Comment by Pentaphon** [comment]
> Stream 1 Codec: PCM MU-LAW (mlaw)

I don't think many phones support that old codec. You may have to use mpv or Next Player since they support more codecs than Just Player does.

**Comment by Korb** [comment]
Same:

```
General
Format: AVI
Format/Info: Audio Video Interleave
Format settings: BitmapInfoHeader / WaveFormatEx
File size: 239 MiB
Duration: 44 min 33 s
Overall bit rate: 751 kb/s
Frame rate: 29.970 FPS
Writing application: VirtualDubMod 1.5.10.1 (build 2439/release)
Writing library: VirtualDubMod build 2439/release

Video
ID: 0
Format: MPEG-4 Visual
Format profile: Advanced Simple@L5
Format settings: BVOP2
Format settings, BVOP: 2
Format settings, QPel: No
Format settings, GMC: No warppoints
Format settings, Matrix: Default (MPEG)
Muxing mode: Packed bitstream
Codec ID: XVID
Codec ID/Hint: XviD
Duration: 44 min 33 s
Bit rate: 644 kb/s
Width: 512 pixels
Height: 384 pixels
Display aspect ratio: 4:3
Frame rate: 29.970 (30000/1001) FPS
Color space: YUV
Chroma subsampling: 4:2:0
Bit depth: 8 bits
Scan type: Progressive
Compression mode: Lossy
Bits/(Pixel*Frame): 0.109
Stream size: 205 MiB (86%)
Writing library: XviD 1.1.0 Beta1 (2005-01-16)

Audio
ID: 1
Format: MPEG Audio
Format version: Version 1
Format profile: Layer 3
Format settings: Joint stereo / Intensity Stereo + MS Stereo
Codec ID: 55
Codec ID/Hint: MP3
Duration: 44 min 33 s
Bit rate mode: Constant
Bit rate: 96.0 kb/s
Channel(s): 2 channels
Sampling rate: 44.1 kHz
Compression mode: Lossy
Stream size: 30.6 MiB (13%)
Alignment: Split across interleaves
Interleave, duration: 33 ms (1.00 video frame)
Interleave, preload duratio: 500 ms
```

Just (Video) Player 0.161 f-droid

```
OS version: Funtouch OS 14
Model: Vivo T1 4G (V2153)
Hardware version: MP_0.1
Build number: PD22010F_EX_A_14.2.7.12.W20
Baseband version: S.HA.1.1.c2-00054-DIVAR_GENSP_PACK-1.29062.88
Kernel version: 4.19.157-perf+, 1 Wed Jun 5 10:25:33 CST 2024
Compile time: 5 Jun 2024 05:20:41
Android security update: 1 June 2024
Google Play system update: 1 May 2024
```

**Comment by Pentaphon** [comment]
Why do you guys insist in playing old formats on phones that can play all the new formats? Upgrade your videos. Your phone can play the new formats just fine. Just Player is using media3 which doesn't support those old AVI and mlaw formats.

**Comment by Korb** [comment]
> Why do you guys insist in playing old formats on phones that can play all the new formats?

In my case, I watch old series on my phone that were digitized at a time when there were no _new_ video formats or players that would only support _new_ formats, putting an end to the digital content of the past.  Because in most cases no one recodes old digitizations.  But they exist, just like old films that have not gone away.

**Comment by Pentaphon** [comment]
> Does it support playing new video, audio and subtitle formats as well as Just (Video) Player?

Yes. You can also try https://github.com/anilbeesetti/nextplayer

Just Player is great but it is limited to media3 and a simple UI for basic usage so people with more needs have to use something else.

**Comment by Korb** [comment]
> @moneytoo closed this as completed 16 hours ago

`Completed` or `Not planned`?

**Comment by moneytoo** [comment]
PCM MU-LAW should be supported (it's enabled in the FFmpeg extension), but AVI container (and its limited support in ExoPlayer) is likely the reason if it doesn't work.
