### ISSUE TITLE
TrueHD problem with tunneled playback enabled

### ISSUE THREAD

**Issue by xanatos** [moneytoo/Player#585]
I have an android TV connected to a soundbar through EARC. The TV is set to passthrough to the soundbar through the Android OS. On Just Player If I use the "Prefer device encoders" + "Tunneled playback = on" and I try to watch a movie with TrueHD audio (MLP FBA 16-ch/Meridian Lossless Packing FBA with 16-channel presentation/Dolby TrueHD with Dolby Atmos/A_TRUEHD) I receive the error

FfmpegAudioRenderer error, index=4, format=Format(2, Atmos 7.1, null, audio/raw, null, -1, it, [-1,-1,-1.0, null, [8, 48000]) , format_supported=NO_UNSUPPORTED_TYPE 

If I set "Prefer device encoders" + "Tunneled playback = off" it works correctly. The audio is probably decoded by Just Player (because on the soundbar I can see that the audio format is PCM audio).

And it is unclear exactly what Tunneled playback does, because other formats of audio are still decoded by the soundbar even when "Tunneled playback = off" and I still get the "Dolby Vision" logo when I watch a DV movie.

**Device (please complete the following information):**
 - Model: Sharp Aquos TVE21A
 - OS: Android 11
 - App Version: 0.160

**Comment by moneytoo** [comment]
Tunneed playback is described https://source.android.com/docs/devices/tv/multimedia-tunneling or https://medium.com/google-exoplayer/tunneled-video-playback-in-exoplayer-84f084a8094d
It should be more performant but even ExoPlayer team mentioned in the past that there are compatibility issues so the solution is not to use it in this case. So I don't think there's much to do.
