### ISSUE TITLE
The F-Droid version is outdated 

### ISSUE THREAD

**Issue by Nitrovenom** [moneytoo/Player#590]
**Describe the bug**
The current version on play store is 0.160 whereas the one in F-Droid is 0.154.

**To Reproduce**
Steps to reproduce the behavior: Not applicable.

**Expected behavior**
The F-Droid version should be on par with the play store and GitHub releases.

**Device (please complete the following information):**
Not applicable.

**Media**
Not applicable.

**Additional context**
Not all users use Google Play and they don't have time to individually keep track of all app updates. So, those who use F-Droid should be able to enjoy the latest update. Moreover, the Google play store shows update available for F-Droid apps now but many people prefer F-Droid version of apps over google play ones.

**Comment by moneytoo** [comment]
Already submitted to F-Droid: https://gitlab.com/fdroid/fdroiddata/-/commit/0a3069f9c9c2597b67898e8b914de52441c3ea50
