### ISSUE TITLE
Google tv 12 et Just Player 163

### ISSUE THREAD

**Issue by Philofil92** [moneytoo/Player#597]
**Describe the bug**
Ne voit pas l'intégralité des dossier et fichiers d'un disque dur de 5 TO,(tronque un certain nombre de dossiers alors que ce même disque est vu correctement sous Google tv Android 11, 

**To Reproduce**
Utiliser Google tv 12 avec un disque de 5To avec plus de 1400 fichiers 

**Device (please complete the following information):**
 - Model: TCL 65C89B
 - GOOGLE TV 12
 - Just Player 163

**Media**
Disque Seagate basic 5TO

**Additional context**

**Comment by Philofil92** [comment]
Je joins un rapport de bug pour étude...C'est un disque Seagate de 5TO avec 200 dossiers / 1421 fichiers
après ouverture disque, il y a une 40 de dossiers qui sont manquants. ALors que ce disque fonctionne très bien et il est parfaitement reconnu sur Google TV 11 et Just Player 163

[Mybugreport Just Player.txt](https://github.com/user-attachments/files/16175694/Mybugreport.Just.Player.txt)

**Comment by moneytoo** [comment]
Latest version actually contains some fixes (triggers MediaScanner). You may also consider using the `-legacy` release instead for full file system access.
