### ISSUE TITLE
Just(video)Player v0.164 Fails to Play Videos via DS Video App on Android TV

### ISSUE THREAD

**Issue by OliMGit** [moneytoo/Player#598]
**Describe the bug**
Just(video)Player cannot play videos via the DS Video (Synology) app on Android TV after updating to version v0.164 from v0.155. The same videos play fine in Just(video)Player v0.164 when selected via a different file browser.

**To Reproduce**
1. Open the DS Video app on Android TV.
2. Select any video to play using Just(video)Player.
3. See error - video tries to play for half a minute, then fails to play.

**Expected behavior**
The video should play smoothly without any errors when selected via the DS Video app, as it did in version v0.155 or as it does in v0.164 when starting the video from a non-DS Video app.

**Device (please complete the following information):**

Model: Sony Bravia A80J
OS: Android TV 10
Just(video)Player Version on Android TV: v0.164
DS Video Version: 1.1.8 on Android TV
Synology NAS Model: DS920+
DSM Version: 7.2.1-69057 Update 5
Media Server Version on Synology: 2.1.0-3304
DS Video Server on Synology: 3.1.1-3168

**Media**
N/A

**Additional context**
All applications, firmware updates, and configurations are up to date. Reverting to v0.155 "resolves" this issue.

**Comment by moneytoo** [comment]
l see that DS Video is no longer available with DSM 7.2.2. However I tried DS Video with DSM 7.2.1 and it worked fine for my on my phone. I dont see much to do as this is probably related to app lifecycle of the DS Video app.
