### ISSUE TITLE
[question] what happened to the "Lite" version?

### ISSUE THREAD

**Issue by throwaway242685** [moneytoo/Player#599]

**Comment by NguoiPhap** [comment]
Hi,
We need lite version for Amazon fire TV stick.
Only lite version has audio passthrough AC3, eac3, dts
Best regards.

**Comment by moneytoo** [comment]
The lite version did nothing in regards to audio passthrough or even decoders in general.

**Comment by moneytoo** [comment]
I have replaced or reworked all the bloated dependencies so now the main version has the size of lite version while keeping all the features (except for chapter detection).
