### ISSUE TITLE
Subtitle and audio synchronization options. 

### ISSUE THREAD

**Issue by yshalsager** [moneytoo/Player#6]
Thanks for building such nice app.
I'd like to suggest to add subtitles and audio syncing option. It'd be very useful, specially subtitles one because not every external subtitle works out of the box with video.

**Comment by moneytoo** [comment]
Changing subtitle time offset isn't supported by upstream ExoPlayer but it could satisfactorily worked around: https://github.com/google/ExoPlayer/issues/854#issuecomment-599237344

**Comment by moneytoo** [comment]
Given especially the lack of support for this in ExoPlayer, I don't think I will be implementing this.

**Comment by fn-ix** [comment]
It's not uncommon for even embedded subtitles to be out of sync, so hoping this feature will be reconsidered.

**Comment by mailinglists35** [comment]
hey @moneytoo this looks as completed.

but how do I do subtitle delay? I don't see any visible option :-(
