### ISSUE TITLE
Amazon store stuck on version 0.154

### ISSUE THREAD

**Issue by Pentaphon** [moneytoo/Player#600]
Please make sure the Amazon store has the latest update.

**Comment by moneytoo** [comment]
Updated

**Comment by Pentaphon** [comment]
@moneytoo could you update the Amazon store version again? I'd like to get the "Fix control of forced tracks" fix in v179 and up Thanks. 

Any way the Amazon version update could be automated in the future or should I just keep asking you for an update whenever I need an important fix?

**Comment by moneytoo** [comment]
![Screenshot_20241228_151152_Vivaldi](https://github.com/user-attachments/assets/7d2c5559-2159-4823-91a3-ef4a5a68dbd0)
![Screenshot_20241228_151234_Vivaldi](https://github.com/user-attachments/assets/a038bae8-f0ba-451f-bf09-5cadb3daea37)
I already uploaded new version few days ago. However, Amazon now forces staged rollout and I am not really sure how/if I can speed it up. Also, there is some sompatibility issue with non Amazon devices which I need to decypher as well.
