### ISSUE TITLE
Orientation control not available on non-touchscreen devices, stuck in landscape

### ISSUE THREAD

**Issue by twisteroidambassador** [moneytoo/Player#601]
**Describe the bug**
On an Android phone with no touchscreen, the orientation control is not visible, and the player is automatically switched to landscape, even when playing a portrait video.
If the phone is rotated, the video flips between the two landscape orientations, but never changes to portrait.

Some examples of non-touchscreen Android phones include the Japanese Keitais (Sharp SH-02L, Kyocera KYF39, etc.), Qin F21 Pro, CAT S22 Flip, etc. I'm happy to see Just Player operate very well with the d-pad, which makes it almost the perfect video player for these phones, if not for this bug.

**To Reproduce**
1. Use a phone without touch screen.
2. Open the app and play any portrait video.
3. The toolbar does not have an orientation button, and the video is playing in landscape.

**Expected behavior**

I imagine the orientation button is hidden because all non-touchscreen devices are treated as TVs.

An easy fix might be adding a settings menu item that is shown regardless of touchscreen availability.

**Device (please complete the following information):**
 - Model: Sharp SH-02L
 - OS: Android 8.1.0
 - Version 0.166

**Comment by moneytoo** [comment]
The orientation control is hidden on TV's as well as devices without touchscreen. My intention was hide that on full Android boxes used with TV's (outside Android TV) that can be detected by not having touchscreen. I will either remove that check or further improve it.

**Comment by twisteroidambassador** [comment]
Thanks for the fix! I would love to test it. When would a release be expected?
I tried to find an automated build in Github Actions, but it seems to not have any build artifacts.

**Comment by moneytoo** [comment]
Check [v0.167](https://github.com/moneytoo/Player/releases/tag/v0.167)
