### ISSUE TITLE
[Feature Request] Allow Caption Preferences Override

### ISSUE THREAD

**Issue by ItsMe-Haris** [moneytoo/Player#602]
#### Device

- **Model:** Samsung Galaxy S23+
- **OS:** Android 14

#### Problem

Samsung doesn't allow to set 0% background opacity for captions, so I'm forced to have some background behind my subtitles. I know using "Caption Preferences" for subtitle appearance is a well received feature but with some manufacturers customization is somewhat limited. If it is possible, please allow some kind of override switch to allow users the choice of having system captions or their custom one.

Thanks!

#### Additional

[Samsung Forums](https://us.community.samsung.com/t5/Galaxy-S23/Does-anyone-know-how-to-get-transparent-background-on-live/td-p/2920482)

<img src="https://github.com/user-attachments/assets/249b2eb6-3cdf-4f0f-a7e3-51bf9215edf5" alt="Screenshot_20240806_133334_Settings" width="512px" >

**Comment by moneytoo** [comment]
It's still possible to get rid of the background by setting the "Background color" to "None".

**Comment by ItsMe-Haris** [comment]
Thanks!

Scrolling up reveals this background color.
