### ISSUE TITLE
[Store distribution request] Accrescent 

### ISSUE THREAD

**Issue by kydauran** [moneytoo/Player#603]
Hi there!

Could you please consider publishing Just Player on the Accrescent App Store for Android in addition to the other distribution channels?

Many users, particularly those using privacy and security-focused Android operating systems like GrapheneOS, or who are simply privacy-conscious, rely on Accrescent for secure app downloads without depending on Google services.

Making this app available on Accrescent would be greatly appreciated by its user community.

Thank you!

https://accrescent.app/

**Comment by moneytoo** [comment]
I believe I looked at this store earlier, but I'm unable to submit an app there as it's not publicly open.

> Registration not permitted

> Accrescent developer registration is currently invite-only. Please come back when registration opens for everyone.

**Comment by moneytoo** [comment]
I tried mailing them ([like others did](https://github.com/fast4x/RiMusic/issues/2355#issuecomment-2176718921)) but I failed to receive any response in 3 weeks.

**Comment by kydauran** [comment]
I have forwarded it to the developer !
Thanks for telling

**Comment by moneytoo** [comment]
Published and available on Accrescent. Thanks for the nudges, folks. And special thank to @lberrymage of Accrescent!

**Comment by PacoBell** [comment]
@moneytoo Would you mind uploading v0.184 to Accrescent? Kthxbye.
