### ISSUE TITLE
[Feature Request] Ordered Chapters Playback Support for MKV Files

### ISSUE THREAD

**Issue by ItsMe-Haris** [moneytoo/Player#604]
Introduce support for ordered chapters playback in MKV files to provide seamless, uninterrupted viewing experience when chapters reference external files or segments within the same file.

Ordered chapters are used to create an episode playlist or skip certain segments within the same file. `mpv-android` works with ordered chapter playback but it is not based on ExoPlayer.

Please look into it (if possible).
Thanks!

**Comment by ItsMe-Haris** [comment]
@moneytoo is it possible?

**Comment by moneytoo** [comment]
I'm afraid this is not that suitable for a simple video player. I tried putting in the chapter markers but the issue is that most of my videos do not use even that so I have very little motivation to add and maintain something like that.
