### ISSUE TITLE
sound quality

### ISSUE THREAD

**Issue by shockergit** [moneytoo/Player#607]
When comparing just player with next player i found the sound of just player is cracking at high volume but no issues with next player as both used exoplayer. Please fix it.

**Comment by moneytoo** [comment]
The highest volume levels (displayed in red) use LoudnessEnhancer to increase the volume past normal maximum. This indeed causes distortion when used, based on the actual gain.

**Comment by shockergit** [comment]
> The highest volume levels (displayed in red) use LoudnessEnhancer to increase the volume past normal maximum. This indeed causes distortion when used, based on the actual gain.

I have only used the system max volume on both players. I think next player tweaked something or you tweaked something in the audio part. It sounds a bit better. Have you changed anything in the audio part of exoplayer.

**Comment by shockergit** [comment]
> The highest volume levels (displayed in red) use LoudnessEnhancer to increase the volume past normal maximum. This indeed causes distortion when used, based on the actual gain.

I have only used the system max volume on both players. I think next player tweaked something or you tweaked something in the audio part. It sounds a bit better. Have you changed anything in the audio part of exoplayer.
