### ISSUE TITLE
Issues MKV H265 profile Dolby Vision & profile HDR+ same time

### ISSUE THREAD

**Issue by NguoiPhap** [moneytoo/Player#608]
Issues with MKV H265 profile Dolby Vision & profile HDR+ same time, black screen all the time, only audio working.
Look like LG tv is confuse with the profile DV and HDR+ same time.

**Comment by moneytoo** [comment]
I'm afraid there's not much for Just Player to be done as it relies on the ExoPlayer (Media3) library in full for that. You might try ExoPlayer Demo or Next Player that also use the same library.
