### ISSUE TITLE
Manuální/Automatické schování ovladacích prvků při pauze

### ISSUE THREAD

**Issue by kalekad** [moneytoo/Player#61]
Bylo by dobré přidat manuální schování ovládacích prvků při pauze (ťuknutím mimo ovládání, stejně jak je tomu u vyvolání/schování ovládání při přehrávání), případně vrátit automatické schování. 

Například, když chci udělat screenshot ovládání zavazí. Nebo je více titulků v jeden okamžik, stopnu a přečtu si je, teď bohužel zavazí ovládání.

**Comment by moneytoo** [comment]
Možnost schovat ovládání během pauzy jsem schválně zkusil zakázat. Kvůli tomu aby bylo tlačítko pro obnovení přehrávání vždy co nejrychleji dostupné. Titulky jsem zkoušel posouvat nad spodní ovládací panel, ale pak zase potenciálně koliduje s prostředním tlačítkem a jejich posun nahoru a dolů tak není úplně ideální (MX Player to tak má, ale tady to není ono).

**Comment by kalekad** [comment]
Spletl jsem se, v posledních verzích před 0.23 nebylo automatické schování ovládaní při pauze.

Je škoda přijít o možnost schování během pauzy.

**Comment by moneytoo** [comment]
Duplicate of #89 (newer issue, but in English so closing this one)
