### ISSUE TITLE
Permission question

### ISSUE THREAD

**Issue by Quantum-Future** [moneytoo/Player#613]
According to F-Droid, this app needs the "Modify System Settings" permission. Why?

**Comment by moneytoo** [comment]
See [README.md](https://github.com/moneytoo/Player?tab=readme-ov-file#features): 

> **`WRITE_SETTINGS` ("Modify system settings") permission**: When the system file chooser is opened, it will always use current system orientation, even if the Player app sets its own. Granting this permission via adb (`adb shell pm grant com.brouken.player android.permission.WRITE_SETTINGS`) or App info screen will allow this app to temporarily enable Auto-rotate to at least partially mitigate [this imperfection](https://issuetracker.google.com/issues/141968218).

**Comment by moneytoo** [comment]
@theothernt There was no issue with this permission.
