### ISSUE TITLE
HDR10+ in hybrid mkv files

### ISSUE THREAD

**Issue by litvcom** [moneytoo/Player#614]
**Describe the bug**
Have problems on Chromecast with Google TV 4K with playback of **hybrid** MKV, plays in HDR10, not HDR10+.

**To Reproduce**
Play any **hybrid** mkv files
`HDR format : Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2094 App 4, Version 1, HDR10+ Profile B compatible`

**Expected behavior**
Play hybrid mkv in HDR10+ as implemented in Kodi 21.x. If possible, add similar functionality as in Kodi, "Allowed HDR dynamic metadate formats" where you can only select HDR10+ or Dolby Vision.

**Device (please complete the following information):**
- Chromecast with Google TV 4k
- Android for TV 12

**Additional context**
A much needed feature for Samsung TV owners (HDR10+)

**Comment by moneytoo** [comment]
Would you have any such media sample? I'm not sure if this could be related to the TV, but at least on phone with HDR10+ display, hybrid DV/HDR10 and DV/HDR10+ videos play fine.
