### ISSUE TITLE
Support for Jellyfin Android Tv as external player

### ISSUE THREAD

**Issue by Dnkhatri** [moneytoo/Player#619]
Hi I am able to use Just Player as an external player on Jellyfin Android TV but the player does not select the audio and subtitle streams that jellyfin android tv sends. It also misses other usability features like skip intro and credits etc but when it comes to actual video playback it works the best so would love to have way to get it to work with my jellyfin even if not through jellyfin android tv player.

**Comment by moneytoo** [comment]
Does it actually work with any other external video player? Say I want to select specific embedded subtitles from Jellyfin. I'm unable to make it work on my phone with VLC, MPV, MX Player... Is there an actual API for all this (I am not sure if the MX Player API covers all that)? I'm away from pc right now so I cannot look at the intents.

**Comment by Dnkhatri** [comment]
> Does it actually work with any other external video player? Say I want to select specific embedded subtitles from Jellyfin. I'm unable to make it work on my phone with VLC, MPV, MX Player... Is there an actual API for all this (I am not sure if the MX Player API covers all that)? I'm away from pc right now so I cannot look at the intents.

jellyfin phone is different from jellyfin android tv player. From what I understood from the dev support for some external apps is in this file others work vlc playstore version does not work need the beta 

https://github.com/jellyfin/jellyfin-androidtv/blob/30fcb192da47df63550c7e1cef9b2b6095188fd2/app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java
