### ISSUE TITLE
Can't access any media on latest Google TV OS

### ISSUE THREAD

**Issue by wube1** [moneytoo/Player#620]
**Describe the bug**
error message appears despite correct permissions on media files. "No indexed video found. To access video files in given storage, enable automatic media scanning in system settings"

**To Reproduce**
1. Most Likely latest Google TV OS
2. Download and install Just Video Player and try opening any media.
3. See error: "No indexed video found. To access video files in given storage, enable automatic media scanning in system settings"

**Expected behavior**
See media files and open them.

**Device (please complete the following information):**
 - Model: Nebula Cosmos 4k SE
 - OS: Google TV 
 - Version Latest

**Media**
www.reddit.com/r/JustPlayer/comments/1efv07f/just_downloaded_just_player_on_my_google_tv_and_i/  

**Additional context**
N/A

**Comment by moneytoo** [comment]
Are you using the latest version? Are the videos stored directly on the device?

**Comment by wube1** [comment]
I downloaded it via play application store. Would you recommend just downloading latest apk and installing manually?

**Comment by moneytoo** [comment]
In that case try installing `-legacy` release from https://github.com/moneytoo/Player/releases

**Comment by wube1** [comment]
thanks, indeed works fine!
