### ISSUE TITLE
Can you imitate mxplayer?

### ISSUE THREAD

**Issue by AlanTse1314** [moneytoo/Player#622]
Can ui operation and gesture operation imitate mxplayer, such as two-finger translation and zoom gestures, long-press multiple playback, etc.
机器翻译的，就是不能平移和缩放，要是能仿 mxplayer 播放器就好了

**Comment by moneytoo** [comment]
Some related gesture support request is tracked in #568 
No major UI changes are planned #13

**Comment by jinggqu** [comment]
Hi @AlanTse1314, I have forked this repo and implemented 2x speed on long press. If you are interested, you can download from https://github.com/jinggqu/Player/releases. Enjoy.
