### ISSUE TITLE
Seeking is not easy

### ISSUE THREAD

**Issue by divyansh10101** [moneytoo/Player#63]
When clicking on seeking bar it doesn't seek to that point. There is a need to seek using seeking circle which is difficult.

**Comment by divyansh10101** [comment]
When seeking all controls are displayed which can be fixed.

**Comment by moneytoo** [comment]
> When clicking on seeking bar it doesn't seek to that point. There is a need to seek using seeking circle which is difficult.

This is intentional to prevent accidental taps. https://github.com/moneytoo/Player/issues/28#issuecomment-781573168

> When seeking all controls are displayed which can be fixed.

In this case controls are displayed to see the current position (and not only time difference shown in the center). https://github.com/moneytoo/Player/issues/20

**Comment by moneytoo** [comment]
This change is making it just like YouTube. Just a tap doesn't do anything but tap and move start the seek.

**Comment by moneytoo** [comment]
> When seeking all controls are displayed which can be fixed.

After adding support for double tap (currently in [pre-release](https://github.com/moneytoo/Player/releases)), I changed it so seek doesn't show controls if they aren't visible already.

>This change is making it just like YouTube. Just a tap doesn't do anything but tap and move start the seek.

I'm hoping that this change will make a good middle ground. If not, voice your feedback.
