### ISSUE TITLE
Add option to play DV HDR10+ videos with only DV metadata (As firestick devices are unable to play DV with HDR10+ fallback)

### ISSUE THREAD

**Issue by suyash192** [moneytoo/Player#631]
Some (or all?) firestick devices are unable to play videos with DV and HDR10+ fallback due to a bug in the mediatek processor. Neither mediatek nor amazon are taking the necessary steps to fix this.

Kodi has implemented a setting for its video player which allows you to disable HDR10+ and play the video with only DV metadata, which fixes the issue completely.

Just Player should also implement such a setting since this bug affects a large number of users.

Below is the setting from Kodi. Just Player could implement a better setting like "Play DV HDR10+ videos as DV only" so that you don't have to change this setting everytime for each movie.

![Allowed HDR Setting](https://github.com/user-attachments/assets/07a6c214-452a-4b9c-9b1b-d82a649b3011)

![HDR Options in Setting](https://github.com/user-attachments/assets/930153a4-5949-46d0-b960-e6da181a2eba)

**Comment by moneytoo** [comment]
I'm afraid such functionality is not feasible for me to support. Just Player relies on ExoPlayer for playback so anything ExoPlayer support, Just Player supports as well. However don't dare supporting that without access to any of these specific devices or even DV screens. If there were such patches to support that in ExoPlayer (even not in upstream), they could be included.

**Comment by suyash192** [comment]
@moneytoo This is interesting because Vimu player has successfully implemented such an option and it uses ExoPlayer [as per their website](https://www.vimu.tv/documentation).

> It's based on the latest version of ExoPlayer.

I know it's closed source so we can't see how they implemented, but still at least it looks to be possible.

**Comment by moneytoo** [comment]
The real blockcker is Firestick itself. If this issue is only happening with Firestick, it's hard to understand what's going on...

**Comment by suyash192** [comment]
It's not just the firestick but all devices with the Mediatek MT8696D processor.

> The real blockcker is Firestick itself. If this issue is only happening with Firestick, it's hard to understand what's going on...

I understand your concern but we don't actually have to know what's going on since the fix is already known. The HDR10+ metadata just needs to be stripped down from DV HDR10+.

**Comment by suyash192** [comment]
@moneytoo Just FYI, I've created a library for exoplayer that can strip HDR10+ from DV HDR10+ videos and can also do Dovi P7 to P8 conversion and Dovi metadata stripping, in case you want to integrate those things as well. Integration is very simple as shown in the README.

https://github.com/suyash192/ExoplayerHdrUtils
