### ISSUE TITLE
Swipe Up/Down to adjust Volume and Brightness not work when put Player in NestScrollview

### ISSUE THREAD

**Issue by duongnv1996** [moneytoo/Player#64]
Thank you for your repository.
I have pushed the player inside **NestScrollview** and test, then I found that gesture swipe **up/down** to adjust the volume and bright not work. I confirm that swipe **left/right** work well.
```
-- androidx.coordinatorlayout.widget.CoordinatorLayout
       ---MyNestedScrollview
            ----androidx.constraintlayout.widget.ConstraintLayout
                  -----CustomStyledPlayerView 

```
So I need some help to modify the layout or structure.
Could you please help me?

**Comment by moneytoo** [comment]
I'm afraid you gonna have to resolve it on your own. Log `onTouch` to find out what's going on.
