### ISSUE TITLE
Not in the Menu list

### ISSUE THREAD

**Issue by aston314** [moneytoo/Player#68]
I have installed the online version.But not in the player menu list .
![C3703B2B-5979-4FA4-AF67-63C812600488](https://user-images.githubusercontent.com/2224932/110240934-2c92d700-7f89-11eb-91c4-501af988afd1.png)

**Comment by moneytoo** [comment]
Post here or send me via email - stream URL or details on how can I reproduce it. Some of the installed media players probably can display url/media details. The current list of supported types is intentionally small.
https://github.com/moneytoo/Player/blob/f4fe270b10dd5073949ca9912aff9d0836d92a26/app/src/online/AndroidManifest.xml#L33-L40

**Comment by aston314** [comment]
The Url is
![Uploading 81E188C6-ECF4-4387-A164-81F2E183A06C.jpeg…]()

**Comment by aston314** [comment]
![Uploading 57BA7967-FC6D-4DDD-8A5D-E210CDB1578F.jpeg…]()

**Comment by aston314** [comment]
https://vod4.buycar5.cn/20210305/1mtjz3nf/index.m3u8

**Comment by moneytoo** [comment]
Try the latest pre-release of v0.24: https://github.com/moneytoo/Player/releases

**Comment by aston314** [comment]
Thanks.
Work perfect.
But I find other problem.
I have set up the volume maximum,but when I open a new online video,the volume is small,I have to press the volume up button and the volume just   become normal (my original setup).
Please fix that.

**Comment by aston314** [comment]
When I first run the online version,the button has just like mouse over color,but when I play a online. video,and has no the button mouse over color.I am very hard to control the fuction with the remit controller,because I don’t know where am I .

**Comment by moneytoo** [comment]
> I have set up the volume maximum,but when I open a new online video,the volume is small,I have to press the volume up button and the volume just become normal (my original setup).

The extra volume boost is intentionally not persistable. It should stay active for a while if you don't close the app or the system doesn't unload the app. Launching already loud video with headphones and not remembering it's on max could be quite unpleasant.

> When I first run the online version,the button has just like mouse over color,but when I play a online. video,and has no the button mouse over color.I am very hard to control the fuction with the remote controller,because I don’t know where am I .

Yes, the button highlight on focus can be sometimes visible quite poorly. I'm already experimenting with alternatives (fa4c4b26d72fc41afee770eb1e9f2113b7432eda).

**Comment by aston314** [comment]
But I use it on TV. Not use headphones.
