### ISSUE TITLE
Videos from Huawei Gallery won't play

### ISSUE THREAD

**Issue by ThracianKnight1907** [moneytoo/Player#7]
Hello, 

I'd like to report a possible bug. I'm trying to use this app as the default video player on my phone, but if i try to play a file from the Gallery, the player will open, but nothing would actually play. Oddly, if i open the same videos from file manager it works ok.  I'm running android 10, and my phone model is Huawei P20 Pro.

**Comment by moneytoo** [comment]
Hi. Could you try opening "App info" detail for Just Player (the screen from where you uninstall an app or clear its data) and grant it Storage permission? Does it work then?

**Comment by ThracianKnight1907** [comment]
This fixed my issue, thanks. However I don't believe it prompted me for this permission when I first installed it.

**Comment by moneytoo** [comment]
Yes, the player app currently doesn't ask for this storage permission. It shouldn't be needed when interacting with other modern and properly written apps (at least from Android 7 and up). System apps are excluded from the requirements to target higher Android versions. I planning on adding the prompt for the storage permission eventually (when opening from these "unsupported" apps).

**Comment by moneytoo** [comment]
I hope I will be able to maintain this app over time so I focus on the actually maintainable and "testable" feature set. Support for these kind of hacks - receiving apps need storage permission when [it's actually the task for the sender app](https://developer.android.com/training/secure-file-sharing/share-file#GrantPermissions) - is fortunately needed less and less and eventually going fully away with latest Android releases. I even removed the storage access permission from the latest versions. This player really tries to go to the extreme.

(Still, you can continue using the `-online` build from Github that can be manually given the storage permission.)
