### ISSUE TITLE
Preferovat externí titulky

### ISSUE THREAD

**Issue by kalekad** [moneytoo/Player#70]
Bylo by možné přehodnotit, které titulky mají/nemají být zobrazeny.

Například: 
1. načíst a zobrazit externí titulky
2. vnořené tit. automaticky nezobrazovat

Stejně jako u titulků, by u audia nemělo docházet k automatickému výběru stopy na základě jazyka zařízení.

**Comment by moneytoo** [comment]
Externí titulky by měli mít prioritu nad interními, až na případy, kdy jsou interní titulky označeny jako forced.

**Comment by kalekad** [comment]
1. interní titulky (titulky neoznačeny jako výchozí) a forced a externí titulky. Při této  kombinaci se automaticky zobrazí externí titulky. Při nastaveni jazyka v captions je tento zobrazen.

2.interní titulky (titulky neoznačeny jako výchozí) a forced. Při této  kombinaci se nezobrazí žádné titulky. Při nastaveni jazyka v captions je tento zobrazen.

3.  interní titulky (jedny titulky označeny jako výchozí) a externí titulky. Při této kombinaci se automaticky zobrazí interní s výchozím tagem.

4. interní titulky (jedny titulky označeny jako výchozí (ENG)) a forced (ENG). V captions nastaven preferovaný jazyk na CZE. Při této kombinaci se automaticky zobrazí interní CZE. Bez captions se zobrazí interní s výchozým tagem.
