### ISSUE TITLE
Načtení správných externích titulků

### ISSUE THREAD

**Issue by kalekad** [moneytoo/Player#71]
Ve složce je několik videosouborů a externí titulky ke každému z nich pojmenované stejně jako videosoubory.  Takto se načtou správné titulky k videu. 

Kdyz například u videa č. 8 smažu titulky, načtou se titulky k videu č. 3 

Nebo je ve složce video a ext. titulky se stejnými názvy, v pořádku se načtou. Titulky přejmenuji a načtou se také. Ne, že by to byla chyba v tomto případě, ale podle čeho se přiřazují ext. titulky k jednotlivým videím?

**Comment by moneytoo** [comment]
Titulky se stejným názvem (eventuelně ještě obsahující kód jazyka) jsou preferovány, ale načtou se i ty s jiným názvem, pokud jsou ve složce s videem.

**Comment by kalekad** [comment]
Nevím jestli nemúže výběr "čehokoli" ve složce plné různych videí a titulků uživatele spíše zmást.

**Comment by moneytoo** [comment]
Je to vedlejší efekt funkcionality, aby se načetli titulky i pokud nesedí jméno a nemusely se titulky přejmenovávat. Jediná další alternativa je asi pak vyžadovat přesné jméno...

**Comment by kalekad** [comment]
Obecně vidím přímočařejší variantu s přesným jménem. Ale zase, v tomto konkrétním případě, jak by to působilo na uživatele. Zvoli složku, ze které se maji automaticky načist titulky a ony se mu žádné nenačtout, protože nemá pojmenováno. Ale zase, co když se mu tit. načtou, ale úplně jiné, neni v takovém případě nenačíst žádné a uživateli dát tímto signál, že musi sám přiřadit titulky nebo  přejmenovat. Tak jako tak, uživatel musí provést akci.

**Comment by moneytoo** [comment]
Ale dalo by se s tím ještě něco dělat. Počítat skóre podobnosti názvu titulků vs videa. Vzít do toho v potaz i počet dalších video souborů ve složce...
Zatím jsem to ale moc neřešil. Je to první verze. Zajímavé by bylo se podívat, jak to mají jiné přehrávače.

**Comment by moneytoo** [comment]
V posledním [pre-releasu](https://github.com/moneytoo/Player/releases) jsem přidal vyhodnocování podobnosti souborů titulků s videem. Nahodil jsem tam nějaké minimální skóre podobnosti na základě pár testů reálných jmen. Kdyžtak pak dejte vědět s nějakými příklady, pokud by se to nechovalo dostatečně rozumně.

**Comment by kalekad** [comment]
Zkoušel jsem a není to ono. Stav kdy se načtou "jakékoliv" titulky trvá. Ve složce kde je několik videí s téměř stejným názvem (seriál) se vždy po odmazání jedněch ext. tit. vyberou další, předpokládané chování je, že se nevyberou žádné.

Nova Video Player, MX Player Pro bez přesného jména ext. titulky nenačtou.

**Comment by moneytoo** [comment]
~~Zkuste mi napsat nějaký reálný případ (jméno souboru s videem a jméno chybně vybraných titulků), ať se mám čeho chytnout...~~

I když teď mě napadá případ, když složka obsahuje videa s jednotlivými díly seriálu a titulky budou mít pouze některé. Jednotlivé jména titulků se budou lišit tak v jednom znaku, takže skóre podobnosti bude hodně vysoké, ale reálně uživatel nebude chtít, aby se načetli.

Takže asi fakt dává smysl jen načíst titulky se stejným jménem nebo titulky ve složce, kde je právě jedno video.
