### ISSUE TITLE
Give subtitles a black outline for better visibility on white backgrounds

### ISSUE THREAD

**Issue by Pentaphon** [moneytoo/Player#72]
I know there's a shadow but the top of the letters still blend in with white backgrounds too much. There needs to be just enough black outline to not have them blend in with white or very light backgrounds and the default subtitle configuration would be perfect.  Perhaps remove the shadow and just add the outline? 

I don't know if subtitles will be configurable in the future but with a slight outline, that will be enough for most people to read in all situations without wanting to change it.

**Comment by moneytoo** [comment]
There was just an outline before but I switched to shadow to match MX Player style. Now I doubt that too as it's harder sometimes to read the subtitles. I may indeed switch back to outline.

However you should be able to customize subtitles already: https://github.com/moneytoo/Player#how-do-i-change-subtitle-font-size-or-color

**Comment by Pentaphon** [comment]
Yes, please go back to outline. I don't know what MX Player is doing but they have it all wrong. What matters is that people can actually read the subtitles no matter what is playing. Also, the caption section on my device is quite limited. I would have to enable a black background to make them more visible and I would just prefer an outline instead. I don't think you're going to add a subtitle configuration page so an outline would be the next best thing for all users.
