### ISSUE TITLE
Controller background doesn't extend to notch/cutout area

### ISSUE THREAD

**Issue by 1nikolas** [moneytoo/Player#73]
I have an OnePlus 7T and the control background cuts off on notch area. This is how it looks like:
![image](https://user-images.githubusercontent.com/30593419/111077938-cfa09f00-84fb-11eb-801a-02477f245ca3.png)

The 7T notch is a little teardrop on the center so the missing background is not covered by the notch.
I suspect this is an exoplayer problem since it happens on MX Player too (MX is based on exoplayer). Is there any way we can fix this?

**Comment by 1nikolas** [comment]
```
FrameLayout.LayoutParams params = (FrameLayout.LayoutParams) controlView.getLayoutParams();
params.leftMargin = -cutoutHeightPixels;
controlView.setLayoutParams(params);
```

Something like this would work but we need to get the cutout height

**Comment by moneytoo** [comment]
Currently this is just a simplest setup to handle cutouts. I'm definitely going to improve that. Last time I tried I learned that I need to take special care about the time bar so it wasn't one liner.

**Comment by 1nikolas** [comment]
Okay so a solution would be to set `windowLayoutInDisplayCutoutMode` to `never` and then set negative margins to everything. `getWindow().getDecorView().getRootWindowInsets().getDisplayCutout()` returns the pixel height of the cutout. I'm going to try that now and see if I can get it working

**Comment by 1nikolas** [comment]
```
@Override
    public void onAttachedToWindow() {
        super.onAttachedToWindow();

        //NOTCH FIX FOR LANDSCAPE
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            WindowManager.LayoutParams lp = this.getWindow().getAttributes();

            lp.layoutInDisplayCutoutMode = WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES;

            WindowInsets windowInsets = this.getWindow().getDecorView().getRootView().getRootWindowInsets();

            DisplayCutout displayCutout = windowInsets.getDisplayCutout();

            FrameLayout.LayoutParams params = (FrameLayout.LayoutParams) controlView.getLayoutParams();
            // Left or Right depends on landscape orientation
            params.leftMargin = -displayCutout.getSafeInsetLeft();
            params.rightMargin = -displayCutout.getSafeInsetRight();
            
            //TODO same for exo_progress and exo_controls_background
        }
    }
```

This seems to be working (with windowLayoutInDisplayCutoutMode set to shortEdges) and fixes the problem but it would be better to extend the background instead of extending the whole controlView/exo_progress and exo_controls_background
