### ISSUE TITLE
Possibility to add "Just Player" into Kodi 18.9?

### ISSUE THREAD

**Issue by Wesler99** [moneytoo/Player#74]
Hi all together,

this is not really a general issue, but i was wondering if this "Just Player" can be integrated into Kodi 18.9 as external player? I am using a Nvidia Shield Pro and previously i have had the ExoPlayer installed in addition to Kodi 18.9 in order to play video files with DV.

To realize this i had a playcorefactory.xml file in my Kodi folder with the following content:

`<playercorefactory>`
`<players>`
`<player name="ExoPlayer" type="ExternalPlayer" audio="false" video="true">`
`<filename>com.google.android.exoplayer2.demo</filename>`
`<hidexbmc>true</hidexbmc>`
`<playcountminimumtime>120</playcountminimumtime>`
`</player>`
`</players>`
`<rules action="prepend">`
`<rule video="true" player="dvdplayer">`
`<rule filename=".*DV.*" player="ExoPlayer"/>`
`</rule>`
`</rules>`
`</playercorefactory>`

Someone recommended to use the new update of "Just Player" as it is based on Exoplayer and should have some improvements.
Actually it worked out fine before, apart of the support of subtitlesm, therefore i wanted to give "Just Player" a try.

After uninstalling the old version and installing the "Just Player" i have updated the content in the XML file, too - but it didnt work out as hoped, the external player just won't start.

I used the following changes:
`<filename>com.brouken.player</filename>`

for the player name and player i tried various options like:
"Just Player"
"JustPlayer"
"Just.Player"
and i kept "ExoPlayer"

but none of these actually worked out.

Does anybody have an idea what i am doing wrong and what i could use instead?

Thank you in advance for any help

**Comment by moneytoo** [comment]
`com.brouken.player` is id for the "offline" version (also installable from Play Store or F-Droid), `com.brouken.player.online` for "online" version.

**Comment by Wesler99** [comment]
Hi moneytoo, 
many thanks for your quick reply, much appreciated.

I forgot to mention, the version i have installed is the "Just.Player.v0.24-offline.apk", so i assume the filename "com.brouken.player" is correctly choosen. 
Shall i use the online version instead with player name "JustPlayer" ?
If its of importance: My files are located on a NAS, i hope this isnt an issue.

Thanks again for your kind help.

**Comment by moneytoo** [comment]
Only the online version can access files outside device storage so you may want to try using that version.

**Comment by Rocky2242** [comment]
From where do I get/download the content online version..

**Comment by Shawn9347** [comment]
> From where do I get/download the online version..

No idea. Can't find it anywhere. Don't think there is an "online" version.
