### ISSUE TITLE
com.ibm.icu makes the app size 10mb more

### ISSUE THREAD

**Issue by kevin4dhd** [moneytoo/Player#76]
Recommend replacing or changing the algorithm, remove the library and the app now weighs 7mb, it is exaggeratedly large since it is only used for subtitles.

![image](https://user-images.githubusercontent.com/22886367/111429668-4b027c00-86c7-11eb-9285-be0c91408934.png)

**Comment by moneytoo** [comment]
I also hate it but this is the only library I found to work for correctly detecting file encodings (including mine like `cp1250`). If you know any smaller that works just as well...

The thing is that if the majority of users install the app from Google Play, thanks to differential update mechanism they won't really redownload the same stuff over and over, just the difference.

I tried and can make specific builds with/without this library, even builds for specific architecture (ABI) so apk is just about 5 MB. I would do that but than I would also have to explain a lot to the users. Just for saving a few MB.

**Comment by moneytoo** [comment]
The all arch APK is now 56 MB. On the other hand the update size on Google Play is only 5 MB (new downloads are 24 to 30 MB). The latter is what really matters. I'm open to replacing currently used larges libraries but I don't know any better alternatives right now so I'm closing this.
