### ISSUE TITLE
Play videos directly from URL 

### ISSUE THREAD

**Issue by M4NN3** [moneytoo/Player#77]
How to play the video directly from URL ?

**Comment by moneytoo** [comment]
Currently url streams play only when you open the link from other apps. (You also need to have the online version.)

**Comment by Rocky2242** [comment]
> Currently url streams play only when you open the link from other apps. (You also need to have the online version.)

Where do I find the online version??

**Comment by moneytoo** [comment]
> Where do I find the online version??

https://github.com/moneytoo/Player/releases
