### ISSUE TITLE
Online videos and special characters

### ISSUE THREAD

**Issue by DarremMolko** [moneytoo/Player#80]
Hi. I just found this player and I must say that I love its simplicity. But I noticed that it doesn't recognize videos with special characters (as shown below):

This is what I did, I tried to stream a video from my cloud 
![01](https://user-images.githubusercontent.com/70179709/112767507-7c474a00-8fed-11eb-845b-53e26dbc247b.jpg)
It is only recognized by MX Player
![02](https://user-images.githubusercontent.com/70179709/112767524-94b76480-8fed-11eb-9715-4fce0a588522.jpg)
Then I tried streaming another video without special characters
![03](https://user-images.githubusercontent.com/70179709/112767545-ab5dbb80-8fed-11eb-9fc8-6a0c0e69a6e0.jpg)
And as you can see below it was recognized without a problem
![04](https://user-images.githubusercontent.com/70179709/112767563-c16b7c00-8fed-11eb-9720-c19e157bf631.jpg)

Maybe this was reported before but I couldn't find anything related after doing a quick search. Anyway, thanks in advance.

**Comment by moneytoo** [comment]
It should work in the latest [pre-release](https://github.com/moneytoo/Player/releases).
