### ISSUE TITLE
Seek not working for Dolby vision/Dolby atmos eac3 file

### ISSUE THREAD

**Issue by pulsebeam** [moneytoo/Player#83]
The test videos available on Dolby Website at https://developer.dolby.com/tools-media/sample-media/video-streams/dolby-vision-streams/

The specific videos is at
http://media.developer.dolby.com/DolbyVision_Atmos/mp4/P81_GlassBlowing2_3840x2160%4059.94fps_15200kbps_fmp4.mp4

The video plays but I cannot seek to any specific time. It just plays from the beginning if I touch at a specific location on the seek bar.
I tried to play with other players and when I try to go to the middle of the video, only video plays and audio is not there. May be an audio format issue.
Kodi and Nova video player play the file perfectly and seek also works perfectly.
Please look into it.
Thank you

File description

Video
ID                             : 1
Format                         : HEVC
Format/Info                    : High Efficiency Video Coding
Format profile                 : Main 10@L5.1@Main
HDR format                     : Dolby Vision, Version 1.0, dvhe.08.09, BL+RPU, HDR10 compatible / SMPTE ST 2086, HDR10 compatible
Codec ID                       : hev1
Codec ID/Info                  : High Efficiency Video Coding
Duration                       : 2 min 55 s
Bit rate                       : 15.1 Mb/s
Width                          : 3 840 pixels
Height                         : 2 160 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 59.940 (60000/1001) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0 (Type 2)
Bit depth                      : 10 bits
Bits/(Pixel*Frame)             : 0.030
Stream size                    : 316 MiB (96%)
Default                        : Yes
Alternate group                : 1
Color range                    : Limited
Color primaries                : BT.2020
Transfer characteristics       : PQ
Matrix coefficients            : BT.2020 non-constant
Mastering display color primar : BT.2020
Mastering display luminance    : min: 0.0050 cd/m2, max: 4000 cd/m2
Codec configuration box        : hvcC+dvvC

Audio
ID                             : 2
Format                         : E-AC-3 JOC
Format/Info                    : Enhanced AC-3 with Joint Object Coding
Commercial name                : Dolby Digital Plus with Dolby Atmos
Codec ID                       : ec-3
Duration                       : 2 min 58 s
Bit rate mode                  : Constant
Bit rate                       : 640 kb/s
Channel(s)                     : 6 channels
Channel layout                 : L R C LFE Ls Rs
Sampling rate                  : 48.0 kHz
Frame rate                     : 31.250 FPS (1536 SPF)
Compression mode               : Lossy
Stream size                    : 13.6 MiB (4%)
Service kind                   : Complete Main
Default                        : Yes
Alternate group                : 2
Complexity index               : 16
Number of dynamic objects      : 15
Bed channel count              : 1 channel
Bed channel configuration      : LFE

Phone:
Poco F1
Lineage 17.1 ROM

**Comment by moneytoo** [comment]
This file is a `fmp4` without `sidx` box which isn't currently supported for seeking in ExoPlayer: https://github.com/google/ExoPlayer/issues/6704

**Comment by pulsebeam** [comment]
OK thanks
