### ISSUE TITLE
A MKV video is not playing in the player in VLC and MX it plays

### ISSUE THREAD

**Issue by divyansh10101** [moneytoo/Player#85]
It is an MKV file I will try to provide you any information you need about that file just fix it.

**Comment by moneytoo** [comment]
Yes, please provide output from mediainfo (may or may not be enough) or share a sample.

**Comment by divyansh10101** [comment]
Right now I can provide you this-
H.264 AVC
MPEG

**Comment by divyansh10101** [comment]
Well how can I cut this video to sample without any disturbance to sample.

**Comment by moneytoo** [comment]
Try providing more info using [mediainfo](https://mediaarea.net/en/MediaInfo). I would cut sample using ffmpeg but you should probably google any how to article you're comfortable with (and verify that the sample also doesn't play).

**Comment by divyansh10101** [comment]
https://drive.google.com/file/d/1XOsN-V08otOSoPerTRuJfHoJz25QRjYW/view?usp=sharing

**Comment by divyansh10101** [comment]
Just I have my Android so tell me an app that I can extract sample of video with

**Comment by moneytoo** [comment]
> https://drive.google.com/file/d/1XOsN-V08otOSoPerTRuJfHoJz25QRjYW/view?usp=sharing

This content doesn't seem to be public or accessible.

**Comment by divyansh10101** [comment]
Now it is accessible

**Comment by Pentaphon** [comment]
> Well how can I cut this video to sample without any disturbance to sample.

Use Avidemux to cut a clip with copy mode.

**Comment by divyansh10101** [comment]
> > Well how can I cut this video to sample without any disturbance to sample.
> 
> Use Avidemux to cut a clip with copy mode.

I only have android and it is a software for PC

**Comment by moneytoo** [comment]
I'm not able to reproduce the issue without a sample.

**Comment by divyansh10101** [comment]
Well it's ok but fix it if you find any such file and also some complex subtitles (Subtitles which act as an overlay on a video) are not shown properly one such example can be found in one of the episodes in this telegram channel
https://t.me/one_punch_man_dub

**Comment by divyansh10101** [comment]
![Uploading Screenshot_20210512-221922.png…]()
Even files doesn't generates thumbnail for these videos

**Comment by moneytoo** [comment]
> Well it's ok but fix it if you find any such file and also some complex subtitles (Subtitles which act as an overlay on a video) are not shown properly one such example can be found in one of the episodes in this telegram channel
> https://t.me/one_punch_man_dub

The videos you're referring to have PGS subtitles. Unfortunately, ExoPlayer doesn't support all PGS features - https://github.com/google/ExoPlayer/issues/7458
