### ISSUE TITLE
yuv420p10 pixel format decoding failed

### ISSUE THREAD

**Issue by YanceyChiew** [moneytoo/Player#87]
When playing a movie in yuv420p10 pixel format, an exception is thrown:   

>Decoder Failed: OMX.qcom.video.decoder.avc

![image](https://user-images.githubusercontent.com/35898533/114085052-6ede6980-98e3-11eb-92ea-580584891ee0.png)

There is some more detailed information below：

![image](https://user-images.githubusercontent.com/35898533/114085312-c7ae0200-98e3-11eb-8e23-a668792dfe2b.png)

**Comment by YanceyChiew** [comment]
In addition, the yuv420p10 pixel format source under hevc encoding can be decoded normally, and the above problems should only occur on the avs decoder.

**Comment by moneytoo** [comment]
Unfortunately the vast majority of Android devices don't handle 10 bit AVC. Android's MediaPlayer won't play that so neither ExoPlayer as it uses only platform decoders (at least for AVC).

**Comment by bbCLeon** [comment]
Can you provide the error message thrown?
