### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Github-com-foss** [moneytoo/Player#9]
Pls push update on fdroid as soon as possible.

**Comment by moneytoo** [comment]
It was already submitted and it waits to be merged. It will take couple more days at least.

**Comment by moneytoo** [comment]
Latest stable release is available on F-Droid.

**Comment by jerryn70** [comment]
@moneytoo Did you stopped updating app in fdroid ? The latest fdroid version is still 0.45.

**Comment by moneytoo** [comment]
I will probably push next update to F-Droid in two weeks.

**Comment by jerryn70** [comment]
@moneytoo thank you .
