### ISSUE TITLE
[Feature request] Allow playing video while on call

### ISSUE THREAD

**Issue by SinTan1729** [moneytoo/Player#90]
I often watch stuff with friends over phone. That's simply not possible using JustPlayer. I really hope this is added so that I don't have to keep another video player installed just for this reason.

**Comment by moneytoo** [comment]
Audio focus is the culprit here. Not sure if it's the ExoPlayer's Audio focus manager or just Audio focus in general. I will have to learn more about that and check that.

**Comment by moneytoo** [comment]
Enabling playback during a phone call would require either not using audio focus, ignoring audio focus or playback without audio. ExoPlayer's [AudioFocusManager](https://github.com/google/ExoPlayer/blob/r2.13.3/library/core/src/main/java/com/google/android/exoplayer2/AudioFocusManager.java) doesn't allow playback to start when it isn't able to gain audio focus.

For now I still see the bigger benefit in working with audio focus. So fixing this would require reimplemet the audio focus manager.
