### ISSUE TITLE
A question about the Just Player

### ISSUE THREAD

**Issue by GYT-cool** [moneytoo/Player#91]
After the installation, the player will have this problem, unable to open the local file. The problem is shown in the figure below.
![IMG_20210421_164929](https://user-images.githubusercontent.com/45682244/115965213-a0e60180-a55a-11eb-8185-c4803203b3e3.jpg)

**Comment by moneytoo** [comment]
Is that Android TV? If yes, then https://github.com/moneytoo/Player/issues/26#issuecomment-778677387:

> Android TV is missing native file chooser so opening files from within Just Player isn't currently supported. If you install [Material Files](https://github.com/zhanghai/MaterialFiles), you will be able to open files, but from internal storage only. If you need to open file from external storage, select and open it from a file manager. Pretty good and simple is this [File manager](https://play.google.com/store/apps/details?id=com.hitv.explore).

**Comment by GYT-cool** [comment]
Thank you for your course！I've been able to play Dolby Vision MKV files successfully, but I found a bug about the Exoplayer,  that is… the hard subtitles in the black edge cannot be displayed.
