### ISSUE TITLE
Not able to install on Android tv

### ISSUE THREAD

**Issue by RanbirSingh** [moneytoo/Player#94]
Hi Brother awesome work
I tired to install apk on MI BOX 4k but it shows error that cant be installed 
Help to install this awesome player on Android TV.

Thanks for all the efforts putting for the Android developer Community.

**Comment by moneytoo** [comment]
How are you installing it?

**Comment by RanbirSingh** [comment]
creating backup from phone i guess i need to create version from android Studio

**Comment by moneytoo** [comment]
Or just download [latest release](https://github.com/moneytoo/Player/releases/latest).
