### ISSUE TITLE
[Feature Request] Auto Frame Rate

### ISSUE THREAD

**Issue by vladlenas** [moneytoo/Player#98]
Please add AFR support, for your player.

"Modern AFR (fully implemented in the Android 6+ API) for processing in Kodi 17+, ViMu (with ViMu Engine), Archos, Plex, etc.
That means software (video players) independently control the resolution and the frequency of the display in the necessary way, accordingly to software logic. At the same time, everything that APP does not going to spread beyond the software (i.e. when APP stopped, and the system itself restored to the standard parameters). This is the ideal AFR implementation and this is the future. The problem only few TV Box manufacturers implement such abilities for AFR."

https://ugoos.com/system-auto-frame-rate-for-tv-boxes

**Comment by rost1980** [comment]
Yes, there is a lack of AFR support.

**Comment by moneytoo** [comment]
It should already work at least on Android 11+ as ExoPlayer [supports the newest API](https://github.com/google/ExoPlayer/blob/r2.13.3/library/core/src/main/java/com/google/android/exoplayer2/video/VideoFrameReleaseHelper.java#L389).

For older Android versions, there's [preferredDisplayModeId](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#preferredDisplayModeId). Not sure why ExoPlayer isn't using that (at least on Android TV).

Anyway, does frame rate matching work in Plex? AFAIK, they also use ExoPlayer now...

**Comment by vladlenas** [comment]
AFR works on Plex and changes the screen resolution depending on the content, on boxes where the system afr is implemented. Your player works great with DV content on Shield TV 2019, Ugoos, Tivo, Sabrina (GTV box) and AFTV 4K. And I know many people who use your player.)

**Comment by moneytoo** [comment]
Should the automatic frame rate switching also switch to different resolutions? Say I have 60 FPS FullHD video and current mode is 4k, but say this 4k mode allows only 30 Hz max. Should it stay in this case at 4k or switch to lower resolution that allows 60 Hz (possibly also depending on video resolution?)?
Or just ignore any resolutions that don't match current one?

**Comment by vladlenas** [comment]
Resolution switching is just as important as frequency switching. There is a general opinion that the TV scales better than, for example, any media box. The same Shield with its AI scaling, in my opinion, loses to the scaling of any TV. For example, players such as Vima and iptv player TiviMate did not support resolution switching for a long time, but under pressure from the community, they nevertheless included this feature in their development. I also want to remind you that such giants as Kodi, Plex, Emby have supported this for a long time, and also media players like Dune, Zidoo which have their own stock players.
The best and most correct way is to switch the frequency and resolution!

Sorry for the long answer.)

**Comment by vladlenas** [comment]
Ahah, I got too carried away and didn't answer the main question. I think that it is necessary to switch it to 1080/60, but not to stay in 4k and even more so at 30 Hz.
But for a start, switching the frequency would be enough.

**Comment by moneytoo** [comment]
Try the `-framerate` build from https://brouken.com/player/

I do not have any suitable device for testing this so I have no idea if it actually works. However, it looks like ExoPlayer doesn't report framerate for most of the videos I tried so I need to look more into that.

**Comment by vladlenas** [comment]
I checked the test player, that something switches something that is not.
For example test clips DV 4K 60Hz mp4 switched to 720 60Hz. Files in the mkv container do not switch at all, only one file in the mp4 container switched well.

**Comment by vladlenas** [comment]
I tested on Shield 2019, all mkv displayed "preferred display mode - 1". 
On mp4 files, the same message only with a positive number (83, 753, etc.), but not all switched the frequency.

**Comment by moneytoo** [comment]
> For example test clips DV 4K 60Hz mp4 switched to 720 60Hz.

I hope I fixed that in latest build. I also improved logging to see video and display rates (instead of mode ids).

I will try using `ffprobe` from https://github.com/tanersener/ffmpeg-kit to detect video frame rate.

**Comment by moneytoo** [comment]
Video frame rate is now detected for all the videos I tried. 🤞

**Comment by vladlenas** [comment]
I checked it on Shield, run mkv files and after 1-2 seconds the player crashes. mp4 everything that I ran correctly determined the frequency, but some files did not switch the frequency. Displays a message such as "Video refresh rate 23, 976" "Display frame rate 60,00".
Tested on _-framerate4_

**Comment by vladlenas** [comment]
A piece of the log, here I ran three files. Maybe something will help.
[log.txt](https://github.com/moneytoo/Player/files/6633853/log.txt)

**Comment by moneytoo** [comment]
> A piece of the log, here I ran three files. Maybe something will help.
> [log.txt](https://github.com/moneytoo/Player/files/6633853/log.txt)

That helped! (Builds updated)

**Comment by vladlenas** [comment]
Excellent!!!

**Comment by vladlenas** [comment]
On a few test DV clips, it does not switch, the information about the video shows 23.976 and the display information is 60.00. All these files are in an mp4 container. Files in a mkv container perfectly switches the frequency.

**Comment by vladlenas** [comment]
After switching the frequency, the video pauses. This is not very convenient, you have to press play again. Correct it if possible.)

**Comment by vladlenas** [comment]
At the beginning of video playback, it is better to pause for 1-2 seconds and turn on the black screen. This avoids unnecessary blinking when switching frequencies. This is how I see .....

Good job, I donate you a little.)

**Comment by moneytoo** [comment]
> Good job, I donate you a little.)

Thank you!

> On a few test DV clips, it does not switch, the information about the video shows 23.976 and the display information is 60.00. All these files are in an mp4 container. Files in a mkv container perfectly switches the frequency.

I'm rounding the refresh rates now. I'm not sure if it's necessary to support fractional refresh rates - do TVs/displays even support that?

> After switching the frequency, the video pauses. This is not very convenient, you have to press play again. Correct it if possible.)

I have few ideas about that but I will probably try to test it myself first.

**Comment by vladlenas** [comment]
> I'm rounding the refresh rates now. I'm not sure if it's necessary to support fractional refresh rates - do TVs/displays even support that?

Yes, of course they do. I can see this from the screen settings on the Shield, he also takes data from EDID TV. And I know for sure that top TV models also work with fractional frequencies.

**Comment by vladlenas** [comment]
I checked version 6, now everything works correctly with any video that I have.
Perfect!

**Comment by moneytoo** [comment]
Fractional frame rates should be supported now. Because of issues with different precision from ExoPlayer vs FFprobe I had to switch to use FFprobe only for frame rate detection. I tried it with one old TV which supported 50.0, 59.94 and 60 Hz modes and I was able to switch to all of them so I have a good feeling about that.

I disabled "auto play" when there's mode switching. It should be possible to properly handle that in the future but I should hopefully have opportunities to test it on two more devices next week.

Because of the FFmpeg/FFprobe dependency size, I'm enabling frame rate switching in `-online` builds only (at least for now).

**Comment by vladlenas** [comment]
Great job!
I checked version 0.36, now everything switches fine.
Only these 25-50, 29.97-59.94 and 30-60 doubles, which I think is not critical and quite correct. 

Thanks again from many users of your player.)

**Comment by moneytoo** [comment]
As power consumption isn't a constraint, highest refresh rate could benefit from compatibility with multiple video frame rates and avoid additional switches (like 120 Hz mode can be use for 24, 30, 60 video frame rates). It will also allow smoother UI animations.

Anyway, another version is already in pre-release: https://github.com/moneytoo/Player/releases/tag/v0.36

Thank you for your testing. This was actually good motivation to polish some other Android TV imperfections and finally make it somewhat usable.

**Comment by MattL0** [comment]
Thanks a lot! 

Does this mean the resolution will match the video content now?

on Ugoos am6b with other players if i choose the option to change resolution +refreshrate… it is picking the el layer 1080 as a frequency hint to set resolution…but it should ‘’take’’the 2160 stream to ouput 2160p.

**Comment by moneytoo** [comment]
@MattL0 As currently implemented, this feature only changes the frame rate and leaves resolution as it is.
