### ISSUE TITLE
ShieldTVPro 2019 not detect DTS-HD

### ISSUE THREAD

**Issue by Koloss78** [moneytoo/Player#99]
I use the latest JP offline Version 0.29 and mkv files with DTS-HD only detect the core DTS.
The same problem with older version from JP.

The ExoPLayer Exoplayer_Chapters_Support_03_08_2020_no_debug.apk detect DTS-HD.

**Comment by moneytoo** [comment]
DTS-HD passthrough isn't supported by ExoPlayer itself (https://github.com/google/ExoPlayer/issues/6225) so the binary you mention probably contains custom handling.

**Comment by moneytoo** [comment]
Experimental DTS-HD support/apk: https://github.com/moneytoo/Player/issues/139#issuecomment-893816783
